### ISSUE TITLE
Enable stalebot?

### ISSUE THREAD

**Issue by superm1** [fwupd/fwupd#1393]
I've seen this in a few projects and think it generally helps keep the issues list fresh.  There's a ton of old stuff that it can stay on top of for us then, especially stuff that is marked `needinfo` and never gets a response.

https://github.com/apps/stale

What do you think?

**Comment by hughsie** [comment]
I think it's a good idea. I've installed it for fwupd and lvfs-website -- what do you think of the default settings? If you do a PR then it LGTM.
