### ISSUE TITLE
Thank. you.

### ISSUE THREAD

**Issue by maxime1992** [fwupd/fwupd#1759]
This software is amazing. 

After an update I had the chip of my logitech completely broken and was not able to use it.

With 2 commands from fwupd it worked again (+ connecting the keyboard using solaar).

Thanks a lot :tada: :tada: :tada: :tada: 

(feel free to close this "issue" :D!)

PS: this comment saved me https://github.com/fwupd/fwupd/issues/655#issuecomment-435378508

**Comment by hughsie** [comment]
Great, thanks! :)
