### ISSUE TITLE
1.3.7 can't install UEFI capsule update

### ISSUE THREAD

**Issue by Sean-StarLabs** [fwupd/fwupd#1764]
Trying to install updates using 1.3.7 "hangs" on the BIOS splash screen. It shows:
```
Found update fwupd-....
Adding new capsule
```

It times out and reboots after 60 seconds or so. Can't find anything in the logs regarding the update (apart from it being scheduled).

1.3.6 worked fine. Likely a duplicate of #1753

```
shell
client version:	1.3.7
compile-time dependency versions
	gusb:	0.3.0
	efivar:	37
daemon version:	1.3.7
```

**Comment by hughsie** [comment]
Ya, I'll tag a new release today with the fix. Sorry for the bother.

**Comment by superm1** [comment]
duplicate of #1756
