### ISSUE TITLE
Laptop went to suspend while installing thunderbolt controller update

### ISSUE THREAD

**Issue by allanday** [fwupd/fwupd#1814]
Deets:

- Operating system and version: Fedora 31 Silverblue
- Is secure boot enabled (only for the UEFI plugin)? Presumably.
- Device: Lenovo X1 Carbon 6th gen, connected to a dock by thunderbolt, lid closed with a single external display

What happened:

  - I was in the Software app, and saw that there was an update pending for my thunderbolt controller
 - I clicked update. The button became insensitive and said installing.
 - My external monitor suddenly went blank, there was a pause of a few seconds, then the power button on the dock started to pulse. After a few seconds I pressed the button and was able to log in.

Not a great experience.

**Comment by hughsie** [comment]
I think what happened here is:

 * Laptop in docking station with lid closed
 * TBT update started
 * External monitor went away momentarily
 * GNOME did the laptop-lid-closed action

I think we need to do the same logind inihibit that PackageKit does, i.e. https://www.freedesktop.org/wiki/Software/systemd/inhibit/ for the duration of the update. I can work on this after lunch.
