### ISSUE TITLE
Checking for a touchpad firmware update breaks touchpad

### ISSUE THREAD

**Issue by akullpp** [fwupd/fwupd#1823]
Hi,

I have a X1C 7th Gen running Arch (latest) and Gnome (latest) and using the gnome-firmware GUI breaks the touchpad and I can't seem to be able to get it to work again, any ideas?

**Comment by superm1** [comment]
What version of fwupd are you using?  1.3.8 or older?

From it working, if you can please provide the output of the following:

```
/usr/libexec/fwupd/fwupdtool get-devices --verbose
```

That should give some indication what's happening.
Also presumably it won't be working after that, if you can confirm that's true.
