### ISSUE TITLE
Group list of devices when using get-updates by state

### ISSUE THREAD

**Issue by dadosch** [fwupd/fwupd#1840]
Currently for every device either

> $name has no available firmware updates

or

> $name  has the latest available firmware version

or the equivalent when there is a new update is shown when doing get-updates.

This is very crowded and you have to look exactly do distinguish between the states.

I propose instead:

> **Devices with the latest available firmare version:**
> - name
> - name
>
> **Devices with no available firmware updates:**
> - name
> 
> **Device with updates available:**
> - name

where the latter is only show if there devices with updates.

**Comment by superm1** [comment]
I think it seems like a reasonable proposal.  Would you be interested at taking a stab at implementing it?  It should mean patching the 4 times this comes up (in `src/fu-util.c` and `src/fu-tool.c`)

**Comment by hughsie** [comment]
How would this work with tree nesting of composite devices?

**Comment by superm1** [comment]
I think you would show the tree at the end, and those two groups at the start.

**Comment by dadosch** [comment]
> I think it seems like a reasonable proposal. Would you be interested at taking a stab at implementing it? It should mean patching the 4 times this comes up (in `src/fu-util.c` and `src/fu-tool.c`)

My knowledge of C is too limited for that🙈

**Comment by superm1** [comment]
@stoiandan maybe you can take a stab?
