### ISSUE TITLE
/usr/lib/systemd/system-shutdown/fwupd.shutdown failed with exit status -127

### ISSUE THREAD

**Issue by freefreeno** [fwupd/fwupd#1861]
**Describe the bug**
/usr/lib/systemd/system-shutdown/fwupd.shutdown failed with exit status -127
On every reboot I see this message in Arch Linux

**Steps to Reproduce**
Reboot

**Expected behavior**
No errors during reboot

**fwupd version information**
$ fwupdmgr --version
client version: 1.3.9
compile-time dependency versions
        gusb:   0.3.4
        efivar: 37
daemon version: 1.3.9

Please note how you installed it (`apt`, `dnf`, `pacman`, source, etc):
pacman in Arch Linux

**fwupd device information**
```
Precision 7540
│
├─Thunderbolt Controller:
│     Device ID:           6155c2b78f43685ec91f1b228ffe0214770eee20
│     Summary:             Unmatched performance for high-speed I/O
│     Current version:     41.01
│     Vendor:              Dell (TBT:0x00D4)
│     GUIDs:               98693963-c8d9-5f94-a80a-ce945716849f
│                          b982caab-eb37-5b45-9bf5-f92b70a93aac
│     Device Flags:        • Internal device
│                          • Updatable
│                          • Requires AC power
│                          • Device stages updates
│   
├─PM981a NVMe Samsung 256GB:
│     Device ID:           4eaff2823dc972f445fd5eca658978950f45609d
│     Summary:             NVM Express Solid State Drive
│     Current version:     15302029
│     Vendor:              Samsung Electronics Co Ltd (NVME:0x144D)
│     GUIDs:               92129901-9091-586c-8986-cbd5e9d5523f
│                          4dd8e6a7-2e7f-884f-9879-73328600e2d3
│     Device Flags:        • Internal device
│                          • Updatable
│                          • Requires AC power
│                          • Needs a reboot after installation
│                          • Device is usable for the duration of the update
│   
├─Samsung SSD 970 EVO Plus 250GB:
│     Device ID:           03281da317dccd2b18de2bd1cc70a782df40ed7e
│     Summary:             NVM Express Solid State Drive
│     Current version:     2B2QEXM7
│     Vendor:              Samsung Electronics Co Ltd (NVME:0x144D)
│     GUIDs:               6e54c992-d302-59ab-b454-2d26ddd63e6d
│                          47335265-a509-51f7-841e-1c94911af66b
│                          0a385028-4a26-5bc4-8282-40889897c5e8
│     Device Flags:        • Internal device
│                          • Updatable
│                          • Requires AC power
│                          • Needs a reboot after installation
│                          • Device is usable for the duration of the update
│   
├─System Firmware:
│     Device ID:           cac9de2369fa3c52f34448afb98d95c9d18cc6d4
│     Current version:     1.7.0
│     Minimum Version:     1.7.0
│     Vendor:              Dell Inc. (DMI:Dell Inc.)
│     GUID:                74992bad-d49d-4f82-bb77-bbe865bea34e
│     Device Flags:        • Internal device
│                          • Updatable
│                          • Requires AC power
│                          • Supported on remote server
│                          • Needs a reboot after installation
│                          • Cryptographic hash verification is available
│                          • Device is usable for the duration of the update
│   
└─TPM 2.0:
      Device ID:           c6a80ac3a22083423992a3cb15018989f37834d6
      Summary:             Platform TPM device
      Current version:     7.2.1.0
      Vendor:              Dell Inc. (PCI:0x1028)
      GUIDs:               09cdc289-b360-5234-90a7-c51ac47d7a6b
                           ff71992e-52f7-5eea-94ef-883e56e034c6
                           7d65b10b-bb24-552d-ade5-590b3b278188
                           6f5ddd3a-8339-5b2a-b9a6-cf3b92f6c86d
                           fe462d4a-e48f-5069-9172-47330fc5e838
      Device Flags:        • Internal device
                           • Updatable
                           • Requires AC power
                           • Needs a reboot after installation

```shell
$ fwupdmgr get-devices --show-all-devices
```
Precision 7540
│
├─Thunderbolt Controller:
│     Device ID:           6155c2b78f43685ec91f1b228ffe0214770eee20
│     Summary:             Unmatched performance for high-speed I/O
│     Current version:     41.01
│     Vendor:              Dell (TBT:0x00D4)
│     GUIDs:               98693963-c8d9-5f94-a80a-ce945716849f ← TBT-00d40926-native
│                          b982caab-eb37-5b45-9bf5-f92b70a93aac ← TBT-00d40926-native-0000:05:00.0
│     Device Flags:        • Internal device
│                          • Updatable
│                          • Requires AC power
│                          • Device stages updates
│   
├─Intel AMT [unprovisioned]:
│     Device ID:           e2623122c99d58220498aacbfcfdb1baebbae3c5
│     Summary:             Hardware and firmware technology for remote out-of-band management
│     Current version:     12.0.47.1524
│     Bootloader Version:  12.0.47.1524
│     Vendor:              Intel Corporation
│     GUID:                2800f812-b7b4-2d4b-aca8-46e0ff65814c
│     Device Flags:        • Internal device
│   
├─Lexa XT [Radeon PRO WX 3200]:
│     Device ID:           71b677ca0f1bc2c5b804fa1d59e52064ce589293
│     Vendor:              Advanced Micro Devices, Inc. [AMD/ATI] (PCI:0x1002)
│     GUIDs:               5c0901d4-e6e6-5ae5-b077-63310cd92b16 ← PCI\VEN_1002&DEV_6981&REV_00
│                          67320c50-75f3-50a0-a8d6-e81c12ee9fc5 ← PCI\VEN_1002&DEV_6981
│     Device Flags:        • Internal device
│                          • Cryptographic hash verification is available
│   
├─PM981a NVMe Samsung 256GB:
│     Device ID:           4eaff2823dc972f445fd5eca658978950f45609d
│     Summary:             NVM Express Solid State Drive
│     Current version:     15302029
│     Vendor:              Samsung Electronics Co Ltd (NVME:0x144D)
│     Serial Number:       S4GVNF0M852186
│     GUIDs:               92129901-9091-586c-8986-cbd5e9d5523f ← STORAGE-DELL-108184
│                          4dd8e6a7-2e7f-884f-9879-73328600e2d3
│     Device Flags:        • Internal device
│                          • Updatable
│                          • Requires AC power
│                          • Needs a reboot after installation
│                          • Device is usable for the duration of the update
│   
├─Samsung SSD 970 EVO Plus 250GB:
│     Device ID:           03281da317dccd2b18de2bd1cc70a782df40ed7e
│     Summary:             NVM Express Solid State Drive
│     Current version:     2B2QEXM7
│     Vendor:              Samsung Electronics Co Ltd (NVME:0x144D)
│     Serial Number:       S4P3NF0M409419Z
│     GUIDs:               6e54c992-d302-59ab-b454-2d26ddd63e6d ← NVME\VEN_144D&DEV_A808&REV_00
│                          47335265-a509-51f7-841e-1c94911af66b ← NVME\VEN_144D&DEV_A808
│                          0a385028-4a26-5bc4-8282-40889897c5e8 ← Samsung SSD 970 EVO Plus 250GB
│     Device Flags:        • Internal device
│                          • Updatable
│                          • Requires AC power
│                          • Needs a reboot after installation
│                          • Device is usable for the duration of the update
│   
├─System Firmware:
│     Device ID:           cac9de2369fa3c52f34448afb98d95c9d18cc6d4
│     Current version:     1.7.0
│     Minimum Version:     1.7.0
│     Vendor:              Dell Inc. (DMI:Dell Inc.)
│     GUID:                74992bad-d49d-4f82-bb77-bbe865bea34e
│     Device Flags:        • Internal device
│                          • Updatable
│                          • Requires AC power
│                          • Supported on remote server
│                          • Needs a reboot after installation
│                          • Cryptographic hash verification is available
│                          • Device is usable for the duration of the update
│   
├─TPM 2.0:
│ │   Device ID:           c6a80ac3a22083423992a3cb15018989f37834d6
│ │   Summary:             Platform TPM device
│ │   Current version:     7.2.1.0
│ │   Vendor:              Dell Inc. (PCI:0x1028)
│ │   GUIDs:               09cdc289-b360-5234-90a7-c51ac47d7a6b ← 0926-2.0
│ │                        ff71992e-52f7-5eea-94ef-883e56e034c6 ← system-tpm
│ │                        7d65b10b-bb24-552d-ade5-590b3b278188 ← DELL-TPM-2.0-NTC-NPCT
│ │                        6f5ddd3a-8339-5b2a-b9a6-cf3b92f6c86d ← DELL-TPM-2.0-NTC-NPCT75x
│ │                        fe462d4a-e48f-5069-9172-47330fc5e838 ← DELL-TPM-2.0-NTC-NPCT75xrls
│ │   Device Flags:        • Internal device
│ │                        • Updatable
│ │                        • Requires AC power
│ │                        • Needs a reboot after installation
│ │ 
│ └─Event Log:
│       Device ID:         58bd405f31c48e6eca290b425f530a94c91e955c
│       Vendor:            Dell Inc. (PCI:0x1028)
│       GUID:              a25657fe-b5dc-5be0-8b78-8b9dfec678ff ← system-tpm-eventlog
│       Device Flags:      • Internal device
│     
└─UHD Graphics 630 (Mobile):
      Device ID:           bbbf1ce3d1cf15550c3760b354592040292415bb
      Vendor:              Intel Corporation (PCI:0x8086)
      GUIDs:               12c60b98-52cd-500a-b99e-087aa6b47f0b ← PCI\VEN_8086&DEV_3E9B&REV_00
                           db677673-1102-5481-a11e-6f397e123ced ← PCI\VEN_8086&DEV_3E9B
      Device Flags:        • Internal device
                           • Cryptographic hash verification is available

**Additional questions**
This has been like this on two different Arch installs on same PC.

- Operating system and version:
Operating System: Arch Linux 
KDE Plasma Version: 5.18.3
KDE Frameworks Version: 5.67.0
Qt Version: 5.14.1
Kernel Version: 5.5.8-arch1-1
OS Type: 64-bit
Processors: 12 × Intel® Core™ i7-9750H CPU @ 2.60GHz
Memory: 15.4 GiB of RAM

- Have you tried rebooting?
This is when the error occurs
- Is this a regression?
This started for me seems like after the last update in Arch.

**Comment by FFY00** [comment]
We also received a bug report downstream that seems to actually identiofy the issue.

https://bugs.archlinux.org/task/65814

**Comment by freefreeno** [comment]
@FFY00 Ok thanks I have changed that line so mine should be fixed.

**Comment by superm1** [comment]
This was fixed in master here https://github.com/fwupd/fwupd/commit/d9597df863ca21e0fb2ff821f0c612e0eb0558b2 and backported to 1_3_X as well.  I think about when we tag 1.4.0 we should probably also tag a 1.3.10.
