### ISSUE TITLE
Please also install the unit tests

### ISSUE THREAD

**Issue by rossburton** [fwupd/fwupd#1956]
fwupd has two test suites: a set of unit tests (as ran by `meson test`) and an integration test (which is installed).

In some situations, such as in cross-compilation, it's useful to be able to also install the unit tests so that they can be executed on the target.  Please consider also installing the unit tests.

**Comment by superm1** [comment]
Several projects have started to do this, I don't think there is any problem with it.  If you've got some cycles, definitely happy to review a PR.

**Comment by FFY00** [comment]
I think this should be optional, adding a meson option should be pretty easy.

**Comment by hughsie** [comment]
Where would we install the local self tests? Would they be called by a new `installed-test` as well?

**Comment by superm1** [comment]
For libjcat we did:
`/usr/libexec/installed-tests/libjcat/`

**Comment by superm1** [comment]
should be fixed in master now

**Comment by superm1** [comment]
Something to note, as part of this change many binaries were removed from tree and won't be installed.  You can fetch them at runtime using `contrib/ci/get_test_firmware.sh`
