### ISSUE TITLE
When is the newest release planned?

### ISSUE THREAD

**Issue by Salt-Factory** [fwupd/fwupd#1982]
**Describe the question**
I was wondering when the next official release was planned.
You recently fixed on issue for updating the AIAIAI (#1890) which a couple of other people I know have encountered now.
However, building from source is too technical for them and thus they have to wait for a new release (and then its update on Snap, Ubuntu Packages, ...).

If the release date is still far away I might attempt at guiding them through the building process.

**Comment by hughsie** [comment]
Tuesday. :)
