### ISSUE TITLE
1.3.9 release notes commit missing on master

### ISSUE THREAD

**Issue by djcampello** [fwupd/fwupd#2059]

**Comment by superm1** [comment]
Do you mean specifically this commit? https://github.com/fwupd/fwupd/commit/3343edb45b6c8d9d38662414eafb40cf8918e147 should be on master?  I guess it's because we branched to 1_3_X so that riskier stuff in 1.4.0 wouldn't land there and we did a 1.3.9 after that.

**Comment by djcampello** [comment]
Yes, I was reading the release notes on  data/org.freedesktop.fwupd.metainfo.xml and 1.3.9 is missing.
