### ISSUE TITLE
OUI Quirk

### ISSUE THREAD

**Issue by jkiusAlarus** [fwupd/fwupd#2070]
as per https://github.com/fwupd/fwupd/wiki/ATA-Disk:-OUI-Quirk-Required I'm reporting the issue here. 
I hope this is the right place. I have several disks which seem to require OUI Quircks:

[DeviceInstanceId=OUI\000cca]
Vendor = Western Digital
VendorId = ATA:0x101C

[DeviceInstanceId=OUI\0024e9]
Vendor = Samsung
VendorId = ATA:0x144D

regards
Laurent Jacquot

**Comment by hughsie** [comment]
Would a pull request be possible please? Thanks!
