### ISSUE TITLE
Add the chromeos ebuild directly as a CI target (and cross compile target)

### ISSUE THREAD

**Issue by bleungatchromium** [fwupd/fwupd#2141]
@djcampello 
It would be ideal if we could run the chromeos ebuild directly as a CI target, maybe even a cross compile CI target.  Any chance you guys can try to put that together?

_Originally posted by @superm1 in https://github.com/fwupd/fwupd/issues/2131#issuecomment-634230392_

**Comment by hughsie** [comment]
@djcampello is this something still interesting to you? It would certainly help us with making syre we don't break anything.

**Comment by djcampello** [comment]
Yes, this is something on my to-do list
