### ISSUE TITLE
Build with -Dbuild=standalone -Dman=true fails: ERROR: Unknown variable "help2man".

### ISSUE THREAD

**Issue by Polynomial-C** [fwupd/fwupd#2192]
Build fails when meson is being called with `-Dbuild=standalone -Dman=true`. The problem is in `src/meson.build`:
```
if build_daemon and get_option('man')
  help2man = find_program('help2man')
```
but later in that file there is:
```
  if get_option('agent')
    custom_target('fwupdagent-man',
      input : fwupdagent,
      output : 'fwupdagent.1',
      command : [
        help2man, '@INPUT@',
```
and
```
if get_option('man')
  custom_target('fwupdtool-man',
    input : fwupdtool,
    output : 'fwupdtool.1',
    command : [
      help2man, '@INPUT@',
```
which then could (agent) or will (man) break because `help2man` variable is not set. The option `-Dbuild=standalone` sets `build_daemon` to `false`, so that variable never gets populated.

See also downstream bug report https://bugs.gentoo.org/728484

**Comment by hughsie** [comment]
Can we just change the `if build_daemon and get_option('man')` to `if get_option('man')`?
