### ISSUE TITLE
fu-device-list:  fu_device_list_replace should save custom flags

### ISSUE THREAD

**Issue by bleungatchromium** [fwupd/fwupd#2298]
**Describe the bug**
My plugin sets some custom flags. On attach or detach, when my usb device is rebooted, and fwupd replaces on the new device enumeration, the new instance of the device doesn't bring over the custom flags.

**Steps to Reproduce**
Steps to reproduce the behavior.
Reproduced it consistently using my WIP series here #2289

**Expected behavior**
On device replacement, custom flags that were set on the old device should be copied to the new one.

**fwupd version information**
Please provide the version of the daemon and client.
```shell
$ fwupdmgr --version
```
client version: 1.5.0
compile-time dependency versions
gusb: 0.3.5

Please note how you installed it (`apt`, `dnf`, `pacman`, source, etc):

**fwupd device information**
Please provide the output of the fwupd devices recognized in your system.

```shell
$ fwupdmgr get-devices --show-all-devices
```

**Additional questions**
- Operating system and version:
- Have you tried rebooting?
- Is this a regression?

**Comment by bleungatchromium** [comment]
I posted this to my series that addresses this: https://github.com/fwupd/fwupd/pull/2289/commits/e60beb5361badb121f043926fe58be85a477b79e

**Comment by hughsie** [comment]
That looks entirely sane; if you split out the commit into a new PR we can merge it as-is. Out of interest, what custom flags are you using? Custom flags used by more than one plugin usually get converted to, well, _ordinary_ flags :)

**Comment by bleungatchromium** [comment]
> That looks entirely sane; if you split out the commit into a new PR we can merge it as-is. Out of interest, what custom flags are you using? Custom flags used by more than one plugin usually get converted to, well, _ordinary_ flags :)

I'm using flags to indicate whether my rw region was written this time around or my ro region. This is a tiny bit of state I need preserved between ANOTHER_WRITE_REQUIRED loops.
