### ISSUE TITLE
Please keep the changelog

### ISSUE THREAD

**Issue by mendel5** [fwupd/fwupd#2304]
The release 1.4.5 at https://github.com/fwupd/fwupd/releases/tag/1.4.5 has a changelog. I think this is a very good idea and would be happy about the changelog being kept for future releases.

**Comment by superm1** [comment]
It's supposed to be automatic on releases.  We'll see at 1.4.6 and 1.5.0 if it works properly.
https://github.com/fwupd/fwupd/blob/master/.circleci/config.yml#L169

**Comment by mendel5** [comment]
Thanks!

**Comment by superm1** [comment]
Just FYI; it looks like automatic changelogs are working properly now.  They're showing in the recent 1.5.5 release:
https://github.com/fwupd/fwupd/releases/tag/1.5.5
