### ISSUE TITLE
fwupdmgr security check on Legacy Systems (Intel Bay Trail)

### ISSUE THREAD

**Issue by dnoliver** [fwupd/fwupd#2309]
**Describe the question**
A clear and concise description of what you are wondering about.

Currently, if you run the security check on a system using Intel Bay Trail, there is no information about the TXE version.
The reason could be that this systems do not provide version information in the `mei0/fw_ver` file:

```shell
cat /sys/devices/pci0000:00/0000:00:1a.0/mei/mei0/fw_ver
0:0.0.0.0
0:0.0.0.0
0:0.0.0.0
```

For checking the version on this systems, you need to use the "Legacy" version of the CSME Detection Tool https://downloadcenter.intel.com/download/29057/CSME_Detection_Tool_Legacy_Linux.tar.gz

The result is that, you get no version information with the security test. 

```shell
$ fwupdmgr security --force
Host Security ID: HSI:0 (v1.5.0)

HSI-1
✔ SPI write:                     Disabled
✔ TPM v2.0:                      Found
✔ UEFI dbx:                      Found
✘ SPI BIOS region:               Unlocked
✘ SPI lock:                      Disabled

HSI-2
✔ TPM PCR0 reconstruction:       Valid
✘ IOMMU:                         Not foun
```

If you run the `intel_csme_detection_tool_legacy` tool, you get:

```shell
Intel(R) CSME Detection Tool For Legacy Systems
Copyright(C) 2017-2019, Intel Corporation, All rights reserved.

Application Version: 1.0.16.0
Scan date: 2020-08-10 16:22:32 GMT

*** Host Computer Information ***
Name: ------------------------
Manufacturer: ----------------
Model: ------------------------
Processor Name: Intel(R) Atom(TM) CPU  E3845  @ 1.91GHz
OS Version: Fedora 31 Thirty One (5.5.17-200.fc31.x86_64)

*** Intel(R) ME Information ***
Engine: Intel(R) Trusted Execution Engine
Version: 1.0.2.1060

*** Risk Assessment ***
Based on the analysis performed by this tool: The system is not supported
Firmware versions of Intel(R) ME 3.x thru 5.x,
Intel(R) TXE 1.x thru 2.x and Intel(R) Server Platform Services 1.x thru 2.x are no longer supported,
thus were not assessed for the vulnerabilities/CVEs listed in these Security Advisories.
There is no new release planned for these versions.

For more information refer to the
Intel(R) CSME Detection Tool For Legacy Systems Guide or the
Intel Security Advisory Intel-SA-00086 at the following link:
https://www.intel.com/sa-00086-support
```

My question is, should you get a similar output on `fwupdmgr security` as well?

**fwupd version information**
Please provide the version of the daemon and client if applicable to your current installation of `fwupd`.
```shell
$ fwupdmgr --version
```

fwupdmgr version is the latest built master

**Comment by hughsie** [comment]
Lets use https://github.com/fwupd/fwupd/issues/2308 for discussion.
