### ISSUE TITLE
OUI Quirk Issue

### ISSUE THREAD

**Issue by Darkovian** [fwupd/fwupd#2322]
Hello, I've been trying to get fwupd working today after putting it off awhile and ran into this issue. The link mentioned submitting an issue with the information if I wasn't comfortable doing it the other way. Here is the information fwupd is giving me:

[DeviceInstanceId=OUI\030302]
Vendor = SK hynix
VendorId = ATA:0x1C5C

Thanks, hope this helps!

**Comment by superm1** [comment]
Would you be able to submit a PR for adding this?   The file to patch is https://github.com/fwupd/fwupd/blob/master/plugins/ata/ata.quirk

**Comment by Darkovian** [comment]
I believe I managed to submit a PR for the addition. Hopefully I got it right, not totally used to all of git just yet.

Link: [https://github.com/fwupd/fwupd/pull/2323](https://github.com/fwupd/fwupd/pull/2323)

**Comment by superm1** [comment]
closed by https://github.com/fwupd/fwupd/pull/2323
