### ISSUE TITLE
Presentation: Easiest way to infect hardware? (Introducing the Linux Vendor Firmware Service)

### ISSUE THREAD

**Issue by mendel5** [fwupd/fwupd#2333]
At https://people.freedesktop.org/~hughsient/temp/LVFS.pdf there is a presentation called "Introducing the Linux Vendor Firmware Service".

The title of slide number 5 is "Easiest way to infect hardware?" and this diagram is shown:
![screenshot](https://user-images.githubusercontent.com/60322520/90985361-bf36d000-e57b-11ea-94c3-0adaf1357482.png)

What does the light blue "???" stand for?

**Comment by hughsie** [comment]
You need to watch the presentation: https://www.youtube.com/watch?v=u7A7VqQCpIE&t=38s

A github issue really isn't the best way to ask these kinds of questions.

**Comment by mendel5** [comment]
Thanks for the link, I just watched the presentation.

The answer seems to be:
> The easiest way to infect hardware is through unpatched vulnerabilities. Often there is a patch/ firmware update available for a specific kind of hardware but many people don't install these firmware updates.
