### ISSUE TITLE
Rename dbxtool

### ISSUE THREAD

**Issue by FFY00** [fwupd/fwupd#2363]
**Is your feature request related to a problem? Please describe.**
It looks like the latest fwupd version installs a dbxtool binary, which conflicts with https://github.com/rhboot/dbxtool.

**Describe the solution you'd like**
Rename the executable. A suggestion would be `fwupd-dbxtool`.

**Describe alternatives you've considered**
I can rename it manually in the downstream package, but I think it would be better solved in the upstream.

**Comment by hughsie** [comment]
It's deliberately a replacement of rhboot/dbxtool -- with the blessing of Peter the original maintainer. In Fedora, fwupd now obsoletes dbxtool.

**Comment by FFY00** [comment]
Thanks, I will adjust the arch package.

@vathpela would be possible to add this information in the project README?
