### ISSUE TITLE
Transifex - please authorize join to team requests

### ISSUE THREAD

**Issue by p-bo** [fwupd/fwupd#2390]
Hello,
requested for joining to Czech team long ago, but nobody noticed - looking at state of other languages, I'm probably not alone. May I ask you to do it please?
(and maybe, due lack of capacities, to authorize manually, to allow joining automatically?)
Thanks
Pavel

**Comment by hughsie** [comment]
The transifex project is set up as assigned to the freedesktop.org team -- and I agree this isn't working well as the messages to the team are not being processed. It seems most other software has moved to managing it's own team of translators -- which I'm not super-keen on doing if I can avoid it. Can you tell me your transifex username and I'll try to add you manually perhaps?

**Comment by p-bo** [comment]
Thanks for insight (and intervention) - my transifex username is pavelb

**Comment by piotrdrag** [comment]
So, I added Richard as a maintainer on Transifex but also I accepted Pavel to the team. :)

**Comment by hughsie** [comment]
Thanks @piotrdrag, much appreciated.
