### ISSUE TITLE
Logitech HERO firmware upgrade

### ISSUE THREAD

**Issue by r3pek** [fwupd/fwupd#2395]
**Describe the question**
Logitech released on Set 15th a firmware upgrade to the HERO sensor making it 25K capable. (https://blog.logitech.com/2020/09/15/logitech-g-introduces-hero-25k-sensor-the-industrys-highest-performing-dpi-offering/)

Will this firmware upgrade be distributed via LVFS?

**fwupd version information**
```shell
$ fwupdmgr --version
client version:	1.4.5
compile-time dependency versions
	gusb:	0.3.4
	efivar:	37
daemon version:	1.4.5
```

**Comment by hughsie** [comment]
Moved to https://github.com/Logitech/fw_updates/issues/31 -- sorry -- I forgot that Logitech manages the fw updates repo on their own organisation.
