### ISSUE TITLE
Intel ME firmware update

### ISSUE THREAD

**Issue by EdiDD** [fwupd/fwupd#2438]
Is it possible to udpate intel management engine on Asus Z370-A motherboard ? 

    fwupdmgr get-devices
only listing :

- ssds
- system firmware
- UEFI dbx

but nothing about intel ME 

    fwupdmgr --version

client version:	1.4.6
compile-time dependency versions
	gusb:	0.3.4
	efivar:	37
daemon version:	1.4.6

**Comment by hughsie** [comment]
ASUS are testing the LVFS, but I don't think for that motherboard. I think you need to contact ASUS support and ask them there I'm afraid.

**Comment by EdiDD** [comment]
Thank you for reply and suggestion.
