### ISSUE TITLE
Please install bash completions for fwupdmgr 

### ISSUE THREAD

**Issue by joakim-tjernlund** [fwupd/fwupd#2547]
The meson build file only installs completions for fwupdtool and fwupdagent:
https://github.com/fwupd/fwupd/blob/master/data/bash-completion/meson.build

**Comment by superm1** [comment]
Eh? https://github.com/fwupd/fwupd/blob/master/data/bash-completion/meson.build#L30

**Comment by joakim-tjernlund** [comment]
> Eh? https://github.com/fwupd/fwupd/blob/master/data/bash-completion/meson.build#L30

hmm, seems like this ic connect to build option agent(I did not have that set), why?

**Comment by hughsie** [comment]
I think we should drop the agent requirement here, no?

**Comment by superm1** [comment]
No, it's intentional: https://github.com/fwupd/fwupd/commit/789d308f7955e61a9183d793dbd0b313f13ff5e3

**Comment by hughsie** [comment]
Ahh, indeed, thanks!
