### ISSUE TITLE
UEFI warning always printed even if uefi plugin is not built on ppc64

### ISSUE THREAD

**Issue by gyakovlev** [fwupd/fwupd#2576]
**Describe the bug**
the following warning is always printed on `ppc64` platform.
```
WARNING: UEFI capsule updates not available or enabled
  See https://github.com/fwupd/fwupd/wiki/PluginFlag:capsules-unsupported for more information.
```
of course `fwupd` is built without uefi support.
I tried also adding `DisabledPlugins=test;invalid;uefi` to config file, just in case, warning is still printed on every `fwupdmgr` invocation.

**Steps to Reproduce**
Steps to reproduce the behavior.
run `fwupdmgr`, warning printed every time despite efi support is not even built in.

**Expected behavior**
No warning printed.

**fwupd version information**
```shell
$ fwupdmgr --version
client version: 1.5.1
compile-time dependency versions
        gusb:   0.3.5

daemon version: 1.5.1
```

Please note how you installed it (`apt`, `dnf`, `pacman`, source, etc):
installed via emerge (gentoo package manager)

**fwupd device information**
Please provide the output of the fwupd devices recognized in your system.

```shell
$ fwupdmgr get-devices --show-all-devices
```

**Additional questions**
- Operating system and version:
gentoo rolling ppc64le
- Have you tried rebooting?
irrelevant, but yes
- Is this a regression?
I haven't checked previous versions.

**Comment by gyakovlev** [comment]
with @meklort 's help we figured out it's bios plugin

`DisabledPlugins=test;invalid;bios` does help.
I'll disable bios plugin build on ppc64 hosts in gentoo packages then.

**Comment by meklort** [comment]
In the source code, it's caused by https://github.com/fwupd/fwupd/blob/master/plugins/bios/fu-plugin-bios.c#L56

**Comment by gyakovlev** [comment]
actually, looks like there's no meson knob to disable bios plugin build. So I can't just opt-out on ppc without editing config =)
