### ISSUE TITLE
fwupdtool fails if /root/.cache is not writable

### ISSUE THREAD

**Issue by osresearch** [fwupd/fwupd#2580]
**Describe the bug**
When running on a system with a read only root filesystem, `fwupdtool get-update` detects updates, but `fwupdtool update` fails to install them if `/root/.cache/fwupd` is not writable:

```
# fwupdtool update
Loading…                 [-                                      ]10:35:36:0874 FuEngine             device e421b2fc248391f6fe3e55ddbb3c9043be068bd0 [INTEL SSDSCKKW256G8] does not define a vendor-id!
Loading…                 [***************************************]
• INTEL SSDSCKKW256G8 has no available firmware updates
20HQS3C300 must remain plugged into a power source for the duration of the update to avoid damage. Continue with update? [Y|n]: y
Failed to create '/root/.cache/fwupd': Read-only file system
• UEFI Device Firmware has the latest available firmware version
20HQS3C300 must remain plugged into a power source for the duration of the update to avoid damage. Continue with update? [Y|n]: y
Failed to create '/root/.cache/fwupd': Read-only file system
• UEFI Device Firmware has no available firmware updates
```

**Steps to Reproduce**

```
# mount -o ro,remount /
# fwupdtool update
```

**Expected behavior**
`/tmp` would be used instead?

**fwupd version information**
```shell
fwupdmgr --version
client version:	1.3.11
compile-time dependency versions
	gusb:	0.3.4
	efivar:	37
daemon version:	1.3.11
```
Installed via Ubuntu 20.04 package manager.

**Additional questions**
- Operating system and version: Ubuntu 20.04 with SecureBoot enabled and custom UEFI PK
- Have you tried rebooting? Yes
- Is this a regression? No?

**Comment by hughsie** [comment]
Out of interest, why using fwupdtool and not fwupdmgr? Then you don't need to download and store the file as root. I also think 1.5.1 might fix this for you by not storing the cache file by default IIRC.
