### ISSUE TITLE
Problem with firmware update for the dock

### ISSUE THREAD

**Issue by mueihn** [fwupd/fwupd#2603]
**Describe the bug**

The firmware updates fails with an error messages.

**Steps to Reproduce**
Steps to reproduce the behavior.

mue@schneckenhaus:~> sudo fwupdmgr update
[sudo] Passwort für mue: 
No upgrades for Latitude 7390 Thunderbolt Controller, current is 41.00: 23.00=older
Downloading 43.00 for Thunderbolt controller in Dell dock...
Entpacken …              [***************************************]
Authentifizierung …      [***************************************]
device ID 7b3cbc344094ace839263dd4711c84ea99bb6dc3 was not found
mue@schneckenhaus:~>

**Expected behavior**

There are firmware updates available. They should have been installed.

**fwupd version information**
Please provide the version of the daemon and client.

mue@schneckenhaus:~> fwupdmgr --version
client version:	1.2.11
compile-time dependency versions
	gusb:	0.3.0
	efivar:	37
daemon version:	1.2.11
mue@schneckenhaus:~>

It came pre-installed with my opensuse leap 15.2 distribution if I am not mistaken. Thus, it is likely part of the distribution-native package management controlled by zypper.

**fwupd device information**
Please provide the output of the external fwupd devices recognized in your system.

mue@schneckenhaus:~> fwupdmgr get-devices --filter=~internal
Verarbeitung der Argumente schlug fehl: Unbekannte Option --filter=~internal
mue@schneckenhaus:~> fwupdmgr get-devices
Latitude 7390 Thunderbolt Controller
  DeviceId:             fbe0d0a92b5921e5110308659a2b2a22c625fd4b
  Guid:                 0c4c1146-581e-5a06-9efb-ecd847f88c82
  Summary:              Unmatched performance for high-speed I/O
  Plugin:               thunderbolt
  Flags:                internal|updatable|require-ac|supported|registered
  Vendor:               Dell
  VendorId:             TBT:0x00D4
  Version:              41.00
  VersionFormat:        pair
  Icon:                 thunderbolt
  Created:              2020-11-19

Thunderbolt controller in Dell dock
  DeviceId:             41c056e49eb16aabbb076701ba290418697f0b66
  ParentDeviceId:       a455a3a21752e5d31c228f1f5b51761dad88a432
  Guid:                 c94770ca-1773-592c-b20a-e87243bc7cd0
  Summary:              Thunderbolt controller
  Plugin:               thunderbolt
  Flags:                updatable|require-ac|supported|registered
  Vendor:               Dell Inc
  VendorId:             TBT:0x00D4
  Version:              40.00
  VersionFormat:        pair
  Icon:                 thunderbolt
  InstallDuration:      22
  Created:              2020-11-19

RTS5487 in Dell dock
  DeviceId:             acb404019656654d44f80922d94735e831d9bb40
  ParentDeviceId:       a455a3a21752e5d31c228f1f5b51761dad88a432
  Guid:                 707c63d2-e597-5c40-84db-9b1bb4c48d96
  Guid:                 acfcd89b-105d-55b9-b85b-08bf8508f38c
  Guid:                 568ffa1e-a0db-5287-9ea3-872b60f7730b
  Summary:              USB 3.1 Generation 2 Hub
  Plugin:               dell_dock
  Flags:                updatable|require-ac|supported|registered
  Vendor:               Dell Inc
  VendorId:             USB:0x413C
  Version:              01.47
  VersionFormat:        pair
  Icon:                 dock-usb
  InstallDuration:      3
  Created:              2020-11-19

WD19TB
  DeviceId:             a455a3a21752e5d31c228f1f5b51761dad88a432
  Guid:                 cd357cf1-40b2-5d87-b8df-bb2dd82774aa
  Summary:              High performance dock
  Plugin:               dell_dock
  Flags:                updatable|require-ac|supported|registered|wait-for-replug
  Vendor:               Dell Inc
  Version:              01.00.00.00
  VersionLowest:        01.00.00.00
  VersionFormat:        quad
  Icon:                 dock-usb
  InstallDuration:      80
  Created:              2020-11-19
  UpdateMessage:        Updates will complete after the dock is unplugged. The dock will be unavailable for approximately 1 minute.

Package level of Dell dock
  DeviceId:             1eca9eabb0c992c136e1deb1f89e3f70c465aa1c
  ParentDeviceId:       a455a3a21752e5d31c228f1f5b51761dad88a432
  Guid:                 8ceeeffd-51b6-580c-9b75-69143227aff8
  Summary:              A representation of dock update status
  Plugin:               dell_dock
  Flags:                updatable|supported|registered
  Vendor:               Dell Inc
  Version:              01.00.14.01
  VersionFormat:        quad
  InstallDuration:      5
  Created:              2020-11-19
  Modified:             2020-11-19
  UpdateState:          success

VMM5331 in Dell dock
  DeviceId:             58931e8c9ef5eead9c007563814f96fcadb1b993
  ParentDeviceId:       a455a3a21752e5d31c228f1f5b51761dad88a432
  Guid:                 89fec0b6-6b76-5008-b82c-5e5c6c164007
  Summary:              Multi Stream Transport controller
  Plugin:               dell_dock
  Flags:                updatable|require-ac|supported|registered
  Vendor:               Dell Inc
  Version:              05.04.03
  VersionFormat:        triplet
  Icon:                 video-display
  InstallDuration:      360
  Created:              2020-11-19
  Modified:             2020-11-19
  UpdateState:          success

RTS5413 in Dell dock
  DeviceId:             ca36279eeac13463fd5d974c88794859294fbfb1
  ParentDeviceId:       a455a3a21752e5d31c228f1f5b51761dad88a432
  Guid:                 86fb40c0-8bf5-5a8b-a4ad-3156cf6bfaf4
  Guid:                 b27d25f1-019d-5718-b41a-02ddaefe5577
  Guid:                 ac5b774c-b49d-566b-9255-85f0f7f8a4ed
  Summary:              USB 3.1 Generation 1 Hub
  Plugin:               dell_dock
  Flags:                updatable|require-ac|supported|registered
  Vendor:               Dell Inc
  VendorId:             USB:0x413C
  Version:              01.21
  VersionFormat:        pair
  Icon:                 dock-usb
  InstallDuration:      14
  Created:              2020-11-19

Latitude 7390 System Firmware
  DeviceId:             38390d47b6b0e59dab94e5feafcd6adefefdb76e
  Guid:                 a86a3f07-b7d3-4545-9238-0274fc1ba682
  Plugin:               uefi
  Flags:                internal|updatable|require-ac|supported|registered|needs-reboot
  Vendor:               Dell Inc.
  Version:              0.1.16.0
  VersionLowest:        0.1.16.0
  VersionFormat:        quad
  Icon:                 computer
  Created:              2020-11-19

INTEL SSDPEKNW020T8
  DeviceId:             e11623b2caa18fee292058a5c09ca4e6152f7ecf
  Guid:                 c6cd9ab0-8f20-512e-9e1f-1af55b8454b9
  Guid:                 82741c78-f5dc-5c23-a152-00de5799edc8
  Guid:                 7c0505be-b609-566e-bf94-561e441a9171
  Summary:              NVM Express Solid State Drive
  Plugin:               nvme
  Flags:                internal|updatable|require-ac|registered|needs-reboot
  Vendor:               Intel Corporation
  VendorId:             NVME:0x8086
  Version:              002C
  VersionFormat:        plain
  Icon:                 drive-harddisk
  Created:              2020-11-19

________________________________________________

Nicht korrekt aktualisierte Geräte:

 • VMM5331 in Dell dock (5.03.010 → 05.04.03)

Das Hochladen von Firmware-Berichten hilft Hardwareherstellern, fehlerhafte und erfolgreiche Aktualisierungen auf realen Geräten schnell zu erkennen.
Bericht jetzt hochladen? (Erfordert Internetverbindung) [Y|n]: 
Ziel:                    https://fwupd.org/lvfs/firmware/report
Nutzdaten:               {
                           "ReportVersion" : 2,
                           "MachineId" : "996b48a043e947c979fa903ff71ef82e0dd0dd45de1628dba8d07efe8ab8a18c",
                           "Metadata" : {
                             "DistroId" : "opensuse-leap",
                             "DistroVersion" : "15.2"
                           },
                           "Reports" : [
                             {
                               "Checksum" : "90fc13732f343a41ea50b5282142865613197665",
                               "UpdateState" : 3,
                               "UpdateError" : "device ID 7b3cbc344094ace839263dd4711c84ea99bb6dc3 was not found",
                               "Guid" : "89fec0b6-6b76-5008-b82c-5e5c6c164007",
                               "Plugin" : "synapticsmst",
                               "VersionOld" : "5.03.010",
                               "VersionNew" : "05.04.03",
                               "Flags" : 42,
                               "Created" : 1605779739,
                               "Modified" : 1605780220,
                               "Metadata" : {
                                 "RuntimeVersion(com.redhat.fwupdate)" : "12",
                                 "CompileVersion(org.freedesktop.gusb)" : "0.3.0",
                                 "CpuArchitecture" : "x86_64",
                                 "RuntimeVersion(org.freedesktop.fwupd)" : "1.2.11",
                                 "DistroId" : "opensuse-leap",
                                 "DistroVersion" : "15.2",
                                 "RuntimeVersion(org.freedesktop.appstream-glib)" : "0.7.14",
                                 "CompileVersion(org.freedesktop.fwupd)" : "1.2.11",
                                 "BootTime" : "1605779698",
                                 "RuntimeVersion(com.dell.libsmbios)" : "2.4",
                                 "CompileVersion(com.redhat.efivar)" : "37",
                                 "KernelVersion" : "5.3.18-lp152.50-default",
                                 "CompileVersion(com.redhat.fwupdate)" : "12"
                               }
                             }
                           ]
                         }
Mit dem Hochladen fortfahren? [Y|n]: 
Der Aktualisierungsfehler ist ein bekanntes Problem, besuchen Sie diese URL für weitere Informationen: https://github.com/fwupd/fwupd/wiki/LVFS-Triaged-Issue:-WD19*:-Device-ID-was-not-found#
mue@schneckenhaus:~>

**Dock SKU**
Please mention which module is installed in your WD19.

- [ ] WD19 (Single-C)
- [x] WD19TB (Thunderbolt)
- [ ] WD19DC (Dual-C)

**Peripherals connected to the dock**
Please describe all devices connected to the dock.  Be as specific as possible,
including USB devices, hubs, monitors, and downstream type-C devices.

- an ethernet cable connecting it to this switch: https://www.amazon.de/gp/product/B000BCC0LO/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

- an hdmi cable connecting it to this monitor: https://www.amazon.de/gp/product/B00WUACE4S/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

- the following USB switch connecting it to a Logiteck K120 keyboard and a Logitech M100 mouse: https://www.amazon.de/gp/product/B01N6GD9JO/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

- the following USB headset: https://www.amazon.de/SoftPhone-Kopfh%C3%B6rer-Cancelling-Lautst%C3%A4rkeregler-Kristallklar/dp/B0852YW96P/ref=sr_1_5?dchild=1&keywords=usb+headset&qid=1604308693&sr=8-5

**Verbose daemon logs**
First enable daemon verbose logs collection.

mue@schneckenhaus:~> fwupdmgr modify-config "VerboseDomains" "*"
Restart the daemon to make the change effective? [Y|n]: 
mue@schneckenhaus:~>

Then try to reproduce the issue.  Even if it doesn't reproduce, please attach the
daemon verbose logs collected from the system journal.

mue@schneckenhaus:~> cat <(sudo journalctl -b -u fwupd.service)
-- Logs begin at Thu 2020-11-19 10:55:00 CET, end at Thu 2020-11-19 11:21:07 CET. --
Nov 19 10:55:36 schneckenhaus systemd[1]: Starting Firmware update daemon...
Nov 19 10:55:39 schneckenhaus fwupd[3971]: 09:55:39:0528 GLib                 GError set over the top of a previous GError or uninitialized memory.
Nov 19 10:55:39 schneckenhaus fwupd[3971]: This indicates a bug in someone's code. You must ensure an error is NULL before it's set.
Nov 19 10:55:39 schneckenhaus fwupd[3971]: The overwriting error message was: missing executable tpm2_pcrread in PATH
Nov 19 10:55:39 schneckenhaus fwupd[3971]: 09:55:39:0529 FuPluginUefi         Failed to get PCR0s: missing executable tpm2_pcrlist in PATH
Nov 19 10:55:41 schneckenhaus fwupd[3971]: 09:55:41:0386 FuEngine             failed to add USB device 0bda:8153: failed to add device using on dell: invalid dock component request Query 2 0 2 4 0
Nov 19 10:55:41 schneckenhaus systemd[1]: Started Firmware update daemon.
Nov 19 11:19:55 schneckenhaus fwupd[3971]: 10:19:55:0008 Fwupd                looking for os-release at /etc/os-release
Nov 19 11:19:55 schneckenhaus fwupd[3971]: 10:19:55:0008 FuConfig             loading /usr/share/fwupd/metainfo
Nov 19 11:19:55 schneckenhaus fwupd[3971]: 10:19:55:0008 XbSilo               attempting to load /var/cache/fwupd/metainfo.xmlb
Nov 19 11:19:55 schneckenhaus fwupd[3971]: 10:19:55:0009 XbSilo               file: 6d1a15b7-1df9-5b5c-9d41-c5c5c50c34cf, current:6d1a15b7-1df9-5b5c-9d41-c5c5c50c34cf, cached: (null)
Nov 19 11:19:55 schneckenhaus fwupd[3971]: 10:19:55:0009 XbSilo               loading silo with file contents
Nov 19 11:19:55 schneckenhaus fwupd[3971]: 10:19:55:0009 FuConfig             using config path of /etc/fwupd
Nov 19 11:19:55 schneckenhaus fwupd[3971]: 10:19:55:0009 FuConfig             loading config from /etc/fwupd/remotes.d/fwupd-tests.conf
Nov 19 11:19:55 schneckenhaus fwupd[3971]: 10:19:55:0009 FuConfig             loading config from /etc/fwupd/remotes.d/lvfs-testing.conf
Nov 19 11:19:55 schneckenhaus fwupd[3971]: 10:19:55:0009 FuConfig             loading config from /etc/fwupd/remotes.d/vendor.conf
Nov 19 11:19:55 schneckenhaus fwupd[3971]: 10:19:55:0010 FuConfig             loading config from /etc/fwupd/remotes.d/vendor-directory.conf
Nov 19 11:19:55 schneckenhaus fwupd[3971]: 10:19:55:0010 FuConfig             loading config from /etc/fwupd/remotes.d/lvfs.conf
Nov 19 11:19:55 schneckenhaus fwupd[3971]: 10:19:55:0010 FuConfig             loading config from /etc/fwupd/remotes.d/dell-esrt.conf
Nov 19 11:19:55 schneckenhaus fwupd[3971]: 10:19:55:0011 FuConfig             using config path of /usr/lib/fwupd
Nov 19 11:19:55 schneckenhaus fwupd[3971]: 10:19:55:0011 FuConfig             path /usr/lib/fwupd/remotes.d does not exist
Nov 19 11:19:55 schneckenhaus fwupd[3971]: 10:19:55:0011 FuConfig             ordering lvfs-testing=lvfs+1
Nov 19 11:19:55 schneckenhaus fwupd[3971]: 10:19:55:0011 FuConfig             ignoring unfound remote fwupd
Nov 19 11:19:55 schneckenhaus fwupd[3971]: 10:19:55:0011 FuConfig             ::configuration changed
Nov 19 11:19:55 schneckenhaus fwupd[3971]: 10:19:55:0013 FuEngine             remote lvfs-testing not enabled, so skipping
Nov 19 11:19:55 schneckenhaus fwupd[3971]: 10:19:55:0013 FuEngine             remote fwupd-tests not enabled, so skipping
Nov 19 11:19:55 schneckenhaus fwupd[3971]: 10:19:55:0013 FuEngine             remote vendor not enabled, so skipping
Nov 19 11:19:55 schneckenhaus fwupd[3971]: 10:19:55:0013 FuEngine             remote vendor-directory not enabled, so skipping
Nov 19 11:19:55 schneckenhaus fwupd[3971]: 10:19:55:0013 XbSilo               attempting to load /var/cache/fwupd/metadata.xmlb
Nov 19 11:19:55 schneckenhaus fwupd[3971]: 10:19:55:0013 XbSilo               0,04ms      parse blob
Nov 19 11:19:55 schneckenhaus fwupd[3971]: 10:19:55:0013 XbSilo               0,12ms      loaded file
Nov 19 11:19:55 schneckenhaus fwupd[3971]: 10:19:55:0013 XbSilo               file: aaa41c3a-e820-5ec2-afba-2a7ffa452e36, current:aaa41c3a-e820-5ec2-afba-2a7ffa452e36, cached: (null)
Nov 19 11:19:55 schneckenhaus fwupd[3971]: 10:19:55:0013 XbSilo               loading silo with file contents
Nov 19 11:19:55 schneckenhaus fwupd[3971]: 10:19:55:0013 XbSilo               0,02ms      parse blob
Nov 19 11:19:55 schneckenhaus fwupd[3971]: 10:19:55:0014 XbSilo               0,93ms      query on / with `components/component` limit=0 -> 500 results
Nov 19 11:19:55 schneckenhaus fwupd[3971]: 10:19:55:0014 FuEngine             500 components now in silo
Nov 19 11:19:55 schneckenhaus fwupd[3971]: 10:19:55:0016 XbSilo               1,01ms      query on / with `components/component/provides/firmware` limit=0 -> 587 results
Nov 19 11:19:55 schneckenhaus fwupd[3971]: 10:19:55:0016 XbSilo               0,54ms      query on / with `components/component/provides/firmware` limit=0 -> 587 results
Nov 19 11:19:55 schneckenhaus fwupd[3971]: 10:19:55:0019 XbSilo               1,48ms      query on / with `components/component/provides/firmware[@type='flashed'][text()='2800f812-b7b4-2d4b-aca8-46e0ff65814c']/../..` limit=1 -> 0 results
Nov 19 11:19:55 schneckenhaus fwupd[3971]: 10:19:55:0019 XbSilo               0,17ms      query on / with `components/component/provides/firmware[@type='flashed'][text()='0c4c1146-581e-5a06-9efb-ecd847f88c82']/../..` limit=1 -> 1 results
Nov 19 11:19:55 schneckenhaus fwupd[3971]: 10:19:55:0019 XbSilo               0,66ms      query on / with `components/component/provides/firmware[@type='flashed'][text()='c94770ca-1773-592c-b20a-e87243bc7cd0']/../..` limit=1 -> 1 results
Nov 19 11:19:55 schneckenhaus fwupd[3971]: 10:19:55:0020 XbSilo               0,51ms      query on / with `components/component/provides/firmware[@type='flashed'][text()='a86a3f07-b7d3-4545-9238-0274fc1ba682']/../..` limit=1 -> 1 results
Nov 19 11:19:55 schneckenhaus fwupd[3971]: 10:19:55:0021 XbSilo               1,40ms      query on / with `components/component/provides/firmware[@type='flashed'][text()='20c968e3-b6e1-53f8-a4b0-f45577c5b1c5']/../..` limit=1 -> 0 results
Nov 19 11:19:55 schneckenhaus fwupd[3971]: 10:19:55:0026 XbSilo               4,52ms      query on / with `components/component/provides/firmware[@type='flashed'][text()='707c63d2-e597-5c40-84db-9b1bb4c48d96']/../..|components/component/provides/firmware[@type='flashed'][text()='acfcd89b-105d-55b9-b85b-08bf8508f38c']/../..|components/component/provides/firmware[@type='flashed'][text()='568ffa1e-a0db-5287-9ea3-872b60f7730b']/../..` limit=1 -> 1 results
Nov 19 11:19:55 schneckenhaus fwupd[3971]: 10:19:55:0027 XbSilo               0,73ms      query on / with `components/component/provides/firmware[@type='flashed'][text()='cd357cf1-40b2-5d87-b8df-bb2dd82774aa']/../..` limit=1 -> 1 results
Nov 19 11:19:55 schneckenhaus fwupd[3971]: 10:19:55:0028 XbSilo               0,84ms      query on / with `components/component/provides/firmware[@type='flashed'][text()='8ceeeffd-51b6-580c-9b75-69143227aff8']/../..` limit=1 -> 1 results
Nov 19 11:19:55 schneckenhaus fwupd[3971]: 10:19:55:0029 XbSilo               0,94ms      query on / with `components/component/provides/firmware[@type='flashed'][text()='89fec0b6-6b76-5008-b82c-5e5c6c164007']/../..` limit=1 -> 1 results
Nov 19 11:19:55 schneckenhaus fwupd[3971]: 10:19:55:0034 XbSilo               5,51ms      query on / with `components/component/provides/firmware[@type='flashed'][text()='86fb40c0-8bf5-5a8b-a4ad-3156cf6bfaf4']/../..|components/component/provides/firmware[@type='flashed'][text()='b27d25f1-019d-5718-b41a-02ddaefe5577']/../..|components/component/provides/firmware[@type='flashed'][text()='ac5b774c-b49d-566b-9255-85f0f7f8a4ed']/../..` limit=1 -> 1 results
Nov 19 11:19:55 schneckenhaus fwupd[3971]: 10:19:55:0038 XbSilo               3,32ms      query on / with `components/component/provides/firmware[@type='flashed'][text()='c6cd9ab0-8f20-512e-9e1f-1af55b8454b9']/../..|components/component/provides/firmware[@type='flashed'][text()='82741c78-f5dc-5c23-a152-00de5799edc8']/../..|components/component/provides/firmware[@type='flashed'][text()='7c0505be-b609-566e-bf94-561e441a9171']/../..` limit=1 -> 0 results
Nov 19 11:19:55 schneckenhaus fwupd[3971]: 10:19:55:0039 XbSilo               1,47ms      query on / with `components/component/provides/firmware[@type='flashed'][text()='fed2efa4-7045-55a1-b4fc-b29283d59fe5']/../..|components/component/provides/firmware[@type='flashed'][text()='8b72a10c-1279-5f8e-a28a-34fb11a58240']/../..` limit=1 -> 0 results
mue@schneckenhaus:~>

**Additional questions**
- Operating system and version: opensuse leap 15.2
- Have you tried unplugging the dock or any peripherals from your machine? I unplugged the dock. Then I retried the update. There were no updates possible then as the only one left was the one for the dock. I replugged the dock and tried it again. Then the update worked.
- Have you tried to power cycle the dock from the AC adapter? No.
- Is this a regression? I do not understand the question.

**Comment by mueihn** [comment]
I was able to solve it as described in the ticket.

**Comment by superm1** [comment]
Thanks for sharing.  Some of the architecture of how the update works has changed in modern fwupd versions, so I expect it's less problematic there.  Glad you sorted it after a few tries though on the older version.
