### ISSUE TITLE
invalid cast from 'GParamGType' to 'FwupdDevice'

### ISSUE THREAD

**Issue by artgreen** [fwupd/fwupd#2624]
**Describe the bug**
During boot or when adding/removing thunderbolt 3 dock, this message is seen.  fwupd is reported as failed with systemctl.

syslog:
Nov 28 11:22:27 rayon fwupd[2250]: 17:22:27:0354 GLib-GObject         invalid cast from 'GParamGType' to 'FwupdDevice'
Nov 28 11:22:27 rayon fwupd[2250]: 17:22:27:0354 Fwupd                fwupd_device_get_id: assertion 'FWUPD_IS_DEVICE (device)' failed
Nov 28 11:22:27 rayon fwupd[2250]: 17:22:27:0355 GLib-GObject         ../../../gobject/gsignal.c:3482: invalid object type 'GParamGType' for value type 'FuDevice'
Nov 28 11:22:27 rayon kernel: [  521.494387] show_signal_msg: 23 callbacks suppressed
Nov 28 11:22:27 rayon kernel: [  521.494392] fwupd[2250]: segfault at 7f150079657e ip 00007f15c39297a1 sp 00007fffa89c6490 error 4 in libgobject-2.0.so.0.6400.3[7f15c38fb000+36000]
Nov 28 11:22:27 rayon kernel: [  521.494413] Code: 00 00 00 49 8b 04 24 48 89 f7 48 85 c0 0f 84 a6 00 00 00 48 8b 28 48 81 fd fc 03 00 00 0f 86 f6 00 00 00 48 89 e8 48 83 e0 fc <0f> b6 70 16 40 c0 ee 02 89 f2 83 e6 01 83 e2 01 48 81 ff fc 03 00
Nov 28 11:22:28 rayon systemd[1]: fwupd.service: Main process exited, code=dumped, status=11/SEGV
Nov 28 11:22:28 rayon systemd[1]: fwupd.service: Failed with result 'core-dump'.

**Steps to Reproduce**
Boot or add/remove thunderbolt 3 dock.

**Expected behavior**
No SEGV and daemon remains running.

**fwupd version information**
Please provide the version of the daemon and client.
```shell
$ fwupdmgr --version
```
client version:	1.3.11
compile-time dependency versions
	gusb:	0.3.4
	efivar:	37
daemon version:	1.3.11

Please note how you installed it (`apt`, `dnf`, `pacman`, source, etc):
Installation of Pop!_OS and all updates.

**fwupd device information**
Please provide the output of the fwupd devices recognized in your system.

```shell
$ fwupdmgr get-devices --show-all-devices
```
20TK001FUS
│
├─ThinkPad Thunderbolt 3 Dock:
│ │   Device ID:           ffc1970ee618a65b745eaad8461c0aaa2772d1fe
│ │   Current version:     50.00
│ │   Vendor:              Lenovo (TBT:0x0108)
│ │   GUID:                75039175-c354-5df9-a798-5da41461c007
│ │   Device Flags:        • Updatable
│ │                        • Requires AC power
│ │                        • Device stages updates
│ │ 
│ ├─USB2.0 Hub:
│ │ │   Device ID:         7622d5fdbf1d1e08138156da7d83bf693986ad16
│ │ │   Summary:           USB 2.x Hub
│ │ │   Current version:   51.13
│ │ │   Vendor:            VIA Labs, Inc. (USB:0x17EF)
│ │ │   Install Duration:  15 seconds
│ │ │   GUIDs:             d5b585c2-e278-56ff-bd47-9bf0ad2bf9a9
│ │ │                      8ee94f0e-9b44-596a-bdd9-6f90401664cc
│ │ │                      0987e3c9-b1ee-5763-ac6e-51329b034e4b
│ │ │                      0488c1ec-e9d6-589f-8620-f0a7426a3c4e
│ │ │   Device Flags:      • Updatable
│ │ │                      • Cryptographic hash verification is available
│ │ │                      • Device stages updates
│ │ │                      • Device can recover flash failures
│ │ │ 
│ │ └─MSP430:
│ │       Device ID:       36cd45c89e19806b1cd99ece89baf4eed34ab921
│ │       Summary:         I²C Dock Management Device
│ │       Current version: 28.1
│ │       Vendor:          VIA Labs, Inc. (USB:0x17EF)
│ │       GUID:            3b09a564-e8a7-5e39-b93b-5b8468e5e3b8
│ │       Device Flags:    • Updatable
│ │     
│ ├─USB3.1 Hub:
│ │ │   Device ID:         48b0e21e27b6bab9c8208a603e5b65d8a42344e5
│ │ │   Summary:           USB 3.x Hub
│ │ │   Current version:   51.13
│ │ │   Vendor:            VIA Labs, Inc. (USB:0x17EF)
│ │ │   Install Duration:  15 seconds
│ │ │   GUIDs:             4ad676ff-8529-5cb0-930d-e3a1da2c60cb
│ │ │                      8aab7e9b-2ae8-559b-9be0-49bf5a647a2a
│ │ │                      a9866465-e1ec-5ce0-855d-162d817aeca2
│ │ │                      06fb2b19-690e-5296-8d0a-6e32a6fccd84
│ │ │   Device Flags:      • Updatable
│ │ │                      • Cryptographic hash verification is available
│ │ │                      • Device stages updates
│ │ │                      • Device can recover flash failures
│ │ │ 
│ │ ├─MSP430:
│ │ │     Device ID:       61004711a9f6eed5d7a2a22e0469643b241012cf
│ │ │     Summary:         I²C Dock Management Device
│ │ │     Current version: 28.1
│ │ │     Vendor:          VIA Labs, Inc. (USB:0x17EF)
│ │ │     GUID:            7a810ce4-928e-5a4a-b0cd-564f46cfe3a7
│ │ │     Device Flags:    • Updatable
│ │ │   
│ │ └─USB3.1 Hub:
│ │       Device ID:       26c4f1230928a9765029f8f2e5c82bef85f55d8e
│ │       Summary:         USB 3.x Hub
│ │       Current version: 51.13
│ │       Vendor:          VIA Labs, Inc. (USB:0x17EF)
│ │       Install Duration:15 seconds
│ │       GUIDs:           4ad676ff-8529-5cb0-930d-e3a1da2c60cb
│ │                        8aab7e9b-2ae8-559b-9be0-49bf5a647a2a
│ │                        672d37eb-2a8c-54fd-88f2-0faecea5f5e6
│ │                        06fb2b19-690e-5296-8d0a-6e32a6fccd84
│ │       Device Flags:    • Updatable
│ │                        • Cryptographic hash verification is available
│ │                        • Device stages updates
│ │                        • Device can recover flash failures
│ │     
│ ├─ThinkPad Thunderbolt 3 Dock USB Audio:
│ │     Device ID:         901515bb1e030acc17640c170ae1505f8e6d7766
│ │     Summary:           CX20985 USB audio device
│ │     Current version:   04-0E-90
│ │     Bootloader Version:02.00.00.00
│ │     Vendor:            Lenovo (USB:0x17EF)
│ │     Install Duration:  3 seconds
│ │     GUIDs:             b106286b-108d-5708-a4bd-dff70ce90eea
│ │                        1d987aa4-e89a-5bd3-b78c-5ec8bdc6e213
│ │                        d66bf84b-c3ba-508c-bc55-0d445413d3d4
│ │                        7083139e-9fec-5fc3-9e1a-a0fb3ae1bccf
│ │     Device Flags:      • Updatable
│ │   
│ └─USB2.0 Hub:
│       Device ID:         41e05553a1ab1f2890f40d27053a8f09772f8353
│       Summary:           USB 2.x Hub
│       Current version:   51.13
│       Vendor:            VIA Labs, Inc. (USB:0x17EF)
│       Install Duration:  15 seconds
│       GUIDs:             d5b585c2-e278-56ff-bd47-9bf0ad2bf9a9
│                          8ee94f0e-9b44-596a-bdd9-6f90401664cc
│                          0987e3c9-b1ee-5763-ac6e-51329b034e4b
│                          0488c1ec-e9d6-589f-8620-f0a7426a3c4e
│       Device Flags:      • Updatable
│                          • Cryptographic hash verification is available
│                          • Device stages updates
│                          • Device can recover flash failures
│     
├─Thunderbolt Controller:
│     Device ID:           dc588f768d2e8e322ca16c0ab66d55676b222f7e
│     Summary:             Unmatched performance for high-speed I/O
│     Current version:     59.00
│     Vendor:              Lenovo (TBT:0x0109)
│     GUIDs:               0c42d35e-20c9-5c9b-9fc2-9d596a7f1c9e
│                          66f32039-10c2-5be5-90dc-123e0648f99a
│     Device Flags:        • Internal device
│                          • Updatable
│                          • Requires AC power
│                          • Device stages updates
│   
├─Prometheus:
│ │   Device ID:           d432baa2162a32c1554ef24bd8281953b9d07c11
│ │   Summary:             Fingerprint reader
│ │   Current version:     10.01.3224691
│ │   Vendor:              Synaptics (USB:0x06CB)
│ │   Install Duration:    2 seconds
│ │   GUIDs:               09e8bf16-3e69-50f5-bb66-c7a040248352
│ │                        8088f861-6318-5b1e-9ce4-fbddbedb09ac
│ │   Device Flags:        • Updatable
│ │                        • Supported on remote server
│ │                        • Cryptographic hash verification is available
│ │ 
│ └─Prometheus IOTA Config:
│       Device ID:         8dcffb5d059857368caa2b7b22371ebd831b0c0c
│       Current version:   0030
│       Minimum Version:   0030
│       Vendor:            Synaptics (USB:0x06CB)
│       GUID:              7c5a1e62-38fa-5859-9337-09dbac6377e4
│       Device Flags:      • Updatable
│                          • Supported on remote server
│     
├─Display controller:
│     Device ID:           71b677ca0f1bc2c5b804fa1d59e52064ce589293
│     Current version:     a1
│     Vendor:              NVIDIA Corporation (PCI:0x10DE)
│     GUIDs:               e8982b3b-d8c4-5f23-af8e-33999c0e8026
│                          6eec15ed-752e-5418-99ae-3171b61091ef
│     Device Flags:        • Internal device
│                          • Cryptographic hash verification is available
│   
├─SKHynix HFS512GD9TNI-L2B0B:
│     Device ID:           08e1798bf5d9cb56a0290b552cab6c1a371b5089
│     Summary:             NVM Express Solid State Drive
│     Current version:     11710C10
│     Vendor:              SK hynix (NVME:0x1C5C)
│     GUIDs:               af90743d-93b0-5a7f-b3aa-08db33ab1f82
│                          85ef24c5-fc0a-57a6-ab37-5711ac8acfbb
│                          930d3ce1-d73d-582e-84df-190dad19f650
│     Device Flags:        • Internal device
│                          • Updatable
│                          • Requires AC power
│                          • Needs a reboot after installation
│                          • Device is usable for the duration of the update
│   
├─System Firmware:
│     Device ID:           da99ffa7e037e614f6f43e730e9aedba0a603152
│     Current version:     0.1.7
│     Minimum Version:     0.1.0
│     Vendor:              LENOVO (DMI:LENOVO)
│     Update Error:        TPM PCR0 differs from reconstruction, please see https://github.com/fwupd/fwupd/wiki/TPM-PCR0-differs-from-reconstruction
│     GUID:                6e58e73d-8061-44e4-8949-33b7f0d5c726
│     Device Flags:        • Internal device
│                          • Updatable
│                          • Requires AC power
│                          • Supported on remote server
│                          • Needs a reboot after installation
│                          • Cryptographic hash verification is available
│                          • Device is usable for the duration of the update
│   
├─TPM:
│ │   Device ID:           c6a80ac3a22083423992a3cb15018989f37834d6
│ │   Current version:     1.258.0.0
│ │   Vendor:              ST Microelectronics (TPM:STM)
│ │   GUIDs:               ff71992e-52f7-5eea-94ef-883e56e034c6
│ │                        84df3581-f896-54d2-bd1a-372602f04c32
│ │                        bfaed10a-bbc1-525b-a329-35da2f63e918
│ │                        70b7b833-7e1a-550a-a291-b94a12d0f319
│ │                        06f005e9-cb62-5d1a-82d9-13c534c53c48
│ │   Device Flags:        • Internal device
│ │ 
│ └─Event Log:
│       Device ID:         58bd405f31c48e6eca290b425f530a94c91e955c
│       Vendor:            ST Microelectronics (TPM:STM)
│       GUID:              a25657fe-b5dc-5be0-8b78-8b9dfec678ff
│       Device Flags:      • Internal device
│     
├─UEFI Device Firmware:
│     Device ID:           b8b1b1380354a2ed53080188804a3b8745d875c8
│     Current version:     224.36.1158
│     Minimum Version:     0.0.1
│     Vendor:              DMI:LENOVO
│     GUID:                bafed3f2-f4e7-42d7-b9e1-4defa2fbf157
│     Device Flags:        • Internal device
│                          • Updatable
│                          • Requires AC power
│                          • Needs a reboot after installation
│                          • Device is usable for the duration of the update
│   
├─UEFI Device Firmware:
│     Device ID:           6d9eb6430db8e288b0287036bbb254bf92aa52c6
│     Current version:     0.1.5
│     Minimum Version:     0.1.5
│     Vendor:              DMI:LENOVO
│     GUID:                b616d3d6-cca9-40bd-964e-b86ffb62744d
│     Device Flags:        • Internal device
│                          • Updatable
│                          • Requires AC power
│                          • Supported on remote server
│                          • Needs a reboot after installation
│                          • Device is usable for the duration of the update
│   
├─UEFI Device Firmware:
│     Device ID:           dbea39b96e61b7b1bc31f03e8b0530935b3989bb
│     Current version:     1.0.6
│     Minimum Version:     0.0.1
│     Vendor:              DMI:LENOVO
│     GUID:                439d54f4-5548-4698-a8b0-46a047c0e66e
│     Device Flags:        • Internal device
│                          • Updatable
│                          • Requires AC power
│                          • Needs a reboot after installation
│                          • Device is usable for the duration of the update
│   
└─UEFI Device Firmware:
      Device ID:           aaa9b84f8cf13c5db4bbc894a23240288b663514
      Current version:     0.1.258
      Minimum Version:     0.1.258
      Vendor:              DMI:LENOVO
      GUID:                3fb9a55d-d7f1-4d1b-b216-74e328e28f51
      Device Flags:        • Internal device
                           • Updatable
                           • Requires AC power
                           • Needs a reboot after installation
                           • Device is usable for the duration of the update

**Additional questions**
- Operating system and version:
Linux rayon 5.8.0-7630-generic #32~1605108853~20.04~8bcf10e-Ubuntu SMP Wed Nov 11 22:42:16 UTC  x86_64 x86_64 x86_64 GNU/Linux
- Have you tried rebooting?
A thousand times.
- Is this a regression?
Unknown - first time dealing with thunderbolt 3 and this issue.

**Comment by hughsie** [comment]
Does the problem disappear with 1.4.x or 1.5.x?

**Comment by superm1** [comment]
This feels like a hand install and packaged install both on the same system.  Do you have anything lingering in `/usr/local`?
