### ISSUE TITLE
fix config section in example uefi_capsule.conf

### ISSUE THREAD

**Issue by gdamjan** [fwupd/fwupd#2748]
**Describe the bug**
 The config section name in the example [uefi_capsule.conf](https://github.com/fwupd/fwupd/blob/master/plugins/uefi-capsule/uefi_capsule.conf) file needs to changed to `[uefi_capsule]`, since the change of the plugin name.

**Steps to Reproduce**

Install fwupd, edit `/etc/fwupd/uefi_capsule.conf` to un-comment (for ex. `DisableShimForSecureBoot=true`), the configuration is not honored.

**fwupd version information**

```shell
$ fwupdmgr --version
client version: 1.5.5
compile-time dependency versions
        gusb:   0.3.5

Unknown                  [***************************************]
daemon version: 1.5.5
```

```
$ pacman -Qs fwupd
local/fwupd 1.5.5-1
    Simple daemon to allow session software to update firmware
```

**Comment by superm1** [comment]
@gdamjan thanks for filing. Would you mind submitting a PR?
@hughsie Bessides the starting template conf, do we need to think about this for upgrades at all you think?  Some sort of migration from `[uefi]` to `[uefi_capsule`?

**Comment by hughsie** [comment]
@superm1 I think migrations like this are probably handled better by the packagers rather than "upstream" -- and certainly a `sed` could be done in the debian scripts.
