### ISSUE TITLE
fwupdtool install can't deal with multiple firmware files in one shot (*.cab)

### ISSUE THREAD

**Issue by CragW** [fwupd/fwupd#2812]
**Describe the bug**
Given fuzzy files path/to/*.cab to fwupdtool install, will see failures in either device no found or Invalid arguments. Issue is not seen if only one file in the result.

**Steps to Reproduce**
Scenario 1, no *.cab at all
```
# ls -al /tmp/*.cab
ls: cannot access '/tmp/*.cab': No such file or directory
# fwupdtool install /tmp/*.cab
Loading…                 [***************************************] ]
WARNING: This package has not been validated, it may not work properly.
Failed to open file “/tmp/*.cab”: No such file or directory
Segmentation fault
```

Scenario 2, device not found
```
# ls -al /tmp/*.cab
-rw-r--r-- 1 crabx crabx 353422 Jan 27 21:48 /tmp/SSSTC_CL1_22301115.cab
-rw-r--r-- 1 crabx crabx 358896 Jan 27 21:48 /tmp/SSSTC_CL1_22321113.cab
# fwupdtool install /tmp/*.cab
Loading…                 [***************************************] ]
WARNING: This package has not been validated, it may not work properly.
device ID /tmp/SSSTC_CL1_22321113.cab was not found
```

Scenario 3, Invalid arguments
```
# ls -al /tmp/*.cab
-rw-r--r-- 1 crabx crabx 552949 Jan 27 21:48 /tmp/BC501A_80001101_128GB.cab
-rw-r--r-- 1 crabx crabx 353422 Jan 27 21:48 /tmp/SSSTC_CL1_22301115.cab
-rw-r--r-- 1 crabx crabx 358896 Jan 27 21:48 /tmp/SSSTC_CL1_22321113.cab
# fwupdtool install /tmp/*.cab
Loading…                 [***************************************] ]
WARNING: This package has not been validated, it may not work properly.
Invalid arguments

Use fwupdtool --help for help
```

**Expected behavior**
The number of values should be handled nicely

**fwupd version information**
```shell
$ fwupdmgr --version
client version: 1.5.5-94-gda7b898f
compile-time dependency versions
        gusb:   0.3.5
```

Please note how you installed it (`apt`, `dnf`, `pacman`, source, etc):
source

**fwupd device information**
Please provide the output of the fwupd devices recognized in your system.

```shell
# skipped
```

**Additional questions**
- Operating system and version: Ubuntu 20.04.1 LTS (Focal Fossa)
- Have you tried rebooting? Yes
- Is this a regression? No

**Comment by CragW** [comment]
filename = /tmp/*.cab
`fu_common_get_contents_bytes` finds no content for ***.cab** therefore returned back to the caller `fu_util_cmd_arrary_run` callback.

```
	filename = fu_util_download_if_required (priv, values[0], error);
	if (filename == NULL)
		return FALSE;

	/* parse silo */
	blob_cab = fu_common_get_contents_bytes (filename, error);
	if (blob_cab == NULL) {
		fu_util_maybe_prefix_sandbox_error (filename, error);
		return FALSE;
	}
```

**Comment by hughsie** [comment]
The crash is at least fixed by https://github.com/fwupd/fwupd/pull/2814/commits/46764bd83f0827587ad77ccc866c95b050f9bbdc

**Comment by hughsie** [comment]
Shouldn't the shell do the glob expansion?

**Comment by CragW** [comment]
Yes, you are right. I think fuzzy search is in fact working properly, no issues in that part.  The fuzzy files **\*.cab** can be expanded correctly with its presence, and install worked properly if only 1 cab file exists.

I think the real issues are:
1. No **\*.cab** found at all, i.e.: `filename = /tmp/*.cab`, ultimately install failed (zero content)
2. Multiple **\*.cab** found: could be device no found if results = 2, also could be `Invalid arguments` if results > 2.

I will update the bug description.

**Comment by hughsie** [comment]
I think `fwupdtool` isn't going to love multiple files and that's okay. Remember fwupdtool is really only for fwupd development and debugging -- most users should be using `fwupdmgr` and the dameon.

**Comment by CragW** [comment]
Sure, I'm going to close this as won't fix.
