### ISSUE TITLE
install_dell_bios_exe.py: ValueError: Namespace Fwupd not available

### ISSUE THREAD

**Issue by paulmenzel** [fwupd/fwupd#2836]
On Debian sid/unstable, trying to follow https://github.com/fwupd/firmware-dell/blob/master/README.md, the command fails.

```
$ dpkg -l fwupd
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  fwupd          1.5.5-2      amd64        Firmware update daemon
$ fwupdmgr --version
client version:	1.5.5
compile-time dependency versions
	gusb:	0.3.5

daemon version:	1.5.5
$ sudo /usr/share/fwupd/install_dell_bios_exe.py XPS_13_9310_2-in-1_2.0.0.exe
Traceback (most recent call last):
  File "/usr/share/fwupd/install_dell_bios_exe.py", line 13, in <module>
    gi.require_version('Fwupd', '2.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Fwupd not available
```

**Comment by superm1** [comment]
Do you have the gir package installed too?

**Comment by paulmenzel** [comment]
> Do you have the `gir1.2-fwupd-2.0` package installed too?

It was not installed. `apt install gir1.2-fwupd-2.0` fixed the issue. It’s not listed in the package metadata:

    Recommends: python3, bolt, dbus, secureboot-db, udisks2, fwupd-signed

There is no `Suggests` entry.

**Comment by superm1** [comment]
Yeah we don't want it installed by default, so not in `Recommends` I think is the correct solution.  Suggests seems like a good consolation.

**Comment by paulmenzel** [comment]
Sounds good.

Additionally, is there a way to catch this error, and print instructions to install the required packages?

**Comment by superm1** [comment]
The package name is going to vary from OS to OS, I guess we can list a few things to try though maybe.

**Comment by paulmenzel** [comment]
Indeed. Or link to some Wiki page or so.
