### ISSUE TITLE
fwupdmgr refresh on a Fitlet device can't resolve hostname

### ISSUE THREAD

**Issue by carlospenedorocha** [fwupd/fwupd#2862]
**Describe the bug**
First, let me say that I'm not totally sure this issue is related to fwupd or to the firmware vendor itself or LVFS per se. 

I have a Fitlet device (from Compulab) running Ubuntu Core16. All snaps are up to date.

When I run `sudo uefi-fw-tools.fwupdmgr refresh`, I get the following:
"Failed to download https://secure-lvfs.rhcloud.com/downloads/firmware.xml.gz.asc: Cannot resolve hostname"

From the device, I can ping any other hosts, even "rhcloud.com". It's not a DNS thing going on in the device.

**Steps to Reproduce**
1. on a Fitlet device, just run `uefi-fw-tools.fwupdmgr refresh`

**Expected behavior**
Should be able to refresh.

**fwupd version information**

It is a snap package.
_uefi-fw-tools: version 1.5.4-0.7.2+git, rev 48, latest/beta_ (same issue was observed in rev 22 latest/stable)

**fwupd device information**
![image](https://user-images.githubusercontent.com/10661562/107507644-27b45080-6ba0-11eb-9152-edd25f8fb2fa.png)

**System UEFI configuration**
Please provide the output of the following commands:
```shell
$ efibootmgr -v
```
![image](https://user-images.githubusercontent.com/10661562/107531967-abc90100-6bbd-11eb-8e28-8fdf1607f377.png)

**Additional questions**
- Operating system and version: _Ubuntu Core16_
- Have you tried rebooting? _Yes_
- Is this a regression? _Don't know, first time trying, but I know it works on Dell gateway devices_ 
- Are you using an NVMe disk? _Not sure, probably not as per the specs_
- Is secure boot enabled? _No_
- Is this a Lenovo system with 'Boot Order Lock' turned on in the BIOS? _No_

**Comment by hughsie** [comment]
> Failed to download https://secure-lvfs.rhcloud.com/downloads/firmware.xml.gz.asc

We've not used that domain for several years. I think you've installed the wrong snap.
