### ISSUE TITLE
No device test for the Lenovo 3in1 device

### ISSUE THREAD

**Issue by hughsie** [fwupd/fwupd#2941]
**Describe the bug**

There is no device-test .json file for the Lenovo 3-in-1 hub, and so I'm unable to test if it still works before I tag each release. Can you please upload two test firmwares to the LVFS, preferably with the HUB and i2c firmware and then create a pull request with the .json file please? I can see the usbhub enumerate fine, but the _presumably_ parade device doesn't show up. Thanks!

**Comment by memily** [comment]
An update: we're on standby, awaiting ODM response!
