### ISSUE TITLE
quirk error with samsung nvme ssd

### ISSUE THREAD

**Issue by githubamaury** [fwupd/fwupd#2965]
Mär 03 00:19:59 Ubuntu fwupd[64915]: ERROR:esys:src/tss2-esys/esys_context.c:69:Esys_Initialize() Initialize default tcti. ErrorCode (0x000a000a)
Mär 03 00:19:59 Ubuntu fwupd[64915]: 23:19:59:0514 FuDeviceList         ignoring device 021c53bc312787cabde26ca5239ad8cdd7bbcd70 [ata] existing device f7827>
Mär 03 00:19:59 Ubuntu fwupd[64915]: 23:19:59:0518 FuDeviceList         ignoring device 329753bec683ffe0ab0b54462e27303bf2764c58 [ata] existing device f7827>
Mär 03 00:19:59 Ubuntu fwupd[64915]: OUI quirk required, please see https://github.com/fwupd/fwupd/wiki/ATA-Disk:-OUI-Quirk-Required!
Mär 03 00:19:59 Ubuntu fwupd[64915]: ---
Mär 03 00:19:59 Ubuntu fwupd[64915]: [DeviceInstanceId=OUI\0024e9]
Mär 03 00:19:59 Ubuntu fwupd[64915]: Vendor = Samsung
Mär 03 00:19:59 Ubuntu fwupd[64915]: VendorId = ATA:0x144D

**Comment by hughsie** [comment]
Hi thanks for the report, but we added a workaround for this case. Newer fwupd versions have fixed this. Thanks!

https://github.com/fwupd/fwupd/wiki/ATA-Disk:-OUI-Quirk-Required
