### ISSUE TITLE
elantp plugin incorrectly sets multiple GTypes

### ISSUE THREAD

**Issue by tari** [fwupd/fwupd#3148]
The elantp plugin's `fu_plugin_init` function calls `fu_plugin_set_device_gtype` multiple times, with the effect that the second call replaces the first which ends up having no effect.

If I correctly understand how GType assignment works, this means I2C devices will never be handled because every device associated with that plugin will be a `FuElanTpHidDevice`, with the `GType` quirk for I2C devices being ignored. Or if I've misunderstood that, at least the multiple calls to `set_device_gtype` are misleading.

**Comment by hughsie** [comment]
I think the ccgx is misleading in the same way. I don't think it's a bug per-se, as elantp specifies `GType = FuElantpHidDevice` and `GType = FuElantpI2cDevice` in the quirk file, which takes precedence over the plugin default. I think ccgx is _lucky_ also. Patch coming up to make it a lot clearer.
