### ISSUE TITLE
Implement --enable-json-state in fwupdmgr (currently only on fwupdtool)

### ISSUE THREAD

**Issue by djcampello** [fwupd/fwupd#3198]

**Comment by superm1** [comment]
Counter-argument - Why not just use `fwupdagent get-devices` after you're done with `fwupdmgr` calls?

**Comment by djcampello** [comment]
I do not have that binary: 
$ equery f fwupd | grep fwupdagent

**Comment by hughsie** [comment]
@djcampello you need to build with -Dagent=true (which is default, so I think you might have switched it off by mistake).

**Comment by djcampello** [comment]
Thank you!
