### ISSUE TITLE
Package dependancy for Hirsute

### ISSUE THREAD

**Issue by Sean-StarLabs** [fwupd/fwupd#3340]
Debian package doesn't work when built for Hirsute, has the error `/usr/libexec/fwupd/efi/fwupdx64.efi cannot be found`.

Seems to be dependency related, as`libtss2-esys0` doesn't exist and has been replaced with `libtss2-esys-3.0.2-0`

Not sure how to submit a PR, as changing the package name in the `dependancies.xml` would break more version than it would fix.

**Comment by superm1** [comment]
It's intentionally split, but the packages aren't landed in Ubuntu or Debian yet.   Build the package for the EFI binary from here: http://github.com/fwupd/fwupd-efi
