### ISSUE TITLE
Building with gi-docgen fails with with: docs/meson.build:17:2: ERROR: Unknown variable "fwupd_gir".

### ISSUE THREAD

**Issue by Whissi** [fwupd/fwupd#3355]
**Describe the bug**
Trying to build fwupd-1.6.1 with gi-docgen fails in configure phase with error
```docs/meson.build:17:2: ERROR: Unknown variable "fwupd_gir".```

**Steps to Reproduce**
Try building with `-Ddocs=docgen`.

**Comment by superm1** [comment]
Do you have introspection turned off? Can you please share your build command and environment for reproducing?

**Comment by Whissi** [comment]
Yes, introspection was turned off.

**Comment by superm1** [comment]
Docgen uses introspection data, so to be expected. Added a commit to make it clearer in future.
