### ISSUE TITLE
purpose of upower.conf

### ISSUE THREAD

**Issue by binaryNewts** [fwupd/fwupd#3384]
In the most recent version of upower.conf, line 5, `#BatteryThreshold=10`, is commented out. I was wondering what the purpose of this file is without this line. What does this file do in the current version, or should it be removed?

( @bleungatchromium @g2pop @djcampello )

**Comment by superm1** [comment]
Since you're CC chrome people it's worth mentioning - chrome doesn't use upower though.

**Comment by bleungatchromium** [comment]
> Since you're CC chrome people it's worth mentioning - chrome doesn't use upower though.

We know. :)

I'd like to introduce my interns for the summer, @binaryNewts  and @g2pop . They're going to add a new plugin to support the power manager daemon we use on Chrome OS.

**Comment by hughsie** [comment]
In that context, I think it makes sense to move the data in upower.quirk into some kind of common place. We don't need to duplicate that.

**Comment by superm1** [comment]
Nice to meet y'all.

Agree Richard.

Maybe `daemon.conf`?

**Comment by hughsie** [comment]
.quirk, but yes.
