### ISSUE TITLE
New FW seems published twice ?

### ISSUE THREAD

**Issue by joakim-tjernlund** [fwupd/fwupd#3434]
Looking at https://fwupd.org/lvfs/firmware/new is looks like most(every?) FW release is published twice.

**Comment by hughsie** [comment]
Hmm, interesting. Investigating now.

**Comment by hughsie** [comment]
Probably fixed in https://gitlab.com/fwupd/lvfs-website/-/merge_requests/1035 -- will test with staging first.

**Comment by hughsie** [comment]
Okay mostly fixed. There's one issue I need to fix lower prio where some FirmwareEvent objects are duplicated for some reason.

**Comment by joakim-tjernlund** [comment]
I can see that, thanks :)

**Comment by joakim-tjernlund** [comment]
FYI, the latest  ```Lenovo ThinkStation P620 Embedded Controller Update``` also looks duplicated. 
I guess this is due to the  ```FirmwareEvent objects``` you mentioned above.

**Comment by hughsie** [comment]
Hmm, this is kinda legitimate:

![Screenshot 2021-07-04 at 17-51-33 LVFS Target](https://user-images.githubusercontent.com/151380/124393114-d6dcfa00-dcf0-11eb-8167-46fb8497e29c.png)

I think I need a `distinct` or something in the query.

**Comment by hughsie** [comment]
Fixed properly in https://gitlab.com/fwupd/lvfs-website/-/commit/68ada3d1bbde630cfc37a5c973e09320601757a3 -- will deploy that sometime the end of this week.

**Comment by joakim-tjernlund** [comment]
Does that fix the latest dell fw with same name but different versions? Details for both these point to the same version.

Skaffa Outlook för Android<https://aka.ms/ghei36>

________________________________
