### ISSUE TITLE
ThinkPad Thunderbolt 3 Workstation Dock Gen 1 & 2; firmware incompatible, got VL820Q8, expected VL820Q7

### ISSUE THREAD

**Issue by josiah47** [fwupd/fwupd#3460]
**Describe the bug**
sudo fwupdmgr update
results in error firmware incompatible, got VL820Q8, expected VL820Q7

**Steps to Reproduce**
sudo fwupdmgr get-updates
sudo fwupdmgr update
Restarting device…       [-                                      ]Devices with no available firmware updates: 
 • Thunderbolt host controller
 • UEFI Device Firmware
 • UEFI Device Firmware
 • USB2.0 Hub
 • USB2.0 Hub
 • USB3.0 Hub
Upgrade available for ThinkPad Thunderbolt 3 Dock from 56.00 to 62.00
ThinkPad Thunderbolt 3 Dock and all connected devices may not be usable while updating. Continue with update? [Y|n]: y
Downloading…             [***************************************]
Decompressing…           [***************************************]
Authenticating…          [***************************************]
Authenticating…          [***************************************]
Updating ThinkPad Thunderbolt 3 Dock USB Audio…******************]
Restarting device…       [***************************************]
Updating USB3.1 Hub…     [************************************** ]
Restarting device…       [************************************** ]firmware incompatible, got VL820Q8, expected VL820Q7

**Expected behavior**
Firmware to be applied

**fwupd version information**
Please provide the version of the daemon and client.
```shell
$ fwupdmgr --version
```
fwupdmgr --version
client version:	1.6.0
compile-time dependency versions
	gusb:	0.3.6

Restarting device…       [-                                      ]daemon version:	1.6.0

Please note how you installed it (`apt`, `dnf`, `pacman`, source, etc):
`sudo fwupdmgr update

**fwupd device information**
Please provide the output of the fwupd devices recognized in your system.

```shell
$ fwupdmgr get-devices --show-all-devices
```
fwupdmgr get-devices --show-all-devices
Restarting device…       [-                                      ]20SUS34700
│
├─ThinkPad Thunderbolt 3 Dock:
│ │   Device ID:          11ef1614a9d17196a5e780378194750b11296379
│ │   Current version:    56.00
│ │   Vendor:             Lenovo (THUNDERBOLT:0x0108|TBT:0x0108)
│ │   GUIDs:              45c1814e-eb83-5b03-8997-ef8d4d8ade29
│ │                       03b97e38-f4b8-5a19-917c-28f95ca29768
│ │                       75039175-c354-5df9-a798-5da41461c007
│ │   Device Flags:       • Updatable
│ │                       • System requires external power source
│ │                       • Supported on remote server
│ │                       • Device stages updates
│ │ 
│ ├─USB3.1 Hub:
│ │ │   Device ID:        48b0e21e27b6bab9c8208a603e5b65d8a42344e5
│ │ │   Summary:          USB 3.x Hub
│ │ │   Current version:  51.53
│ │ │   Vendor:           VIA Labs, Inc. (USB:0x17EF)
│ │ │   Install Duration: 15 seconds
│ │ │   GUIDs:            8ee94f0e-9b44-596a-bdd9-6f90401664cc
│ │ │                     a1727546-5530-5e5a-96a0-9fcd47956b54
│ │ │                     8aab7e9b-2ae8-559b-9be0-49bf5a647a2a
│ │ │                     a9866465-e1ec-5ce0-855d-162d817aeca2
│ │ │                     06fb2b19-690e-5296-8d0a-6e32a6fccd84
│ │ │   Device Flags:     • Updatable
│ │ │                     • Supported on remote server
│ │ │                     • Cryptographic hash verification is available
│ │ │                     • Device stages updates
│ │ │                     • Device can recover flash failures
│ │ │ 
│ │ └─USB3.1 Hub:
│ │   │   Device ID:      26c4f1230928a9765029f8f2e5c82bef85f55d8e
│ │   │   Summary:        USB 3.x Hub
│ │   │   Current version:51.33
│ │   │   Vendor:         VIA Labs, Inc. (USB:0x17EF)
│ │   │   Install Duration:15 seconds
│ │   │   GUIDs:          8ee94f0e-9b44-596a-bdd9-6f90401664cc
│ │   │                   3e9ec9de-6c88-520b-b768-d3839446d508
│ │   │                   8aab7e9b-2ae8-559b-9be0-49bf5a647a2a
│ │   │                   672d37eb-2a8c-54fd-88f2-0faecea5f5e6
│ │   │                   06fb2b19-690e-5296-8d0a-6e32a6fccd84
│ │   │   Device Flags:   • Updatable
│ │   │                   • Supported on remote server
│ │   │                   • Cryptographic hash verification is available
│ │   │                   • Device stages updates
│ │   │                   • Device can recover flash failures
│ │   │ 
│ │   └─ThinkPad Thunderbolt 3 Dock USB Audio:
│ │         Device ID:    901515bb1e030acc17640c170ae1505f8e6d7766
│ │         Summary:      CX20985 USB audio device
│ │         Current version:04-0E-92
│ │         Bootloader Version:02.00.00.00
│ │         Vendor:       Lenovo (USB:0x17EF)
│ │         Install Duration:3 seconds
│ │         GUIDs:        effe6afa-9e41-5ed0-b66e-dad13853a7bb
│ │                       1d987aa4-e89a-5bd3-b78c-5ec8bdc6e213
│ │                       d66bf84b-c3ba-508c-bc55-0d445413d3d4
│ │                       7083139e-9fec-5fc3-9e1a-a0fb3ae1bccf
│ │         Device Flags: • Updatable
│ │                       • Supported on remote server
│ │       
│ └─USB2.0 Hub:
│   │   Device ID:        7622d5fdbf1d1e08138156da7d83bf693986ad16
│   │   Summary:          USB 2.x Hub
│   │   Current version:  51.53
│   │   Vendor:           VIA Labs, Inc. (USB:0x17EF)
│   │   Install Duration: 15 seconds
│   │   GUIDs:            3f573903-3939-5e9d-9350-7d02a283a03a
│   │                     8ee94f0e-9b44-596a-bdd9-6f90401664cc
│   │                     0987e3c9-b1ee-5763-ac6e-51329b034e4b
│   │                     0488c1ec-e9d6-589f-8620-f0a7426a3c4e
│   │   Device Flags:     • Updatable
│   │                     • Cryptographic hash verification is available
│   │                     • Device stages updates
│   │                     • Device can recover flash failures
│   │ 
│   └─USB2.0 Hub:
│         Device ID:      41e05553a1ab1f2890f40d27053a8f09772f8353
│         Summary:        USB 2.x Hub
│         Current version:51.33
│         Vendor:         VIA Labs, Inc. (USB:0x17EF)
│         Install Duration:15 seconds
│         GUIDs:          a023c536-1f42-5215-9b66-1d330c939426
│                         8ee94f0e-9b44-596a-bdd9-6f90401664cc
│                         1e96bd9e-b77e-5eb1-ba44-9c04a3d7c288
│                         0488c1ec-e9d6-589f-8620-f0a7426a3c4e
│         Device Flags:   • Updatable
│                         • Cryptographic hash verification is available
│                         • Device stages updates
│                         • Device can recover flash failures
│       
├─Thunderbolt host controller:
│     Device ID:          eb46550a2a3fa5dee2d5124ec363655e8a425749
│     Summary:            Unmatched performance for high-speed I/O
│     Current version:    58.00
│     Vendor:             Lenovo (THUNDERBOLT:0x0109|TBT:0x0109)
│     GUIDs:              89ed2e28-cda1-525b-9f93-3a612886ed2f
│                         ba579c8e-a00d-51ca-bcad-8a5ec2e11cce
│                         5225cc79-d03b-51d3-9c2e-e6717e230901
│                         324807c0-e420-53ab-9322-432018cd2f93
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Device stages updates
│   
├─Embedded Controller:
│     Device ID:          5be5a414a88d3f7bb76496a2f38a33883723c8d2
│     Current version:    65550
│     Minimum Version:    65550
│     Vendor:             DMI:LENOVO
│     GUIDs:              907f1b02-59a6-4b5a-b1ec-288eb7513434
│                         a8b99c9d-df13-5f6f-bde0-b38689673405
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Supported on remote server
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─Intel Management Engine:
│     Device ID:          489e154fdb22e0d8e8d59e41eb8c726707b6902c
│     Current version:    224.48.1605
│     Minimum Version:    0.0.1
│     Vendor:             DMI:LENOVO
│     GUIDs:              fe3092e8-99e0-4ff6-b7c3-357d08f77580
│                         481df13f-be2b-5460-9cda-e0f3d4326c88
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Supported on remote server
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─Intel(R) Core™ i5-10400H CPU @ 2.60GHz:
│     Device ID:          4bde70ba4e39b28f9eab1628f9dd6e6244c03027
│     Current version:    0x000000ea
│     Vendor:             Intel
│     GUIDs:              b9a2dd81-159e-5537-a7db-e7101d164d3f
│                         30249f37-d140-5d3e-9319-186b1bd5cac3
│                         a45b0522-5722-54bd-b802-86cd044262df
│                         7b9b6e8c-226c-5db6-86cb-ea3187578013
│     Device Flags:       • Internal device
│   
├─SKHynix HFS512GD9TNI-L2B0B:
│     Device ID:          08e1798bf5d9cb56a0290b552cab6c1a371b5089
│     Summary:            NVM Express Solid State Drive
│     Current version:    11720C10
│     Vendor:             SK hynix (NVME:0x1C5C)
│     GUIDs:              424e8633-6c06-5c41-bd78-fbcb483dc0fb
│                         b7603cf7-873e-59e8-b7aa-9d8a9877b6e7
│                         af90743d-93b0-5a7f-b3aa-08db33ab1f82
│                         85ef24c5-fc0a-57a6-ab37-5711ac8acfbb
│                         930d3ce1-d73d-582e-84df-190dad19f650
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Supported on remote server
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─System Firmware:
│ │   Device ID:          5f177a3bd519ece03c345228af4255a1f5916ae2
│ │   Current version:    0.1.21
│ │   Vendor:             LENOVO (DMI:LENOVO)
│ │   GUIDs:              e1678770-bdc9-47f9-8d90-340e28b6f196
│ │                       230c8b18-8d9b-53ec-838b-6cfc0383493a
│ │                       9d64c9c6-c8e7-569a-b109-2df1038c896b
│ │   Device Flags:       • Internal device
│ │                       • Updatable
│ │                       • System requires external power source
│ │                       • Supported on remote server
│ │                       • Needs a reboot after installation
│ │                       • Cryptographic hash verification is available
│ │                       • Device is usable for the duration of the update
│ │ 
│ ├─Intel AMT [unprovisioned]:
│ │     Device ID:        e2623122c99d58220498aacbfcfdb1baebbae3c5
│ │     Summary:          Hardware and firmware technology for remote out-of-band management
│ │     Current version:  14.0.48.1605
│ │     Bootloader Version:14.0.48.1605
│ │     Vendor:           Intel Corporation
│ │     GUID:             2800f812-b7b4-2d4b-aca8-46e0ff65814c
│ │     Device Flags:     • Internal device
│ │   
│ └─UEFI dbx:
│       Device ID:        362301da643102b9f38477387e2193e57abaa590
│       Summary:          UEFI Revocation Database
│       Current version:  83
│       Minimum Version:  83
│       Vendor:           UEFI:Linux Foundation
│       Install Duration: 1 second
│       GUIDs:            14503b3d-73ce-5d06-8137-77c68972a341
│                         5971a208-da00-5fce-b5f5-1234342f9cf7
│                         c6682ade-b5ec-57c4-b687-676351208742
│                         f8ba2887-9411-5c36-9cee-88995bb39731
│       Device Flags:     • Internal device
│                         • Updatable
│                         • Supported on remote server
│                         • Needs a reboot after installation
│     
├─TPM:
│     Device ID:          c6a80ac3a22083423992a3cb15018989f37834d6
│     Current version:    1.257.0.0
│     Vendor:             ST Microelectronics (TPM:STM)
│     GUIDs:              ff71992e-52f7-5eea-94ef-883e56e034c6
│                         84df3581-f896-54d2-bd1a-372602f04c32
│                         bfaed10a-bbc1-525b-a329-35da2f63e918
│                         70b7b833-7e1a-550a-a291-b94a12d0f319
│                         06f005e9-cb62-5d1a-82d9-13c534c53c48
│     Device Flags:       • Internal device
│   
├─TU117GLM [Quadro T1000 Mobile]:
│     Device ID:          ce4c74a5188d5b9cdb1e72ed32dad2d313c1c999
│     Current version:    a1
│     Vendor:             NVIDIA Corporation (PCI:0x10DE)
│     GUIDs:              cc85703c-a8a3-5fde-93d9-3a5c2fde0da3
│                         d190181c-080c-577e-94ec-31310c32ddfe
│                         f71f56b0-8808-5f2c-99ae-afc499f476c3
│                         aea1c72d-ddad-5702-9aaf-2b9bf2442a80
│     Device Flags:       • Internal device
│                         • Cryptographic hash verification is available
│   
├─UEFI Device Firmware:
│     Device ID:          86b69c290878beafd4f677cc014c19b80ff03cde
│     Current version:    16842760
│     Minimum Version:    1
│     Vendor:             DMI:LENOVO
│     GUIDs:              8472117f-10c2-4a17-b7b2-20632d59a29c
│                         f7faad1e-645b-5332-ab70-8f895d4992f5
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─UEFI Device Firmware:
│     Device ID:          b0caea18485ba629c08723f541138fc7c9b07f32
│     Current version:    65793
│     Minimum Version:    65793
│     Vendor:             DMI:LENOVO
│     GUIDs:              86dcfb01-3cf1-4a2d-9d9e-3768f7fae141
│                         94c02553-f483-5301-a2b5-ea00228a5752
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─USB3.0 Hub:
│     Device ID:          583e74d4f51ea275aa6ff1d3f9cd8db502ce8468
│     Summary:            USB 2.x Hub
│     Current version:    90.91
│     Vendor:             VIA Labs, Inc. (USB:0x2109)
│     Install Duration:   10 seconds
│     GUIDs:              d1b64cee-cc80-5822-a2ae-6ee1cca73856
│                         7aaf809e-a3f1-5beb-8a28-09e44471534b
│                         f1175e69-cf09-55de-b71b-da24d8f331d4
│                         63d270bb-eaf6-5e84-8ad5-c998739ef366
│                         cd3a7a5a-f5cf-546e-8f18-0a758327aa3e
│                         d812d765-cb6d-5486-8a25-c61bf4c8dfb0
│     Device Flags:       • Updatable
│                         • Cryptographic hash verification is available
│   
└─Unifying Receiver:
      Device ID:          506ad032bedb5227b5d11040e02f4f3058bfd2d6
      Summary:            A miniaturised USB wireless receiver
      Current version:    RQR12.01_B0019
      Bootloader Version: BOT01.02_B0014
      Vendor:             HIDRAW:0x046D|USB:0x046D
      Install Duration:   30 seconds
      GUIDs:              9d131a0c-a606-580f-8eda-80587250b8d6
                          fcf55bf5-767b-51ce-9c17-f6f538c4ee9f
                          279ed287-3607-549e-bacc-f873bb9838c4
      Device Flags:       • Updatable
                          • Supported on remote server
    
________________________________________________

Devices that were not updated correctly:

 • USB3.1 Hub (51.53 → 51.63)

**Additional questions**
- Operating system and version:
- Have you tried rebooting?
- Is this a regression?

**Comment by hughsie** [comment]
@josiah47 just to confirm, this is the "Thunderbolt 3 Dock **2**" -- right?

**Comment by josiah47** [comment]
Yes it is a Dock Gen 2

**Comment by josiah47** [comment]
Original Dock when Issue first submitted
![20210712_070719](https://user-images.githubusercontent.com/870875/125505125-6f5a242c-3988-4a45-b7ed-cfe327012c01.jpg)

Secondary Dock: But this is a first gen

also same error 

sudo fwupdmgr update
Restarting device…       [-                                      ]Devices with no available firmware updates: 
 • Thunderbolt host controller
 • UEFI Device Firmware
 • UEFI Device Firmware
 • USB2.0 Hub
 • USB2.0 Hub
 • USB3.0 Hub
Upgrade available for ThinkPad Thunderbolt 3 Dock from 39.00 to 62.00
ThinkPad Thunderbolt 3 Dock and all connected devices may not be usable while updating. Continue with update? [Y|n]: Y
Downloading…             [***************************************]
Decompressing…           [***************************************]
Authenticating…          [***************************************]
Authenticating…          [***************************************]
Updating ThinkPad Thunderbolt 3 Dock USB Audio…******************]
Restarting device…       [***************************************]
Updating USB3.1 Hub…     [************************************** ]
Restarting device…       [************************************** ]firmware incompatible, got VL820Q8, expected VL820Q7

![20210713_142339](https://user-images.githubusercontent.com/870875/125505192-ddbcf67f-fb64-4a5a-be73-630852f6eb26.jpg)

**Comment by hughsie** [comment]
Okay, I can reproduce here. Debugging.

**Comment by amigadave** [comment]
I tried updating the VIA USB hubs on the Thunderbolt 3 Gen 2 Dock just now, and it failed with 1.7.0 and 1.7.1 with the fix in https://github.com/fwupd/fwupd/pull/3504 with the same error message (firmware incompatible, got VL820Q8, expected VL820Q7). Downgrading to 1.5.9 I was able to upgrade without problems.
