### ISSUE TITLE
Add a clang-format specification file

### ISSUE THREAD

**Issue by djcampello** [fwupd/fwupd#3505]
I have been playing around with clang-format --style and it seems that this is close to what we want:

```
clang-format --style='{IndentWidth: 8, UseTab: 'Always', SpaceBeforeParens: 'Always', BinPackArguments: false, BinPackParameters: false, AlwaysBreakAfterReturnType: 'All', BreakBeforeBraces: Custom, BraceWrapping: { AfterFunction: true } }'
```

We may be able to add this to the commit hooks

@bleungatchromium @g2pop @binaryNewts

**Comment by hughsie** [comment]
`g_autoptr (GObject)` needs to have some kind of override. I also like the structs defined in blocks, e.g. 

	 typedef struct {
	-       gboolean         ret;
	-       gchar           *str;
	-       GError          *error;
	-       GPtrArray       *array;
	-       GMainContext    *context;
	-       GMainLoop       *loop;
	-       GVariant        *val;
	-       GHashTable      *hash;
	-       GBytes          *bytes;
	-       FwupdDevice     *device;
	+       gboolean ret;
	+       gchar *str;
	+       GError *error;
	+       GPtrArray *array;
	+       GMainContext *context;
	+       GMainLoop *loop;
	+       GVariant *val;
	+       GHashTable *hash;
	+       GBytes *bytes;
	+       FwupdDevice *device;
	 } FwupdClientHelper;

**Comment by djcampello** [comment]
AlignConsecutiveDeclarations: 'AcrossEmptyLinesAndComments' for the second issue

Unfortunately I don't think we can treat g_autoptr differently and it is kind of arbitrary to me. Why do we treat it differently?

**Comment by djcampello** [comment]
Here it is in file format:

```
$ cat .clang-format 
IndentWidth: 8
UseTab: 'Always'
SpaceBeforeParens: 'Always'
BinPackArguments: false
BinPackParameters: false
AlwaysBreakAfterReturnType: 'AllDefinitions'
AlignConsecutiveDeclarations: 'AcrossEmptyLinesAndComments'
BreakBeforeBraces: Custom
BraceWrapping:
 AfterFunction: true
 AfterStruct: true
```

**Comment by hughsie** [comment]
>Why do we treat it differently

g_autoptr(Type) is essentially a type in itself. It's certainly not a macro or function.

**Comment by djcampello** [comment]
maybe ugly but we could treat the exception outside clang-format in a follow up script

```
clang-format $1 | sed 's/g_autoptr (/g_autoptr(/g'
```

**Comment by superm1** [comment]
So FYI I did try to come up with something before but eventually gave up:
https://github.com/fwupd/fwupd/pull/568

**Comment by djcampello** [comment]
https://github.com/fwupd/fwupd/pull/568 looks good... Why was it abandoned?

**Comment by superm1** [comment]
> https://github.com/fwupd/fwupd/pull/568 looks good... Why was it abandoned?

I was busy and it it was feeling like more and more bandaids on top of band-aid. If you want to take it as a starting point or parts of it please feel free.
