### ISSUE TITLE
1_5_X: No Prometheus IOTA Config on HP laptop with version 1.5.11

### ISSUE THREAD

**Issue by andch-nn** [fwupd/fwupd#3554]
**Describe the bug**
Use fwupdmgr get-devices to list all devices on HP laptop, Promethues IOTA config will miss in 1.5.11-0ubuntu1~21.04.1.

**Steps to Reproduce**
1. Enable proposed package in Ubuntu Hirsute
2. sudo apt install fwupd
3. fwupdmgr get-devices

**Expected behavior**
├─Prometheus:
│ │ Device ID: 0fef0a0c55f6442bffaebd774ae771341c89571b
│ │ Summary: Fingerprint reader
│ │ Current version: 10.01.3273255
│ │ Vendor: Synaptics (USB:0x06CB)
│ │ Install Duration: 2 seconds
│ │ GUIDs: 816af83b-646c-5033-ae19-26391eeb675d
│ │ 8b06355d-849b-5125-85ec-6d02a20cf1ac
│ │ Device Flags: • Updatable
│ │ • Supported on remote server
│ │ • Cryptographic hash verification is available
│ │
│ └─Prometheus IOTA Config:
│ Device ID: 40b77e58384a02768e3ce90ed74c93ca2311327d
│ Current version: 0021
│ Minimum Version: 0021
│ Vendor: Synaptics (USB:0x06CB)
│ GUIDs: 0e58a9cb-f338-567b-a7ca-2a821eb8f3c2
│ 7b93dd19-18d1-5a0c-a32d-79a5d27e2b38
│ Device Flags: • Updatable
│ • Supported on remote server

**fwupd version information**
1.5.11.

```shell
fwupdmgr --version
```
client version: 1.5.11
compile-time dependency versions
        gusb:   0.3.5

daemon version: 1.5.11
Please note how you installed it (`apt`, `dnf`, `pacman`, source, etc):
apt
**fwupd device information**
Please provide the output of the fwupd devices recognized in your system.

```shell
fwupdmgr get-devices --show-all-devices
```
HP ZBook Fury 15 G7 Mobile Workstation
│
├─Thunderbolt host controller:
│     Device ID:          22ec5d304a254d9e72059a7661ad2e09dbb49d2f
│     Summary:            Unmatched performance for high-speed I/O
│     Current version:    62.00
│     Vendor:             HP Inc. (THUNDERBOLT:0x00F0, TBT:0x00F0)
│     GUIDs:              e0eb3006-c0f8-5868-8e2f-547c2c9e9904
│                         012e4cf2-92de-5067-96b2-7269ba095b54
│                         2a296088-9b04-556c-bf2c-5a47d66f5760
│                         59d64b52-7286-56f7-a15a-f2504c6e6cd6
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Device stages updates
│   
├─ELAN0720:00 04F3:313A:
│     Device ID:          37127274da0461232269feecebfc638f30488887
│     Summary:            Elan Touchpad
│     Current version:    0x000c
│     Bootloader Version: 0x0001
│     Vendor:             HIDRAW:0x04F3
│     GUIDs:              c717932e-2ba1-5069-9b46-abdd310ac0fb
│                         0935eabd-a697-54c2-aa1f-3a6abdba4680
│                         677cfdf6-cb54-54f2-8557-d8a3ae290437
│                         15e96dd6-4f5e-5d56-a991-2e63e82d1bd2
│                         6a52b599-cc0c-551b-9151-644fd7e5af18
│     Device Flags:       • Internal device
│                         • Updatable
│   
├─Intel(R) Core™ i7-10850H CPU @ 2.70GHz:
│     Device ID:          4bde70ba4e39b28f9eab1628f9dd6e6244c03027
│     Current version:    0x000000ea
│     Vendor:             Intel
│     GUIDs:              b9a2dd81-159e-5537-a7db-e7101d164d3f
│                         30249f37-d140-5d3e-9319-186b1bd5cac3
│                         a45b0522-5722-54bd-b802-86cd044262df
│                         7b9b6e8c-226c-5db6-86cb-ea3187578013
│     Device Flags:       • Internal device
│   
├─Prometheus:
│     Device ID:          0fef0a0c55f6442bffaebd774ae771341c89571b
│     Summary:            Fingerprint reader
│     Current version:    10.01.3273255
│     Vendor:             Synaptics (USB:0x06CB)
│     Install Duration:   2 seconds
│     GUIDs:              816af83b-646c-5033-ae19-26391eeb675d
│                         8b06355d-849b-5125-85ec-6d02a20cf1ac
│     Device Flags:       • Updatable
│                         • Cryptographic hash verification is available
│   
├─System Firmware:
│ │   Device ID:          2da33e3102f9d708d38bd556cdc6b814260b8e04
│ │   Current version:    17104896
│ │   Minimum Version:    1
│ │   Vendor:             HP (DMI:HP)
│ │   GUIDs:              28bc856b-bb59-4868-893a-6988357432d6
│ │                       230c8b18-8d9b-53ec-838b-6cfc0383493a
│ │                       8d74ddfd-4098-5ee4-ada6-1b4196f245da
│ │   Device Flags:       • Internal device
│ │                       • Updatable
│ │                       • System requires external power source
│ │                       • Needs a reboot after installation
│ │                       • Cryptographic hash verification is available
│ │                       • Device is usable for the duration of the update
│ │ 
│ ├─Intel AMT [unprovisioned]:
│ │     Device ID:        e2623122c99d58220498aacbfcfdb1baebbae3c5
│ │     Summary:          Hardware and firmware technology for remote out-of-band management
│ │     Current version:  14.1.53.1649
│ │     Bootloader Version:14.1.53.1649
│ │     Vendor:           Intel Corporation
│ │     GUID:             2800f812-b7b4-2d4b-aca8-46e0ff65814c
│ │     Device Flags:     • Internal device
│ │   
│ └─UEFI dbx:
│       Device ID:        362301da643102b9f38477387e2193e57abaa590
│       Summary:          UEFI Revocation Database
│       Current version:  84
│       Minimum Version:  84
│       Vendor:           UEFI:Linux Foundation
│       Install Duration: 1 second
│       GUIDs:            95641a6b-bc03-5b8b-bdfc-c92dab523a06
│                         7689caf4-c147-5c67-bff9-5dbe59a441bd
│                         c6682ade-b5ec-57c4-b687-676351208742
│                         f8ba2887-9411-5c36-9cee-88995bb39731
│       Device Flags:     • Internal device
│                         • Updatable
│                         • Needs a reboot after installation
│     
├─TPM:
│ │   Device ID:          c6a80ac3a22083423992a3cb15018989f37834d6
│ │   Current version:    7.85.17.51968
│ │   Vendor:             Infineon (TPM:IFX)
│ │   GUIDs:              ff71992e-52f7-5eea-94ef-883e56e034c6
│ │                       5eebb112-75ad-5536-b173-a11eb3399402
│ │                       ddf995da-1b32-5a8a-bc1b-8d5af4b38b51
│ │                       6d81ab63-db2e-50ac-934f-6be9accf5e02
│ │                       301555de-680d-5ddc-b995-7553fc9138f1
│ │   Device Flags:       • Internal device
│ │ 
│ └─Event Log:
│       Device ID:        58bd405f31c48e6eca290b425f530a94c91e955c
│       GUID:             a25657fe-b5dc-5be0-8b78-8b9dfec678ff
│       Device Flags:     • Internal device
│     
├─TU104GLM [Quadro RTX 5000 Mobile / Max-Q]:
│     Device ID:          ce4c74a5188d5b9cdb1e72ed32dad2d313c1c999
│     Current version:    a1
│     Vendor:             NVIDIA Corporation (PCI:0x10DE)
│     GUIDs:              b992198c-d3a2-53d3-9a74-d3db3b96fb45
│                         1808b7a1-33d2-5914-98e5-c291f5440edd
│                         e5e573b3-022b-529b-ae07-0cccc2a8548e
│                         d945da8a-e378-5e83-bff2-bc9a98876b0c
│     Device Flags:       • Internal device
│                         • Cryptographic hash verification is available
│   
├─UEFI Device Firmware:
│     Device ID:          dad4e477b879ed83fbfdcfc90df47a589b06db7f
│     Current version:    353107968
│     Minimum Version:    1
│     Vendor:             DMI:HP
│     GUIDs:              b58cfc31-3a86-6286-a620-f2a1c6c03ac2
│                         183918a0-c2cb-54b4-8792-1c5bb717d2f6
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─UEFI Device Firmware:
│     Device ID:          88adb13cb38fb834b5dfa2a8c5d86e30c413f06e
│     Current version:    1040253441
│     Minimum Version:    1
│     Vendor:             DMI:HP
│     GUIDs:              894cc322-4047-488f-abd5-1db35ddebefe
│                         7a548d52-3abd-528f-be78-c1c494c8af67
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─UEFI Device Firmware:
│     Device ID:          e5bc8293022f9dd9771a7a9b0f66d393aa5a90a7
│     Current version:    352518144
│     Minimum Version:    1
│     Vendor:             DMI:HP
│     GUIDs:              ca1146a5-1403-4385-9661-619f4e9eefbb
│                         1df69089-f106-59af-8ab5-f8aed243f939
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─UHD Graphics:
│     Device ID:          5792b48846ce271fab11c4a545f7a3df0d36e00a
│     Current version:    05
│     Vendor:             Intel Corporation (PCI:0x8086)
│     GUIDs:              069c33f5-c294-546c-aed0-cb2f9f515778
│                         06024758-3602-5eda-ab23-7e912c547e2d
│                         6c3dbf6c-4e6f-5309-9954-c5ab7aca617e
│                         3777783a-3f83-56a5-95f4-533eb6a2bd19
│     Device Flags:       • Internal device
│                         • Cryptographic hash verification is available
│   
└─WDC PC SN730 SDBPNTY-512G-1006:
      Device ID:          03281da317dccd2b18de2bd1cc70a782df40ed7e
      Summary:            NVM Express Solid State Drive
      Current version:    HPS2
      Vendor:             Sandisk Corp (NVME:0x15B7)
      GUIDs:              7b974856-317d-5538-a915-de0a6353750f
                          12c86995-0b90-5ec5-98f3-7a6ed4ca50e0
                          a39943dd-3afb-54f8-b110-c5a21f071200
                          fccbb6ea-e20e-58ad-bf8a-7fb7d43ff4c2
                          430b96d5-8289-5250-a02c-2f0ec84e7f09
      Device Flags:       • Internal device
                          • Updatable
                          • System requires external power source
                          • Needs a reboot after installation
                          • Device is usable for the duration of the update
    
**Additional questions**

- Operating system and version: Ubuntu Hirsute
- Have you tried rebooting? Yes
- Is this a regression?

**Comment by superm1** [comment]
Can you please share verbose daemon log with 1.5.11?

**Comment by andch-nn** [comment]
Hi @superm1 ,
The attached file is daemon log.
[fwupd-202007282139.log](https://github.com/fwupd/fwupd/files/6893515/fwupd-202007282139.log)

**Comment by superm1** [comment]
```
 七  28 21:13:39 ubuntu-HP-ZBook-Fury-15-G7-Mobile-Workstation fwupd[6113]: 13:13:39:0671 FuDevice             cannot change (null) physical ID from (null) to usb:01:00:08 as FuDevice->setup() has already completed
 七  28 21:13:39 ubuntu-HP-ZBook-Fury-15-G7-Mobile-Workstation fwupd[6113]: 13:13:39:0671 FuDevice             failed to ensure child: cannot ensure ID: FuSynapromConfig:
 七  28 21:13:39 ubuntu-HP-ZBook-Fury-15-G7-Mobile-Workstation fwupd[6113]: Prometheus IOTA Config
 七  28 21:13:39 ubuntu-HP-ZBook-Fury-15-G7-Mobile-Workstation fwupd[6113]:   ParentDeviceId:       0fef0a0c55f6442bffaebd774ae771341c89571b
 七  28 21:13:39 ubuntu-HP-ZBook-Fury-15-G7-Mobile-Workstation fwupd[6113]:   Guid:                 0e58a9cb-f338-567b-a7ca-2a821eb8f3c2 <- USB\VID_06CB&PID_00DF-cfg
 七  28 21:13:39 ubuntu-HP-ZBook-Fury-15-G7-Mobile-Workstation fwupd[6113]:   Guid:                 7b93dd19-18d1-5a0c-a32d-79a5d27e2b38 <- USB\VID_06CB&PID_00DF&CFG1_3483&CFG2_500
 七  28 21:13:39 ubuntu-HP-ZBook-Fury-15-G7-Mobile-Workstation fwupd[6113]:   Protocol:             com.synaptics.prometheus.config
 七  28 21:13:39 ubuntu-HP-ZBook-Fury-15-G7-Mobile-Workstation fwupd[6113]:   Flags:                updatable
 七  28 21:13:39 ubuntu-HP-ZBook-Fury-15-G7-Mobile-Workstation fwupd[6113]:   Vendor:               Synaptics
 七  28 21:13:39 ubuntu-HP-ZBook-Fury-15-G7-Mobile-Workstation fwupd[6113]:   VendorId:             USB:0x06CB
 七  28 21:13:39 ubuntu-HP-ZBook-Fury-15-G7-Mobile-Workstation fwupd[6113]:   Version:              0026
 七  28 21:13:39 ubuntu-HP-ZBook-Fury-15-G7-Mobile-Workstation fwupd[6113]:   VersionLowest:        0026
 七  28 21:13:39 ubuntu-HP-ZBook-Fury-15-G7-Mobile-Workstation fwupd[6113]:   VersionFormat:        plain
 七  28 21:13:39 ubuntu-HP-ZBook-Fury-15-G7-Mobile-Workstation fwupd[6113]:   Icon:                 touchpad-disabled
 七  28 21:13:39 ubuntu-HP-ZBook-Fury-15-G7-Mobile-Workstation fwupd[6113]:   LogicalId:            cfg
 七  28 21:13:39 ubuntu-HP-ZBook-Fury-15-G7-Mobile-Workstation fwupd[6113]: 13:13:39:0673 FuPlugin             ignoring add: cannot ensure ID: FuSynapromConfig:
 七  28 21:13:39 ubuntu-HP-ZBook-Fury-15-G7-Mobile-Workstation fwupd[6113]: Prometheus IOTA Config
 七  28 21:13:39 ubuntu-HP-ZBook-Fury-15-G7-Mobile-Workstation fwupd[6113]:   ParentDeviceId:       0fef0a0c55f6442bffaebd774ae771341c89571b
 七  28 21:13:39 ubuntu-HP-ZBook-Fury-15-G7-Mobile-Workstation fwupd[6113]:   Guid:                 0e58a9cb-f338-567b-a7ca-2a821eb8f3c2 <- USB\VID_06CB&PID_00DF-cfg
 七  28 21:13:39 ubuntu-HP-ZBook-Fury-15-G7-Mobile-Workstation fwupd[6113]:   Guid:                 7b93dd19-18d1-5a0c-a32d-79a5d27e2b38 <- USB\VID_06CB&PID_00DF&CFG1_3483&CFG2_500
 七  28 21:13:39 ubuntu-HP-ZBook-Fury-15-G7-Mobile-Workstation fwupd[6113]:   Protocol:             com.synaptics.prometheus.config
 七  28 21:13:39 ubuntu-HP-ZBook-Fury-15-G7-Mobile-Workstation fwupd[6113]:   Flags:                updatable
 七  28 21:13:39 ubuntu-HP-ZBook-Fury-15-G7-Mobile-Workstation fwupd[6113]:   Vendor:               Synaptics
 七  28 21:13:39 ubuntu-HP-ZBook-Fury-15-G7-Mobile-Workstation fwupd[6113]:   VendorId:             USB:0x06CB
 七  28 21:13:39 ubuntu-HP-ZBook-Fury-15-G7-Mobile-Workstation fwupd[6113]:   Version:              0026
 七  28 21:13:39 ubuntu-HP-ZBook-Fury-15-G7-Mobile-Workstation fwupd[6113]:   VersionLowest:        0026
 七  28 21:13:39 ubuntu-HP-ZBook-Fury-15-G7-Mobile-Workstation fwupd[6113]:   VersionFormat:        plain
 七  28 21:13:39 ubuntu-HP-ZBook-Fury-15-G7-Mobile-Workstation fwupd[6113]:   Icon:                 touchpad-disabled
 七  28 21:13:39 ubuntu-HP-ZBook-Fury-15-G7-Mobile-Workstation fwupd[6113]:   LogicalId:            cfg
```

I feel like we saw this on master as well, @hughsie do you remember?  Probably something we need  to backport to 1.5.x.

**Comment by superm1** [comment]
Can you please try applying https://github.com/fwupd/fwupd/commit/832231da9c1c3cc8a40ea9145a1925f85f237a98 to your build?

**Comment by andch-nn** [comment]
Hi @superm1 ,
After I applied this change on Ubuntu, IOTA config pops up in the list.
Thanks.

**Comment by andch-nn** [comment]
Hi,
I tried to use `fwupdmgr reinstall [Device id]`, and I got failure. Is it expected?
```
ubuntu@ubuntu-HP-ZBook-Fury-15-G7-Mobile-Workstation:~$ fwupdmgr reinstall 40b77e58384a02768e3ce90ed74c93ca2311327d
Prometheus IOTA Config and all connected devices may not be usable while updating. Continue with update? [Y|n]: y
Downloading…             [***************************************]
Decompressing…           [***************************************]
Authenticating…          [***************************************]
==== AUTHENTICATING FOR org.freedesktop.fwupd.update-hotplug-trusted ===
Authentication is required to update the firmware on a removable device
Authenticating as: ubuntu,,, (ubuntu)
Password: 
==== AUTHENTICATION COMPLETE ===
Authenticating…          [***************************************]
Installing on Prometheus…[***************************************]
Installing on Prometheus IOTA Config…****************************]
Installing on Prometheus…[***                                    ]
Restarting device…       [***************************************]
error status: 0x62a
```
[fwupd-2021-07301927.log](https://github.com/fwupd/fwupd/files/6907193/fwupd-2021-07301927.log)

**Comment by hughsie** [comment]
I don't think you can reinstall the config on the Prometheus device; it's strictly upgrade only.

**Comment by superm1** [comment]
> I don't think you can reinstall the config on the Prometheus device; it's strictly upgrade only.

Really?  Maybe we need to prevent that then.

**Comment by hughsie** [comment]
It's like the dbx that can only ever be updated. Maybe something like FWUPD_DEVICE_FLAG_ONLY_UPGRADE?

**Comment by superm1** [comment]
Can it downgrade to an old config though?  It just can't reinstall?

**Comment by hughsie** [comment]
> Can it downgrade to an old config though

Nope, just update. It's a PITA to test as you only get "one try".

**Comment by superm1** [comment]
>Nope, just update. It's a PITA to test as you only get "one try".

Well that's too bad.  But if you get it right you only needed one try ;)

>It's like the dbx that can only ever be updated. Maybe something like FWUPD_DEVICE_FLAG_ONLY_UPGRADE?

I don't know how important an extra flag is for this - UX will never show reinstall and downgrade in a list of automatic actions.
Maybe just the plugin's write vfunc looks at `FWUPD_INSTALL_FLAG_ALLOW_REINSTALL` and `FWUPD_INSTALL_FLAG_ALLOW_DOWNGRADE` and returns an error not supported.

**Comment by superm1** [comment]
>Maybe just the plugin's write vfunc looks at FWUPD_INSTALL_FLAG_ALLOW_REINSTALL and FWUPD_INSTALL_FLAG_ALLOW_DOWNGRADE and returns an error not supported.

Oh, but I looked now and the plugin doesn't parse the version.  So yeah this probably does need a daemon flag.

**Comment by hughsie** [comment]
> Oh, but I looked now and the plugin doesn't parse the version

This is kinda deliberate, I don't really want plugins doing version comparison logic at the point where they're supposed to be writing.

I've added a flag here: https://github.com/fwupd/fwupd/pull/3580

**Comment by andch-nn** [comment]
I think this issue can be closed. If it's ok, I'll close it.
