### ISSUE TITLE
Add dfu support for more Poly usb devices

### ISSUE THREAD

**Issue by zhj8407** [fwupd/fwupd#3558]
**Is your feature request related to a problem? Please describe.**
Poly releases some new usb cameras. All of them support the dfu. To support them, we need to specify some Flags in the dfu.qurik

**Describe the solution you'd like**
Add the USB VID/PID and Flags to dfu.qurik

**Describe alternatives you've considered**

**Additional context**

**Comment by zhj8407** [comment]
#3559 is for this issue.

**Comment by hughsie** [comment]
Looks good. In the _future_ no need for an issue, you can just do a pull request. Thanks!

**Comment by zhj8407** [comment]
Thanks. Will do.
