### ISSUE TITLE
Dell check update_state upon cleanup

### ISSUE THREAD

**Issue by binaryNewts** [fwupd/fwupd#3560]
Changes will soon be made to call composite and update cleanups upon running into an error. Thus, these vfuncs may be called even if the update does not complete successfully, which would cause problems for the Dell dock in its current state.

(via https://github.com/fwupd/fwupd/pull/3489)

**Comment by CragW** [comment]
The post configuration in composite_cleanup has no immediate op for checking update_state. I will take the possibilities to future changes, thanks for the suggestion.
