### ISSUE TITLE
Please give 'fwupdmgr clear-offline' a more helpful error message

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [fwupd/fwupd#3581]
It would be good were

`$ fwupdmgr clear-offline`

to produce a more helpful error message than the one that it does. The present error message is:

`failed to execute prepared statement: attempt to write a readonly database`

What the message is trying to say, and should say, is: you need root for this.

**My system**

Linux Mint Cinnamon 20.2
```
$ fwupdmgr --version
client version:	1.3.11
compile-time dependency versions
	gusb:	0.3.4
	efivar:	37
daemon version:	1.3.11
```
fwup installed via `apt`.

**Comment by hughsie** [comment]
I think to fix this properly, it needs a daemon method and a polkit authorisation. Or we move it to fwupdtool, which needs root for everything.
