### ISSUE TITLE
flashrom plugin tries to read ME region when attempting to update/downgrade

### ISSUE THREAD

**Issue by Sean-StarLabs** [fwupd/fwupd#3649]
The exact error is `failed to back up original firmware` if the CSME is enabled. fwupd is basically doing:
```
flashrom -p internal -w bios.rom -i bios --ifd
```
Which will attempt to read the whole flash, including the ME region (and fail). To make it work, you have to give it the `-N` or `--noverify-all` switch, so it'll only read the region it's actually flashing. i.e.
```
flashrom -p internal -w coreboot.rom -i bios --ifd --noverify-all
```
So question is, what would be the best way to fix it? Changing the backup method to only do the BIOS region would be straightforward but then, I guess, it should only ever write to the BIOS... if there's ever a case where it shouldn't?

**Comment by superm1** [comment]
Maybe this is a good case for a private flag in the plugin to control the behavior.

**Comment by Sean-StarLabs** [comment]
Flag for flashing something other than the BIOS, right? That'll be 99.9% of use cases

**Comment by hughsie** [comment]
What's the libflashrom flag for -N out of interest?

**Comment by Sean-StarLabs** [comment]
(--noverify-all) Don't check all regions. Default behaviour is to read them all before and after, to check if they have/haven't changed accordingly.

**Comment by hughsie** [comment]
No, the thing we have to set in the code when using libflashrom.h

**Comment by Sean-StarLabs** [comment]
I read that very wrong...

FLASHROM_FLAG_VERIFY_WHOLE_CHIP = 0
