### ISSUE TITLE
Dell dock: proxy device is stalled

### ISSUE THREAD

**Issue by CragW** [fwupd/fwupd#3732]
**Describe the bug**
Failed to install mst firmware, error message is seen: `Failed to query active bank: failed after 5 retries: failed to SetReport: endpoint stalled or request not supported`

<img width="449" alt="Screenshot from 2021-09-10 15-54-30" src="https://user-images.githubusercontent.com/30334596/132821515-c0b9ad69-aea2-471d-a1d7-53248fcf740b.png">

**Steps to Reproduce**
`# fwupdtool install dell-dock.cab -v --allow-reinstall`

**Expected behavior**
mst firmware is applied successfully, no error message.

**fwupd version information**
client version:	1.6.1-174-g15b668c0c
compile-time dependency versions
	gusb:	0.3.5

**Please note how you installed it (`apt`, `dnf`, `pacman`, source, etc):**
source

**Verbose daemon logs**
[15b668c0c-proxy-device-failed.log](https://github.com/fwupd/fwupd/files/7142104/15b668c0c-proxy-device-failed.log)

**Additional info**
- Operating system and version: Ubuntu 21.04
- Is this a regression? yes
- Commit 15b668c0c is causing this failure.
- Issue is unseen with previous commit a0fd32f41, verbose log [a0fd32f41-proxy-device-passed.log](https://github.com/fwupd/fwupd/files/7142140/a0fd32f41-proxy-device-passed.log)

**Comment by hughsie** [comment]
Okay, super-uncool, sorry about the regression. Lets make the proxy fallback an opt-in flag. Give me 10 minutes.
