### ISSUE TITLE
Running `fwupdate -l` triggers coredump

### ISSUE THREAD

**Issue by johannbg** [fwupd/fwupd#3811]
**Describe the bug**

An issue created as requested in the discussion dialog...

`# fwupdate -l
(fwupdate:4092): FuPluginUefiCapsule-WARNING **: 06:31:44.184: SMBIOS BIOS Characteristics Extension Byte 2 is invalid -- UEFI Specification is unsupported, but /sys/firmware/efi exists: SMBIOS not supported
Segmentation fault (core dumped)`

`Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055b544efeae9 in main (argc=<optimized out>, argv=<optimized out>) at ../plugins/uefi-capsule/fu-uefi-tool.c:280
280	../plugins/uefi-capsule/fu-uefi-tool.c: No such file or directory.`

[fwupdbt.txt](https://github.com/fwupd/fwupd/files/7241598/fwupdbt.txt)

**Comment by hughsie** [comment]
Both fixed in https://github.com/fwupd/fwupd/pull/3812
