### ISSUE TITLE
fwupd not possible for Dell XPS 15 9550

### ISSUE THREAD

**Issue by fbruetting** [fwupd/fwupd#3830]
I had UEFI v1.6.1 installed and for whatever reason, I could not find a way to update via fwupdmgr or GNOME Software. I ran Fedora 32, 34 and 35b, but Software showed nothing and fwupdmgr always told me that I have the most recent version.

I now tried it within the UEFI and that most recent EXE from the Dell server. That worked. Sad thing is that I now cannot show you verbous outputs anymore, but maybe you can still have a look at that?

**Comment by superm1** [comment]
I'm pretty sure this is https://github.com/fwupd/firmware-dell/issues/69.

**Comment by hughsie** [comment]
Agreed, closing a dup. Thanks!
