### ISSUE TITLE
publish-docs failed for 1.7.0

### ISSUE THREAD

**Issue by hughsie** [fwupd/fwupd#3838]
I'm seeing

    cp: cannot stat ‘../*.js’: No such file or directory

Any ideas?

**Comment by superm1** [comment]
Pretty sure regression from 9d113822c970376e264fb02b51bf9ba0f152d213

**Comment by hughsie** [comment]
Thanks! DO I have to do anything or do you have ACLs to re-run that CI job?

**Comment by superm1** [comment]
can't just re-run the CI job - it works directly from tags, I would suggest manually build locally, clone fwupd.github.io, copy them over and commit the docs and push.
