### ISSUE TITLE
Installed tests look for redfish plug-in in the build directory

### ISSUE THREAD

**Issue by jtojnar** [fwupd/fwupd#3880]
**Describe the bug**
Trying to run installed tests for latest fwupd fails:

```
FuPluginRedfish:ERROR:../plugins/redfish/fu-self-test.c:41:fu_test_self_init: assertion failed (error == NULL): failed to open plugin /build/fwupd-1.7.0/build/plugins/redfish/libfu_plugin_redfish.so: /build/fwupd-1.7.0/build/plugins/redfish/libfu_plugin_redfish.so: cannot open shared object file: No such file or directory (g-io-error-quark, 0)
Bail out! FuPluginRedfish:ERROR:../plugins/redfish/fu-self-test.c:41:fu_test_self_init: assertion failed (error == NULL): failed to open plugin /build/fwupd-1.7.0/build/plugins/redfish/libfu_plugin_redfish.so: /build/fwupd-1.7.0/build/plugins/redfish/libfu_plugin_redfish.so: cannot open shared object file: No such file or directory (g-io-error-quark, 0)
```

**Steps to Reproduce**
Run installed tests after deleting the build directory.

**Expected behavior**
Installed tests should run without any files missing.

**fwupd version information**
1.7.0 installed using our Nix package (https://github.com/NixOS/nixpkgs/pull/133550)

**fwupd device information**
n/a

**Additional questions**

- Operating system and version: NixOS unstable
- Have you tried rebooting? n/a
- Is this a regression? yes, installed tests worked in 1.5

**Comment by hughsie** [comment]
> Run installed tests after deleting the build directory

How _exactly_ are you running the installed tests? Thanks.
