### ISSUE TITLE
Links generated by fwupdagent command are invalid

### ISSUE THREAD

**Issue by skontar** [fwupd/fwupd#3893]
**Describe the bug**
When I run `fwupdagent security --force` I get a JSON with URLs. However, all of them resolve to 404 page.

**Steps to Reproduce**

1. Run `fwupdagent security --force`
2. Open any link, e.g. https://fwupd.github.io/hsi.html#org.fwupd.hsi.IntelSmap

**Expected behavior**
Load a webpage with information.

**fwupd version information**
Please provide the version of the daemon and client.

```shell
$ fwupdmgr --version
client version:	1.5.12
compile-time dependency versions
	gusb:	0.3.7

daemon version:	1.5.12
```

Please note how you installed it (`apt`, `dnf`, `pacman`, source, etc):
Pre-installed on the system (Fedora 34).

**fwupd device information**
Please provide the output of the fwupd devices recognized in your system.

_I do not believe this is relevant._

**Additional questions**

- Operating system and version: Fedora 34
- Have you tried rebooting? N/A
- Is this a regression? N/A

**Comment by superm1** [comment]
It should be at https://fwupd.github.io/libfwupdplugin/hsi.html#org.fwupd.hsi.IntelSmap
