### ISSUE TITLE
Add meson option to enable/disable the fastboot plugin.

### ISSUE THREAD

**Issue by bleungatchromium** [fwupd/fwupd#3920]
**Is your feature request related to a problem? Please describe.**
Google issuetracker issue b/203644293.

On Chromebooks with M93 and later, fwupd is running as a daemon. Inside of Google, we use a web based flashstation for fastboot smartphones. Our internal web flashstation tool is disrupted on Chrome OS when fwupd and the web flashstation are both trying to access the fastboot device at the same time.

In the case of Chrome OS, we don't actually deploy any firmware via fwupd to fastboot devices, so fwupd is just doing the "get-devices" phase.

**Describe the solution you'd like**
A simple way to disable the fastboot plugin at compile time.

**Describe alternatives you've considered**
DisabledPlugins=fastboot in daemon.conf works too.

**Additional context**

**Comment by superm1** [comment]
> On Chromebooks with M93 and later, fwupd is running as a daemon. 

Awesome!

> A simple way to disable the fastboot plugin at compile time.

Meson option seems fine to me.
