### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by skontar** [fwupd/fwupd#3941]
**Describe the bug**
Some of the links on https://fwupd.github.io/libfwupdplugin/hsi.html page are broken.

_Rest of the template not applicable._

**Intel C200 Datasheet** link to http://www.intel.com/content/www/us/en/chipsets/6-chipset-c200-chipset-datasheet.html redirects to https://www.intel.com/content/www/us/en/support.html

**ME Manufacturing Mode: obscured dangers** link to http://blog.ptsecurity.com/2018/10/intel-me-manufacturing-mode-macbook.html says that the blog article was removed.

**Comment by superm1** [comment]
For the datasheet it seems https://www.intel.com/content/dam/www/public/us/en/documents/datasheets/6-chipset-c200-chipset-datasheet.pdf is a better link
