### ISSUE TITLE
TPM v1.2 never found

### ISSUE THREAD

**Issue by kerneis-anssi** [fwupd/fwupd#3972]
The following line has a typo: https://github.com/fwupd/fwupd/blob/main/plugins/tpm/fu-plugin-tpm.c#L293

It should be "tpm0" instead of "tmp0".

As a result, TPM v1.2 would never be detected.

In addition of fixing this, that's one more reason why this module should be tested by loading the plugin and setting `FWUPD_SYSFSTPMDIR` to `testdatadir` instead of instantiating the TPM v1 and v2 devices. (Another reason is that it would allow testing the HSI checks end-to-end.)

Introduced in https://github.com/fwupd/fwupd/pull/3923 (the logic to distinguish v1 and v2 seems to have been different previously).

**Comment by hughsie** [comment]
@kerneis-anssi you got this or want me to fix it?

**Comment by hughsie** [comment]
It's actually worse than you describe, as we never actually add the V1 device... Patch incoming.

**Comment by kerneis-anssi** [comment]
> It's actually worse than you describe, as we never actually add the V1 device... Patch incoming.

Ah, I was wondering what kind of gobject magic loaded the V1 device :-D
