### ISSUE TITLE
Incorrect description in "CSME Version" section

### ISSUE THREAD

**Issue by skontar** [fwupd/fwupd#4034]
**Describe the bug**
I am looking at https://fwupd.github.io/libfwupdplugin/hsi.html#org.fwupd.hsi.Mei.Version
I think it contradicts itself:
- "not-valid: is not affected by the most critical CVEs"
- "To meet HSI-1 on systems that run this test, the result must be valid."

Also, based on my tests with `fwupdagent security --force`, valid seems to have a `Success` flag, and not-valid does not have it.
It seems to me that result descriptions of valid and not-valid on the page is swapped.

_The rest of the sections do not seem to be applicable_

**Comment by hughsie** [comment]
>  It seems to me that result descriptions of valid and not-valid on the page is swapped.

Completely agree, good catch. Fixed, thanks!
