### ISSUE TITLE
Managing Best Known Configuration downstream

### ISSUE THREAD

**Issue by ErwanAliasr1** [fwupd/fwupd#4040]
**Is your feature request related to a problem? Please describe.**
By reading https://blogs.gnome.org/hughsie/2021/11/29/firmware-best-known-configuration-in-fwupd/, I was wondering if we could have some override downstream.
With the existing feature, Vendors can define the set of stable firmware to be used, therefore on some infra, users would love to get another set of stable firmware for the following reasons : 
- the fw didn't got tested yet
- the vendor consider the fw as stable but the end users have issues and need to rollback on other releases before a fix is distributed
- the newest fw breaks some configuration/features, users needs to stay on a different version

**Describe the solution you'd like**
Having a way to define overrides downstream to set our list of stable firmware for a given fleet of servers.

**Additional context**
By running 10000s of servers, you know fw are broken on a daily basis and you need to maintain your own list proved to be perfectly functional.

Thx !

**Comment by superm1** [comment]
I think some more explanation of your situation needs to be described to come up with the right solution.
* Specifically I would wonder - are you directly taking LVFS as a remote or will you have a local remote that has the firmware?
