### ISSUE TITLE
Enable Snap package lzo compression

### ISSUE THREAD

**Issue by the-spyke** [fwupd/fwupd#4048]
**Is your feature request related to a problem? Please describe.**

Current snap cold start time is too long.

**Describe the solution you'd like**

Part of the issue is that by default Snap uses `xz` compression. There's a setting to enable much more faster `lzo` compression.

1. https://snapcraft.io/blog/snap-speed-improvements-with-new-compression-algorithm
2. https://snapcraft.io/blog/why-lzo-was-chosen-as-the-new-compression-method

Hoe to enable it: https://forum.snapcraft.io/t/how-to-switch-your-snap-to-use-lzo-compression/21714

**Describe alternatives you've considered**

**Additional context**

**Comment by hughsie** [comment]
@superm1 do you want to add "compression: lzo" ?? it seems the snap package would get bigger, but start faster -- so a tradeoff to consider. I'm okay with a smaller snap and slower commands if that helps.

**Comment by superm1** [comment]
No concerns to me. Seems like a reasonable tradeoff.

**Comment by hughsie** [comment]
@the-spyke would you be okay to do a pull request to add the extra line please?
