### ISSUE TITLE
Suspend-to-ram shows "Enabled" despite using a swapfile on encrypted hard drive

### ISSUE THREAD

**Issue by mYnDstrEAm** [fwupd/fwupd#4173]
**Describe the bug**
The output of `fwupdmgr security --force` includes these lines:
```
✘ Encrypted RAM:                 Not supported
✘ Suspend-to-ram:                Enabled
✘ Linux swap:                    Invalid
```
even though I'm using a swapfile located on a fully-encrypted hard drive.

**Steps to Reproduce**
On Debian11/KDE with a swapfile run `fwupdmgr security --force`.

**Expected behavior**
I think that at least "Suspend-to-ram" should probably have another value set.

**fwupd version information**
```
client version: 1.5.7
compile-time dependency versions
        gusb:   0.3.5

daemon version: 1.5.7
```

Please note how you installed it (`apt`, `dnf`, `pacman`, source, etc): apt (Apper)

**fwupd device information**

**Additional questions**
I don't know how encrypted swapfiles affect other elements scanned for here or how useful having a swapfile (on an encrypted drive) would be for security in practice (maybe info on how useful or not this could be is relevant here).

- Operating system and version: Debian11
- Have you tried rebooting? No
- Is this a regression? No

**Comment by superm1** [comment]
> even though I'm using a swapfile located on a fully-encrypted hard drive.

That's correct.  The problem isn't the swapfile, but it's the fact that your system offers suspend to RAM which has known attacks.
