### ISSUE TITLE
Can you change the visibility in organization people settings

### ISSUE THREAD

**Issue by Neustradamus** [fwupd/fwupd#4175]
@hughsie: I wish you a Happy New Year 2022!

Can you add you in public in the fwupd organization?
- https://github.com/orgs/fwupd/people

Thanks in advance.

**Comment by hughsie** [comment]
@superm1 also want to be public?

**Comment by superm1** [comment]
Sure

**Comment by hughsie** [comment]
Ohh, I think you need to opt in to that.

**Comment by Neustradamus** [comment]
@hughsie, @superm1: Thanks, it is better ^^
