### ISSUE TITLE
Missing librairies in snap version

### ISSUE THREAD

**Issue by clauded** [fwupd/fwupd#4195]
**Describe the bug**
I'm running fwupd snap version 1.7.4 on Solus and I get the following errors when running fwupdmgr:

```shell
>fwupdmgr --version

/snap/fwupd/3728/bin/../lib/x86_64-linux-gnu/../libgnutls.so.30: version `GNUTLS_3_6_13' not found (required by /usr/lib/gio/modules/libgiognutls.so)
Failed to load module: /usr/lib/gio/modules/libgiognutls.so
/usr/lib/gio/modules/libgiolibproxy.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/gio/modules/libgiolibproxy.so
/snap/core18/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /usr/lib64/gvfs/libgvfscommon.so)
Failed to load module: /usr/lib/gio/modules/libgioremote-volume-monitor.so
/snap/core18/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /usr/lib/gio/modules/libgvfsdbus.so)
Failed to load module: /usr/lib/gio/modules/libgvfsdbus.so
/usr/lib/gio/modules/libgioopenssl.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/gio/modules/libgioopenssl.so

(fwupdmgr:16463): GLib-GObject-WARNING **: 11:00:18.217: cannot register existing type 'DConfSettingsBackend'

(fwupdmgr:16463): GLib-CRITICAL **: 11:00:18.217: g_once_init_leave: assertion 'result != 0' failed

(fwupdmgr:16463): GLib-GIO-WARNING **: 11:00:18.217: Tried to register an extension of the type (null) to extension point gsettings-backend. Expected type is GObject.
client version: 1.7.4
compile-time dependency versions
        gusb:   0.3.10

daemon version: 1.7.4
```

**Steps to Reproduce**

```shell
sudo snap install fwupd --classic
fwupdmgr get-updates
fwupdmgr update
```

**Expected behavior**
I did update successfully my bios but I worry about those errors/warnings.

**fwupd version information**

```shell
> fwupdmgr --version
[error lines removed]
client version: 1.7.4
compile-time dependency versions
        gusb:   0.3.10
daemon version: 1.7.4

>snap list

Name    Version    Rev    Tracking       Publisher       Notes
core    16-2.52.1  11993  latest/stable  canonical✓      core
core18  20211215   2284   latest/stable  canonical✓      base
fwupd   1.7.4      3728   latest/stable  richard-hughes  classic
```

**fwupd device information**

N/A

**Additional questions**

- Operating system and version: Solus (fully patched)
- Have you tried rebooting? yes
- Is this a regression? N/A

**Comment by superm1** [comment]
I think this is caused by the wrapper for the snap fwupd commands: https://github.com/fwupd/fwupd/blob/main/contrib/snap/fwupd-command#L36

It seems that your host OS modules are incompatible in some way.

**Comment by clauded** [comment]
I guess fwupd tries to use the local lib instead of the snap lib. For example I renamed /usr/lib/gio/modules/libgiognutls.so and the first error message (version `GNUTLS_3_6_13' not found) is not displayed:

`sudo mv /usr/lib/gio/modules/libgiognutls.so /usr/lib/gio/modules/libgiognutls.so.bak`

Any ideas on how to solve this?

**Comment by superm1** [comment]
I think it needs smarter guys who know the snap than me.  I summon @kenvandine for advice!

**Comment by clauded** [comment]
In the meantime, I wrote a little bash script to avoid those errors:
```shell
#!/bin/bash
# fix fwupdmgr installed as a snap on Solus
LIB_GIO_PATH=/usr/lib/gio/modules
sudo mv ${LIB_GIO_PATH} ${LIB_GIO_PATH}.bak
fwupdmgr "$@" --no-reboot-check
sudo mv ${LIB_GIO_PATH}.bak ${LIB_GIO_PATH}
```

**Comment by clauded** [comment]
With fwupd 1.8.6-17-ga12a5053b on Solus, I still have those errors when running fwupdmgr :

```
/snap/fwupd/4400/usr/lib/x86_64-linux-gnu/glib-2.0/gio-querymodules: error while loading shared libraries: libpcre.so.3: cannot open shared object file: No such file or directory
/snap/fwupd/4400/bin/fwupdmgr: error while loading shared libraries: libpcre.so.3: cannot open shared object file: No such file or directory
```

**Comment by superm1** [comment]
I've added that library into the snap, have a try with the latest in the edge channel (not stable channel right now).

**Comment by clauded** [comment]
Same problem with fwupd   1.8.6-30-g95e014a84  4403   latest/edge. Please note if I install localy libprce3, I then get a libssl.so.3 not found.

**Comment by superm1** [comment]
I guess you need to install some other local stuff then too, try to install `libssl3`

**Comment by clauded** [comment]
On solus, I have to create manually a symlink (ln -s libssl3.so libssl.so.3). But then I get:
`/snap/fwupd/4405/bin/fwupdmgr: error while loading shared libraries: libcrypto.so.3: cannot open shared object file: No such file or directory`
Those libs (libpcre3, libssl3 and libcrypto3) are available in the core22 snap and those libs should be used instead of searching the local ones. I guess this is related to the classic mode and LD_LIBRARY_PATH should be set to use core libs first...
