### ISSUE TITLE
Remember window size

### ISSUE THREAD

**Issue by n1729m** [fwupd/fwupd#4237]
**Is your feature request related to a problem? Please describe.**

On opening the GUI firmware, the window size [right pan] doesn't display information completely.

![fwupd](https://user-images.githubusercontent.com/96682069/151827517-6db85141-ffcd-4fa6-9aee-c4893063bbdf.png)

So to display it properly, I resize it as below:

![fwupd_resized](https://user-images.githubusercontent.com/96682069/151827809-35d72e02-e810-40d0-96db-d766de0a60c8.png)

Upon relaunching the firmware app, the resized window size is not remembered and it defaults to display as seen in the first screenshot.

**Describe the solution you'd like**

- Possibility to remember the window size as resized by user.
- Dynamically resize window to display all info without user having to resize it.

**Additional context**

- OS: Arch Linux
- DE: Gnome 41.3 on Wayland.

**Comment by hughsie** [comment]
Can you file this here please: https://gitlab.gnome.org/hughsie/gnome-firmware-updater

**Comment by n1729m** [comment]
I apologize for opening issue at wrong place. Really appreciate for pointing me right direction.
