### ISSUE TITLE
failed to probe device usb:02:00:01:03:04: USB error on device 1131:1001 : Entity not found [-5]

### ISSUE THREAD

**Issue by necros2k7** [fwupd/fwupd#4258]
**Describe the bug**
C:\Program Files (x86)\fwupd\bin>fwupdtool get-updates
Loading…                 [-                                      ]22:30:07:0809 FuEngine             failed to probe device usb:02:00:01:03:04: USB error on device 1131:1001 : Entity not found [-5]
Loading…                 [***************************************]
WARNING: This package has not been validated, it may not work properly.
No detected devices

**fwupd version information**
1.7.5

**Additional questions**

- Operating system and version: win11 
- Have you tried rebooting? yes

**Comment by hughsie** [comment]
> USB error on device 1131:1001

Is that a KY-BT100 Bluetooth Adapter? Can you get the `fwupdmgr get-devices --verbose` output after you've set `FWUPD_PROBE_VERBOSE=1` in the environment please? I'm not entirely sure how to do that on win32, but it's probably something like `set FWUPD_PROBE_VERBOSE=1`...

Also, can you get me the `sudo lsusb -vvv` output on this same system with all the same devices attached, but in Linux please? Thanks.
