### ISSUE TITLE
../meson.build:459:4: ERROR: Got unknown keyword arguments "define_variable"

### ISSUE THREAD

**Issue by hughsie** [fwupd/fwupd#4341]
I just ran meson on a Fedora 36 host:

    ../meson.build:459:4: ERROR: Got unknown keyword arguments "define_variable"

This is with meson 0.60.3 -- is that too old or new perhaps?

**Comment by hughsie** [comment]
I think 8281e17a4b01df21c0c30710c013885295db9fe2 broke this; dep.get_variable doesn't have `define_variable`, but dep.get_pkgconfig_variable does.

**Comment by superm1** [comment]
What's your command used to repro?

**Comment by hughsie** [comment]
just:

    mkdir build && cd build
    meson ../ --prefix=/home/hughsie/.root -Dudevdir=/tmp -Dsystemd_root_prefix=/tmp

**Comment by superm1** [comment]
fixed by https://github.com/fwupd/fwupd/pull/4342
