### ISSUE TITLE
fwupdmgr-p2p.sh should use `@libexecdir@/fwupd/fwupd`

### ISSUE THREAD

**Issue by tomfitzhenry** [fwupd/fwupd#4360]
While packaging fwupd 1.7.6 for NixOS, a review suggested that https://github.com/fwupd/fwupd/blob/777103f93a641a932277158fe86139f0e3916e8c/data/installed-tests/fwupdmgr-p2p.sh#L13 should use `@libexecdir@/fwupd/fwupd` rather than `/usr/libexec/fwupd/fwupd`, along with an appropriate meson directive.

This is useful to allow distributes to run this test during its builds, while allowing for a configuration libexec directory.

**Comment by hughsie** [comment]
Yup, makes sense. Do you want to have a go at this and do a PR? Thanks.
