### ISSUE TITLE
shim isn't installed to the EFI system partition error when updating T14/G2 AMD laptop on RHEL9

### ISSUE THREAD

**Issue by vbenes** [fwupd/fwupd#4396]
**Describe the bug**
After installing clean RHEL9 on T14G2 with AMD internals I am unable to update firmware from testing repo via software:
getting error:
Unable to update Thinkpad T14/P14s Gen 2 AMD system update, Secure boot is enabled but shim isn't installed to the EFI system partition. 

**Steps to Reproduce**
clean install from net iso, via anaconda, adding repos (I think c9s would behave the same), using the quite standard disk partitioning with LVM and when in GNOME, just start Software, enable testing repo where 1.15 firmware is available from and start update. Error seen.

**Expected behavior**
Reboot and firmware update performed.

**fwupd version information**

```shell
fwupdmgr --version
```
client version:	1.5.9
compile-time dependency versions
	gusb:	0.3.6

daemon version:	1.5.9

Please note how you installed it (`apt`, `dnf`, `pacman`, source, etc):
anaconda :-) so probably dnf

**fwupd device information**
Please provide the output of the fwupd devices recognized in your system.

```shell
fwupdmgr get-devices --show-all-devices
```
[vbenes@localhost ~]$ fwupdmgr get-devices --show-all-devices
20XLS1WL00
│
├─AMD Ryzen 7 PRO 5850U with Radeon Graphics     :
│     Device ID:          4bde70ba4e39b28f9eab1628f9dd6e6244c03027
│     Vendor:             AMD
│     GUIDs:              b9a2dd81-159e-5537-a7db-e7101d164d3f
│                         22f9ecf4-588d-5c0a-8326-6ebff3655c6d
│                         79759cdc-94db-5098-be7b-eb02521fbbec
│                         20b595b0-5892-5870-8e4c-688133ad6e34
│     Device Flags:       • Internal device
│   
├─Integrated Camera:
│     Device ID:          301046452a49d84af6356d23e43a684b8f10660f
│     Current version:    61.18
│     Vendor:             Chicony Electronics Co.,Ltd. (USB:0x04F2)
│     GUIDs:              d6d1a39a-3fbc-5ad1-ab40-336ec0776a38
│                         f8d483f9-9284-51b6-9363-7e6d59c40a97
│     Device Flags:       • Updatable
│   
├─Prometheus:
│ │   Device ID:          96a0be68fa5cf5d60d3d2d392797c6844ab64d33
│ │   Summary:            Fingerprint reader
│ │   Current version:    10.01.3478575
│ │   Vendor:             Synaptics (USB:0x06CB)
│ │   Install Duration:   2 seconds
│ │   GUIDs:              09e8bf16-3e69-50f5-bb66-c7a040248352
│ │                       8088f861-6318-5b1e-9ce4-fbddbedb09ac
│ │   Device Flags:       • Updatable
│ │                       • Supported on remote server
│ │                       • Cryptographic hash verification is available
│ │ 
│ └─Prometheus IOTA Config:
│       Device ID:        b869c71992c6719542d6dd2a02ef4e18617778ea
│       Current version:  0029
│       Minimum Version:  0029
│       Vendor:           Synaptics (USB:0x06CB)
│       GUIDs:            7c5a1e62-38fa-5859-9337-09dbac6377e4
│                         8a12a1dd-5e54-5cb8-9607-c3a4e3e9a7e4
│       Device Flags:     • Updatable
│                         • Supported on remote server
│     
├─SAMSUNG MZVLB512HBJQ-000L7:
│     Device ID:          71b677ca0f1bc2c5b804fa1d59e52064ce589293
│     Summary:            NVM Express Solid State Drive
│     Current version:    5M2QEXF7
│     Vendor:             Samsung Electronics Co Ltd (NVME:0x144D)
│     GUIDs:              0b4d773a-7ac3-58c1-a541-e22ef1cdfe02
│                         c9d531ea-ee7d-5562-8def-c64d0d144813
│                         6e54c992-d302-59ab-b454-2d26ddd63e6d
│                         47335265-a509-51f7-841e-1c94911af66b
│                         f4ceb2a8-09c4-55c0-af2a-13ccd63925b1
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Supported on remote server
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─System Firmware:
│ │   Device ID:          90ed7708d2bb60dcf699de61732818ba16c78136
│ │   Current version:    0.1.13
│ │   Vendor:             LENOVO (DMI:LENOVO)
│ │   Update State:       Transient failure
│ │   Update Error:       Secure boot is enabled, but shim isn't installed to the EFI system partition
│ │   Last modified:      2022-03-16 14:13
│ │   GUIDs:              8fb7e1f9-447b-41fb-8832-ae5ef955665f
│ │                       230c8b18-8d9b-53ec-838b-6cfc0383493a
│ │                       2f587fcf-b814-56ef-8496-db1a4a256e5e
│ │   Device Flags:       • Internal device
│ │                       • Updatable
│ │                       • System requires external power source
│ │                       • Supported on remote server
│ │                       • Needs a reboot after installation
│ │                       • Cryptographic hash verification is available
│ │                       • Device is usable for the duration of the update
│ │ 
│ └─UEFI dbx:
│       Device ID:        362301da643102b9f38477387e2193e57abaa590
│       Summary:          UEFI Revocation Database
│       Current version:  267
│       Minimum Version:  267
│       Vendor:           UEFI:Linux Foundation
│       Install Duration: 1 second
│       GUIDs:            1e9c3d61-4bd9-514e-ad87-0a9b61b9e77d
│                         304a9ede-aff2-58f6-b5e5-0e651b065f1a
│                         c6682ade-b5ec-57c4-b687-676351208742
│                         f8ba2887-9411-5c36-9cee-88995bb39731
│       Device Flags:     • Internal device
│                         • Updatable
│                         • Supported on remote server
│                         • Needs a reboot after installation
│     
├─TPM:
│ │   Device ID:          c6a80ac3a22083423992a3cb15018989f37834d6
│ │   Current version:    1.258.0.0
│ │   Vendor:             ST Microelectronics (TPM:STM)
│ │   GUIDs:              ff71992e-52f7-5eea-94ef-883e56e034c6
│ │                       84df3581-f896-54d2-bd1a-372602f04c32
│ │                       bfaed10a-bbc1-525b-a329-35da2f63e918
│ │                       70b7b833-7e1a-550a-a291-b94a12d0f319
│ │                       06f005e9-cb62-5d1a-82d9-13c534c53c48
│ │   Device Flags:       • Internal device
│ │ 
│ └─Event Log:
│       Device ID:        58bd405f31c48e6eca290b425f530a94c91e955c
│       GUID:             a25657fe-b5dc-5be0-8b78-8b9dfec678ff
│       Device Flags:     • Internal device
│     
├─UEFI Device Firmware:
│     Device ID:          886dc9784f28875115f0089bb567c70606789020
│     Current version:    24856
│     Minimum Version:    1
│     Vendor:             DMI:LENOVO
│     GUIDs:              b812d23e-16e9-4ea2-a1e8-dae7845eb651
│                         74e2e4e5-9fe8-533b-9ebb-c69ae6685d89
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─UEFI Device Firmware:
│     Device ID:          40d94c54377bcdd4d547d5750399adaa5aee6dc0
│     Current version:    251925028
│     Vendor:             DMI:LENOVO
│     GUIDs:              22f4906d-d7df-4702-85a7-1db4870b34fc
│                         9916cf36-4638-54bd-9cd0-bd38c5b6e4d0
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─UEFI Device Firmware:
│     Device ID:          7f59c6ea2700b0029b5c7dff1a0c38cb2caea09b
│     Current version:    16785739
│     Minimum Version:    1
│     Vendor:             DMI:LENOVO
│     GUIDs:              37132c80-5c8b-4726-a502-6f8c456da9b4
│                         79591539-2db5-564d-9e52-4d7d2c40dca4
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─UEFI Device Firmware:
│     Device ID:          7a0c54fa21bad61c623c3ca1dc683107e0c0033b
│     Current version:    65794
│     Minimum Version:    65794
│     Vendor:             DMI:LENOVO
│     GUIDs:              2c9769a8-bd83-4e1c-857b-471b64912ced
│                         d359ced7-d8af-57b5-b99e-65e89cbbb7e7
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
└─UEFI Device Firmware:
      Device ID:          0309fe7d84b0b8e838ad1b2f22bd153906121cfc
      Current version:    65549
      Minimum Version:    65549
      Vendor:             DMI:LENOVO
      GUIDs:              4bea12df-56e3-4cdb-97dd-f133768c9051
                          31bfb296-9f8b-5519-94ad-04dadf19d202
      Device Flags:       • Internal device
                          • Updatable
                          • System requires external power source
                          • Needs a reboot after installation
                          • Device is usable for the duration of the update

**System UEFI configuration**
Please provide the output of the following commands:

```shell
efibootmgr -v
```
BootCurrent: 0000
Timeout: 0 seconds
BootOrder: 0000,0017,0018,0019,001A,001B,001C
Boot0000* Red Hat Enterprise Linux	HD(1,GPT,e44192e1-1557-48ef-a298-686b61c93c34,0x800,0x12c000)/File(\EFI\redhat\shimx64.efi)
Boot0010  Setup	FvFile(721c8b66-426c-4e86-8e99-3457c46ab0b9)
Boot0011  Boot Menu	FvFile(126a762d-5758-4fca-8531-201a7f57f850)
Boot0012  Diagnostic Splash Screen	FvFile(a7d8d9a6-6ab0-4aeb-ad9d-163e59a7a380)
Boot0013  Lenovo Diagnostics	FvFile(3f7e615b-0d45-4f80-88dc-26b234958560)
Boot0014  ThinkShield secure wipe	FvFile(3593a0d5-bd52-43a0-808e-cbff5ece2477)
Boot0015  Startup Interrupt Menu	FvFile(f46ee6f4-4785-43a3-923d-7f786c3c8479)
Boot0016  Rescue and Recovery	FvFile(665d3f60-ad3e-4cad-8e26-db46eee9f1b5)
Boot0017* USB CD	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,86701296aa5a7848b66cd49dd3ba6a55)
Boot0018* USB FDD	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,6ff015a28830b543a8b8641009461e49)
Boot0019* NVMe0	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,001c199932d94c4eae9aa0b6e98eb8a400)
Boot001A* ATA HDD0	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,91af625956449f41a7b91f4f892ab0f600)
Boot001B* USB HDD	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,33e821aaaf33bc4789bd419f88c50803)
Boot001C* PXE BOOT	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,78a84aaf2b2afc4ea79cf5cc8f3d3803)
Boot001D  Regulatory Information	FvFile(478c92a0-2622-42b7-a65d-5894169e4d24)
Boot001E* Boot Next Boot Option	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,a7ca6d35b2c2684783721826a7404894)

```shell
efivar -l | grep fw
```
0abba7dc-e516-4167-bbf5-4d9d1c739416-fwupd-8fb7e1f9-447b-41fb-8832-ae5ef955665f-0
0abba7dc-e516-4167-bbf5-4d9d1c739416-fwupd-ux-capsule

```shell
tree /boot
```
/boot
├── config-5.14.0-70.1.1.el9.x86_64
├── efi
│   └── EFI
│       ├── BOOT
│       │   ├── BOOTX64.EFI
│       │   └── fbx64.efi
│       ├── redhat
│       │   ├── BOOTX64.CSV
│       │   ├── grub.cfg
│       │   ├── grub.cfg.rpmsave
│       │   ├── grubx64.efi
│       │   ├── mmx64.efi
│       │   ├── shimx64.efi
│       │   └── shimx64-redhat.efi
│       └── rhel
│           └── fw
│               ├── fwupd-3b8c8162-188c-46a4-aec9-be43f1d65697.cap
│               └── fwupd-8fb7e1f9-447b-41fb-8832-ae5ef955665f.cap
├── grub2
│   ├── fonts
│   │   └── unicode.pf2
│   ├── grub.cfg
│   └── grubenv
├── initramfs-0-rescue-e248ce683379481dbacbcf35d20b0805.img
├── initramfs-5.14.0-70.1.1.el9.x86_64.img
├── initramfs-5.14.0-70.1.1.el9.x86_64kdump.img
├── loader
│   └── entries
│       ├── e248ce683379481dbacbcf35d20b0805-0-rescue.conf
│       └── e248ce683379481dbacbcf35d20b0805-5.14.0-70.1.1.el9.x86_64.conf
├── symvers-5.14.0-70.1.1.el9.x86_64.gz -> /lib/modules/5.14.0-70.1.1.el9.x86_64/symvers.gz
├── System.map-5.14.0-70.1.1.el9.x86_64
├── vmlinuz-0-rescue-e248ce683379481dbacbcf35d20b0805
└── vmlinuz-5.14.0-70.1.1.el9.x86_64

10 directories, 24 files

**Additional questions**

- Operating system and version:
RHEL9.0
- Have you tried rebooting?
yes, no luck
- Is this a regression?
no idea, a new machine so probably no
- Are you using an NVMe disk?
yes, Samsung Electronics Co Ltd (NVME:0x144D) 
- Is secure boot enabled?
yes, it is
- Is this a Lenovo system with 'Boot Order Lock' turned on in the BIOS?
Lenovo yes, Boot order lock turned off

**Comment by vbenes** [comment]
ok, so as suggested in #3762 I've copied over shimx64.efi and shimx64-redhat.efi to the rhel directory and I got rid of the issue. But, after reboot, I am in Verification failed: (0x1A) Security Violation blue tab and the only thing I can do is press OK.

hmm hmm, we need something more to do, but definitely, something is missing here in the directory structure.

**Comment by superm1** [comment]
> rhel directory

That's not expected!  @hughsie is the OS directory set wrong for the RHEL build of fwupd?  It should be "redhat" from that above output it seems.

**Comment by superm1** [comment]
Also I don't know why there are two shims, if shimx64.efi doesn't work, what happens if you copy shimx64-redhat.efi over it?  Does that work?

**Comment by hughsie** [comment]
> is the OS directory set wrong for the RHEL build of fwupd

Doh. It appears efi_os_dir is unset in RHEL 9. I'm guessing it's falling back to the "ID" in /etc/os-release? -- @vbenes can you attach the os-release here for a sanity check please.

**Comment by superm1** [comment]
> > Also I don't know why there are two shims, if shimx64.efi doesn't work, what happens if you copy shimx64-redhat.efi over it? Does that work?
> 
> I've renamed shimx64-redhat.efi to shimx64.efi in rhel subdir but then I see normal grub after reboot, so of no help here :-(

Did you stage the update again presumably?

Can you give efibootmgr output specifically after it's staged with the copied over shim in rhel directory?

**Comment by superm1** [comment]
After you overwrote the binary, re-run the update and when it prompts you to reboot run `efibootmgr -v` in another terminal and then share that and let it reboot.

**Comment by vbenes** [comment]
[root@localhost boot]# efibootmgr -v
BootNext: 0001
BootCurrent: 0000
Timeout: 0 seconds
BootOrder: 0000,0017,0018,0019,001A,001B,001C,0001
Boot0000* Red Hat Enterprise Linux	HD(1,GPT,e44192e1-1557-48ef-a298-686b61c93c34,0x800,0x12c000)/File(\EFI\redhat\shimx64.efi)
Boot0001* Linux-Firmware-Updater	HD(1,GPT,e44192e1-1557-48ef-a298-686b61c93c34,0x800,0x12c000)/File(\EFI\rhel\shimx64.efi)\.f.w.u.p.d.x.6.4...e.f.i...
Boot0010  Setup	FvFile(721c8b66-426c-4e86-8e99-3457c46ab0b9)
Boot0011  Boot Menu	FvFile(126a762d-5758-4fca-8531-201a7f57f850)
Boot0012  Diagnostic Splash Screen	FvFile(a7d8d9a6-6ab0-4aeb-ad9d-163e59a7a380)
Boot0013  Lenovo Diagnostics	FvFile(3f7e615b-0d45-4f80-88dc-26b234958560)
Boot0014  ThinkShield secure wipe	FvFile(3593a0d5-bd52-43a0-808e-cbff5ece2477)
Boot0015  Startup Interrupt Menu	FvFile(f46ee6f4-4785-43a3-923d-7f786c3c8479)
Boot0016  Rescue and Recovery	FvFile(665d3f60-ad3e-4cad-8e26-db46eee9f1b5)
Boot0017* USB CD	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,86701296aa5a7848b66cd49dd3ba6a55)
Boot0018* USB FDD	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,6ff015a28830b543a8b8641009461e49)
Boot0019* NVMe0	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,001c199932d94c4eae9aa0b6e98eb8a400)
Boot001A* ATA HDD0	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,91af625956449f41a7b91f4f892ab0f600)
Boot001B* USB HDD	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,33e821aaaf33bc4789bd419f88c50803)
Boot001C* PXE BOOT	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,78a84aaf2b2afc4ea79cf5cc8f3d3803)
Boot001D  Regulatory Information	FvFile(478c92a0-2622-42b7-a65d-5894169e4d24)
Boot001E* Boot Next Boot Option	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,a7ca6d35b2c2684783721826a7404894)

**Comment by vbenes** [comment]
and again, normal grub and system boot

**Comment by superm1** [comment]
Okay so that matches my expectations with knowing the OS directory set as it is.

If that doesn't work now on reboot then there is something wrong with shim (second bug in rhel9).

**Comment by hughsie** [comment]
@vbenes can you open a RH bz against RHEL 9 please and I'll do a c9s build with the s/rhel/redhat fix please.

**Comment by hughsie** [comment]
@vbenes great, thanks. When i get qa-ack I'll do a test build.

**Comment by superm1** [comment]
What about the second bug though? Even when shim is in the place fwupd expects it isn't working.

**Comment by hughsie** [comment]
Yup, that looks like a shim issue.
