### ISSUE TITLE
Request support so that the image file in the cab file can be referenced in the LVFS::UpdateImage field in metainfo.xml

### ISSUE THREAD

**Issue by chlee75** [fwupd/fwupd#4407]
"LVFS::UpdateImage" field  and <screenshots>/<image> in metainfo.xml refer to URL link only.
Using URL link for image need more time and resources to prepare and maintain.
So I request support so that the image file in the cab file can be referenced in the "LVFS::UpdateImage" and <screenshots>/<image>  field in metainfo.xml as well as URL link.

**Comment by hughsie** [comment]
I think we just want the LVFS to handle mirroring this. See https://gitlab.com/fwupd/lvfs-website/-/merge_requests/1267

**Comment by hughsie** [comment]
I merged the LVFS patch with docs.
