### ISSUE TITLE
Disable colors when output is not a terminal or NO_COLOR is set

### ISSUE THREAD

**Issue by kerneis-anssi** [fwupd/fwupd#4503]
`fwupdtool security > report.txt`  and `NO_COLOR=1 fwupdtool security` (https://no-color.org/) should strip terminal escape codes for colors to yield a plain-text output.

**Comment by hughsie** [comment]
Don't you want `fwupdtool security --json` in that case?

**Comment by kerneis-anssi** [comment]
I didn't know about it and it may work around my issue nicely, thanks. I still think that in general the coloring routines of any shell program should detect whether they're outputting to a shell or not and disable color in the latter case.
