### ISSUE TITLE
Install the D-Bus interfaces XML file even if using `-Dintrospection=false`

### ISSUE THREAD

**Issue by lancer1268** [fwupd/fwupd#4551]
**Is your feature request related to a problem? Please describe.**
I want to access the D-Bus interfaces XML file in `$(datadir)/dbus-1/interfaces/` with the `-Dintrospection=false` option.

As described in the [D-Bus API Design Guidelines](https://dbus.freedesktop.org/doc/dbus-api-design.html)
> Interface files for public API should be installed to `$(datadir)/dbus-1/interfaces` so that other services can load them.

**Describe the solution you'd like**
Install the D-Bus interfaces XML file even if using `-Dintrospection=false`. For example, revert [this commit](https://github.com/fwupd/fwupd/pull/4038/commits/e284b90cc102c642caaefcbec0cb08285243af1e).

**Describe alternatives you've considered**
Use another flag to enable the installation of the D-Bus XML file.

**Additional context**
I find the description of `introspection` in the `meson_options.txt`. It seems that the `introspection` here means the "GObject Introspection" instead of the "D-BUS Interface Introspection". Therefore, the D-Bus XML file should still be installed even if using `-Dintrospection=false`.
```
option('introspection', type : 'feature', description : 'generate GObject Introspection data', deprecated: {'true': 'enabled', 'false': 'disabled'})
```

**Comment by superm1** [comment]
Would you mind doing a PR to change this?

**Comment by hughsie** [comment]
Ack, pr please.

**Comment by lancer1268** [comment]
Ok, I can create PRs for this.

The `meson.build` for the `main` branch and `1_7_X` branch are different. Should I create one PR for each of them?

Note: My project currently uses the `1_7_X` branch.

**Comment by superm1** [comment]
> Ok, I can create PRs for this.
> 
> The `meson.build` for the `main` branch and `1_7_X` branch are different. Should I create one PR for each of them?
> 
> Note: My project currently uses the `1_7_X` branch.

It should be done first in main. Then it should be backported/redone for 1_7_X.

**Comment by lancer1268** [comment]
I see. Thank you.

**Comment by hughsie** [comment]
Done! Can you do the same for 1_7_X pls

**Comment by lancer1268** [comment]
Sure, but how can I do that for `1_7_X`? The presubmit check fails when I try to commit code to the `1_7_X` branch.
```
Don't commit to branch...................................................Failed
- hook id: no-commit-to-branch
- exit code: 1
```

**Comment by superm1** [comment]
> Sure, but how can I do that for `1_7_X`? The presubmit check fails when I try to commit code to the `1_7_X` branch.
> 
> ```
> Don't commit to branch...................................................Failed
> - hook id: no-commit-to-branch
> - exit code: 1
> ```

Check out 1_7_X and then fork that to another branch.

**Comment by superm1** [comment]
Thanks!
