### ISSUE TITLE
fwupdmgr install <url> does not work in 1.8.0

### ISSUE THREAD

**Issue by djcampello** [fwupd/fwupd#4576]
It used to be possible to use a URL to install a .cab hosted on a remote server. This does not work anymore as it returns `Invalid arguments`. Is it possible to get this functionality back or is there another combination of fwupdmgr commands that would achieve the same functionality?

**Comment by hughsie** [comment]
Oops, unintentional. `fwupdmgr local-install http://foo.bar/baz.cab` should qork, but we should probably add back the compat behaviour.

**Comment by djcampello** [comment]
Sounds good... I will change our tests in the meantime. Thank you!
