### ISSUE TITLE
Error when opening the Ubuntu Software or the Flatpak Software app

### ISSUE THREAD

**Issue by Overcraft90** [fwupd/fwupd#4664]
**Describe the bug**
Once the apps Ubuntu Software or Flatpak Software are launched for the first time after booting into the system an error message is displayed as blow:
 --FLATPAK--
![Screenshot from 2022-05-23 16-57-58](https://user-images.githubusercontent.com/98895614/169848250-714ff702-4e52-4967-8d82-d4fbabbe8f08.png)
--UBUNTU--
![Screenshot from 2022-05-23 16-58-15](https://user-images.githubusercontent.com/98895614/169848268-bbc618c4-ee66-4feb-860f-7d1eda5b88c7.png)

**Steps to Reproduce**
Click on the icon for Ubuntu Software or Flatpak Software on the Deck.
![Screenshot from 2022-05-23 16-59-41](https://user-images.githubusercontent.com/98895614/169848903-421ad4bd-1aaa-46ae-aeba-3e7743e879ed.png)

**Expected behavior**
The application should start without prompting any error message (as used to be previously).

**fwupd version information**

```shell
Failed to connect to daemon: Error calling StartServiceByName for org.freedesktop.fwupd: Unit snap.fwupd.fwupd.service not found.
```
Please note how you installed it (`apt`, `dnf`, `pacman`, source, etc):

**fwupd device information**
Please provide the output of the fwupd devices recognized in your system.

```shell
Failed to connect to daemon: Error calling StartServiceByName for org.freedesktop.fwupd: Unit snap.fwupd.fwupd.service not found.
```

**Additional questions**

- Operating system and version: Ubuntu 22.04 "JAMMY JELLYFISH".
- Have you tried rebooting? Yes.
- Is this a regression? No.

**Comment by superm1** [comment]
Did you install the snap at some point?  22.04 has a pretty recent version of fwupd, you should be able to just use the packaged one.

**Comment by Overcraft90** [comment]
I'm not sure what you mean by "the snap". I have both Ubuntu Software and Flatpak — I installed this one since it is faster and apps are more stable and up to date.

Should I remove Ubuntu Software and simply keep Flatpak? What I've done is installing `fwupd` in the Flatpak app; now, I'm prompted with this message when I open Ubuntu Software:

![Screenshot from 2022-05-23 17-31-17](https://user-images.githubusercontent.com/98895614/169855028-44e8ad39-841a-488a-b6dd-2f01f1052565.png)

No more messages when I open the Flatpak app, though. Let me know what to do, thanks!
