### ISSUE TITLE
LUKS Full Disk Encryption stop superio updates working

### ISSUE THREAD

**Issue by Sean-StarLabs** [fwupd/fwupd#4688]
This has been a known behaviour for a while since the "offline" mode was made primary back in `1.3.X`, but I was thinking that we can use the "online" mode either when LUKS is detected, or just always using it  (set via a quirk).

As for what happens; The update appears and will schedule correctly. On the next reboot, it appears that it gets as far as putting the EC into programming mode and then can't do anything else - so has to be hard reset to recover.

**Comment by hughsie** [comment]
I guess I have a slight concern in that "live" EC updates are kinda risky (e.g. user typing on keyboard) but if that's what you want, then it probably makes sense for it to be quirkable per-model. Would that solve the issue for you?

**Comment by Sean-StarLabs** [comment]
Rust 🤮

Is it just us who update the ECs? If it is, we could use online a short term solution, and then use this when flashrom finally tag a version: https://review.coreboot.org/c/flashrom/+/55715

**Comment by Sean-StarLabs** [comment]
Oh, and I would worry about building on older distros, they don't have meson 60 so don't stand a chance.

**Comment by superm1** [comment]
How has adoption been for COD thus far?  Long term - I really would prefer to see vendors adopting that instead of the RT service.  It's a lot less fragile in my mind.
I think it's also more possible to support in Windows :)
