### ISSUE TITLE
PolicyKit error during running ./contrib/setup in Ubuntu

### ISSUE THREAD

**Issue by chlee75** [fwupd/fwupd#4711]
**Describe the bug**

PolicyKit error happens after running ./contrib/setup in Ubuntu 22.04.
See below.
Install developer-friendly **unsafe** PolicyKit rules into /etc/polkit-1/rules.d? (y/N) y
cp: cannot create regular file '/etc/polkit-1/rules.d/': Not a directory

**Steps to Reproduce**
1) Get FWUPD source from GitHub
   $git clone https://github.com/fwupd/fwupd.git
2) Run ./contrib/setup script in the fwupd directory
  $cd fwupd
  $./contrib/setup

**Expected behavior**
 No PolicyKit error is expected.

**fwupd version information**
 fwupd version is 1.8.1

**Comment by superm1** [comment]
> Isn't /etc/polkit-1/rules.d created by polkit in Ubuntu? I wondered if it was a different location or something

Maybe by default it's not made because no rules are overridden? I don't know for sure.

I would suggest to try to mkdir it before running the script and then see if it works properly or not.
