### ISSUE TITLE
Setup script error message

### ISSUE THREAD

**Issue by chlee75** [fwupd/fwupd#4857]
**Describe the bug**
"No package metadata was found for meson" message happen when run ./contrib/setup script.
  [setup.log](https://github.com/fwupd/fwupd/files/9165218/setup.log)

 **Steps to Reproduce**
1) Get Latest fwupd 
2) run ./contribe/setup 

**Expected behavior**
No error message is expected.

**fwupd version information**
fwupd main

**Environment**
 Fedora 36

**Comment by hughsie** [comment]
Yup, we're working on that in https://github.com/fwupd/fwupd/pull/4856
