### ISSUE TITLE
Busybox's `gzip` does not support `--keep`

### ISSUE THREAD

**Issue by rrbq** [fwupd/fwupd#4866]
**Describe the question**
The usage of `gzip --keep` in `src/tests/host-emulate/meson.build` makes it incompatible with Busybox's variant of gzip, which only recognizes the short option `-k`.

Would it be possible to use `-k` instead of `--keep` so fwupd can be built using Busybox's gzip?

**fwupd version information**
fwupd 1.8.3 on Alpine Linux (with Busybox 1.35.0)

**Comment by hughsie** [comment]
Sure thing! Can you do a PR please?
