### ISSUE TITLE
Support asmedia usb4 format

### ISSUE THREAD

**Issue by superm1** [fwupd/fwupd#4913]
There are patches on the mailing list that will be adding support for the NVM format used by ASMedia. We should make sure that the matching code for fwupd is also updated for this.

https://lore.kernel.org/linux-usb/20220810101743.11214-1-chensiying21@gmail.com/

**Comment by hughsie** [comment]
Got a hint? Would this be a variant of libfwupdplugin/fu-intel-nvm.c as added in wip/hughsie/FuIntelNvm?

**Comment by superm1** [comment]
Yeah it should definitely come with or after that.

I was just raising it now in case it makes sense to fold into the same branch.

**Comment by superm1** [comment]
> variant of libfwupdplugin/fu-intel-nvm.c

I haven't looked closely; but I don't have any expectation that it shares same characteristics as this.  It should be "another" kind of NVM, not subclass that.

**Comment by superm1** [comment]
They submitted a v3, here's the updated link for it:
https://lore.kernel.org/linux-usb/202208152107.P6jLM6te-lkp@intel.com/T/#m1a8b1478fad56317e8f2c0895e996876a3aafca4

I left some comments with the goal that they can re-use the existing sysfs files so userspace doesn't need to change how the version string parses significantly.  Depending on what is accepted we will want to at _least_ update our unit tests.

**Comment by superm1** [comment]
With the changes in 1.8.5 I suspect this is no work unless we get more details from ASMedia, so I'm going to close it.  If we to end up needing changes will revisit then.
