### ISSUE TITLE
Redfish credential creation via IPMI does not work with Supermicro

### ISSUE THREAD

**Issue by flanfly** [fwupd/fwupd#5129]
Hi. This is more meant as a heads up and RFC for PRs I'm planning on getting into fwupd.

**Describe the bug**
The Redfish plugin automatically creates a fwupd user via the host's IPMI interface if IpmiDisableCreateUser is not True. With Supermicro BMCs there are several problems.

1. `fu_redfish_plugin_ipmi_create_user` assumes that the Redfish user ID is the IPMI user ID minus one (line 350). At least on my BMC this is not the case. They are actually equal.
2. The same function assumes that if a user named fwupd exists, it is usable and its password is known. Supermicro changes their password policy between updates. If a user's password does not satisfy the policy the password reset. In this case fwupd sees the user, does nothing and is later unable to log in.
3. While we're on the topic of password policies: The passwords created with `fu_common_generate_password` will not satisfy the policy of newer Supermicro BMCs (lack of digits and special characters). 

**Steps to Reproduce**
Try to use fwupdmgr update with Supermicro systems in the wild.

**Expected behavior**
It Just Works (TM)

**fwupd version information**
6054d09f354ae511d89d3ce579aa3273349e49d0

**Additional questions**

- Operating system and version:
- Have you tried rebooting?
- Is this a regression?

**Comment by hughsie** [comment]
> assumes that the Redfish user ID is the IPMI user ID minus one

Urgh, this might be a Lenovoism. If so, we can quirk it. Do you what other vendors do?

> fu_common_generate_password will not satisfy the policy

Patches welcome on adding special chars and then validating the random password is acceptable; it should be pretty easy.

Richard.
