### ISSUE TITLE
snap fails to run

### ISSUE THREAD

**Issue by Overcraft90** [fwupd/fwupd#5138]
**Describe the bug**
When opened for the first time after booting into the system the `Flatpack Software App` shows an error message related to _**fwupd**_.

**Steps to Reproduce**
Log into the account, press on the app icon Software (Flatpack).

**Expected behavior**
A clear screen which allows me to navigate the app and search for system updates.

**fwupd version information**
Please provide the version of the daemon and client.

```shell
/snap/fwupd/4397/bin/fwupdmgr: error while loading shared libraries: libfwupdplugin.so: cannot open shared object file: No such file or directory
```

Please note how you installed it (`apt`, `dnf`, `pacman`, source, etc):
I installed _**fwupd**_ on my machine using the following link: https://flathub.org/apps/details/org.gnome.Firmware. 

However, today for some reason it stopped working properly. Noted, the app has been installed long ago; today, it simply happened to have this malfunction.
<details>

<summary>**fwupd device information**</summary>

Please provide the output of the fwupd devices recognized in your system.

```shell
/snap/fwupd/4397/bin/fwupdmgr: error while loading shared libraries: libfwupdplugin.so: cannot open shared object file: No such file or directory
```

</details>

**Additional questions**

- Operating system and version: UBUNTU 22.04 "Jammy Jellyfish"
- Have you tried rebooting? Yes
- Is this a regression? No

See attachment
![Screenshot from 2022-10-07 21-10-24](https://user-images.githubusercontent.com/98895614/194687889-7934babf-bb5a-44fa-bb8c-cc0d99311328.png)

**Comment by superm1** [comment]
This is actually a bug with the snap it seems to me not the flatpak.

**Comment by Overcraft90** [comment]
@superm1 Thanks for the clarification, thing is how can I address it?

**Comment by superm1** [comment]
I think we need to dig into it to see what went wrong with the snap build. If you don't have a need for the snap I suggest you uninstall it and use the distro package instead.

**Comment by Overcraft90** [comment]
Thanks again, how can I do so? In fact if I remove the Flatpak app the one installed in Snap gets deleted too and vice-versa..., or at least that is what happened during my 'experimentation' in order to fix this issue. 
Let me know, thank you!

**Comment by Overcraft90** [comment]
@superm1 Never mind I did it! Just wonder when the actual app from your side will be ready. It is great to have it and very convenient.

**Comment by superm1** [comment]
>  0x000000000000001d (RUNPATH)            Library runpath: [/lib/x86_64-linux-gnu/fwupd-1.8.7]

It looks like the rpath in the snap is not correct..   I'll have to read up on what we can do about that.

**Comment by superm1** [comment]
I'm guessing what we need to do is patch the snap build process to update the RUNPATH  to a relative one based on `$ORIGIN`.  Something like `$ORIGIN/../lib`

**Comment by Overcraft90** [comment]
Hi again @superm1,

Actually after going back to the distro package the command line was working perfectly. Then I though why not trying to get the software app for Flatpak.

This time around it works, it might have been that I was missing the distro? Has it always have to be present for any other higher level `fwupd` software to work? Well, anyway I think we can close for now.

Thanks again!

**Comment by superm1** [comment]
I think there's a real problem with the snap still, let's keep this open to track that.

**Comment by clauded** [comment]
I have the same problem with the snap on Solus. Is there a way to patch manually the snap to test ?

> I'm guessing what we need to do is patch the snap build process to update the RUNPATH to a relative one based on `$ORIGIN`. Something like `$ORIGIN/../lib/x86_64-linux-gnu/fwupd-1.8.7`

I have the same problem with the snap on Solus. Is there a way to patch manually the snap to test this workaround?

**Comment by superm1** [comment]
@clauded you can have a try with my PR idea if you want.

**Comment by clauded** [comment]
@superm1 unfortunately I don't have the tools to build the snap and patching the current snap don't work.

**Comment by superm1** [comment]
OK.  Well once that merges we'll have a new snap built.

**Comment by clauded** [comment]
The new snap still fails on Solus:
`/snap/fwupd/4399/bin/fwupdmgr: error while loading shared libraries: libffi.so.8: cannot open shared object file: No such file or directory`
Also, this bug is not resolved on Solus: https://github.com/fwupd/fwupd/issues/4195

**Comment by PhilippWendler** [comment]
With the snap in version 1.8.6-13-gbbf62261d on Ubuntu 22.04 I get:
```
$ fwupd.fwupdtool 
/snap/fwupd/4399/bin/fwupdtool: error while loading shared libraries: libprotobuf-c.so.1: cannot open shared object file: No such file or directory
```
I also cannot start the `fwupd` daemon because it fails with the same error message and thus `fwupdmgr` times out.

Just wanted to note this here since the referenced library is a different one than the one reported by clauded.

**Comment by superm1** [comment]
It seems that several of these libraries were already installed on my local environment is probably why I didn't hit it.

I think they probably need to be added to stage packages phase.
