### ISSUE TITLE
Pop OS  complains about firmware upgrade

### ISSUE THREAD

**Issue by alefq** [fwupd/fwupd#5159]
Obviously this is going to keep coming up.  I'm personally happy that we have the safety check in place.  If nothing else it prevents fwupd from being the cause of non-obvious breakage to users.

I've added a wiki page to document this further:
https://github.com/fwupd/fwupd/wiki/Blocked-executable-in-the-ESP,-ensure-grub-and-shim-are-up-to-date

_Originally posted by @superm1 in https://github.com/fwupd/fwupd/issues/5035#issuecomment-1265716581_
      
I want to contribute my experience as same solution mentioned as "A User adds..."  on the wiki page helped me too. I've solved the issue on a Asus  ZeenBook; with windows 11 and Pop OS 22.04. 
System settings' firmware upgrade tool from Pop OS; finished upgrade normally after deleting the mentioned backup file.

**Comment by hughsie** [comment]
Great, thanks!
