### ISSUE TITLE
ccgx: Godzilla Creek version number always reported as 0.0.0.0

### ISSUE THREAD

**Issue by hughsie** [fwupd/fwupd#5202]
**Describe the bug**

The Godzilla Creek version number is always reported as 0.0.0.0, regardless of versions specified in the firmware.

**Steps to Reproduce**

	[hughsie@hughsie-work Downloads]$ fwupdtool firmware-parse godzila/use\ for\ upgrade/godzilla_creek_0_0_0_6.bin ccgx-dmc
	<firmware gtype="FuCcgxDmcFirmware">
	  <flags>has-checksum</flags>
	  <version>0.0.0.6</version>
	  <version_raw>0x6</version_raw>
	  <data size="0x46f42">FWCT@....... R.</data>
	  <fw_data_size>0x46b00</fw_data_size>
	  <image_records>0x7</image_records>
	  <firmware>
	    <data size="0x46f42">FWCT@....... R.</data>
	  </firmware>
	</firmware>
	[hughsie@hughsie-work Downloads]$ fwupdtool firmware-parse godzila/use\ for\ downgrade/godzilla_creek_0_0_0_4.bin ccgx-dmc
	<firmware gtype="FuCcgxDmcFirmware">
	  <flags>has-checksum</flags>
	  <version>0.0.0.4</version>
	  <version_raw>0x4</version_raw>
	  <data size="0x55442">FWCT@....... R.</data>
	  <fw_data_size>0x55000</fw_data_size>
	  <image_records>0x7</image_records>
	  <firmware>
	    <data size="0x55442">FWCT@....... R.</data>
	  </firmware>
	</firmware>

So this points the finger at `plugins/ccgx/fu-ccgx-dmc-device.c`

The way this works is we use `DMC_RQT_CODE_DOCK_STATUS` to get info about the dock and then read out the `composite_version`. This either isn't the right way to do this for Godzilla Creek or there's a different offset or something. Or, and I'm only including this for completeness, there could also be a firmware bug. :)

**Expected behavior**

The `composite_version` from DMC_RQT_CODE_DOCK_STATUS matches the `version_raw` specified in the firmware.

**fwupd version information**

git master

**Comment by bleungatchromium** [comment]
Captured `fwupdtool get-devices --plugins=ccgx --verbose` output for you.

https://gist.github.com/bleungatchromium/af359e79f6f0ef75f07d0a87f9ab5c61

**Comment by bleungatchromium** [comment]
Here's the same thing with a related hub, the Anker Thunderbolt 4 Mini Hub.

https://gist.github.com/bleungatchromium/c9f801b457f58fa5b9193e3dfbabc7bf

Same thing is observed.

```
  Version:              0.0.0.0
  VersionFormat:        quad
```

**Comment by hughsie** [comment]
@chlee75 I think we need your help with this please.

**Comment by chlee75** [comment]
@hughsie 

Could you share godzilla_creek_0_0_0_4.bin and godzilla_creek_0_0_0_6.bin that you have tested with me?
And let me know where those files come from.

For my urgent work these days, it may take one week or later for me to check those files.

Thanks.

**Comment by hughsie** [comment]
> Could you share godzilla_creek_0_0_0_4.bin and godzilla_creek_0_0_0_6.bin that you have tested with me?

I've emailed them to you. According to fwupdtool the version stored in the files is correct.

**Comment by bleungatchromium** [comment]
Any update on this issue, Chee?

**Comment by chlee75** [comment]
@bleungatchromium 
I sent a query about Godzilla creek to the person in charge.  No response from him. He seems to be out of the office or on the leave this week.
I will let you know when I get a response from him.

**Comment by chlee75** [comment]
@hughsie 

Is the version of Godzilla creek 0.0.0.0 after you updated godzilla_creek_0_0_0_6.bin or godzilla_creek_0_0_0_4.bin? 

How did you update godzilla_creek_0_0_0_6.bin or godzilla_creek_0_0_0_4.bin to Godzilla creek? 
Did you modify quirk, use fwupdmgr command with cab file of godzilla_creek_0_0_0_6.bin  or godzilla_creek_0_0_0_4.bin?

Thanks.

**Comment by hughsie** [comment]
> Is the version of Godzilla creek 0.0.0.0 after you updated godzilla_creek_0_0_0_6.bin or godzilla_creek_0_0_0_4.bin?

Both. It never returns a non-zero `composite_version`.

> How did you update godzilla_creek_0_0_0_6.bin or godzilla_creek_0_0_0_4.bin to Godzilla creek?

Using `fwupdtool install-blob`

**Comment by chlee75** [comment]
@hughsie 
> Both. It never returns a non-zero composite_version.

So Is the composite version from Godzilla creek 0.0.0.6 after you update godzilla_creek_0_0_0_6.bin? 

Do you have no issue in GodZilla creek with  godzilla_creek_0_0_0_6.bin or godzilla_creek_0_0_0_4.bin?

**Comment by hughsie** [comment]
> So Is the composite version from Godzilla creek 0.0.0.6 after you update godzilla_creek_0_0_0_6.bin?

No, it's always returned as 0x0 from `DMC_RQT_CODE_DOCK_STATUS` regardless of what we flash.

**Comment by chlee75** [comment]
@hughsie 
I asked the dock team to ship Godzilla creek to me.
After I get it and I will check this issue.

**Comment by hughsie** [comment]
@chlee75 when it's all working we should probably get https://fwupd.org/lvfs/vendors/prodcerts done -- as this is what Intel will hopefully be using for component selection going forward. It'll be a race between Cypress and TI :)

**Comment by chlee75** [comment]
@hughsie 
I ask help Infineon dock team about this issue.
They asked me something.

1. Can you share fwupd log when you update version 0.0.0.4 and 0.0.0.6 to godzilla creek?
2. Could you let me know where you get godzilla creek and dmc image version 0.0.0.4 and 0.0.0.6?

**Comment by chlee75** [comment]
@bleungatchromium 
I ask help Infineon dock team about this issue.
They asked me something.
1. where do you get Anker dock and QSI dock?
2. Have you ever updated firmware to Anker dock and QSI dock before you get the version from those devices?

**Comment by hughsie** [comment]
> Can you share fwupd log when you update version 0.0.0.4

That's a @bleungatchromium question too I'm afraid, I only have Gatkek in my office.

**Comment by chlee75** [comment]
@hughsie 
Did benson update composite image version 0.0.0.4 and 0.0.0.6 to Godzilla creek and read the version? Not you?

**Comment by chlee75** [comment]
@bleungatchromium 
1. Can you share fwupd log when you update version 0.0.0.4 and 0.0.0.6 to godzilla creek?
2. Could you let me know where you get godzilla creek and dmc image version 0.0.0.4 and 0.0.0.6?
3. Where do you get Anker dock and QSI dock?
4. Have you ever updated firmware to Anker dock and QSI dock before you get the version from those devices?

**Comment by bleungatchromium** [comment]
Hi  chlee75:

Unfortunately I have no .cab file or .bin file for Godzilla device or the ANker and QSI dock. 

I have the hardware, but no one has provided me with firmware payload files to deploy.

Can you address the fact that the `get-devices`  step gets the wrong answer?

Benson

**Comment by bleungatchromium** [comment]
I believe Arie at Intel was the one who was doing this experimentation on a Godzilla Creek. Can we reach out to him?

**Comment by krankun** [comment]
@bleungatchromium @chlee75 Arie doesnt use github let me know if I can connect you over email. thanks!

**Comment by bleungatchromium** [comment]
@krankun , yes please do. Please start a new email thread.

**Comment by alebrati** [comment]
Hi All,
i was trying on Godzilla Creek only, and prepared the cab files.
I dont have the card anymore, but i will share here link to download :
[https://www.idrive.com/idrive/sh/sh?k=r7b5p2h6a3](url)

also, the only log i have is the get-devices at that time..

root@ccelaptop-Swift-SFX14-51G:/tmp# fwupdmgr get-devices
WARNING: This package has not been validated, it may not work properly.
Acer Swift SFX14-51G
│
├─Unknown Device:
│     Device ID:          7c5b6dadf8126e3820c86cb56d9e1777084a98a8
│     Current version:    39.82
│     Vendor:             USB:0x8087
│     GUIDs:              b3f8b518-ebdd-5969-9b44-6b096eff5b9b ← USB\VID_8087&PID_0B40
│                         27f4ed60-ed53-52a7-ae28-ea87d9a23302 ← USB\VID_8087&PID_0B40&REV_1234
│                         2590556b-dcca-595c-8c71-c9c2247556b3 ← TBT-80871234
│     Device Flags:       • Updatable
│                         • Signed Payload
│
├─12th Gen Intel Core™ i5-1240P:
│     Device ID:          4bde70ba4e39b28f9eab1628f9dd6e6244c03027
│     Current version:    0x00000421
│     Vendor:             Intel
│     GUIDs:              b9a2dd81-159e-5537-a7db-e7101d164d3f ← cpu
│                         30249f37-d140-5d3e-9319-186b1bd5cac3 ← CPUID\PRO_0&FAM_06
│                         ab855c04-4ff6-54af-8a8a-d8193daa0cd8 ← CPUID\PRO_0&FAM_06&MOD_9A
│                         3ebbde86-d03e-549a-a8fd-02ebf9aa537a ← CPUID\PRO_0&FAM_06&MOD_9A&STP_3
│     Device Flags:       • Internal device
│
├─DMC Device:
│     Device ID:          2dfd7e39f0f500d95fb01e2a59b4ffcdc86ae070
│     Current version:    0.0.0.0
│     Vendor:             Cypress Semiconductor (USB:0x04B4)
│     Serial Number:      11AD1D0A2A4C4B092A180B00
│     GUIDs:              3944302d-f32a-5b80-903e-1a70f3e40fc1 ← USB\VID_04B4&PID_5220
│                         28438c12-f72f-526b-9de9-4652562b488c ← USB\VID_04B4&PID_5220&REV_1746
│     Device Flags:       • Updatable
│                         • System requires external power source
│                         • Device stages updates
│                         • Device can recover flash failures
│                         • Signed Payload
│
├─Display controller:
│     Device ID:          5792b48846ce271fab11c4a545f7a3df0d36e00a
│     Current version:    0c
│     Vendor:             Intel Corporation (PCI:0x8086)
│     GUIDs:              eaad9970-8e4d-56da-88ab-41a8c1e2811f ← PCI\VEN_8086&DEV_46A6
│                         ed0b9458-c2f1-54c5-9063-dea8f75b4039 ← PCI\VEN_8086&DEV_46A6&REV_0C
│                         e3c16b37-ed6f-5f01-b42f-457681b7ef78 ← PCI\VEN_8086&DEV_46A6&SUBSYS_1025160C
│                         3b703a18-e1ed-5a90-89ef-fa8702aba688 ← PCI\VEN_8086&DEV_46A6&SUBSYS_1025160C&REV_0C
│                         c4625510-a985-517c-8800-0ecfc6f68c8f ← PCI\VEN_8086&DEV_46A6&REV_00
│                         6f9345b8-4474-5272-9459-8c78f1b9f38a ← PCI\VEN_8086&DEV_46A6&SUBSYS_1025160C&REV_00
│     Device Flags:       • Internal device
│                         • Cryptographic hash verification is available
│
├─GA107M [GeForce RTX 3050 Ti Mobile]:
│     Device ID:          ce4c74a5188d5b9cdb1e72ed32dad2d313c1c999
│     Current version:    a1
│     Vendor:             NVIDIA Corporation (PCI:0x10DE, PCI:0x8086)
│     GUIDs:              f85e1eb1-8164-5121-ab09-be4641866f8a ← PCI\VEN_10DE&DEV_25A0
│                         e9c1ea31-13e6-5147-8765-38747fb8b784 ← PCI\VEN_10DE&DEV_25A0&REV_A1
│                         87695077-82e0-5e1a-88e0-d1391d577d6c ← PCI\VEN_10DE&DEV_25A0&SUBSYS_1025160C
│                         d5fd65d8-1f4c-57f9-bd8a-1dedefefd741 ← PCI\VEN_10DE&DEV_25A0&SUBSYS_1025160C&REV_A1
│                         ebeb20ab-a48a-5dde-970d-b8f7abcfdc1d ← PCI\VEN_8086&DEV_464D
│                         987a22ea-406f-5e45-be9d-821e8a5364d7 ← PCI\VEN_8086&DEV_464D&REV_02
│                         5d09c07d-90aa-59f8-a396-f7dbe9cfd1a9 ← PCI\VEN_8086&DEV_464D&SUBSYS_1025160C
│                         abebe9fd-0537-5cbd-9054-619a9e396545 ← PCI\VEN_8086&DEV_464D&SUBSYS_1025160C&REV_02
│     Device Flags:       • Internal device
│                         • Cryptographic hash verification is available
│
├─Intel Thunderbolt generic model name:
│     Device ID:          1651cd2e6ad91b17d6554f1232945b318d677174
│     Current version:    39.82
│     Vendor:             Intel Thunderbolt generic vendor name (THUNDERBOLT:0x8087, TBT:0x8087)
│     Update State:       Success
│     GUIDs:              4371c7e1-ae4e-57a5-900a-a76eca89d19a ← THUNDERBOLT\VEN_8087&DEV_1234
│                         2ef89a74-303c-5990-8bb3-903d3c92a12d ← THUNDERBOLT\VEN_8087&DEV_1234&REV_00
│                         2590556b-dcca-595c-8c71-c9c2247556b3 ← TBT-80871234
│                         3875adf9-b265-5673-814f-a0a2ca6167ae ← TBT-80871234-controller1-1
│     Device Flags:       • Updatable
│                         • System requires external power source
│                         • Device stages updates
│                         • Signed Payload
│
├─System Firmware:
│ │   Device ID:          a45df35ac0e948ee180fe216a5f703f32dda163f
│ │   Summary:            UEFI ESRT device
│ │   Current version:    1412763649
│ │   Minimum Version:    1412763649
│ │   Vendor:             Acer (DMI:Insyde Corp.)
│ │   Update State:       Success
│ │   GUIDs:              05bc899e-45c1-4160-ae0c-461dac1d5ae1
│ │                       230c8b18-8d9b-53ec-838b-6cfc0383493a ← main-system-firmware
│ │   Device Flags:       • Internal device
│ │                       • Updatable
│ │                       • System requires external power source
│ │                       • Needs a reboot after installation
│ │                       • Cryptographic hash verification is available
│ │                       • Device is usable for the duration of the update
│ │
│ └─UEFI dbx:
│       Device ID:        362301da643102b9f38477387e2193e57abaa590
│       Summary:          UEFI revocation database
│       Current version:  83
│       Minimum Version:  83
│       Vendor:           UEFI:Linux Foundation
│       Install Duration: 1 second
│       GUIDs:            c6682ade-b5ec-57c4-b687-676351208742 ← UEFI\CRT_A1117F516A32CEFCBA3F2D1ACE10A87972FD6BBE8FE0D0B996E09E65D802A503
│                         f8ba2887-9411-5c36-9cee-88995bb39731 ← UEFI\CRT_A1117F516A32CEFCBA3F2D1ACE10A87972FD6BBE8FE0D0B996E09E65D802A503&ARCH_X64
│                         9ecf9719-4f8c-5276-a52a-6f3000088b6d ← UEFI\CRT_050CC39C6C27BCE57882DDDE095B918571FB5A048DCEB7C15D4A39B6B44EA78A
│                         611a8c59-c339-5d53-9d61-201d84879d93 ← UEFI\CRT_050CC39C6C27BCE57882DDDE095B918571FB5A048DCEB7C15D4A39B6B44EA78A&ARCH_X64
│       Device Flags:     • Internal device
│                         • Updatable
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│                         • Only version upgrades are allowed
│                         • Signed Payload
│
├─TPM:
│     Device ID:          c6a80ac3a22083423992a3cb15018989f37834d6
│     Summary:            TPM 2.0 Device
│     Current version:    600.18.0.0
│     Vendor:             Intel (TPM:INTC)
│     GUIDs:              ff71992e-52f7-5eea-94ef-883e56e034c6 ← system-tpm
│                         34801700-3a50-5b05-820c-fe14580e4c2d ← TPM\VEN_INTC&DEV_0000
│                         93532b61-86ce-57cf-8a31-f5a5553966c7 ← TPM\VEN_INTC&MOD_ADL
│                         03f304f4-223e-54f4-b2c1-c3cf3b5817c6 ← TPM\VEN_INTC&DEV_0000&VER_2.0
│                         12e61a33-eef7-58d6-855d-ece38114294d ← TPM\VEN_INTC&MOD_ADL&VER_2.0
│     Device Flags:       • Internal device
│
├─UEFI Device Firmware:
│     Device ID:          349bb341230b1a86e5effe7dfe4337e1590227bd
│     Summary:            UEFI ESRT device
│     Current version:    310
│     Vendor:             DMI:Insyde Corp.
│     Update State:       Success
│     GUID:               832af090-2ef9-7c47-8f6d-b405c8c7f156
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│
├─USB4 Retimer:
│     Device ID:          fa7ebe94a3e7265f44a1d3346dffe26f29f1be42
│     Summary:            A physical layer protocol-aware, software-transparent extension device that forms two separate electrical link segments
│     Current version:    10.00
│     Vendor:             Intel (THUNDERBOLT:0x8087)
│     GUIDs:              e6f2e4ac-f76a-5fc4-b36a-6f9cb548689e ← THUNDERBOLT\VEN_8087&DEV_15EE
│                         f00257c8-0e09-5a32-bbb3-f49748ae6cc5 ← THUNDERBOLT\VEN_8087&DEV_15EE&REV_00
│                         dfeacc0a-7af4-5460-ab40-22ed630568de ← TBT-808715ee-retimer1-0:1.1
│     Device Flags:       • Internal device
│                         • Updatable
│                         • Device stages updates
│
└─WD PC SN810 SDCQNRY-512G-1014:
      Device ID:          c430a03ca2a65dfe2412ff950c79c51f6aec1317
      Summary:            NVM Express solid state drive
      Current version:    61470100
      Vendor:             Sandisk Corp (NVME:0x15B7)
      Serial Number:      212597448801
      GUIDs:              887c0622-74ea-5036-99bd-c6c63082bd37 ← NVME\VEN_15B7&DEV_5011
                          7b4c7b46-e1da-54fa-97fa-656c216629a2 ← NVME\VEN_15B7&DEV_5011&REV_01
                          b029d0ec-3f85-5cb7-a403-85c6f3bb4d83 ← NVME\VEN_15B7&DEV_5011&SUBSYS_15B75011
                          04de4e6b-264e-58a5-8947-a2bd85924418 ← NVME\VEN_15B7&DEV_5011&SUBSYS_15B75011&REV_01
                          b79c0df3-4987-5c8d-a4f5-370b57d9caaf ← WD PC SN810 SDCQNRY-512G-1014
      Device Flags:       • Updatable
                          • System requires external power source
                          • Needs a reboot after installation

**Comment by chlee75** [comment]
@bleungatchromium and @hughsie 

When it is factory mode, the firmware composite version is always 0.0.0.0 in Infineon DMC Docks (Gatkex/Godzilla/... Creek).
Factory mode states that no firmware has been updated since it was manufactured.

That's why the firmware version in fwupd is 0.0.0.0 in Anker Thunderbolt 4 Mini Dock that you mentioned above.

I purchased the ARTMU T4D110 dock, a Goodway DBD1010 equivalent dock (based on Intel Godzilla creek).
Anker Thunderbolt 4 Mini Dock that you mentioned above is also a Goodway DBD1010 equivalent dock.
See https://dancharblog.wordpress.com/2021/02/05/usb4-tb4-docks

As a test, I reran fwupd after I rebuilt it by adding ARTMU T4D110 information to the quirk file.
Also, I manually created a new cab file for the dock.

The ARTMU T4D110 dock was in factory mode when I checked it by the internal tool.
The dock firmware version 0.0.0.0 is in fwupd.
See the log of $fwupdmgr get-devices. 
[artmu_lvfs_0.0.0.0.log](https://github.com/fwupd/fwupd/files/10139098/artmu_lvfs_0.0.0.0.log)

I updated the ARTMU T4D110 dock with a new cab file whose version is 0.0.0.9.
$fwupdmgr install ARTMU-T4D1100-V0.0.0.9.cab
You can see the version has been changed from 0.0.0.0 to 0.0.0.9.
See the log of $fwupdmgr get-devices.
[artmu_lvfs_0.0.0.9.log](https://github.com/fwupd/fwupd/files/10139101/artmu_lvfs_0.0.0.9.log)

**It is not an issue that the firmware version number is 0.0.0.0 in thunderbolt docks based on Godzilla creek.**

**Comment by chlee75** [comment]
@alebrati and @bleungatchromium 

I checked the GUID in dmc_pd.metainfo.xml of gatkex and godzilla creek of your link above.
The GUID of gatkex creek is `<firmware type="flashed">28438c12-f72f-526b-9de9-4652562b488c</firmware>`.
The GUID of godzilla creek is `<firmware type="flashed">26fc6a1d-c95f-524c-ac5a-9fe24f16cd96</firmware>`.

Both GUID of gatkex and godzilla creek do not match with USB\VID_04B4&PID_5220.

The Intel Gatkex and Godzilla creek have the same USB VID/PID (04B4/5220) and the GUID should be `<firmware type="flashed">3944302d-f32a-5b80-903e-1a70f3e40fc1</firmware>`. by appstream-util generate-guid “USB\VID_04B4&PID_5220”

I think that you have never succeeded to update the firmware with your cab files to Gatkex or Godzilla creek.
Please create new cab files after fixing the GUID of dmc_pd.metainfo.xml and try to update the firmware with new cab files.

Be careful that FWUPD can't distinguish gatkex from godzilla because they have same USB VID/PID.
So you need to match cab files and Intel creek.  Gatkex firmware can be updated to Godzilla creek if cab and dock do not match. It seems very unsafe.

As I mentioned at https://github.com/fwupd/fwupd/pull/4801, 
USB VID/PID of Infineon Goshen Ridge EVBs such as Godzilla, Gorilla and Gatkex Creek etc. are not unique. And it can make an issue such as a wrong firmware update on Infineon Goshen Ridge EVBs. That's why I suggested that do not update the firmware to Infineon Goshen Ridge EVBs in fwupd.

**Comment by alebrati** [comment]
I am sorry,
here is the link:
https://www.idrive.com/idrive/sh/sh?k=p7s1k7d6r8

i will check above comments Sunday..
thanks!

**Comment by alebrati** [comment]
@bleungatchromium  - maybe you can try it on your Godzila ? in above link you will find the cab

**Comment by bleungatchromium** [comment]
Ok, will do. Will try today at the office.

**Comment by bleungatchromium** [comment]
Sorry for the late reply everyone. It looks like my docking station is a QSI branded one: [USB\VID_2BEF&PID_9065]

**Comment by hughsie** [comment]
@chlee75 I'm now testing on a retail Caldigit Element Hub. I'm getting the `0.0.0.0` composite version too -- and I don't think the element hub is in factory mode. Is there a way to check if the device has successfully exited factory mode? I also see 6 `DevxStatus` sections in the `DmcDockStatus` -- can you provide any details about what these are, and if any of these should be used as fallbacks in the event that the device composite version is zero?

	FuCcgxDmcDevice:
	  DeviceId:             15d9ee733307504cb179fda844bf97df280dc962
	  Name:                 Element Hub
	  Guid:                 c15b1b1a-502a-535a-99a5-f929a3cf9593 ← USB\VID_2188&PID_0035
	  Guid:                 03129e01-d32c-584e-a3e3-af9549a2fffe ← USB\VID_2188&PID_0035&REV_1746
	  Serial:               11AD1D85A109300E41150B00
	  Plugin:               ccgx
	  Protocol:             com.cypress.ccgx.dmc
	  Protocol:             com.infineon.ccgx.dmc
	  Flags:                updatable|require-ac|registered|dual-image|self-recovery|signed-payload
	  Vendor:               CalDigit, Inc.
	  VendorId:             USB:0x2188
	  Version:              0.0.0.0
	  VersionFormat:        quad
	  Created:              2023-02-02
	  Guid[quirks]:         f2c15b7b-987a-5790-ac36-164bce8667c6 ← USB\VID_2188
	  Guid[quirks]:         00513169-b132-5fe6-859b-bd8fb04f89d9 ← USB\CLASS_11
	  Guid[quirks]:         d7e609dc-f5b4-52f3-a5d2-14959051dd16 ← USB\CLASS_11&SUBCLASS_00
	  Guid[quirks]:         48c55639-9b8b-5410-a1bc-3a011cb3a799 ← USB\CLASS_11&SUBCLASS_00&PROT_00
	  Guid[quirks]:         4bd986bc-4aaf-5baf-8bc2-9f7928182387 ← USB\CLASS_FF
	  Guid[quirks]:         78c9681b-f906-52ee-aaa7-9b58bc4a1505 ← USB\CLASS_FF&SUBCLASS_03
	  Guid[quirks]:         d27ab148-1c4b-53f6-9414-d9032eb5abfe ← USB\CLASS_FF&SUBCLASS_03&PROT_00
	  PhysicalId:           usb:07:00:01:01:08
	  RemoveDelay:          732000
	  AcquiesceDelay:       2500
	  PossiblePlugin:       ccgx
	  ParentPhysicalIds:    usb:07:00:01:01,usb:07:00:01
	  InternalFlags:        replug-match-guid|is-open|only-wait-for-replug
	  UpdateModel:          None
	  EpBulkOut:            0x1
	  EpIntrIn:             0x82
	  TriggerCode:          0x0
	  DeviceStatus:         idle
	  DeviceCount:          0x6
	  StatusLength:         0xc8
	  CompositeVersion:     0x0
	  DevxStatus:0x00:
	    DeviceType:         0x2
	    ComponentId:        0x0
	    ImageMode:          0x1
	    CurrentImage:       0x2
	    ImgStatus:          0x11
	    FwVersion[boot]:    0x10e5646d330006c4
	    FwVersion[img1]:    0x000f6568330006d2
	    FwVersion[img2]:    0x000f6568330006d2
	  DevxStatus:0x01:
	    DeviceType:         0xff
	    ComponentId:        0x1
	    ImageMode:          0x0
	    CurrentImage:       0x0
	    ImgStatus:          0x0
	    FwVersion[boot]:    0x0000000000000000
	    FwVersion[img1]:    0x0000000000000000
	    FwVersion[img2]:    0x0000000000000000
	  DevxStatus:0x02:
	    DeviceType:         0xb
	    ComponentId:        0x2
	    ImageMode:          0x1
	    CurrentImage:       0x2
	    ImgStatus:          0x11
	    FwVersion[boot]:    0x10036d64330006ab
	    FwVersion[img1]:    0x000d6d64330006d2
	    FwVersion[img2]:    0x000d6d64330006d2
	  DevxStatus:0x03:
	    DeviceType:         0xa
	    ComponentId:        0x3
	    ImageMode:          0x2
	    CurrentImage:       0x1
	    ImgStatus:          0x11
	    FwVersion[boot]:    0x0000000000000000
	    FwVersion[img1]:    0x0000000000004060
	    FwVersion[img2]:    0x0000000000004060
	  DevxStatus:0x04:
	    DeviceType:         0x4
	    ComponentId:        0x4
	    ImageMode:          0x2
	    CurrentImage:       0x2
	    ImgStatus:          0x11
	    FwVersion[boot]:    0x00016e6231000388
	    FwVersion[img1]:    0x30016e6233010045
	    FwVersion[img2]:    0x30016e6233010045
	  DevxStatus:0x05:
	    DeviceType:         0x4
	    ComponentId:        0x5
	    ImageMode:          0x2
	    CurrentImage:       0x2
	    ImgStatus:          0x11
	    FwVersion[boot]:    0x00016e6231000388
	    FwVersion[img1]:    0x30016e6233010045

**Comment by chlee75** [comment]
@hughsie 

The composite version will be 0.0.0.0 if there is no firmware update since manufacturing.
So version 0.0.0.0 is not a problem.

Does your Caldigit Element Hub work properly?

For firmware information, you need to contact Caldigit.

And please add Brent.Wu@infineon.com into this issue loop. He takes LVFS support instead of me.

Thanks.

**Comment by hughsie** [comment]
@chlee75 I'll follow up with Brent on email, but do you know his GitHub account name? You can't add by email unfortunately.

**Comment by IfxBrent** [comment]
@hughsie 
I found a detailed guilde about the information you may need here.
[https://www.infineon.com/dgdl/Infineon-EZ-PD_Dock_Reference_Design_Guide-ReferenceDesign-v01_00-EN.pdf?fileId=8ac78c8c7d0d8da4017d0f68e4205aea&da=t](url)

Please refer to the page 40 for the version, and you can find some other bits definition in this guilde as well.

**Comment by hughsie** [comment]
Right, all fixed, thanks all.
