### ISSUE TITLE
Make filing issues for the documentation easier

### ISSUE THREAD

**Issue by pentamassiv** [fwupd/fwupd#5232]
**Is your feature request related to a problem? Please describe.**
I noticed missing documentation/a broken link on https://fwupd.github.io/libfwupdplugin/hsi.html and wanted to file an issue. I found the https://github.com/fwupd/fwupd.github.io repo. However there is no issues tab in the repo. There also is no README file that tells the user where to file an issue. I assumed that you might want to collect all issues in this repo, but I am unsure.

**Describe the solution you'd like**
It would be good to put a little symbol or link to the Github repo on all pages of the documentation so that people can quickly find the repo, improve the docs with PRs or file issues. It would also be nice to add a small README.md file to the https://github.com/fwupd/fwupd.github.io repo that tells the user where to file issues regarding the documentation.

**Comment by hughsie** [comment]
> add a small README.md file to the https://github.com/fwupd/fwupd.github.io repo

This is autogenerated every time we push a new release unfortunately. I think filing issues here is obvious enough.
