### ISSUE TITLE
AMD Rollback Protection and/or Firmware Replay Protection should say it is enabled but instead says it's disabled

### ISSUE THREAD

**Issue by andreldmonteiro** [fwupd/fwupd#5261]
**Describe the bug**
AMD Rollback Protection and/or Firmware Replay Protection show as disabled/not supported but the feature is enabled on the UEFI BIOS on an ASUS PRIME X670E-PRO WIFI AMD motherboard:
![1](https://user-images.githubusercontent.com/56444382/201958475-b8bc5118-e21b-4da8-bb13-1d5daf179da4.jpg)
![2](https://user-images.githubusercontent.com/56444382/201958482-256c51bb-4881-4c11-8ead-83bf083e066e.jpg)
![UEFI](https://user-images.githubusercontent.com/56444382/201958910-3b55f018-4cdd-4d97-8732-79345f45512b.jpg)
In this context the option on the UEFI BIOS set as disabled means the feature is actually enabled.

**Steps to Reproduce**
1. Check that "BIOS Image Rollback Support" is Disabled on the UEFI BIOS on an ASUS PRIME X670E-PRO WIFI AMD motherboard.
2. Open GNOME Settings
3. Then go to Device Security
4. "AMD Rollback Protection" on Level 1 security should say it's enabled but it doesn't and says it's disabled instead.

**Expected behavior**
AMD Rollback Protection and/or Firmware Replay Protection should show as enabled.

**fwupd version information**
fwupd-1.8.7-2.fc37.x86_64

```shell
fwupdmgr --version
```
runtime   org.freedesktop.fwupd         1.8.7
runtime   org.freedesktop.fwupd-efi     1.3
runtime   com.dell.libsmbios            2.4
runtime   com.hughsie.libjcat           0.1.12
compile   com.hughsie.libjcat           0.1.12
runtime   org.kernel                    6.0.8-300.fc37.x86_64
compile   org.freedesktop.gusb          0.4.1
compile   org.freedesktop.fwupd         1.8.7
runtime   org.freedesktop.gusb          0.4.2

Please note how you installed it (`apt`, `dnf`, `pacman`, source, etc):

It was already installed with fedora 37.

<details>

<summary>**fwupd device information**</summary>

Please provide the output of the fwupd devices recognized in your system.

```shell
fwupdmgr get-devices --show-all-devices
```
ASUS System Product Name
│
├─Dispositivo desconhecido:
│     ID do dispositivo:  f685512aa07369c9e77742acef941d779d31e766
│     GUID:               37b440a9-2473-5087-a39b-db84f32a8ed8 ← GPIO\ID_AMDI0030:00
│   
├─Dispositivo desconhecido:
│     ID do dispositivo:  0785bd3eac5b152d9fc34e5549136304ca025e4c
│     GUID:               bc9f6c6f-473f-5bc2-a0d1-3171c965d0d3 ← GPIO\ID_AMDIF031:00
│   
├─Mass storage controller:
│     ID do dispositivo:  26430eaf915ee60285f1ee05944b7629be3c01ea
│     Versão atual:       01
│     Fornecedor:         Advanced Micro Devices, Inc. [AMD] (PCI:0x1022)
│     GUIDs:              c12a74b6-78b0-5cfb-95a3-cd65a12f9e94 ← PCI\VEN_1022&DEV_43F6
│                         eb935b99-5869-5b16-ba2c-e2815a2ff8bd ← PCI\VEN_1022&DEV_43F6&REV_01
│                         b5ead2d1-eba8-5d36-8943-fe306b1f2bd7 ← PCI\VEN_1022&DEV_43F6&SUBSYS_1B213328
│                         8ed2e32c-3b83-5ccd-a310-d3141360fe3a ← PCI\VEN_1022&DEV_43F6&SUBSYS_1B213328&REV_01
│                         67d3b17f-d200-5c56-979e-8a3a4ab46c2b ← PCI\VEN_1022&DEV_43F5
│                         a221019f-651b-56e2-ad6e-7460fd558d9b ← PCI\VEN_1022&DEV_43F5&REV_01
│                         6b2e126d-81a8-530b-a8d3-a93e65bd30b2 ← PCI\VEN_1022&DEV_43F5&SUBSYS_1B213328
│                         63647588-a7c1-5c44-b2d4-72128628c523 ← PCI\VEN_1022&DEV_43F5&SUBSYS_1B213328&REV_01
│     Opções do dispositivo:• Dispositivo interno
│                         • A verificação criptográfica de hash está disponível
│   
├─Mass storage controller:
│     ID do dispositivo:  9c9e35b58089f8ce84c28ec3a5685fd6489eb912
│     Versão atual:       01
│     Fornecedor:         Advanced Micro Devices, Inc. [AMD] (PCI:0x1022)
│     GUIDs:              c12a74b6-78b0-5cfb-95a3-cd65a12f9e94 ← PCI\VEN_1022&DEV_43F6
│                         eb935b99-5869-5b16-ba2c-e2815a2ff8bd ← PCI\VEN_1022&DEV_43F6&REV_01
│                         b5ead2d1-eba8-5d36-8943-fe306b1f2bd7 ← PCI\VEN_1022&DEV_43F6&SUBSYS_1B213328
│                         8ed2e32c-3b83-5ccd-a310-d3141360fe3a ← PCI\VEN_1022&DEV_43F6&SUBSYS_1B213328&REV_01
│                         67d3b17f-d200-5c56-979e-8a3a4ab46c2b ← PCI\VEN_1022&DEV_43F5
│                         a221019f-651b-56e2-ad6e-7460fd558d9b ← PCI\VEN_1022&DEV_43F5&REV_01
│                         6b2e126d-81a8-530b-a8d3-a93e65bd30b2 ← PCI\VEN_1022&DEV_43F5&SUBSYS_1B213328
│                         63647588-a7c1-5c44-b2d4-72128628c523 ← PCI\VEN_1022&DEV_43F5&SUBSYS_1B213328&REV_01
│     Opções do dispositivo:• Dispositivo interno
│                         • A verificação criptográfica de hash está disponível
│   
├─Ryzen 5 7600X 6-Core Processor:
│ │   ID do dispositivo:  4bde70ba4e39b28f9eab1628f9dd6e6244c03027
│ │   Versão atual:       0x0a601203
│ │   Fornecedor:         AMD
│ │   GUIDs:              b9a2dd81-159e-5537-a7db-e7101d164d3f ← cpu
│ │                       22f9ecf4-588d-5c0a-8326-6ebff3655c6d ← CPUID\PRO_0&FAM_19
│ │                       16dd7d28-eade-5077-adb8-0775fdfbb2e5 ← CPUID\PRO_0&FAM_19&MOD_61
│ │                       6c9f4098-a058-5cd6-a1ce-36bfe27404fb ← CPUID\PRO_0&FAM_19&MOD_61&STP_2
│ │   Opções do dispositivo:• Dispositivo interno
│ │ 
│ └─Secure Processor:
│       ID do dispositivo:c54ab0237d7a8db8c717b68e0be78e4374a2a079
│       Fornecedor:       AMD (PCI:0x1022)
│       GUIDs:            9844da3e-1df2-52fe-9413-d4378af6221e ← PCI\VEN_1022&DEV_1649
│                         2f07ce4f-42d2-5848-a963-a58e6fcad38e ← PCI\VEN_1022&DEV_1649&REV_00
│                         f3ba4376-77c1-5b2d-bf2e-a6a144b809c1 ← PCI\VEN_1022&DEV_1649&SUBSYS_10438877
│                         b32e6f72-5e4a-5fb9-bded-f8a5c556ca4e ← PCI\VEN_1022&DEV_1649&SUBSYS_10438877&REV_00
│       Opções do dispositivo:• Dispositivo interno
│     
├─System Firmware:
│ │   ID do dispositivo:  a45df35ac0e948ee180fe216a5f703f32dda163f
│ │   Resumo:             UEFI ESRT device
│ │   Versão atual:       2057
│ │   Versão mínima:      2057
│ │   Fornecedor:         ASUS (DMI:American Megatrends Inc.)
│ │   Estado da atualização:Sucesso
│ │   GUIDs:              e16b08e2-0157-535d-8e2f-d6de5e4efda2
│ │                       230c8b18-8d9b-53ec-838b-6cfc0383493a ← main-system-firmware
│ │   Opções do dispositivo:• Dispositivo interno
│ │                       • Atualizável
│ │                       • O sistema exige uma fonte de alimentação externa
│ │                       • Precisa de uma reinício após a instalação
│ │                       • A verificação criptográfica de hash está disponível
│ │                       • O dispositivo pode ser usado durante a atualização
│ │ 
│ ├─UEFI Platform Key:
│ │     ID do dispositivo:6924110cde4fa051bfdc600a60620dc7aa9d3c6a
│ │     Resumo:           ASUSTeK MotherBoard PK Certificate
│ │     GUID:             54ef26b1-94d9-51d5-9e46-91732769a3c2 ← UEFI\CRT_6F52EF400A8634497D726A7A7D469FCA5905BADD
│ │   
│ └─UEFI dbx:
│       ID do dispositivo:362301da643102b9f38477387e2193e57abaa590
│       Resumo:           UEFI revocation database
│       Versão atual:     217
│       Versão mínima:    217
│       Fornecedor:       UEFI:Linux Foundation
│       Duração de instalação:1 segundo
│       GUIDs:            fda6234b-adcb-5105-8515-9af647d29775 ← UEFI\CRT_D7F66BE77CEF858C174BF4338A99263C8795B74E02026411F5F532F716AE3263
│                         f8ff0d50-c757-5dc3-951a-39d86e16f419 ← UEFI\CRT_D7F66BE77CEF858C174BF4338A99263C8795B74E02026411F5F532F716AE3263&ARCH_X64
│                         c6682ade-b5ec-57c4-b687-676351208742 ← UEFI\CRT_A1117F516A32CEFCBA3F2D1ACE10A87972FD6BBE8FE0D0B996E09E65D802A503
│                         f8ba2887-9411-5c36-9cee-88995bb39731 ← UEFI\CRT_A1117F516A32CEFCBA3F2D1ACE10A87972FD6BBE8FE0D0B996E09E65D802A503&ARCH_X64
│                         7d5759e5-9aa0-5f0c-abd6-7439bb11b9f6 ← UEFI\CRT_ED1FE72CB9CA31C9AF5B757AFCD733323D675825032E6CED7FE1AE9EB767998C
│                         0c7691e1-b6f2-5d71-bc9c-aabee364c916 ← UEFI\CRT_ED1FE72CB9CA31C9AF5B757AFCD733323D675825032E6CED7FE1AE9EB767998C&ARCH_X64
│       Opções do dispositivo:• Dispositivo interno
│                         • Atualizável
│                         • Suporte no servidor remoto
│                         • Precisa de uma reinício após a instalação
│                         • O dispositivo pode ser usado durante a atualização
│                         • Apenas atualizações de versão são permitidas
│                         • Signed Payload
│     
├─TPM:
│     ID do dispositivo:  c6a80ac3a22083423992a3cb15018989f37834d6
│     Resumo:             TPM 2.0 Device
│     Versão atual:       6.24.0.6
│     Fornecedor:         AMD (TPM:AMD)
│     GUIDs:              ff71992e-52f7-5eea-94ef-883e56e034c6 ← system-tpm
│                         9305de1c-1e12-5665-81c4-37f8e51219b8 ← TPM\VEN_AMD&DEV_0001
│                         78a291ae-b499-5b0f-8f1d-74e1fefd0b1c ← TPM\VEN_AMD&MOD_AMD
│                         65a3fced-b423-563f-8098-bf5c329fc063 ← TPM\VEN_AMD&DEV_0001&VER_2.0
│                         5e704f0d-83cb-5364-8384-f46d725a23b8 ← TPM\VEN_AMD&MOD_AMD&VER_2.0
│     Opções do dispositivo:• Dispositivo interno
│   
├─Unifying Receiver:
│     ID do dispositivo:  f45dd49c8d3986730837ee81361f96bf13f82fb1
│     Resumo:             Miniaturised USB wireless receiver
│     Versão atual:       RQR12.10_B0032
│     Versão do gestor de arranque:BOT01.02_B0014
│     Fornecedor:         HIDRAW:0x046D|USB:0x046D
│     Duração de instalação:30 segundos
│     GUIDs:              9d131a0c-a606-580f-8eda-80587250b8d6
│                         279ed287-3607-549e-bacc-f873bb9838c4 ← HIDRAW\VEN_046D&DEV_C52B
│                         fcf55bf5-767b-51ce-9c17-f6f538c4ee9f ← HIDRAW\VEN_046D&DEV_C52B&REV_00
│     Opções do dispositivo:• Atualizável
│                         • Suporte no servidor remoto
│                         • Unsigned Payload
│   
└─WDS100T1X0E-00AFY0:
      ID do dispositivo:  71b677ca0f1bc2c5b804fa1d59e52064ce589293
      Resumo:             NVM Express solid state drive
      Versão atual:       613200WD
      Fornecedor:         Sandisk Corp (NVME:0x15B7)
      Número de série:    204540802062
      GUIDs:              887c0622-74ea-5036-99bd-c6c63082bd37 ← NVME\VEN_15B7&DEV_5011
                          7b4c7b46-e1da-54fa-97fa-656c216629a2 ← NVME\VEN_15B7&DEV_5011&REV_01
                          b029d0ec-3f85-5cb7-a403-85c6f3bb4d83 ← NVME\VEN_15B7&DEV_5011&SUBSYS_15B75011
                          04de4e6b-264e-58a5-8947-a2bd85924418 ← NVME\VEN_15B7&DEV_5011&SUBSYS_15B75011&REV_01
                          c2f1c6cb-87a3-5a62-99fc-c23d4006b176 ← WDS100T1X0E-00AFY0
      Opções do dispositivo:• Dispositivo interno
                          • Atualizável
                          • O sistema exige uma fonte de alimentação externa
                          • Precisa de uma reinício após a instalação
                          • O dispositivo pode ser usado durante a atualização
    
</details>

**Additional questions**

- Operating system and version: Fedora 37
- Have you tried rebooting? Yes
- Is this a regression? I don't know

**Comment by hughsie** [comment]
Can you get us the output of `sudo fwupdtool security --force --verbose` please

**Comment by andreldmonteiro** [comment]
Yes: [fwupdtool security --force --verbose.txt](https://github.com/fwupd/fwupd/files/10014160/fwupdtool.security.--force.--verbose.txt)

**Comment by hughsie** [comment]
>  ASUS needs to be contacted about it.

Do you have any OEM contacts from the AMD side? Happy to move this to private email if that helps.

**Comment by superm1** [comment]
> Do you have any OEM contacts from the AMD side?  Happy to move this to private email if that helps

I'll ask around, but @andreldmonteiro you should also contact ASUS.

**Comment by superm1** [comment]
I had some discussion today about this.  There is no fwupd or kernel bug here.  The BIOS setting in the ASUS BIOS does not enable AMD's secure processor firmware anti rollback (FAR), it is an ASUS specific implementation.

My proposal is that we change the level used for AMD platform rollback support from "1" to something higher such as "4".  I'm opening a PR to discuss that.

**Comment by superm1** [comment]
@andreldmonteiro FYI, we did make the change to set AMD platform rollback protection to level 4 and this will be in the next version; thanks for the bug report.
