### ISSUE TITLE
https://fwupd.org/lvfs/devices/com.dell.uefib9870160.firmware not found

### ISSUE THREAD

**Issue by w5pny** [fwupd/fwupd#5280]
The latest Dell Precision 7760 firmware today is announced as available but clicking on the cab file yields "Not Found" and the fwupd update procedure gets "Not Found" as well when trying to download it.

**Comment by hughsie** [comment]
I get the same. Doing a fsck on the database now.

**Comment by hughsie** [comment]
Issue opened https://jira.linuxfoundation.org/plugins/servlet/desk/portal/2/IT-24877 will report back when we know what happened. It's very odd!

**Comment by hughsie** [comment]
Well, thankfully it's only one..

![Screenshot 2022-11-24 at 22-05-58 LVFS File system checks](https://user-images.githubusercontent.com/151380/203868780-2010bdf0-f071-4a89-9753-fd5e8f3c36bb.png)

**Comment by hughsie** [comment]
I've removed this file from the metadata in the meantime as all the sysadmin team is doing Thanksgiving and I don't have direct access to the EFS share.

**Comment by SicLuceatLux** [comment]
Since #5282 is realted to this issue. 404 Error is gone. It is downloading properly but now i got this 
![image](https://user-images.githubusercontent.com/43041463/205098124-317959c5-eed0-4040-99ef-406e1d100314.png)

**Comment by SicLuceatLux** [comment]
opend dedicated issue #5296

**Comment by w5pny** [comment]
Dell finally uploaded this missing file(s)...
