### ISSUE TITLE
fwupmgr update - 404 response

### ISSUE THREAD

**Issue by SicLuceatLux** [fwupd/fwupd#5282]
Since yesterday there is a new firmware for my Dell Precission 7560 
1.16.0 -> 1.17.1 

But everytime when confirming it is prompting 
`Failed to download, server response was 404`
I'm using fwupdmgr since years now on different Dell devices its the first time that this happens to me.
Of course PC is connected to internet etc. Since I thought there is some server issue i have waited a day to retry it but with the same outcome.
 
![Screenshot from 2022-11-25 09-09-47](https://user-images.githubusercontent.com/43041463/203933404-409c0856-02f8-4e48-b420-54f6f424bc2a.png)

**Comment by hughsie** [comment]
This is https://github.com/fwupd/fwupd/issues/5280 -- thanks for reporting it tho.
