### ISSUE TITLE
What does the recommended DMA protection parameter `iommu=pt` do?

### ISSUE THREAD

**Issue by BellaCoola** [fwupd/fwupd#5304]
Hello, I was recently looking at [fwupd documentation on how to enable DMA protection](https://fwupd.github.io/libfwupdplugin/hsi.html#org.fwupd.hsi.Iommu). It states that it can be enabled by using `intel_iommu=on` and `iommu=pt` kernel command line parameters. While the `intel_iommu` parameter is nicely documented in [Linux kernel documentation](https://www.kernel.org/doc/html/latest/admin-guide/kernel-parameters.html), I don't know what the `iommu=pt` parameter does. Please could you provide some more information on what is purpose of this parameter?

What I noticed is that when I use `iommu=pt` I see the following output during boot:

```sh
iommu: Default domain type: Passthrough
```

otherwise I see:

```sh
iommu: Default domain type: Translated
```

**Comment by superm1** [comment]
TBH I don't think we should be suggesting `iommu=pt` in the documentation.  It's _effectively_ turning off the IOMMU because all devices would be in the passthrough domain.  This means the IOMMU forwards all requests even if they should have been segmented.

@hughsie where did that half of the suggestion come from?  I think we should instead say:

```
Resolution: If available, turn on IOMMU in the system BIOS. You may also have to use additional kernel boot parameters, for example on Intel systems `intel_iommu=on`.
```

**Comment by hughsie** [comment]
> where did that half of the suggestion come from

I don't recall; I didn't even know what pt was until a few minutes ago :)

**Comment by superm1** [comment]
Here you go: https://github.com/torvalds/linux/blob/20cf903a0c407cef19300e5c85a03c82593bde36/Documentation/x86/x86_64/boot-options.rst

**Comment by superm1** [comment]
And https://github.com/torvalds/linux/blob/20cf903a0c407cef19300e5c85a03c82593bde36/Documentation/admin-guide/kernel-parameters.txt#L2148

**Comment by superm1** [comment]
The second one explains it pretty well, but I think the part missing is `iommu=pt` is the same as `iommu.passthrough=1`

**Comment by superm1** [comment]
> Thank you. What bugs me is that IOMMU should prevent unsolicited access to part or all of the physical memory address space (this is how I understand it). When IOMMU is using the Translated domain type, it uses a concept of virtual memory to solve this issue, not allowing use of DMA. However when the Passthrough domain type is used, could the IOMMU allow DMA, but only to some specific region of memory, which the software is allowed to access - thus improving performance but still providing the same amount of security because it checks and prevents access outside of bounds of this allowed region? Sorry if this is a stupid question, but I can't find much information on this topic described in some approachable fashion on the internet. This is also the reason why I was asking for some links which would describe this topic in more detail.

No I don't believe it can work that way. You can't have you cake and eat it too. The best you can get is to set up an exclusion for a device or range of devices. But when you do that you have no security for them.
