### ISSUE TITLE
Please provide a quiet switch

### ISSUE THREAD

**Issue by noloader** [fwupd/fwupd#5361]
When I run `fwupdmgr` in my update scripts it produces some irrelevant noise. I want to see errors, but not warnings and not info. In the output below `Updating firmware` is a message from my script. The other output is generated by the tool.

```shell
Updating firmware
WARNING: UEFI capsule updates not available or enabled in firmware setup
  See https://github.com/fwupd/fwupd/wiki/PluginFlag:capsules-unsupported for more information.
WARNING: UEFI capsule updates not available or enabled in firmware setup
  See https://github.com/fwupd/fwupd/wiki/PluginFlag:capsules-unsupported for more information.
Devices with no available firmware updates:
 • 032G74
No updatable devices
```

Here is the piece of script that calls `fwupdmgr`:

```bash
if [[ -n $(command -v fwupdmgr 2>/dev/null) ]]; then
    echo "Updating firmware"
    fwupdmgr refresh 1>/dev/null && fwupdmgr update 1>/dev/null
fi
```

It would be nice to have a quiet switch, like `-q`, to cut down on the extra noise.

**Comment by hughsie** [comment]
There's a --json flag you might be interested in...

**Comment by noloader** [comment]
Thanks @hughsie.

Please forgive my ignorance... Could you provide the commit where the option was added?

**Comment by hughsie** [comment]
Sure, it was added in 1.7.3 but there's been more and more support added for each command for each release. e.g. you can do `fwupdmgr --version --json` in dbd099507161816177028324467384c23ebbe668
