### ISSUE TITLE
CID 1530302:  Resource leaks 

### ISSUE THREAD

**Issue by sabriunal** [fwupd/fwupd#5368]
I used to add Coverity Scan for fwupd.

There are a new report may indicate a resource leak.

Hi, Please find the latest report on new defect(s) introduced to hughsie/fwupd found with Coverity Scan. 1 new defect(s) introduced to hughsie/fwupd found with Coverity Scan.

New defect(s) Reported-by: Coverity Scan Showing 1 of 1 defect(s)
________________________________________________________________________________________________________
*** CID 1530302:  Resource leaks  (RESOURCE_LEAK)
fwupd/plugins/wacom-usb/fu-wac-module-scaler.c: 57 in fu_wac_module_scaler_parse_blocks()
Line: https://github.com/fwupd/fwupd/blob/main/plugins/wacom-usb/fu-wac-module-scaler.c#L57
```
51                                  0x0, /* dst */
52                                  data,
53                                  sz,
54                                  addr, /* src */
55                                  cdata_sz,
56                                  error))
>>>     CID 1530302:  Resource leaks  (RESOURCE_LEAK)
>>>     Variable "bd" going out of scope leaks the storage it points to.
57                      return NULL;
58              bd->crc = ~fu_crc8(bd->cdata, sizeof(bd->cdata));
59              g_ptr_array_add(blocks, bd);
60      }
61      return blocks;
62     }
```

**Comment by hughsie** [comment]
I fixed up the nit in https://github.com/fwupd/fwupd/commit/faeefb66d03f30a76ff42281fff3d6e9536e9ccf#diff-feb9a4a441659d62d9dd764e310359086301a528585ce9d012352806203435d0 about an hour ago -- thanks for the report tho.
