### ISSUE TITLE
fwupd 1.8.8-1 x8_64 tar.zst missing on ALL ArchLinux pacman repositories

### ISSUE THREAD

**Issue by samuel0r** [fwupd/fwupd#5376]
**Describe the question**
Trying to install archlinux followed by installing desktop: eirher gnome, xfce, plasma. Did run reflector - to rate 100 repositories without country limitations. All attempts fail to find fwupd 1.8.8-1 package.
**fwupd version information**
1.8.8-1 x86_64 as required by any desktop.
```shell
fwupdmgr --version
`
During ArchLinux install from recent 2023 iso.
Trying to install a desktop pacakage group: plasma, gnome, xfce. Trying to install just "pacman -S fwupd". All attempts fail to find fwupd-1.8.8-1 x86_64 tar.zst.
As I not able to extract files during fresh unfinished install I attach screen capture.
[fwupd-1.8.8-1.error.txt](https://github.com/fwupd/fwupd/files/10343608/fwupd-1.8.8-1.error.txt)

**Comment by hughsie** [comment]
This isn't an upstream problem, you need to file an issue with archlinux I'm afraid.
