### ISSUE TITLE
Feedback from Lenovo T14 Gen 3 AMD

### ISSUE THREAD

**Issue by patch-work** [fwupd/fwupd#5394]
**Describe the question**

Please check the following. 

Both the output of "fwupdmgr security" and Gnome's Device Security show that the "Processor rollback protection" is disabled. According to its description, "Rollback Protection prevents device software from being downgraded to an older version that has security problems". However, firmware downgrade protection is enabled in the BIOS. 

**fwupd version information**

```shell
fwupdmgr --version

compile   org.freedesktop.fwupd         1.8.9
compile   com.hughsie.libjcat           0.1.12
runtime   org.freedesktop.fwupd-efi     1.3
compile   org.freedesktop.gusb          0.4.3
runtime   com.hughsie.libjcat           0.1.12
runtime   com.dell.libsmbios            2.4
runtime   org.freedesktop.gusb          0.4.3
runtime   org.freedesktop.fwupd         1.8.9
runtime   org.kernel                    6.0.18-300.fc37.x86_64
```

```shell

Host: 21CFCTO1WW ThinkPad T14 Gen 3 
CPU: AMD Ryzen 7 PRO 6850U with Radeon Graphics (16) @ 4.768GHz
Kernel: 6.0.18-300.fc37.x86_64
OS: Fedora Linux 37 (Workstation Edition) x86_64
DE: GNOME 43.2
```

![S1](https://user-images.githubusercontent.com/49366178/211528614-33c05546-0948-488f-b766-b256dd0066d0.png)
![S2](https://user-images.githubusercontent.com/49366178/211528647-27d69fc9-91a9-43bd-8470-c3b9b27efc71.png)
![S3](https://user-images.githubusercontent.com/49366178/211528791-554290b0-fd5d-42cf-9423-9cf5a7d47ef5.png)
![IMG_20230106_195714_991](https://user-images.githubusercontent.com/49366178/211535980-56414281-5fa9-4df0-b3d5-a292964d09be.jpg)

**Comment by superm1** [comment]
That option controls BIOS rollback protection not secure processor rollback protection.
I guess this issue means we need to further disambiguate it in the docs.

**Comment by patch-work** [comment]
The BIOS options with the "Secure Processor" (TPM/Pluton) do not include Pluton rollback protection, but they do include the option to disable Pluton (see photos). 

According to the propaganda, the "AMD Secure Processor" implements Intel Pluton, which claims to be "always up-to-date" "through Windows Update". 

I do not use Windows, so I disabled Pluton (see photo).

![IMG_20230110_161950_531](https://user-images.githubusercontent.com/49366178/211592361-3346b708-bcaa-4eb4-933a-c2f51aed73e8.jpg)
![IMG_20230110_161950_531](https://user-images.githubusercontent.com/49366178/211592392-ed1d40c4-1658-478d-996b-8644c89e12da.jpg)

https://www.amd.com/en/technologies/pro-security

**Comment by superm1** [comment]
I'm not referring to pluton.  Notice in the page you linked there are two security processors referred:

- Microsoft Pluton Security Processor
- AMD Secure processor

The check here is specifically for rollback protection of the AMD secure processor, it's up to the manufacturer to decide whether they want that enabled or not.  Let me draft up a PR to make the documentation a little more clear.


BTW in your above screenshots I notice GNOME panel showed encrypted RAM off but fwupdmgr showed it on.  Were those taken at different boots where you changed the BIOS setting?  Or do we actually have an inconsistency?

**Comment by patch-work** [comment]
> The check here is specifically for rollback protection of the AMD secure processor, it's up to the manufacturer to decide whether they want that enabled or not. Let me draft up a PR to make the documentation a little more clear.

OK

> BTW in your above screenshots I notice GNOME panel showed encrypted RAM off but fwupdmgr showed it on. Were those taken at different boots where you changed the BIOS setting? Or do we actually have an inconsistency?

Same session, so there is an inconsistency.

**Comment by superm1** [comment]
>Do we need to lobby Lenovo for rollback protection?

Not necessarily.  Manufacturers may have valid reasons to not need it enabled.  For example, if the EC validates the entire SPI image and you have BIOS/EC rollback protection enacted then it's **very difficult** to flash an updated security processor firmware.

This is part of the reason that we bumped it up to HSI-4 in the first place.  We found that there are reasons that manufacturers choose not to enable it, and it's up to their product decisions and other security mechanisms in place whether it's still a major threat.

>Same session, so there is an inconsistency.

Glad I checked.  OK... can you please open a bug in the appropriate GNOME tracker?  It looks like fwupd is probably doing it right to me, but the GNOME panel might not be using the flags properly.

**Comment by patch-work** [comment]
https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/2176

**Comment by SamuelBMartins** [comment]
Here it is. 
Btw I had "Rollback protection" disabled in the past and [these instructions](https://forums.lenovo.com/t5/Fedora/AMD-Rollback-protection-not-detected-by-fwupd-on-T14-G3-AMD/m-p/5182708?page=1#5810366) helped me enable it. I noticed the option "Rollback protection" does not exists anymore but now there is "Processor rollback protection" and "BIOS rollback protection". Maybe those instruction can help for your problem too.
![PXL_20230111_154004137 MP](https://user-images.githubusercontent.com/28544097/211850779-0ae45155-a50b-43a9-a9c5-6c88e00b7f6e.jpg)

**Comment by patch-work** [comment]
I followed the instructions. I had the same options set, except for "OS Optimized Defaults". This is the result:

![Screenshot from 2023-01-11 17-01-19](https://user-images.githubusercontent.com/49366178/211855621-eeefb075-bf08-4cb4-ad3c-9d1b9b9f3c23.png)

**Comment by superm1** [comment]
@mrhpearson can you explain?  Is the action of loading "Optimized OS defaults" what is getting security processor rollback protection enabled?

If so; we may want to amend our documentation for this issue.  Thoughts?

**Comment by smallorange** [comment]
Hi,
We've proposed our new GUI in GNOME44 to improve the user experience and the improvement also covers this issue. Could you try the latest version of the firmware security setting panel?
