### ISSUE TITLE
Followup question to #5415

### ISSUE THREAD

**Issue by kernie** [fwupd/fwupd#5431]
**Describe the question**
After learning from #5415 I contacted ASROCK support to ask for activation of the CPU support in the BIOS of the motherboard.

I got following back: 

> BIOS department ask if you have more closer information which BIOS option or feature need to be enable for HSI-1 security?

Since I'm now the man-in-the-middle I wonder if you can provide a reference I can refer to?

Thank you!

**Comment by hughsie** [comment]
@superm1 works for AMD, maybe he can share what exact thing the OEM needs to enable in the BIOS build?

**Comment by superm1** [comment]
For completeness sake, please share run the following and share the `dmesg.txt`
```
# dmesg --clear
# rmmod ccp
# modprobe ccp dyndbg
# dmesg > dmesg.txt

> @superm1 works for AMD, maybe he can share what exact thing the OEM needs to enable in the BIOS build?

I can't talk about that kind of stuff publicly.  I'd suggest you ask them to contact their "AMD BAE" to discuss the details.  But keep in mind CNY is about to start, so probably won't make progress for a week or two.

**Comment by kernie** [comment]
dmesg.txt:
```
[ 2899.277892] ccp 0000:11:00.2: ccp: unable to access the device: you might be running a broken BIOS.
[ 2899.277894] ccp 0000:11:00.2: psp: unable to access the device: you might be running a broken BIOS.
[ 2902.770316] SVM: TSC scaling supported
[ 2902.770318] kvm: Nested Virtualization enabled
[ 2902.770319] SVM: kvm: Nested Paging enabled
[ 2902.770323] SVM: Virtual VMLOAD VMSAVE supported
[ 2902.770323] SVM: Virtual GIF supported
[ 2902.770323] SVM: LBR virtualization supported
```
