### ISSUE TITLE
fwupd.service: Failed with result 'timeout'

### ISSUE THREAD

**Issue by PhilDevProg** [fwupd/fwupd#5450]
Hello,
if I start fwupd via `sudo systemctl start fwupd.service` I get this error: `Job for fwupd.service failed because a timeout was exceeded.`
And if I go to the status of it I see this:

> × fwupd.service - Firmware update daemon
     Loaded: loaded (/usr/lib/systemd/system/fwupd.service; static)
     Active: failed (Result: timeout) since Wed 2023-01-25 16:20:49 CET; 1min 31s ago
       Docs: https://fwupd.org/
    Process: 3303 ExecStart=/usr/libexec/fwupd/fwupd (code=killed, signal=TERM)
   Main PID: 3303 (code=killed, signal=TERM)
        CPU: 401ms
Jan 25 16:17:49 fedora systemd[1]: Starting fwupd.service - Firmware update daemon...
Jan 25 16:17:49 fedora fwupd[3303]: 15:17:49.214 FuBiosSettings       KERNEL BUG: 'type' attribute not exported: (failed to load type: Datei >>/sys/class/firmware-attributes/thinklmi/attributes/SecureBoot/type<< konnte nicht geoeffnet werden: Datei oder>
Jan 25 16:17:49 fedora fwupd[3303]: 15:17:49.380 FuEngine             no GUIDs for device TPM [dfb1a4db3787a1799167fb68010ef732c71041f9]
Jan 25 16:20:49 fedora systemd[1]: fwupd.service: start operation timed out. Terminating.
Jan 25 16:20:49 fedora systemd[1]: fwupd.service: Failed with result 'timeout'.
Jan 25 16:20:49 fedora systemd[1]: Failed to start fwupd.service - Firmware update daemon.

And I can't start it... I'm using a fresh install of Fedora Workstation 37.

**Comment by superm1** [comment]
Can you please modify the unit to add `--verbose` and see if you get a more verbose log on the failure?

**Comment by PhilDevProg** [comment]
Do I have to put `--verbose` into ExecStart? If I do that, nothing changes...

**Comment by hughsie** [comment]
Can you grab the complete output of `sudo /usr/libexec/fwupd/fwupd --verbose` please?

**Comment by PhilDevProg** [comment]
I don't know why but it works again...
