### ISSUE TITLE
No Updates found for Samsung SSD 980 PRO 2TB

### ISSUE THREAD

**Issue by dtrunk90** [fwupd/fwupd#5477]
**Describe the question**
Why `fwupdmgr update` returns `No updateable devices`?
My SSD currently is on FW 3B2QGXA7 and i need to install the FW asap before my SSD probably dies: https://www.tomshardware.com/news/samsung-980-pro-ssd-failures-firmware-update

```shell
$ sudo fwupdmgr get-devices
X299 UD4 Pro
│
├─SSD 980 PRO 2TB:
│     Device ID:          71b677ca0f1bc2c5b804fa1d59e52064ce589293
│     Summary:            NVM Express solid state drive
│     Current version:    3B2QGXA7
│     Vendor:             Samsung (NVME:0x144D)
│     Serial Number:      S69ENF0RA19092X
│     GUID:               4d7a2791-106b-5e72-9cfb-8ea3d89f5421 ← NVME\VEN_144D&DEV_A80A&SUBSYS_144DA801&REV_00
│                         310f81b5-6fce-501e-acfb-487d10501e78 ← NVME\VEN_144D&DEV_A80A&SUBSYS_144DA801
│                         60c89aac-f321-515b-b419-3cf02aa9d375 ← NVME\VEN_144D&DEV_A80A&REV_00
│                         bec63ed7-a95f-54fe-b8cc-8e9fee64ba5a ← NVME\VEN_144D&DEV_A80A
│                         c8bffd05-1744-5cdd-ad4d-0fbc3b20e3c2 ← Samsung SSD 980 PRO 2TB
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│                         • Signed Payload
│   
└─Unifying Receiver:
      Device ID:          fb1a5fd6e7d8cbf5d5a2ba7df68aee106ce41027
      Summary:            Miniaturised USB wireless receiver
      Current version:    RQR24.11_B0036
      Bootloader Version: BOT03.02_B0009
      Vendor:             HIDRAW:0x046D|USB:0x046D
      Install Duration:   30 seconds
      GUID:               cc4cbfa9-bf9d-540b-b92b-172ce31013c1
                          fcf55bf5-767b-51ce-9c17-f6f538c4ee9f ← HIDRAW\VEN_046D&DEV_C52B&REV_00
                          279ed287-3607-549e-bacc-f873bb9838c4 ← HIDRAW\VEN_046D&DEV_C52B
      Device Flags:       • Updatable
                          • Signed Payload
    
$ sudo fwupdmgr --force refresh
Updating lvfs
Downloading…             [***************************************]
Successfully downloaded new metadata: 0 local devices supported
```
Does that mean i just can't use fwupdmgr for my devices because none of them are supported but still listed?

Current fw version based on https://semiconductor.samsung.com/consumer-storage/support/tools/ is 5B2QGXA7.
So why it is telling me there are no updateable devices?

**fwupd version information**
```shell
$ fwupdmgr --version
runtime   org.freedesktop.fwupd         1.7.9
runtime   com.dell.libsmbios            2.4
compile   org.freedesktop.gusb          0.3.4
runtime   org.kernel                    5.15.0-58-generic
compile   com.hughsie.libjcat           0.1.4
compile   org.freedesktop.fwupd         1.7.9
runtime   org.freedesktop.gusb          0.3.4
```

**Comment by hughsie** [comment]
> Does that mean i just can't use fwupdmgr for my devices because none of them are supported but still listed?

Exactly that; if you have a device supported on the LVFS you'd see something like:

	├─Unifying Receiver:
	│     Device ID:          07b9f6c3b0d723cac5ddb859b651b58fdfd1a4df
	│     Summary:            Miniaturised USB wireless receiver
	│     Current version:    RQR12.07_B0029
	│     Bootloader Version: BOT01.02_B0014
	│     Vendor:             HIDRAW:0x046D|USB:0x046D
	│     Install Duration:   30 seconds
	│     GUIDs:              9d131a0c-a606-580f-8eda-80587250b8d6
	│                         279ed287-3607-549e-bacc-f873bb9838c4 ← HIDRAW\VEN_046D&DEV_C52B
	│                         fcf55bf5-767b-51ce-9c17-f6f538c4ee9f ← HIDRAW\VEN_046D&DEV_C52B&REV_00
	│     Device Flags:       • Updatable
	│                         • Supported on remote server
	│                         • Unsigned Payload

I think you need to email Samsung and ask them to upload the firmware update to the LVFS I'm afraid.

**Comment by dtrunk90** [comment]
> I think you need to email Samsung and ask them to upload the firmware update to the LVFS I'm afraid.

Thanks, I'll do that.

**Comment by dtrunk90** [comment]
Samsung support just ignored my request to upload the FW update to LVFS. I've downloaded the ISO and booted to update manually. Pretty cumbersome.

**Comment by hughsie** [comment]
> Samsung support just ignored my request to upload the FW update to LVFS

Can you escalate? I think if one person complains it's easy to ignore, but hundreds of people are much harder to justify ignoring...

**Comment by dtrunk90** [comment]
> Can you escalate? I think if one person complains it's easy to ignore, but hundreds of people are much harder to justify ignoring...

Unfortunately no. I can't get past Natalie from german customer support team. She just repeatedly writes that they only have Magician which is windows only and an ISO which needs to be used for a bootable medium like a usb stick. So I did that because I don't want my SSD to die soon.

**Comment by dtrunk90** [comment]
The request got finally redirected from the support. Hopefully they'll upload future fw updates to LVFS now.

**Comment by hughsie** [comment]
Okay, that's pretty amazing. If they want a point-of-contact feel free to give them richard_at_hughsie.com -- the LVFS product owner.

**Comment by dtrunk90** [comment]
I gave them this issue url

**Comment by iramello** [comment]
If there's some place to +1 this request, please let everyone know.
If Samsung doesn't support LVFS, I'll switch to another brand which does it already.

**Comment by aradapilot** [comment]
this is pretty shocking, a major vendor not following industry standards.  well, they're losing my business too because of it.

**Comment by bjornfor** [comment]
> If Samsung doesn't support LVFS, I'll switch to another brand which does it already.

Do you have any recommendations?

**Comment by dtrunk90** [comment]
> If there's some place to +1 this request, please let everyone know. If Samsung doesn't support LVFS, I'll switch to another brand which does it already.

I don't think that I'll hear anything again from Samsung regarding this tbh :-(



> > If Samsung doesn't support LVFS, I'll switch to another brand which does it already.
> 
> Do you have any recommendations?

I always had great experience with western digital, but here's a list of vendors you could choose from: https://fwupd.org/lvfs/vendors/

**Comment by iramello** [comment]
...
> I always had great experience with western digital, but here's a list of vendors you could choose from: https://fwupd.org/lvfs/vendors/
> 
> EDIT: But since Samsung and WD both "uploading firmware on behalf of other vendors" I guess WD isn't a good choice here?!

Both of them shows as uploading firmware but we do know it is NOT true for Samsung. 

I don't know for Western Digital, somebody could confirm or deny? if WD is not on LVFS either, which other one could be?

**Comment by dtrunk90** [comment]
> ...
> 
> > I always had great experience with western digital, but here's a list of vendors you could choose from: https://fwupd.org/lvfs/vendors/
> > EDIT: But since Samsung and WD both "uploading firmware on behalf of other vendors" I guess WD isn't a good choice here?!
> 
> Both of them shows as uploading firmware but we do know it is NOT true for Samsung.
> 
> I don't know for Western Digital, somebody could confirm or deny? if WD is not on LVFS either, which other one could be?

I assume "uploading firmware on behalf of other vendors"  means that for example if Dell or any other vendor has a device built into one of their products they'll upload firmware updates for that specific device. But the vendor of that device itself doesn't upload firmware. There's also a device list: https://fwupd.org/lvfs/devices/

**Comment by warptozero** [comment]
> EDIT: For 2TB SSDs i can only find 2 entries:

There is also the Samsung PM9A1 which is actually an OEM version of the 980 Pro.

https://fwupd.org/lvfs/search?value=pm9a1
https://fwupd.org/lvfs/devices/com.lenovo.PM9A1.low.firmware.v031101

The firmware seems to be uploaded by Lenovo and Dell. Note how the latest Lenovo firmware version (CL2QGXA7) partly matches the one of the 980 Pro (5B2QGXA7).

**Comment by prahal** [comment]
@dtrunk90 can you share the Samsung contact url or email you send your request to?
I have a 990 Pro 2TB.
I don't expect much but if we don't tell them we care...

A few months ago I attempted to find how they select the firmware in the archive they provide (the way to extract the firmware from the blob has been reverse-engineered, but not how they select which binary in the archive ... though that might be the easiest part I did not complete it.
I believe we cannot have these binaries uploaded to LVFS without Samsung consent though.

**Comment by hughsie** [comment]
> but not how they select which binary in the archive

In fwupd there are a choice of three GUIDs vendors can choose: https://github.com/fwupd/fwupd/blob/main/plugins/nvme/README.md#guid-generation -- if you do work it out for for the magician software please let us know.

**Comment by dtrunk90** [comment]
> @dtrunk90 can you share the Samsung contact url or email you send your request to? I have a 990 Pro 2TB. I don't expect much but if we don't tell them we care...
> 
> A few months ago I attempted to find how they select the firmware in the archive they provide (the way to extract the firmware from the blob has been reverse-engineered, but not how they select which binary in the archive ... though that might be the easiest part I did not complete it. I believe we cannot have these binaries uploaded to LVFS without Samsung consent though.

I've opened a ticket (No. 62306) but cannot find where their ticketing system is. You could however try to contact them by their phone numbers published here: https://semiconductor.samsung.com/consumer-storage/support/service-center/

More than a year went by and never heard of them again.
