### ISSUE TITLE
website: Broken link to metainfo

### ISSUE THREAD

**Issue by tv42** [fwupd/fwupd#5503]
**Describe the bug**

On the website, page https://fwupd.org/lvfs/docs/vendors toward the end has

```
one <a href="/metainfo">.metainfo.xml</a> file that describes the target device and firmware.
```

https://fwupd.org/metainfo gives a 404 The page you're looking for is not found.

Maybe you meant https://lvfs.readthedocs.io/en/latest/metainfo.html ?

**Comment by hughsie** [comment]
Fixed in https://gitlab.com/fwupd/lvfs-website/-/commit/30632180ffd8f1a270c84384316d29d1ec667c2d -- many thanks.

**Comment by hughsie** [comment]
(i'll deploy this when we next do a fix, it seems a bit of a waste to re-spin up all the containers just for a one line HTML change)
