### ISSUE TITLE
Flakiness with fu_progress_get_duration() unit tests

### ISSUE THREAD

**Issue by djcampello** [fwupd/fwupd#5547]
assertion failed (fu_progress_get_duration(progress) == 0.1f (+/- 0.05)): (0.154924 == 0.100000001)

This has happen multiple times in different builders.

From a comment on the original bug report: "These all look like we're just outside the "epsilon" of a floating point comparison. Should the epsilon be bumped a bit? (espsilon == 0.1 instead of 0.05 would cover all this.)"

**Comment by hughsie** [comment]
100ms is a pretty huge epsilon; got any clues on why the timing would be so funky?

**Comment by djcampello** [comment]
It seems it happens when running the unit tests virtualized via qemu as part of building other archs via cross-compiling... Expanding on the above error log:

```
ERROR:../fwupd-1.8.9/libfwupdplugin/fu-self-test.c:3534:fu_progress_func: assertion failed (fu_progress_get_duration(progress) == 0.1f (+/- 0.05)): (0.169768 == 0.100000001)
qemu: uncaught target signal 6 (Aborted) - core dumped
```
