### ISSUE TITLE
Release 1.8.11 @`https://people.freedesktop.org/~hughsient/releases/` ?

### ISSUE THREAD

**Issue by freswa** [fwupd/fwupd#5581]
There is currently no signed release in `https://people.freedesktop.org/~hughsient/releases/`. Have those been discontinued? @hughsie

**Comment by hughsie** [comment]
Yup, as planned -- you need to use https://github.com/fwupd/fwupd/releases now I'm afraid. Using github means any of us can do a release if needed.
