### ISSUE TITLE
fwupdmgr shows device name as 000:00:1f.5 instead of using the device name (which I don't know...

### ISSUE THREAD

**Issue by marcosps** [fwupd/fwupd#5632]
**Describe the bug**
"fwupdmgr update" shows a device number instead of the device name
0000:00:1f.5

I believe this specific device wasn't there before the update of fwupdmgr (on openSUSE Tumbleweed).

**Steps to Reproduce**
fwupdmgr update

**Expected behavior**
Device name instead of device number 0000:00:1f.5

**fwupd version information**
Please provide the version of the daemon and client.

```shell
fwupdmgr --version
compile   org.freedesktop.fwupd         1.8.
compile   com.hughsie.libxmlb           0.3.10
compile   com.hughsie.libjcat           0.1.12
runtime   org.freedesktop.fwupd-efi     1.0
compile   org.freedesktop.gusb          0.3.10
runtime   com.hughsie.libjcat           0.1.12
runtime   com.dell.libsmbios            2.4
runtime   org.freedesktop.gusb          0.3.10
runtime   org.kernel                    6.2.4-1-default
runtime   org.freedesktop.fwupd         1.8.12
```

Please note how you installed it (`apt`, `dnf`, `pacman`, source, etc):
zypper install

<summary>**fwupd device information**</summary>

Please provide the output of the fwupd devices recognized in your system.

```shell
fwupdmgr get-devices --show-all-devices

Reading…                 [ -                                     ]Reading…                 [ -                                     ]Dell Inc. Latitude 5320
│

├─WD19S:
│ │   Device ID:          930f7ad0bd8cf2ce9c98fc73d1af557675051094
│ │   Summary:            High performance dock
│ │   Current version:    01.01.00.03
│ │   Vendor:             Dell Inc. (USB:0x413C)
│ │   Install Duration:   1 minute
│ │   Serial Number:      57CR0L3/3168981644916390
│ │   GUID:               cd357cf1-40b2-5d87-b8df-bb2dd82774aa ← USB\VID_413C&PID_B06E&hub&embedded
│ │   Device Flags:       • Updatable
│ │                       • Supported on remote server
│ │                       • Device stages updates
│ │                       • Device can recover flash failures
│ │                       • Device is usable for the duration of the update
│ │                       • Signed Payload
│ │ 
│ ├─Package level of Dell dock:
│ │     Device ID:        3caede69cb211be4895d966d2b22b4f31d49faef
│ │     Summary:          A representation of dock update status
│ │     Current version:  01.00.25.01
│ │     Vendor:           Dell Inc. (USB:0x413C)
│ │     Install Duration: 5 seconds
│ │     GUIDs:            d8927ff5-a5b2-5618-848b-8e8bfb75b66f
│ │                       8ceeeffd-51b6-580c-9b75-69143227aff8 ← USB\VID_413C&PID_B06E&hub&status
│ │     Device Flags:     • Updatable
│ │                       • Supported on remote server
│ │                       • Device can recover flash failures
│ │                       • Device is usable for the duration of the update
│ │                       • Unsigned Payload
│ │   
│ ├─RTS5413 in Dell dock:
│ │     Device ID:        8f2866a3b89ebabe6ccc7119059c202011bb56ca
│ │     Summary:          USB 3.1 Generation 1 Hub
│ │     Current version:  01.21
│ │     Vendor:           Dell Inc. (USB:0x413C)
│ │     Install Duration: 14 seconds
│ │     GUIDs:            b27d25f1-019d-5718-b41a-02ddaefe5577 ← USB\VID_413C&PID_B06F
│ │                       86fb40c0-8bf5-5a8b-a4ad-3156cf6bfaf4 ← USB\VID_413C&PID_B06F&REV_0101
│ │                       ac5b774c-b49d-566b-9255-85f0f7f8a4ed ← USB\VID_413C&PID_B06F&hub
│ │     Device Flags:     • Updatable
│ │                       • Supported on remote server
│ │                       • Device stages updates
│ │                       • Device is usable for the duration of the update
│ │                       • Signed Payload
│ │   
│ ├─RTS5487 in Dell dock:
│ │     Device ID:        6cc64708fbc1b127f0302928ca74b45224a748ab
│ │     Summary:          USB 3.1 Generation 2 Hub
│ │     Current version:  01.47
│ │     Vendor:           Dell Inc. (USB:0x413C)
│ │     Install Duration: 3 seconds
│ │     GUIDs:            acfcd89b-105d-55b9-b85b-08bf8508f38c ← USB\VID_413C&PID_B06E
│ │                       707c63d2-e597-5c40-84db-9b1bb4c48d96 ← USB\VID_413C&PID_B06E&REV_0101
│ │                       568ffa1e-a0db-5287-9ea3-872b60f7730b ← USB\VID_413C&PID_B06E&hub
│ │     Device Flags:     • Updatable
│ │                       • Supported on remote server
│ │                       • Device stages updates
│ │                       • Device is usable for the duration of the update
│ │                       • Signed Payload
│ │   
│ └─VMM5331 in Dell dock:
│       Device ID:        8686d22e79cb37383ed5ca95b2da7c94e01e733f
│       Summary:          Multi Stream Transport controller
│       Current version:  05.06.03
│       Vendor:           Dell Inc. (USB:0x413C)
│       Install Duration: 6 minutes
│       GUID:             89fec0b6-6b76-5008-b82c-5e5c6c164007 ← MST-panamera-vmm5331-259
│       Device Flags:     • Updatable
│                         • Supported on remote server
│                         • Device stages updates
│                         • Device is usable for the duration of the update
│                         • Unsigned Payload
│     
├─Unknown Device:
│     Device ID:          63223cc2d1b0b8d4c45ef8cedcb1f45315d3ff20
│     GUID:               ca5c154c-a46a-59d8-bf77-0ca40522cc85 ← GPIO\ID_INT34C5:00
│   
├─0000:00:1f.5:
│     Device ID:          b04e387fb80d2b91f37a4d0c7b21461c451775e1
│     Summary:            Memory Technology Device
│     Vendor:             DMI:Dell Inc.
│     GUIDs:              5f93d7e7-e282-59b9-b663-0146e382f8f6 ← MTD\NAME_0000:00:1f.5
│                         b858f197-3e26-5077-a45c-69bb2ddd6a9e ← MTD\VENDOR_Dell-Inc.&NAME_0000:00:1f.5
│                         65c50a26-e842-56be-ae79-4ddcda5de7f1 ← MTD\VENDOR_Dell-Inc.&PRODUCT_Latitude-5320&NAME_0000:00:1f.5
│     Device Flags:       • Internal device
│                         • Updatable
│                         • Needs a reboot after installation
│                         • Cryptographic hash verification is available
│   
├─11th Gen Intel Core™ i7-1185G7 @ 3.00GHz:
│ │   Device ID:          4bde70ba4e39b28f9eab1628f9dd6e6244c03027
│ │   Current version:    0x000000a6
│ │   Vendor:             Intel
│ │   GUIDs:              b9a2dd81-159e-5537-a7db-e7101d164d3f ← cpu
│ │                       30249f37-d140-5d3e-9319-186b1bd5cac3 ← CPUID\PRO_0&FAM_06
│ │                       2347ad97-b545-5bae-b6b3-b70a9553cbba ← CPUID\PRO_0&FAM_06&MOD_8C
│ │                       1df99df5-22f4-5505-98cc-22dcc53b132a ← CPUID\PRO_0&FAM_06&MOD_8C&STP_1
│ │   Device Flags:       • Internal device
│ │ 
│ └─USB4 host controller:
│       Device ID:        0f04dd8aa3f6758950aa38a84653fab0a0dca19d
│       Summary:          Unmatched performance for high-speed I/O
│       GUID:             e72e778e-94f7-5ed2-b560-1c1262ee217c ← TBT-fixed
│       Device Flags:     • Internal device
│                         • System requires external power source
│                         • Signed Payload
│     
├─IM2P33F3A NVMe ADATA 512GB:
│     Device ID:          188dc728af57960ba9943289b8b32546baeac5f5
│     Summary:            NVM Express solid state drive
│     Current version:    92209301
│     Vendor:             ADATA Technology Co., Ltd. (NVME:0x1CC1)
│     Serial Number:      DL4925WPM2QC
│     GUIDs:              53f16832-8fd9-536c-b006-e1610314d459 ← STORAGE-DELL-109737
│                         096da7a8-2137-4343-8d99-bdc6f640016d
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Supported on remote server
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─System Firmware:
│ │   Device ID:          a45df35ac0e948ee180fe216a5f703f32dda163f
│ │   Summary:            UEFI ESRT device
│ │   Current version:    1.24.3
│ │   Minimum Version:    1.24.3
│ │   Vendor:             Dell (DMI:Dell Inc.)
│ │   Update State:       Success
│ │   GUIDs:              8feb4145-631b-4d45-8c6a-9d3eb47e1d02
│ │                       230c8b18-8d9b-53ec-838b-6cfc0383493a ← main-system-firmware
│ │   Device Flags:       • Internal device
│ │                       • Updatable
│ │                       • System requires external power source
│ │                       • Supported on remote server
│ │                       • Needs a reboot after installation
│ │                       • Device is usable for the duration of the update
│ │ 
│ ├─AMT [unprovisioned]:
│ │     Device ID:        8d5470e73fd9a31eaa460b2b6aea95483fe3f14c
│ │     Summary:          Hardware and firmware technology for remote out-of-band management
│ │     Current version:  15.0.42.2235
│ │     Bootloader Version:15.0.42.2235
│ │     Vendor:           Intel Corporation (MEI:0x8086)
│ │     GUIDs:            12f80028-b4b7-4b2d-aca8-46e0ff65814c
│ │                       f18c7464-aa01-5b3d-bd4f-6623597d0f70 ← MEI\VEN_8086&DEV_A0E0
│ │                       395a4458-f3a4-54b5-9947-e8b069f33c31 ← MEI\VEN_8086&DEV_A0E0&REV_20
│ │                       5d71947b-d250-5609-b008-b47413b39292 ← MEI\VEN_8086&DEV_A0E0&SUBSYS_10280A1F
│ │                       0542b70e-4c03-51dd-9a5d-679fe2c8b264 ← MEI\VEN_8086&DEV_A0E0&SUBSYS_10280A1F&REV_20
│ │     Device Flags:     • Internal device
│ │   
│ ├─BootGuard Configuration:
│ │     Device ID:        b0d4430dfa6bde9f0c22680df36dbc8c15c80753
│ │     Current version:  20
│ │     Vendor:           Intel Corporation (MEI:0x8086)
│ │     GUIDs:            dd17041c-09ea-4b17-a271-5b989867ec65
│ │                       f18c7464-aa01-5b3d-bd4f-6623597d0f70 ← MEI\VEN_8086&DEV_A0E0
│ │                       395a4458-f3a4-54b5-9947-e8b069f33c31 ← MEI\VEN_8086&DEV_A0E0&REV_20
│ │                       5d71947b-d250-5609-b008-b47413b39292 ← MEI\VEN_8086&DEV_A0E0&SUBSYS_10280A1F
│ │                       0542b70e-4c03-51dd-9a5d-679fe2c8b264 ← MEI\VEN_8086&DEV_A0E0&SUBSYS_10280A1F&REV_20
│ │     Device Flags:     • Internal device
│ │   
│ ├─UEFI Platform Key:
│ │     Device ID:        6924110cde4fa051bfdc600a60620dc7aa9d3c6a
│ │     Summary:          Dell Inc. Platform Key
│ │     Vendor:           Dell Inc.
│ │     GUID:             5f7cc4ea-9f7a-5c5f-b535-dfbcc73f5ba6 ← UEFI\CRT_2493B118EABD632FD3BA49C333A8329B1982E872
│ │   
│ └─UEFI dbx:
│       Device ID:        362301da643102b9f38477387e2193e57abaa590
│       Summary:          UEFI revocation database
│       Current version:  217
│       Minimum Version:  217
│       Vendor:           UEFI:Linux Foundation
│       Install Duration: 1 second
│       GUIDs:            00fe3755-a4d8-5ef7-ba5f-47979fbb3423 ← UEFI\CRT_E28D59CA489BD2AD580F2EA5D62D6A29BB9C02AE5A818434A37DA7FC11DFF9E9
│                         4a6cd2cb-8741-5257-9d1f-89a275dacca7 ← UEFI\CRT_E28D59CA489BD2AD580F2EA5D62D6A29BB9C02AE5A818434A37DA7FC11DFF9E9&ARCH_X64
│                         c6682ade-b5ec-57c4-b687-676351208742 ← UEFI\CRT_A1117F516A32CEFCBA3F2D1ACE10A87972FD6BBE8FE0D0B996E09E65D802A503
│                         f8ba2887-9411-5c36-9cee-88995bb39731 ← UEFI\CRT_A1117F516A32CEFCBA3F2D1ACE10A87972FD6BBE8FE0D0B996E09E65D802A503&ARCH_X64
│       Device Flags:     • Internal device
│                         • Updatable
│                         • Supported on remote server
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│                         • Only version upgrades are allowed
│                         • Signed Payload
│     
├─TPM 2.0:
│     Device ID:          a3487e128cf1413519bce8e9a1ab3f5981e61458
│     Summary:            UEFI ESRT device
│     Current version:    0.1.1.2
│     Vendor:             Dell Inc. (PCI:0x1028)
│     Update State:       Success
│     Update Error:       [31m[1mUpdating disabled due to TPM ownership[0m
│     GUIDs:              94813093-6f5f-5846-83df-ebc8565dc83e ← 0a1f-2.0
│                         ff71992e-52f7-5eea-94ef-883e56e034c6 ← system-tpm
│     Device Flags:       • Internal device
│                         • System requires external power source
│   
├─TigerLake-LP GT2 [Iris Xe Graphics]:
│     Device ID:          5792b48846ce271fab11c4a545f7a3df0d36e00a
│     Current version:    01
│     Vendor:             Intel Corporation (PCI:0x8086)
│     GUIDs:              54ff3ed7-1ea3-5279-975f-93c13bf2aa53 ← PCI\VEN_8086&DEV_9A49
│                         3c11d563-4f83-5bd1-8369-75359ea6b6f6 ← PCI\VEN_8086&DEV_9A49&REV_01
│                         0c754a14-6b1e-52ab-856e-7a3ee334616f ← PCI\VEN_8086&DEV_9A49&SUBSYS_10280A1F
│                         4e699927-6f29-51c2-9270-87ac330b630d ← PCI\VEN_8086&DEV_9A49&SUBSYS_10280A1F&REV_01
│                         06f2a40f-75b6-5238-9fac-71ea35045c1c ← PCI\VEN_8086&DEV_9A49&REV_00
│                         c19aa53c-4498-54da-97bd-cc749ddc26b0 ← PCI\VEN_8086&DEV_9A49&SUBSYS_10280A1F&REV_00
│     Device Flags:       • Internal device
│                         • Cryptographic hash verification is available
│   
├─UEFI Device Firmware:
│     Device ID:          349bb341230b1a86e5effe7dfe4337e1590227bd
│     Summary:            UEFI ESRT device
│     Current version:    164
│     Minimum Version:    164
│     Vendor:             DMI:Dell Inc.
│     Update State:       Success
│     GUID:               176e090d-0ddb-495e-8173-bc998ccfecd0
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─UEFI Device Firmware:
│     Device ID:          2292ae5236790b47884e37cf162dcf23bfcd1c60
│     Summary:            UEFI ESRT device
│     Current version:    2451608321
│     Minimum Version:    2451608321
│     Vendor:             Dell (DMI:Dell Inc.)
│     Update State:       Success
│     GUID:               096da7a8-2137-4343-8d99-bdc6f640016d
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Supported on remote server
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
└─Unifying Receiver:
      Device ID:          c8ea32ee236c29758b6d64671175a246e9e0d8f1
      Summary:            Miniaturised USB wireless receiver
      Current version:    RQR24.11_B0036
      Bootloader Version: BOT03.02_B0009
      Vendor:             HIDRAW:0x046D|USB:0x046D
      Install Duration:   30 seconds
      GUIDs:              cc4cbfa9-bf9d-540b-b92b-172ce31013c1
                          279ed287-3607-549e-bacc-f873bb9838c4 ← HIDRAW\VEN_046D&DEV_C52B
                          fcf55bf5-767b-51ce-9c17-f6f538c4ee9f ← HIDRAW\VEN_046D&DEV_C52B&REV_00
      Device Flags:       • Updatable
                          • Signed Payload
    
```

</details>

**Additional questions**

I don't remember seeing this device since the last update of fwupd. I also opened a bug on gnome-firmware (https://gitlab.gnome.org/World/gnome-firmware/-/issues/51) but I believe that the problem is on fwupdmgr.

**Comment by hughsie** [comment]
Can you grab me the output of `sudo fwupdtool get-devices --plugins mtd -vv` please?

**Comment by marcosps** [comment]
> sudo fwupdtool get-devices --plugins mtd -vv

Sure:

23:13:54.231 FuDebug              Verbose debugging enabled (on console 0)
23:13:54.231 FuMain               locked /run/lock/fwupdtool
23:13:54.231 GLib-GIO             Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
23:13:54.233 FuMain               Failed to stop daemon: failed to find fwupd.service: GDBus.Error:org.freedesktop.systemd1.NoSuchUnit: Unit fwupd.service not loaded.
23:13:54.233 FuConfig             trying to load config values from /etc/fwupd/daemon.conf
23:13:54.233 FuCommon             reading /etc/fwupd/daemon.conf with 2563 bytes
23:13:54.233 FuConfig             trying to load config values from /var/etc/fwupd/daemon.conf
23:13:54.233 FuConfig             using autodetected max archive size 4.1 GB
23:13:54.234 GLib-GIO             _g_io_module_get_default: Found default implementation local (GLocalVfs) for 'gio-vfs'
23:13:54.234 FuRemoteList         loading /usr/share/fwupd/metainfo
23:13:54.234 XbSilo               attempting to load /var/cache/fwupd/metainfo.xmlb
23:13:54.234 XbSilo               file: 2e361253-a665-01ce-d47f-22f7c53afb85, current:2e361253-a665-01ce-d47f-22f7c53afb85, cached: (null)
23:13:54.234 XbSilo               loading silo with file contents
23:13:54.234 FuRemoteList         loading remote from /etc/fwupd/remotes.d/dell-esrt.conf
23:13:54.234 FuRemoteList         loading remote from /etc/fwupd/remotes.d/vendor-directory.conf
23:13:54.234 FuRemoteList         loading remote from /etc/fwupd/remotes.d/vendor.conf
23:13:54.234 FuRemoteList         skipping invalid file /etc/fwupd/remotes.d/lvfs-testing.conf.rpmsave
23:13:54.234 FuRemoteList         skipping invalid file /etc/fwupd/remotes.d/lvfs.conf.rpmsave
23:13:54.234 FuRemoteList         loading remote from /etc/fwupd/remotes.d/lvfs-testing.conf
23:13:54.234 FuRemoteList         loading remote from /etc/fwupd/remotes.d/lvfs.conf
23:13:54.234 FuRemoteList         skipping invalid file /var/lib/fwupd/remotes.d/lvfs
23:13:54.234 FuRemoteList         ordering lvfs-testing=lvfs+1
23:13:54.234 FuRemoteList         ignoring unfound remote fwupd
23:13:54.234 Jcat                 ignoring GPG-KEY-Linux-Foundation-Firmware as not PKCS-7 certificate
23:13:54.234 Jcat                 ignoring GPG-KEY-Linux-Vendor-Firmware-Service as not PKCS-7 certificate
23:13:54.234 Jcat                 reading /etc/pki/fwupd/LVFS-CA.pem with 1679 bytes
23:13:54.234 Jcat                 loaded 1 certificates
23:13:54.234 Jcat                 ignoring GPG-KEY-Linux-Foundation-Metadata as not PKCS-7 certificate
23:13:54.234 Jcat                 ignoring GPG-KEY-Linux-Vendor-Firmware-Service as not PKCS-7 certificate
23:13:54.234 Jcat                 reading /etc/pki/fwupd-metadata/LVFS-CA.pem with 1679 bytes
23:13:54.234 Jcat                 loaded 1 certificates
23:13:54.234 Jcat                 reading /var/lib/fwupd/pki/secret.key with 2459 bytes
23:13:54.234 Jcat                 reading /var/lib/fwupd/pki/client.pem with 1383 bytes
23:13:54.234 FuEngine             client certificate now exists: nothing to do
23:13:54.234 FuHistory            trying to open database '/var/lib/fwupd/pending.db'
23:13:54.235 FuHistory            got schema version of 8
23:13:54.238 FuPlugin             load(/usr/lib64/fwupd-1.8.12/libfu_plugin_modem_manager.so)
23:13:54.239 FuPluginUefiCapsule  failed to get fwupd-efi runtime version: searching /usr/libexec/fwupd/efi/fwupdx64.efi.signed: needle of 0x24 bytes was not found in haystack of 0xf718 bytes
23:13:54.239 FuContext            added udev subsystem watch of platform
23:13:54.239 FuContext            added udev subsystem watch of pci
23:13:54.239 FuContext            added udev subsystem watch of block
23:13:54.239 GLib                 setenv()/putenv() are not thread-safe and should not be used after threads are created
23:13:54.239 FuPluginDell         Using libsmbios 2.4
23:13:54.239 FuContext            added udev subsystem watch of i2c
23:13:54.239 FuContext            added udev subsystem watch of i2c-dev
23:13:54.239 FuContext            added udev subsystem watch of hidraw
23:13:54.239 FuContext            added udev subsystem watch of gpio
23:13:54.239 FuContext            added udev subsystem watch of mei
23:13:54.239 FuContext            added udev subsystem watch of iommu
23:13:54.239 FuContext            added udev subsystem watch of video4linux
23:13:54.239 FuContext            added udev subsystem watch of msr
23:13:54.239 FuContext            added udev subsystem watch of mtd
23:13:54.239 FuContext            added udev subsystem watch of nvme
23:13:54.240 FuContext            added udev subsystem watch of drm
23:13:54.240 FuContext            added udev subsystem watch of drm_dp_aux_dev
23:13:54.240 FuContext            added udev subsystem watch of serio
23:13:54.240 FuPluginTest         init
23:13:54.240 FuContext            added udev subsystem watch of thunderbolt
23:13:54.240 FuContext            added udev subsystem watch of tpm
23:13:54.240 FuQuirks             loading quirks from /usr/share/fwupd/quirks.d
23:13:54.240 FuQuirks             loading quirks from /var/lib/fwupd/quirks.d
23:13:54.240 XbSilo               attempting to load /var/cache/fwupd/quirks.xmlb
23:13:54.240 XbSilo               file: 3686ad24-d914-27df-6667-0d2e12e1b978, current:3686ad24-d914-27df-6667-0d2e12e1b978, cached: (null)
23:13:54.240 XbSilo               loading silo with file contents
23:13:54.241 FuContext            loading HwId overrides from /etc/fwupd/daemon.conf
23:13:54.241 FuContext            not loading HwId overrides from /var/lib/fwupd/daemon.conf
23:13:54.241 FuContext            smbios property Manufacturer=Dell Inc.
23:13:54.241 FuContext            smbios property EnclosureKind=a
23:13:54.241 FuContext            smbios property Family=Latitude
23:13:54.241 FuContext            smbios property ProductName=Latitude 5320
23:13:54.241 FuContext            smbios property ProductSku=0A1F
23:13:54.241 FuContext            smbios property BiosVendor=Dell Inc.
23:13:54.241 FuContext            smbios property BiosVersion=1.24.3
23:13:54.241 FuContext            smbios property BiosMajorRelease=01
23:13:54.241 FuContext            smbios property BiosMinorRelease=18
23:13:54.241 FuContext            smbios property FirmwareMajorRelease=ff
23:13:54.241 FuContext            smbios property FirmwareMinorRelease=ff
23:13:54.241 FuContext            smbios property BaseboardManufacturer=Dell Inc.
23:13:54.241 FuContext            smbios property BaseboardProduct=074GF2
23:13:54.241 FuContext            failed to load fdt: cannot find /sys/firmware/fdt or override /var/lib/fwupd/system.dtb
23:13:54.244 FuContext            added udev subsystem watch of firmware-attributes
23:13:54.244 FuBiosSettings       reset_bios is not supported
23:13:54.244 FuBiosSettings       loaded 2 BIOS settings
23:13:54.244 FuProgress           raw timing data was { 0.000, 0.000, 0.003, 0.000 } -- steps were set as [ 1 1 3 95 ] but should have been [ 8 1 89 2 ] at ../libfwupdplugin/fu-context.c:810
23:13:54.244 FuEngine             ignoring: Error opening directory "/var/lib/fwupd/local.d": No such file or directory
23:13:54.244 FuEngine             ignoring: Error opening directory "/usr/share/fwupd/local.d": No such file or directory
23:13:54.244 XbSilo               attempting to load /var/cache/fwupd/metadata.xmlb
23:13:54.244 XbSilo               file: db06044c-9108-b502-b56f-01295c3e272a, current:db06044c-9108-b502-b56f-01295c3e272a, cached: (null)
23:13:54.244 XbSilo               loading silo with file contents
23:13:54.245 FuEngine             1939 components now in silo
23:13:54.253 GLib-GIO             Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
23:13:54.255 FuEngine             plugins disabled: flashrom, modem_manager, uefi_capsule, acpi_dmar, acpi_facp, acpi_ivrs, acpi_phat, amd_pmc, amd_gpu, analogix, android_boot, ata, bcm57xx, bios, ccgx, cfu, ch341a, colorhug, corsair, cpu, cros_ec, dell, dell_dock, dell_esrt, dfu, dfu_csr, ebitdo, elantp, elanfp, emmc, ep963x, fastboot, focalfp, fpc, fresco_pd, genesys, goodixmoc, gpio, hailuck, igsc, intel_me, intel_usb4, iommu, jabra, lenovo_thinklmi, linux_lockdown, linux_sleep, linux_swap, linux_tainted, logind, logitech_hidpp, logitech_bulkcontroller, logitech_scribe, msr, nitrokey, nordic_hid, nvme, optionrom, parade_lspcon, pci_bcr, pci_mei, pci_psp, pixart_rf, powerd, qsi_dock, realtek_mst, redfish, rts54hid, rts54hub, steelseries, scsi, superio, synaptics_cape, synaptics_cxaudio, synaptics_mst, synaptics_prometheus, synaptics_rmi, system76_launch, test, test_ble, thelio_io, thunderbolt, ti_tps6598x, tpm, uefi_dbx, uefi_pk, uefi_recovery, uf2, upower, usi_dock, vbe, vli, wacom_raw, wacom_usb, wistron_dock
23:13:54.258 FuContext            battery threshold now 10
23:13:54.259 FuPlugin             startup(mtd)
23:13:54.259 FuEngine             using plugins: mtd
23:13:54.439 FuDevice             using b04e387fb80d2b91f37a4d0c7b21461c451775e1 for DEVPATH=/devices/pci0000:00/0000:00:1f.5/spi_master/spi0/spi0.0/mtd/mtd0
23:13:54.439 FuPlugin             emit added from mtd: b04e387fb80d2b91f37a4d0c7b21461c451775e1
23:13:54.443 FuDeviceList         ::added b04e387fb80d2b91f37a4d0c7b21461c451775e1
23:13:54.443 FuMain               ADDED:
FuMtdDevice:
  DeviceId:             b04e387fb80d2b91f37a4d0c7b21461c451775e1
  Name:                 0000:00:1f.5
  Guid:                 5f93d7e7-e282-59b9-b663-0146e382f8f6 <- MTD\NAME_0000:00:1f.5
  Guid:                 b858f197-3e26-5077-a45c-69bb2ddd6a9e <- MTD\VENDOR_Dell-Inc.&NAME_0000:00:1f.5
  Guid:                 65c50a26-e842-56be-ae79-4ddcda5de7f1 <- MTD\VENDOR_Dell-Inc.&PRODUCT_Latitude-5320&NAME_0000:00:1f.5
  Summary:              Memory Technology Device
  Plugin:               mtd
  Protocol:             org.infradead.mtd
  Flags:                internal|updatable|registered|needs-reboot|can-verify|can-verify-image
  VendorId:             DMI:Dell Inc.
  Icon:                 drive-harddisk-solidstate
  Created:              2023-03-18
  Guid[quirks]:         218e91a5-ec18-5589-9881-72b018d70b61 <- MTD\TYPE_MTD
  Guid[quirks]:         6726a6e0-f18b-5e35-985f-6cc8b2cb903d <- MTD
  PhysicalId:           DEVPATH=/devices/pci0000:00/0000:00:1f.5/spi_master/spi0/spi0.0/mtd/mtd0
  BackendId:            /sys/devices/pci0000:00/0000:00:1f.5/spi_master/spi0/spi0.0/mtd/mtd0
  AcquiesceDelay:       2500
  FirmwareSizeMax:      33554432
  PossiblePlugin:       mtd
  InternalFlags:        is-open|md-set-signed
  EraseSize:            0x1000

23:13:54.445 FuDevice             using 4c6f545e8b07914d7958312136bc2ae8396e8f19 for DEVPATH=/devices/pci0000:00/0000:00:1f.5/spi_master/spi0/spi0.0/mtd/mtd0/mtd1
23:13:54.466 FuEngine             ignoring add event for already loaded settings
23:13:54.469 FuBackend            adding suitable BlueZ device: /org/bluez/hci0/dev_DC_2C_26_26_3B_CA
23:13:54.477 FuEngine             resetting update motd timeout
23:13:54.482 FuMain               FuMtdDevice:
  DeviceId:             b04e387fb80d2b91f37a4d0c7b21461c451775e1
  Name:                 0000:00:1f.5
  Guid:                 5f93d7e7-e282-59b9-b663-0146e382f8f6 <- MTD\NAME_0000:00:1f.5
  Guid:                 b858f197-3e26-5077-a45c-69bb2ddd6a9e <- MTD\VENDOR_Dell-Inc.&NAME_0000:00:1f.5
  Guid:                 65c50a26-e842-56be-ae79-4ddcda5de7f1 <- MTD\VENDOR_Dell-Inc.&PRODUCT_Latitude-5320&NAME_0000:00:1f.5
  Summary:              Memory Technology Device
  Plugin:               mtd
  Protocol:             org.infradead.mtd
  Flags:                internal|updatable|registered|needs-reboot|can-verify|can-verify-image
  VendorId:             DMI:Dell Inc.
  Icon:                 drive-harddisk-solidstate
  Created:              2023-03-18

23:13:54.484 FuPluginTest         destroy
23:13:54.484 FuProgress           raw timing data was { 0.000, 0.000, 0.003, 0.000 } -- steps were set as [ 1 1 3 95 ] but should have been [ 8 1 89 2 ] at ../libfwupdplugin/fu-context.c:810
