### ISSUE TITLE
Flatpak packaging bug: Incorrect permissions on read-only mounted /app/etc/fwupd/fwupd.conf prevents running fwupdtool

### ISSUE THREAD

**Issue by mihailim** [fwupd/fwupd#5817]
**Describe the bug**

The `org.freedesktop.fwupd` flatpak package provides `/app/etc/fwupd/fwupd.conf` with mode `0644`. When run, `fwupdtool` attempts to change it to `0640` (`FU_CONFIG_FILE_MODE_SECURE`) as per [this code section](https://github.com/fwupd/fwupd/blob/218037263454dac4892c6bec49fff58de192b014/libfwupdplugin/fu-config.c#L104), however that fails inside the flaptak sandbox since `/app` is obviously read-only.

The flatpak-ed fwupdtool used to work perfectly before the latest update.

**Steps to Reproduce**

```sh
root@host:~# flatpak install flathub org.freedesktop.fwupd
<snip>
root@host:~# flatpak run org.freedesktop.fwupd --version
Loading…                 [ -                                     ]
Failed to load config: failed to change permission of /app/etc/fwupd/fwupd.conf
```

And, indeed, checking inside the sandbox it looks like this:

```sh
root@host:~# flatpak run --command=sh org.freedesktop.fwupd
[📦 org.freedesktop.fwupd ~]# ls -la /app/etc/fwupd/fwupd.conf
-rw-r--r-- 2 root root 119 ian  1  1970 /app/etc/fwupd/fwupd.conf
[📦 org.freedesktop.fwupd ~]# /app/bin/fwupdtool --version
Loading…                 [ -                                     ]
Failed to load config: failed to change permission of /app/etc/fwupd/fwupd.conf
```

**Expected behavior**

fwupdtool should run.

**fwupd version information**

`org.freedesktop.fwupd` version 1.9.1 at flatpak commit `964c2ffa191e29` installed from Flathub as per the above.

It's not possible to provide the details asked for in the issue template, since fwupdtool will no longer run anything, including `--version`. Fortunately, the system details aren't really pertinent to the issue.

- Operating system and version: Debian bullseye, however it's immaterial.
- Have you tried rebooting?: Yes.
- Is this a regression?: Yes, used to work in 1.8.x.

**Comment by hughsie** [comment]
Weird, and somewhat unexpected -- meson should be installing:

	  install_data(['fwupd.conf'],
	    install_dir: join_paths(sysconfdir, 'fwupd'),
	    install_mode: 'rw-r-----',
	  )

..in flatpak builder.  Any ideas on why this gets overridden?
