### ISSUE TITLE
Capture used space in efivarfs

### ISSUE THREAD

**Issue by superm1** [fwupd/fwupd#5830]
A kernel patch that has been queued up for kernel 6.5 exposes the used and total size of efivarfs.  We should capture this as part of the the report for UEFI capsules and also use this in fwupd to identify some failure scenarios.

https://lkml.org/lkml/2023/5/17/957

**Comment by hughsie** [comment]
Just for the metadata report, or to check *before* to do things like dbx and capsule updates?

**Comment by superm1** [comment]
I think metadata report initially, we need to see how well vendors report this information.
