### ISSUE TITLE
Kensington TBT4 dock model SD5700T

### ISSUE THREAD

**Issue by alebrati** [fwupd/fwupd#5867]
Hi Richard, Benson,
Intel has a meeting with Denis from collabora in order to enable PD of this dock, and we faced some issues while adding the vid/pid to quirk file locally using fwupd tool. Denis has all the logs and asked to open this issue as tracker.
the cypress PD controller we saw was also there : CWPD5235

the dock info:
![image](https://github.com/fwupd/fwupd/assets/106619839/b6876656-604b-4341-844e-f8b15ee03e6d)

usb vendor id is 0x047D
usb device id is 0x809B

we scheduled another session with Denis. in meantime here is the bug and will send link to Denis
[thanks]([fwupd_ccg5_3.txt](https://github.com/fwupd/fwupd/files/11600200/fwupd_ccg5_3.txt))

**Comment by d4s** [comment]
Tried to add it into quirk file in runtime:
```
[USB\VID_047D&PID_809B]
Plugin = ccgx
GType = FuCcgxHpiDevice
```
unfortunately that's not enough even communicate with the PD:
```
08:40:22.611 FuEngine             usb:05:00:01:04:08 added FuUsbDevice:
  Guid:                 9b5e9224-8915-5073-b6cd-049df468cb22 <- USB\VID_047D&PID_809B ?
  Guid:                 94588a7c-e285-5c9e-bad8-9916e09b85b0 <- USB\VID_047D&PID_809B&REV_1746 ?
  Flags:                none
  VendorId:             USB:0x047D
  Version:              17.46
  VersionFormat:        bcd
  VersionRaw:           0x00001746
  Guid[quirks]:         229a49a7-90b2-5d51-be83-0cdd1661e129 <- USB\VID_047D
  Guid[quirks]:         00513169-b132-5fe6-859b-bd8fb04f89d9 <- USB\CLASS_11
  Guid[quirks]:         d7e609dc-f5b4-52f3-a5d2-14959051dd16 <- USB\CLASS_11&SUBCLASS_00
  Guid[quirks]:         48c55639-9b8b-5410-a1bc-3a011cb3a799 <- USB\CLASS_11&SUBCLASS_00&PROT_00
  Guid[quirks]:         4bd986bc-4aaf-5baf-8bc2-9f7928182387 <- USB\CLASS_FF
  Guid[quirks]:         78c9681b-f906-52ee-aaa7-9b58bc4a1505 <- USB\CLASS_FF&SUBCLASS_03
  Guid[quirks]:         d27ab148-1c4b-53f6-9414-d9032eb5abfe <- USB\CLASS_FF&SUBCLASS_03&PROT_00
  PhysicalId:           usb:05:00:01:04:08
  AcquiesceDelay:       2500
  PossiblePlugin:       ccgx
  ParentPhysicalIds:    usb:05:00:01:04,usb:05:00:01
  UsbDeviceClass:       interface-desc

08:40:22.613 FuDevice             already set GType to FuCcgxHpiDevice, ignoring FuCcgxHpiDevice
08:40:22.615 FuDevice             using 47158723785b8d7c60b7538f9022704a447a9f34 for usb:05:00:01:04:08
08:40:22.618 FuDevice             FuCcgxHpiDevice flag 0x1 is unknown -- use fu_device_register_private_flag()
08:40:22.618 FuEngine             failed to add device usb:05:00:01:04:08: get config error: i2c get config error: control xfer: endpoint stalled or request not supported
```
Have no additional info to proceed:
- symmetric/assymetric update
- do we need parent or bootloader mode to communicate with the device?
- Flash size (`CcgxFlashSize`) and metadata offset (`CcgxFlashRowSize`)

**Comment by hughsie** [comment]
Can you get a dump of the windows updater and see what it's doing?

**Comment by d4s** [comment]
I have no device on hands.
@alebrati probably?

**Comment by arao15** [comment]
@hughsie / @d4s : Which windows updater log are you looking for ? Do you have steps that I can follow ?

**Comment by alebrati** [comment]
any updates on that?

**Comment by d4s** [comment]
@hughsie any idea how to catch the update logs from the thunderbolt device on Windows?
