### ISSUE TITLE
Building the best UEFI GUID database using LVFS

### ISSUE THREAD

**Issue by NikolajSchlej** [fwupd/fwupd#5869]
Right now there are several efforts tor build a database of GUIDs related to UEFI and its implementations:
- [UEFITool](https://github.com/LongSoft/UEFITool/blob/new_engine/common/guids.csv)
- [Binarly](https://github.com/binarly-io/guiddb)

Such database is useful for researching images that don't include UI sections, but based on the same sources than other images that do include such sections.

The most recent version of UEFIExtract ([A66](https://github.com/LongSoft/UEFITool/releases/tag/A66)) added automatic dumping of all detected GUID-name pairs into ${filename}.guids.csv when launched with default set of parameters. I know that UEFIExtract is already getting applied to LVFS uploads, so we can build a database of all GUID-name pairs known to LVFS once, and then add entries to it when a new file gets uploaded. The resulting database will likely be miles ahead of both DBs linked above.

**Comment by NikolajSchlej** [comment]
CC @hughsie @matrosov @yeggor

**Comment by NikolajSchlej** [comment]
More GUIDs: https://github.com/abazhaniuk/efi-whitelist

**Comment by hughsie** [comment]
> More GUIDs: https://github.com/abazhaniuk/efi-whitelist

Ohh wow, not a lot of updates in the last 5 years there! Do you think they're still useful?

**Comment by hughsie** [comment]
> Right now there are several efforts tor build a database of GUIDs related to UEFI and its implementations:
>    [UEFITool](https://github.com/LongSoft/UEFITool/blob/new_engine/common/guids.csv)

Would it be acceptable to use the guids.csv data under the CC0-1.0 licence?

**Comment by NikolajSchlej** [comment]
> Ohh wow, not a lot of updates in the last 5 years there! Do you think they're still useful?
Might still be, especially if covering images not covered by LVFS yet.
> Would it be acceptable to use the guids.csv data under the CC0-1.0 licence?
Sure thing.

**Comment by hughsie** [comment]
https://gitlab.com/fwupd/lvfs-website/-/commit/7757355abef97b420e6adb950423049386045c37 is a good start. I'll deploy that and then let the cron job chew it over during the night.

**Comment by NikolajSchlej** [comment]
Thanks a ton, will update my guids.csv now to remove most of those differences (because `UsbRtSmm` is a better name than `USBRT` after all). The growth of the DB is expected and welcome.

**Comment by yeggor** [comment]
> can I absorb the data from guiddb and make it available under a CC0-1.0 licence

@hughsie of course you can

**Comment by hughsie** [comment]
guiddb also imported:

![Screenshot 2023-06-06 at 17-28-28 LVFS Component GUIDs](https://github.com/fwupd/fwupd/assets/151380/15fbe7b5-f218-46d0-bd72-f66a335d5794)

**Comment by yeggor** [comment]
> @yeggor you should be able to edit/add entries with https://fwupd.org/lvfs/shards/ and there's a anonymous download available from https://fwupd.org/lvfs/shards/export/csv -- the latter will take an hour or so to update.

thank you!

**Comment by hughsie** [comment]
@yeggor do you need me to provide a guiddb-compatible export endpoint or is the CSV good for you too?

**Comment by yeggor** [comment]
CSV looks fine, thank you. I will write a script for`guids.json` updates

**Comment by hughsie** [comment]
Okay; lets close for now and we can re-open if Alex gives us the nod for the older GUIDs.

**Comment by JonathonReinhart** [comment]
Hi folks I found this issue while trying to determine if anyone had created a defacto-standard UEFI GUID DB.

Is https://fwupd.org/lvfs/shards/export/csv intended to be just that?

Does https://github.com/LongSoft/UEFITool/commits/new_engine/common/guids.csv pull from LVFS? Vice-versa? Neither? I ask because it contains GUIDs which aren't present here (E.g. `FF11E702-8923-47CC-AD30-D9E0E240DD10,AAFTblDxe`).

I also found https://github.com/Sentinel-One/efi_fuzz/blob/master/guids.csv which has yet other GUIDs.

Thanks, because I haven't found this documented anywhere!

**Comment by JonathonReinhart** [comment]
Oops, just kidding. I must have gotten my files mixed up when comparing.

I wrote this to fetch and merge the CSVs: https://gist.github.com/JonathonReinhart/745b6c29ade75e1b08783339db20297e

I confirmed that LVFS is the most up-to-date:


* https://fwupd.org/lvfs/shards/export/csv
  * Total:   12193
  * Unique:  11
  * Missing: 0
* https://raw.githubusercontent.com/LongSoft/UEFITool/refs/heads/new_engine/common/guids.csv
  * Total:   12182
  * Unique:  0
  * Missing: 11
* https://raw.githubusercontent.com/Sentinel-One/efi_fuzz/refs/heads/master/guids.csv
  * Total:   3375
  * Unique:  0
  * Missing: 8818

Thanks!

**Comment by NikolajSchlej** [comment]
I'm manually pulling the GUID DB from LVFS into UEFITool repo before each release, that's why it gets slightly outdated with the time. 

There are certainly a lot of additional GUIDs we could be collecting using UEFITool if we add an automation to send the newly-determined GUIDs to a server somewhere, and I'm even having a VPS already that might do such a thing, but adding networking into UEFITool that previously never had it seems kinda hard, so I keep sleeping on this. Might open a feature request though, because the idea is decent.
