### ISSUE TITLE
wacom: Unable to flash main (EMR) firmware -- cannot create bytes

### ISSUE THREAD

**Issue by jigpu** [fwupd/fwupd#5971]
While working on pull request #5901, I noticed that after rebasing my commits I lost the ability to flash the main / EMR firmware. Looking at the commit history, I suspected 5ad1462de2d7d2b93376c9f55fe061b5b01d0f0b as the cause, and reverting that commit does indeed restore the functionality.

**Describe the bug**
When attempting to flash firmware for a particular (not-yet-released) device, the following error is printed out and fwupd terminates. This message occurs after the Bluetooth firmware finishes flashing and while fwupd is trying to flash the maim / EMR firmware.

~~~
cannot create bytes @0x800c000 for 0xf809d52e as buffer only 0xa952e bytes in size
~~~

When flashing with the `-vv` option, the following information about the file is printed out prior to the error. Note how the values of `header_fw0_addr` and `programing-start-address` are equal to the offset specified in the error message:

~~~
20:10:51.275 FuPluginWacomUsb     header_fw0_addr: 0x800c000
20:10:51.275 FuPluginWacomUsb     header_fw0_sz:   0xaced4
20:10:51.275 FuPluginWacomUsb     header_fw1_addr: 0x8046000
20:10:51.275 FuPluginWacomUsb     header_fw1_sz:   0xaced6
20:10:51.275 FuPluginWacomUsb     programing-start-address: 0x800c000
~~~

I suspect that this issue is triggered by the following call made by the main / EMR flashing code, where `hdr->addr` (aka `header_fw0_addr` from above) is passed as the offset to `fu_firmware_parse_full()`.
https://github.com/fwupd/fwupd/blob/109c3e4ce5644860a8a945381458f74229a591cb/plugins/wacom-usb/fu-wac-firmware.c#L232-L239

I'm not familiar enough with this particular section of code to understand why the address was being passed as an offset or what the fix should look like.

If I revert commit 5ad1462de2d7d2b93376c9f55fe061b5b01d0f0b the error disappears and I am able to flash the main / EMR firmware without issue.

**Steps to Reproduce**
Although I do not have a second Wacom device handy at the moment, I suspect that trying to flash most devices should trigger something similar to the above error.

1. Attempt to flash the firmware of a supported Wacom tablet
2. Observe that when fwupd reaches the step of updating main / EMR firmware, that an error message similar to the above is printed and fwupd quits.

**Expected behavior**
Fwupd should be able to complete the flash without failure.

**fwupd version information**
Commit 613a3e2044ff54f3fa648e680febd0e6f5b9d1ea installed from source.

**Comment by hughsie** [comment]
Aha, the srec firmware uses the offset in a weird (incorrect!) way -- I'll add some API to make it explicit. Thanks for the report.
