### ISSUE TITLE
1.9.3 snap shows error for `fwupd.fwupdtool security`

### ISSUE THREAD

**Issue by superm1** [fwupd/fwupd#5995]
**Describe the bug**
I installed the fwupd 1.9.3 confined snap and ran `sudo fwupd.fwupdtool security`
I see the following error (in addition to error from https://github.com/fwupd/fwupd/issues/5994):

```
FuPluginLinuxSwap    could not parse /proc/swaps: Error when getting information for file “/swapfile”: No such file or directory
```

**Steps to Reproduce**
Set up a system with a swapfile.  Here's mine:
```
$ cat /proc/swaps
Filename                                Type            Size            Used            Priority
/swapfile                               file            2097148         0               -2
```

Then run:
```
sudo apt remove fwupd
sudo snap install fwupd
sudo fwupd.fwupdtool security
```

**Expected behavior**
No errors

**fwupd version information**
```
compile   org.freedesktop.fwupd         1.9.3
compile   com.hughsie.libxmlb           0.3.6
compile   com.hughsie.libjcat           0.1.9
runtime   org.freedesktop.fwupd-efi     1.4
compile   org.freedesktop.gusb          0.3.10
runtime   com.dell.libsmbios            2.4
runtime   org.freedesktop.gusb          0.3.10
runtime   org.kernel                    6.5.0-rc1-00006-g6bd1e1abc9af
runtime   org.freedesktop.fwupd         1.9.3
```

**Comment by valentindavid** [comment]
I think we need to do something in FuPluginLinuxSwap when we are in a snap. What call is done here? Is it a stat?

**Comment by superm1** [comment]
Yeah; I would expect this is where it gets upset: https://github.com/fwupd/fwupd/blob/1.9.3/plugins/linux-swap/fu-linux-swap.c#L69

**Comment by valentindavid** [comment]
Maybe we can make it prefix `/var/lib/snapd/hostfs`. That should work in theory.
