### ISSUE TITLE
Missing output on `fwupdmgr get-updates --json | cat`

### ISSUE THREAD

**Issue by j5k** [fwupd/fwupd#6036]
**Describe the bug**
`fwupdmgr get-updates --json | cat` is missing content

**Steps to Reproduce**
```shell
# normal output
$ fwupdmgr get-updates --json
{
  "Devices" : [
    {
      "Name" : "System Firmware",
      "DeviceId" : "5bfc5b91c18ef8b751d3d052af77b69ebf738038",
      ...
    }
  ]
}

# output via pipe
$ fwupdmgr get-updates --json | cat
{
  "Devices" : []
}
```

**Expected behavior**
The same output (non-empty `"Devices"`)

**fwupd version information**

```shell
compile   org.freedesktop.fwupd         1.9.3
compile   com.hughsie.libxmlb           0.3.11
compile   com.hughsie.libjcat           0.1.14
runtime   org.freedesktop.fwupd-efi     1.4
compile   org.freedesktop.gusb          0.4.6
runtime   com.hughsie.libjcat           0.1.14
runtime   com.dell.libsmbios            2.4
runtime   org.freedesktop.gusb          0.4.6
runtime   org.kernel                    6.4.6-arch1-1
runtime   org.freedesktop.fwupd         1.9.3

```
Arch Linux (pacman)

**Comment by hughsie** [comment]
> Expected behavior
> The same output (non-empty "Devices")

Some updates require user interaction -- and those won't be shown without a TTY.

**Comment by hughsie** [comment]
What system firmware are you getting with the first command? I can check what the firmware is asking for.

**Comment by hughsie** [comment]
If you open the laptop lid, do you see the updates as expected? If so, I think:

	/* send our implemented feature set */
	if (is_interactive) {
		FwupdFeatureFlags flags =
		    FWUPD_FEATURE_FLAG_CAN_REPORT | FWUPD_FEATURE_FLAG_SWITCH_BRANCH |
		    FWUPD_FEATURE_FLAG_REQUESTS | FWUPD_FEATURE_FLAG_UPDATE_ACTION |
		    FWUPD_FEATURE_FLAG_FDE_WARNING | FWUPD_FEATURE_FLAG_DETACH_ACTION |
		    FWUPD_FEATURE_FLAG_COMMUNITY_TEXT | FWUPD_FEATURE_FLAG_SHOW_PROBLEMS;
		if (!no_authenticate)
			flags |= FWUPD_FEATURE_FLAG_ALLOW_AUTHENTICATION;
		if (!fwupd_client_set_feature_flags(priv->client,
						    flags,
						    priv->cancellable,
						    &error)) {
			/* TRANSLATORS: a feature is something like "can show an image" */
			g_prefix_error(&error, "%s: ", _("Failed to set front-end features"));
			fu_util_print_error(priv, error);
			return EXIT_FAILURE;
		}
	}

...this is too draconian. PR coming up.

**Comment by hughsie** [comment]
@j5k it works as expected with that fix? I can do you a F38 Fedora build if that helps.
