### ISSUE TITLE
katello sync

### ISSUE THREAD

**Issue by gyokiss** [fwupd/fwupd#6119]
**Describe the bug**
Hi first of all thanks for fantastic work!

My issue: i would like to get a repo in Foreman, but during the sync I will get an error message:

`Katello::Errors::Pulp3Error: A file located at the url https://fwupd.org/downloads/ea6baf53f6ecf19e57177607116b034f50c95d6caff894830facb40a7305d647-Signed_1152921505696683688.cab failed validation due to size.
`

That points me: most probably there is a mismatch in file size and reported file size. 

**Steps to Reproduce**
katello sync

Any idea how can I move forward?

Thank you very much

Gyorgy

**Comment by hughsie** [comment]
I think this should be fixed now (manually) but we do need to work out why this gets out of sync every now and then. Would you mind opening a new bug on https://gitlab.com/fwupd/lvfs-website/-/issues and I'll have a look this week please.
