### ISSUE TITLE
MacOS (homebrew-build) fail updating some devices with "missing libarchive support" error

### ISSUE THREAD

**Issue by sorenkrabbe** [fwupd/fwupd#6174]
**Describe the bug**
When trying to update a device on MacOS with fwupd installed via homebrew using the `jabra-gnp` plugin, the update fails with error `missing libarchive support`

https://tvc-16.science/homebrew-libarchive.html indicate it may be an issue with the `uses_from_macos` call in [homebrew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/f/fwupd.rb#L40C3-L40C30)

**Steps to Reproduce**
* Install fwupd with `brew install`
* Attach Jabra Engage2 75 device on outdated firmware version
* run `fwupdtool refresh` then `fwupdtool upgrade`
* update start but fails with `missing libarchive support`

**Expected behavior**
Device would update

**fwupd version information**
1.9.5 installed with `brew install`

**Additional questions**

- Operating system and version: _MacOS Ventura 13.5.2_
- Have you tried rebooting? _yes_
- Is this a regression? _don't know_

**Comment by hughsie** [comment]
Can you update homebrew and see if it works now please.

**Comment by sorenkrabbe** [comment]
Sure. Thanks. That fixed the issue and allows the update to complete.
