### ISSUE TITLE
SuperIO IT85xx EC commands

### ISSUE THREAD

**Issue by Lt-Henry** [fwupd/fwupd#6234]
Hi, I've been working on adding support for EC updates on a laptop brand. Laptop has a IT8528 EC (I have visual confirmation) but superio plugin refuses to detect it.

After some debugging, it looks like plugin timeouts waiting for a command response. This EC seems to ignore SIO_CMD_EC_GET_NAME_STR and SIO_CMD_EC_GET_VERSION_STR commands (0x92/0x93). Also, where are those commands from? I haven't found them on any document all over internet.

On the other hand, it looks like at least It85xx support is limited to identification, neither upload nor firmware dump. Is that correct?

**Comment by Lt-Henry** [comment]
So, If I want to update EC using uefi update capsules, do I need at least SuperIO plugin to detect the EC device and current firmware version?

**Comment by hughsie** [comment]
Nope, if you're using UEFI update capsules you need a GUID in the ESRT table -- and the superio plugin isn't used at all.
