### ISSUE TITLE
gcab unittests failing in cross compile environment

### ISSUE THREAD

**Issue by ntsirakis** [fwupd/fwupd#6325]
**Describe the bug**
Built gcab binary cannot find required libraries during unittest step. Example below (cross-compile sysroot redacted):

```
/path/to/host/sysroot/fwupd/libfwupdplugin/gcab --create --nopath data/installed-tests/fakedevice124.cab ../fwupd/data/installed-tests/fakedevice124.bin ../fwupd/data/installed-tests/fakedevice124.bin.asc ../fwupd/data/installed-tests/fakedevice124.metainfo
.xml                                                                                                                                                          
/path/to/host/sysroot/fwupd/fwupd-build/libfwupdplugin/gcab: error while loading shared libraries: libxmlb.so.2: cannot open shared object file: No such file or directory
```

**Steps to Reproduce**
Run unittests

**Expected behavior**
Everything passes

**fwupd version information**
1.9.7

**Additional questions**

- Operating system and version: ChromeOS
- Have you tried rebooting? N/A
- Is this a regression? Yes

**Comment by superm1** [comment]
Is this a regression?  Or is this just the first of many problems in this environment?  It seems like there should be other tests that fall on their heads too.
