### ISSUE TITLE
Cannot upgrade/downgrade the HP Thunderbolt Dock G4 firmware via LVFS when the first time run.

### ISSUE THREAD

**Issue by RuminDeng** [fwupd/fwupd#6366]
**Describe the bug**
First time to upgrade/downgrade the HP Thunderbolt Dock G4 firmware via LVFS got Installation successfully information popped up, but the firmware didn't be updated in fact. Need to upgrade/downgrade again.

**Steps to Reproduce**
1.Install latest clean Fedora OS.
2.Copy the hp-ws-embargo.conf file to ~/.root/etc/fwupd/remotes.d 
3.Connect to a valid network.
4.Input "sudo dnf upgrade" in "Terminal" to upgrade package list.
5.Input "fwupdmgr --version" to check fwupd version.
6.Input "sudo dnf install gnome-firmware".
7.Input "$sudo fwupdmgr --force refresh" and "$fwupdmgr enable-remote lvfs-testing" to updating LVFS.
8.Attach dock to the Host, click "Firmware" icon in Application list/Activities to launch firmware update interface.
9.Select Dock: HP Thunderbolt Dock G4.
10.Select the latest OCI version v1.4.20.0 under "Available Releases" to upgrade.
11.Click "Install" option, enter account password then press Authenticate button.
12.The process bar will show Downloading and Write.
13.After finish will pop up "Installation successful" message, but check the Dock firmware version still show previous one.
14.Repet step 11~13 again, Firmware can be upgrade successful.

**Expected behavior**
Dock Firmware can be upgraded successfully by the first time.

**fwupd version information**
fwupdmgr fwupd: 1.9.7
OS: Fedora Linux 39(Workstation Edition)
gonme -firmware: v43.2

<summary>**fwupd device information**</summary>

HP Thunderbolt Dock G4

**Additional questions**

- Operating system and version: Fedora Linux 39(Workstation Edition)
- Have you tried rebooting?  Yes. Got same result.
- Is this a regression?  Seems not.

Attach the verbose log:
[gnome-firmware.log](https://github.com/fwupd/fwupd/files/13333642/gnome-firmware.log)

Attach the capture for process:
![1](https://github.com/fwupd/fwupd/assets/150659274/3020bfa1-2049-44e2-b00f-5af0073ab0ee)
![2](https://github.com/fwupd/fwupd/assets/150659274/d0cb43d2-53d1-4aa5-a865-f5b6789a1d60)
![3](https://github.com/fwupd/fwupd/assets/150659274/31bfc13c-dda7-4025-a500-057b5cdf1495)
![4](https://github.com/fwupd/fwupd/assets/150659274/4df8a3f0-30cd-4ffb-bc48-00b518c230a9)

**Comment by hughsie** [comment]
If you use `fwupdmgr install` do you see the same bug? i.e. is this a GUI issue or a upgrade issue?

**Comment by RuminDeng** [comment]
> If you use `fwupdmgr install` do you see the same bug? i.e. is this a GUI issue or a upgrade issue?
Yes. Got same result by "fwupdmgr install".
1st time will complete within 3 mins, 2nd time will take over 10 mins, and update firmware successfully.

**Comment by hughsie** [comment]
I've just tried, and I see the same behaviour on the G5 dock too. Investigating.

**Comment by RuminDeng** [comment]
Hi Hughsie,
May I know how can I get the fix on my platforms? 
Need to wait for the next official release or can upgrade directly?
Thanks~

**Comment by hughsie** [comment]
It'll be in the next release. If you run fedora I have a copr you can use.
