### ISSUE TITLE
fwupdmgr get-devices Does not respond

### ISSUE THREAD

**Issue by Zouhuo** [fwupd/fwupd#6404]
Since Update to 1.9.8, I cannot execute 'fwupdmgr get-devices'. The console just waits for a response and does not return to command line.

Linux kernel 6.6.1
Distro Manjaro
On 3 different hardware:
- Lenovo ThinkPad T14 AMD Ryzen 7 PRO 5850U.
- Aorus - Intel i9 9900k + ATI Radeon RX570
- Gigabyte - Intel i7 9700

**Comment by superm1** [comment]
It should be fixed in main. Any chance you can try there and confirm?

@hughsie after fixing the mediatek thing this week I think it's worth a new respin with how prevalent some of these new bugs are.

**Comment by Zouhuo** [comment]
> It should be fixed in main. Any chance you can try there and confirm?

Hmm, I'm a simple user, I don't have the environment set to compile. Maybe I can do it but not soon. And at the moment, are there other comments that mention the same thing or am I the only one?

**Comment by hughsie** [comment]
@superm1 I agree. I'll merge the mediatek disable-by-default patch and then do a new release on Monday.

**Comment by hughsie** [comment]
@Zouhuo if you're on Fedora, you can use: https://copr.fedorainfracloud.org/coprs/rhughes/fwupd/

**Comment by Shadowstone12** [comment]
I've also had the same issue on a recent install of Arch. Haven't been able to find any warning messages running in verbose or in journalctl. This is on a new framework 13 AMD.

**Comment by superm1** [comment]
> @superm1 I agree. I'll merge the mediatek disable-by-default patch and then do a new release on Monday.

If we can find the hwid that the shot device that needs that uses it could be on by default only for that so as to not regress that one device but if that isn't available in short notice it's pragmatic


Cc @CragW

**Comment by CragW** [comment]
Does it help if mediatek plugin disabled? Adding it to `/etc/fwupd/fwupd.conf`.

```
DisabledPlugins=test;test_ble;mediatek_scaler
```

**Comment by Zouhuo** [comment]
> Does it help if mediatek plugin disabled? Adding it to `/etc/fwupd/fwupd.conf`.
> DisabledPlugins=test;test_ble;mediatek_scaler

No, it's still the same without responding.
By the way, the distro I use is Manjaro, derivative of Arch

**Comment by superm1** [comment]
> Does it help if mediatek plugin disabled? Adding it to `/etc/fwupd/fwupd.conf`.
> 
> ```
> DisabledPlugins=test;test_ble;mediatek_scaler
> ```
> 

The other issue helps with it disabled. This one I think is the client side issue with walking the topology.

**Comment by hughsie** [comment]
> If we can find the hwid on short notice for the system that uses it

@CragW does the HWID make sense? My gut instinct is to do the release with the plugin disabled, and then we re-enable it for the next release when we either have the VCP or HWID checks.

**Comment by sempiternal-aurora** [comment]
> It should be fixed in main. Any chance you can try there and confirm?

I just built from a local clone of the git repo, and encountered the same problem. `fwupdmgr get-devices` just runs, never generates output, and I cannot ctrl-C it, can only suspend the command with ctrl-Z.

**Comment by superm1** [comment]
@sempiternal-aurora can you please try to add `mediatek-scaler` to the `DisabledPlugins` key in `/etc/fwupd/fwupd.conf` and try to restart the daemon?  If you can still reproduce the problem with that please share output for

`sudo fwupdtool get-devices --vv`

**Comment by sempiternal-aurora** [comment]
Give me a sec, I still had fwupd installed the first time so it was running on the old daemon so I am just removing that and rebuilding the library

**Comment by sempiternal-aurora** [comment]
Sorry, I had built the package wrong (this was my first time building a package from source, sorry). After fixing everything I can confirm that building from main with the mediatek plugin running `fwupdmgr get-devices` runs fine. Sorry about all this confusion.

**Comment by superm1** [comment]
OK, it's fixed in 1.9.9.
