### ISSUE TITLE
1.9.9 release build issue

### ISSUE THREAD

**Issue by chenrui333** [fwupd/fwupd#6432]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

```
data/pki/meson.build:3:26: ERROR: Could not get pkg-config variable and no default provided for <PkgConfigDependency jcat: True ['>= 0.1.4']>
```

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/6949618158/job/18908220308?pr=154947
relates to Homebrew/homebrew-core#154947

**Comment by hughsie** [comment]
As an aside, I am a bit confused why it's broken between 1.9.8 and 1.9.9 -- there were no buildsystem changes I'm aware of.

**Comment by superm1** [comment]
This should be fixed now in main (as of https://github.com/fwupd/fwupd/commit/db755512117b7ee0ca4170c9c2ee4c53332d1349).

Please re-open if it's still broke, thanks!
