### ISSUE TITLE
MEMORY_LEAK in /plugins/tpm/fu-tpm-device.c

### ISSUE THREAD

**Issue by ellena13** [fwupd/fwupd#6478]
In __branch 1.8.10__ we found the following:

dynamic memory, referenced by `item`, is allocated at *fu-tpm-device.c:45* by calling function `g_malloc0_n` and lost at *fu-tpm-device.c:47* :

https://github.com/fwupd/fwupd/blob/44137021f26f69d04d5ae250adc06a52d0412bcf/plugins/tpm/fu-tpm-device.c#L41-L54

Changing the order of the operators seems like a better idea. By the way, __this__ option __is implemented in the main branch__ :

https://github.com/fwupd/fwupd/blob/79e9c79d2955e6123d0b66420f13420041cbfb45/plugins/tpm/fu-tpm-device.c#L41-L55

Found by Linux Verification Center ([portal.linuxtesting.ru](https://portal.linuxtesting.ru/)) with SVACE.

Author E. Bykhanova.

**Comment by hughsie** [comment]
We already fixed this in 986b811b3d about 10 months ago I'm afraid. You probably want to analyse the main branch.
