### ISSUE TITLE
Emulation documentation should be end to end 

### ISSUE THREAD

**Issue by superm1** [fwupd/fwupd#6505]
Currently the [device tests part of emulation documentation](https://github.com/fwupd/fwupd/blob/main/docs/device-emulation.md#device-tests) explains that emulation data _can_ be fetched, but doesn't discuss anything about how to get that data into LVFS.

I think this should link to a page/section at [LVFS documentation](https://lvfs.readthedocs.io/en/latest/chromeos.html#device-emulation) that explains how to add emulation data to a release with some screenshots.

I notice that WD19TB is missing emulation data, maybe the exercise of generating some data _specifically_ against the documentation that's provided today will make it obvious where it needs to be improved :)

CC @CragW

**Comment by hughsie** [comment]
> which devices need emulation tag

That's a good question. I think if you try to emulate the proxy the daemon gives you `ECANTDOTHATDAVE`.

**Comment by CragW** [comment]
> @CragW in case you didn't know (or as a screenshot we can use in the docs) it's like this on the LVFS:

Aha, that's where the json file should go! Thanks @hughsie for the screenshot,  Will try the emulation with USB dock.

**Comment by superm1** [comment]
@CragW did you make any progress with getting some emulation data recorded?  We're lately working a lot on getting test coverage improved.  Running emulated updates are a great way to increase coverage.
