### ISSUE TITLE
Documentation incorrect about Intel CET status

### ISSUE THREAD

**Issue by mhalano** [fwupd/fwupd#6506]
**Describe the bug**
[Here](https://fwupd.github.io/libfwupdplugin/hsi.html#org.fwupd.hsi.IntelCet.Active) in the documentation states that is necessary Intel CET to be active to get HSI:3 level. I don't know for sure, if it's a mistake in the documentation or in other place, but I got HSI:3 even I don't have Intel CET active.
```
fwupdmgr security 
Host Security ID: HSI:3! (v1.9.10)

HSI-1
✔ BIOS firmware updates:         Enabled
✔ MEI key manifest:              Valid
✔ csme manufacturing mode:       Locked
✔ csme override:                 Locked
✔ csme v0:15.0.45.2411:          Valid
✔ Platform debugging:            Disabled
✔ SPI write:                     Disabled
✔ SPI lock:                      Enabled
✔ SPI BIOS region:               Locked
✔ Supported CPU:                 Invalid
✔ TPM empty PCRs:                Valid
✔ TPM v2.0:                      Found
✔ UEFI bootservice variables:    Locked

HSI-2
✔ BIOS rollback protection:      Enabled
✔ Intel BootGuard ACM protected: Valid
✔ Intel BootGuard:               Enabled
✔ Intel BootGuard OTP fuse:      Valid
✔ Intel BootGuard verified boot: Valid
✔ Intel GDS mitigation:          Enabled
✔ IOMMU:                         Enabled
✔ Platform debugging:            Locked
✔ TPM PCR0 reconstruction:       Valid

HSI-3
✔ Intel BootGuard error policy:  Valid
✔ Intel CET Enabled:             Enabled
✔ Pre-boot DMA protection:       Enabled
✔ Suspend-to-idle:               Enabled
✔ Suspend-to-ram:                Disabled

HSI-4
✔ Intel SMAP:                    Enabled
✘ Encrypted RAM:                 Not supported

Runtime Suffix -!
✔ fwupd plugins:                 Untainted
✔ Linux swap:                    Disabled
✘ Intel CET Active:              Not supported
✘ Linux kernel lockdown:         Disabled
✘ Linux kernel:                  Tainted
✘ UEFI secure boot:              Disabled

This system has HSI runtime issues.
 » https://fwupd.github.io/hsi.html#hsi-runtime-suffix

Host Security Events
  2023-11-20 21:00:19:  ✔ Supported CPU changed: Valid → Invalid
  2023-09-16 22:51:13:  ✔ Pre-boot DMA protection is enabled
  2023-09-13 18:20:16:  ✘ Secure Boot disabled
  2023-09-13 18:20:16:  ✘ Pre-boot DMA protection is disabled
  2023-09-13 12:27:38:  ✔ TPM v2.0 changed: Not found → Found
  2023-09-13 12:11:31:  ✘ TPM v2.0 changed: Found → Not found
  2023-09-11 13:40:01:  ✘ Kernel lockdown disabled
  2023-09-11 13:40:01:  ✔ TPM v2.0 changed: Not found → Found
  2023-09-11 13:31:29:  ✘ Kernel is tainted
  2023-09-11 13:12:55:  ✔ Kernel is no longer tainted
  2023-09-11 13:12:55:  ✔ Kernel lockdown enabled
  2023-09-11 13:12:55:  ✔ Secure Boot enabled

Host Security ID attributes uploaded successfully, thanks!

```

**Steps to Reproduce**
Just execute `fwupdmgr security`

**Expected behavior**

**fwupd version information**
Please provide the version of the daemon and client.

```shell
fwupdmgr --version
```
compile   com.hughsie.libxmlb           0.3.14
compile   com.hughsie.libjcat           0.1.9
compile   org.freedesktop.fwupd         1.9.10
runtime   org.freedesktop.fwupd-efi     1.4
compile   org.freedesktop.gusb          0.4.5
runtime   org.freedesktop.gusb          0.4.5
runtime   org.freedesktop.fwupd         1.9.10
runtime   org.kernel                    6.5.0-14-generic

Please note how you installed it (`apt`, `dnf`, `pacman`, source, etc):

apt, but using packages from Ubuntu Noble Numbat.

<details>

<summary>**fwupd device information**</summary>

Please provide the output of the fwupd devices recognized in your system.

```shell
fwupdmgr get-devices --show-all-devices
```
Dell Inc. Dell G15 5511
│
├─DELL0A70:00 04F3:317E:
│     Device ID:          f0b5af888f84b1518085848a548471c338c31187
│     Summary:            Touchpad
│     Current version:    0x0005
│     Bootloader Version: 0x0001
│     Vendor:             ELAN Microelectronics (HIDRAW:0x04F3)
│     GUIDs:              db972db2-d0dd-557e-9ddd-ea0a77323371 ← HIDRAW\VEN_04F3&DEV_317E
│                         38d75275-10b3-5f2f-8c9f-a8d60111c768 ← HIDRAW\VEN_04F3&DEV_317E&MOD_0089
│                         4eed77b6-0567-5942-a842-2413a8622e3a ← ELANTP\ICTYPE_10&MOD_0089
│                         44426a60-0574-56d9-889f-48746ea06ba8 ← ELANTP\ICTYPE_10&MOD_0089&DRIVER_HID
│     Device Flags:       • Internal device
│                         • Updatable
│     Device Requests:    • Message
│                         • Image
│   
├─Unknown Device:
│     Device ID:          d324166a5e48e27ba0360ac27eeaa89559930203
│     Serial Number:      H4ZN900158
│     GUID:               e43a20c5-53bc-57ca-8b70-d9a4e9d5c6e7 ← DRM\VEN_SAM&DEV_0F52
│   
├─Unknown Device:
│     Device ID:          bbc98c073ac3282642278424d95dc59fcd055153
│     GUID:               c9ddd069-c7f2-58c5-b382-0487e683463a ← GPIO\ID_INT34C6:00
│   
├─11th Gen Intel Core™ i7-11800H @ 2.30GHz:
│     Device ID:          4bde70ba4e39b28f9eab1628f9dd6e6244c03027
│     Current version:    0x0000004e
│     Vendor:             Intel
│     GUIDs:              a6bd4ca5-75a6-5796-b564-66b5cab1b11b ← CPUID\PRO_0&FAM_06&MOD_8D
│                         d9dd5e77-df17-5bab-b5ec-22827598bfed ← CPUID\PRO_0&FAM_06&MOD_8D&STP_1
│     Device Flags:       • Internal device
│     Device Requests:    • Message
│   
├─184X2:
│     Device ID:          aec1a869eb0df71b7cea6b3ac71d39b830faf164
│     GUID:               eca528bb-e474-56d5-ac6e-2ffc768b2a1f ← DRM\VEN_AUO&DEV_AE8B
│     Device Flags:       • Internal device
│     Device Requests:    • Message
│   
├─GA106M [GeForce RTX 3060 Mobile / Max-Q]:
│     Device ID:          ce4c74a5188d5b9cdb1e72ed32dad2d313c1c999
│     Current version:    a1
│     Vendor:             NVIDIA Corporation (PCI:0x10DE, PCI:0x8086)
│     GUIDs:              76567ea7-c9d9-5b64-9581-755d22386b00 ← PCI\VEN_10DE&DEV_2560
│                         218353e3-7021-5286-8b4f-8016bb66294e ← PCI\VEN_10DE&DEV_2560&SUBSYS_10280A70
│                         c7dac7da-12ca-57be-ba1d-8617ec295689 ← PCI\VEN_8086&DEV_9A01
│                         f0228d97-3a50-557b-a76e-f4139752577d ← PCI\VEN_8086&DEV_9A01&SUBSYS_10280A70
│     Device Flags:       • Internal device
│                         • Cryptographic hash verification is available
│     Device Requests:    • Message
│   
├─IM2P33F3A NVMe ADATA 512GB:
│     Device ID:          03281da317dccd2b18de2bd1cc70a782df40ed7e
│     Summary:            NVM Express solid state drive
│     Current version:    92209301
│     Vendor:             ADATA Technology Co., Ltd. (NVME:0x1CC1)
│     Serial Number:      DL402SJYMPC0
│     GUIDs:              53f16832-8fd9-536c-b006-e1610314d459 ← STORAGE-DELL-109737
│                         096da7a8-2137-4343-8d99-bdc6f640016d
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Supported on remote server
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│     Device Requests:    • Message
│                         • Image
│                         • Image (custom)
│   
├─SSD 990 PRO 2TB:
│     Device ID:          4515e9a4ca4664ef9a2f99a999be418e61193a6a
│     Summary:            NVM Express solid state drive
│     Current version:    3B2QJXD7
│     Vendor:             Samsung (NVME:0x144D)
│     Serial Number:      S6Z2NJ0TB48016T
│     GUIDs:              e693e1a0-df3d-53da-9855-40205fd88f5e ← NVME\VEN_144D&DEV_A80C
│                         2967aa12-dfe5-5a2e-8345-7161c98f544b ← NVME\VEN_144D&DEV_A80C&SUBSYS_144DA801
│                         f23464cf-c30e-514a-838a-380da7b169aa ← Samsung SSD 990 PRO 2TB
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│                         • Signed Payload
│     Device Requests:    • Message
│                         • Image
│                         • Image (custom)
│   
├─System Firmware:
│ │   Device ID:          a45df35ac0e948ee180fe216a5f703f32dda163f
│ │   Summary:            UEFI ESRT device
│ │   Current version:    1.24.1
│ │   Minimum Version:    1.24.1
│ │   Vendor:             Dell (DMI:Dell Inc.)
│ │   Update State:       Success
│ │   GUID:               0320a545-48ca-986d-d52b-c28c648bf8d7
│ │   Device Flags:       • Internal device
│ │                       • Updatable
│ │                       • System requires external power source
│ │                       • Supported on remote server
│ │                       • Needs a reboot after installation
│ │                       • Cryptographic hash verification is available
│ │                       • Device is usable for the duration of the update
│ │   Device Requests:    • Message
│ │                       • Image
│ │                       • Image (custom)
│ │ 
│ ├─BootGuard Configuration:
│ │     Device ID:        b0d4430dfa6bde9f0c22680df36dbc8c15c80753
│ │     Current version:  11
│ │     Vendor:           Intel Corporation (MEI:0x8086)
│ │     GUIDs:            dd17041c-09ea-4b17-a271-5b989867ec65
│ │                       0ad638e6-06cd-51c3-ab0d-d7f8f7d49418 ← MEI\VEN_8086&DEV_43E0
│ │                       74177b94-1b28-5927-a2a2-462180424266 ← MEI\VEN_8086&DEV_43E0&SUBSYS_10280A70
│ │     Device Flags:     • Internal device
│ │     Device Requests:  • Message
│ │   
│ └─UEFI dbx:
│       Device ID:        362301da643102b9f38477387e2193e57abaa590
│       Summary:          UEFI revocation database
│       Current version:  371
│       Minimum Version:  371
│       Vendor:           UEFI:Linux Foundation
│       Install Duration: 1 second
│       GUIDs:            4a6cd2cb-8741-5257-9d1f-89a275dacca7 ← UEFI\CRT_E28D59CA489BD2AD580F2EA5D62D6A29BB9C02AE5A818434A37DA7FC11DFF9E9&ARCH_X64
│                         f8ba2887-9411-5c36-9cee-88995bb39731 ← UEFI\CRT_A1117F516A32CEFCBA3F2D1ACE10A87972FD6BBE8FE0D0B996E09E65D802A503&ARCH_X64
│       Device Flags:     • Internal device
│                         • Updatable
│                         • Supported on remote server
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│                         • Only version upgrades are allowed
│                         • Signed Payload
│       Device Requests:  • Message
│                         • Image
│     
├─TPM:
│     Device ID:          c6a80ac3a22083423992a3cb15018989f37834d6
│     Summary:            TPM 2.0 Device
│     Current version:    600.7.45.2411
│     Vendor:             Intel (TPM:INTC)
│     GUIDs:              34801700-3a50-5b05-820c-fe14580e4c2d ← TPM\VEN_INTC&DEV_0000
│                         00d06c7f-2244-5a35-aa98-5d60704b3f5d ← TPM\VEN_INTC&MOD_TGL
│                         03f304f4-223e-54f4-b2c1-c3cf3b5817c6 ← TPM\VEN_INTC&DEV_0000&VER_2.0
│                         9c3106c7-42ca-5099-9363-96ef5c22cbf7 ← TPM\VEN_INTC&MOD_TGL&VER_2.0
│                         88dda31e-cf5f-5d4d-b331-6c9fd6906362 ← 0a70-2.0
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device can recover flash failures
│                         • Full disk encryption secrets may be invalidated when updating
│                         • Signed Payload
│     Device Requests:    • Message
│                         • Image
│                         • Image (custom)
│   
├─TigerLake-H GT1 [UHD Graphics]:
│     Device ID:          5792b48846ce271fab11c4a545f7a3df0d36e00a
│     Current version:    01
│     Vendor:             Intel Corporation (PCI:0x8086)
│     GUIDs:              542e165e-ec6d-59dd-b7c2-60892a04d76a ← PCI\VEN_8086&DEV_9A60
│                         d09dc701-39aa-5949-90ee-e67ce17ea3b3 ← PCI\VEN_8086&DEV_9A60&SUBSYS_10280A70
│     Device Flags:       • Internal device
│                         • Cryptographic hash verification is available
│     Device Requests:    • Message
│   
├─UEFI Device Firmware:
│     Device ID:          349bb341230b1a86e5effe7dfe4337e1590227bd
│     Summary:            UEFI ESRT device
│     Current version:    78
│     Minimum Version:    78
│     Vendor:             DMI:Dell Inc.
│     Update State:       Success
│     GUID:               176e090d-0ddb-495e-8173-bc998ccfecd0
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│     Device Requests:    • Message
│                         • Image
│                         • Image (custom)
│   
└─UEFI Device Firmware:
      Device ID:          2292ae5236790b47884e37cf162dcf23bfcd1c60
      Summary:            UEFI ESRT device
      Current version:    2451608321
      Minimum Version:    2451608321
      Vendor:             Dell (DMI:Dell Inc.)
      Update State:       Success
      GUID:               096da7a8-2137-4343-8d99-bdc6f640016d
      Device Flags:       • Internal device
                          • Updatable
                          • System requires external power source
                          • Supported on remote server
                          • Needs a reboot after installation
                          • Device is usable for the duration of the update
      Device Requests:    • Message
                          • Image
                          • Image (custom)
    

</details>

**Additional questions**

- Operating system and version: Ubuntu 23.10
- Have you tried rebooting? Yes
- Is this a regression? I don't know for sure

**Comment by hughsie** [comment]
> Intel CET Enabled:             Enabled

It's weird, but that's actually correct. If your system has CET active (in use) you'd actually have `✔ Intel CET Active` in the runtime section -- IIRC, it was split up because the `Enabled` is something that your BIOS firmware vendor needs to fix, and `Active` is something that your *distro* needs to fix.

Maybe it's a bit misleading being `✔ Intel CET Enabled:             Enabled` -- maybe it should be `✔ Intel CET Enabled:             Supported` instead?

**Comment by mhalano** [comment]
That makes sense, @hughsie. What is necessary to activate? I was testing the new 6.6 kernels that have CET/Shadow Stack enabled but still got not supported.

**Comment by hughsie** [comment]
> What is necessary to activate

I'm pretty sure for CET you need to rebuild the entire distro with some extra CPU flags. I think the plan was to do that for Fedora 39, no idea for Ubuntu I'm afraid.

**Comment by superm1** [comment]
So something else I notice here is that CET and SMAP are Intel only checks, but AMD also supports shadow stack and SMAP on recent processors.

Here's a Phoenix (Zen 4) APU:
```
  DeviceId:             4bde70ba4e39b28f9eab1628f9dd6e6244c03027
  Name:                 AMD Ryzen 5 7640U w/ Radeon 760M Graphics
  Guid:                 2a1df9de-fe02-59c8-8af1-32c8bb011f94 ← CPUID\PRO_0&FAM_19&MOD_74
  Guid:                 5a4bca32-6547-584f-bb36-920d9adede25 ← CPUID\PRO_0&FAM_19&MOD_74&STP_1
  Plugin:               cpu
  Flags:                internal|registered
  Vendor:               Advanced Micro Devices, Inc.
  VersionFormat:        hex
  Icon:                 computer
  Created:              2023-12-11
  Guid[quirk]:          22f9ecf4-588d-5c0a-8326-6ebff3655c6d ← CPUID\PRO_0&FAM_19
  PhysicalId:           cpu:0
  AcquiesceDelay:       50
  InternalFlags:        host-cpu
  HasSHSTK:             true
  HasIBT:               false
  HasTME:               false
  HasSMAP:              true
```

The lack of IBT is probably due to my kernel config.
```
CONFIG_CC_HAS_IBT=y
# CONFIG_X86_KERNEL_IBT is not set
```

**Comment by superm1** [comment]
This should be fixed in the 1_9_X branch and also main. Please reopen if you disagree with the results.

**Comment by mhalano** [comment]
Thank you. I will wait the next release be available to test and I will let you know.

**Comment by mhalano** [comment]
I just tested, since it's in Debian repositories, and now shows as supported and green. I hope with Glibc 2.39 supporting Intel CET we can see this option showing as enabled in a near future.
