### ISSUE TITLE
Community supported firmware updates for phones running U-Boot and Linux Mobile distros

### ISSUE THREAD

**Issue by calebccff** [fwupd/fwupd#6510]
**Describe the question**
Hi, I've recently been working on U-Boot support for Qualcomm boards, including support for a handful of phones that the community support running close-to mainline kernels with postmarketOS as well as other distros like Mobian, Arch Linux ARM, etc. I'm also a member of the postmarketOS core team.

Unfortunately due to the locked down nature of these devices, it isn't possible to replace the stock bootloader entirely, but by chain-loading into U-Boot we can provide a much more Linux friendly UEFI firmware environment with multi-booting, kernel version rollback, and of course: capsule updates.

In brief, U-Boot is built with the Linux kernel image header pre-pended to it, and is packed into an Android boot image in the same way Linux usually is. We then have to repurpose an existing partition to be our ESP and keep the kernel/ramdisk there. This is incompatible with how the stock Android OS works, and as such I don't want to attempt to support booting Android via U-Boot.

I have already implemented support for updating U-Boot via the UEFI Capsule Update mechanism and tested it manually, there are still some things that need improving and polishing up. But I wanted to start a conversation to see if and how we could go about providing bootloader updates via FWUPD.

The devices I'm hoping to support initially are:

* OnePlus 6(T)
* Xiaomi PocoPhone F1
* SHIFT6mq

For the SHIFT phone we have previously worked with @amartinz and FWUPD to provide updates for the Android bootloader (thanks @DylanVanAssche !), however for the other vendors it's highly unlikely that we would get any kind of recognition or acknowledgement.

So, I guess my question is, can we provide community maintained firmware for these devices? What are the requirements for doing so?

Hopefully I've provided enough useful context here, I'm fairly new to all this so please forgive me if I'm missing anything obvious.

Here is the output of `fwupdmgr get-devices` on a OnePlus 6 running U-Boot with capsule updates enabled:

```shell
; sudo fwupdmgr get-devices
WARNING: This package has not been validated, it may not work properly.
oneplus OnePlus 6
│
├─KLUEG8U1EA-B0C1:
│     Device ID:          ca29e86f5c8f08aecbfa8f00859ecbf25c0a2f21
│     Summary:            UFS device
│     Current version:    0500
│     Vendor:             SAMSUNG (SCSI:SAMSUNG)
│     Serial Number:      SAMSUNG
│     GUIDs:              8b6f87d9-b90d-51cd-9af1-8d4d23b8912d ← SCSI\VEN_SAMSUNG&DEV_KLUEG8U1EA-B0C1
│                         0ac1109a-221e-5f44-be21-c179771404d6 ← SCSI\VEN_SAMSUNG&DEV_KLUEG8U1EA-B0C1&REV_0500
│     Device Flags:       • Internal device
│                         • Updatable
│
└─Unknown Firmware:
      Device ID:          a45df35ac0e948ee180fe216a5f703f32dda163f
      Summary:            UEFI ESRT device
      Current version:    0
      Vendor:             DMI:U-Boot
      Update State:       Success
      GUID:               2a5aa852-b856-4d97-baa9-5c5f4421551f
      Device Flags:       • Internal device
                          • Updatable
                          • System requires external power source
                          • Needs a reboot after installation
                          • Device is usable for the duration of the update
```

**fwupd version information**

```shell
fwupdmgr --version

compile   com.hughsie.libxmlb           0.3.14
compile   com.hughsie.libjcat           0.1.14
compile   org.freedesktop.fwupd         1.9.9
compile   org.freedesktop.gusb          0.4.8
runtime   com.hughsie.libjcat           0.1.14
runtime   org.freedesktop.gusb          0.4.8
runtime   org.freedesktop.fwupd         1.9.9
runtime   org.kernel                    6.6.3-sdm845
```

**Comment by DylanVanAssche** [comment]
@hughsie We would need to handle the following things:

1. Android bootloader installed on device: `default`
2. UEFI U-Boot bootloader installed on device: `community`

So switching from 1 to 2 would need switching branches feature. That means implementing branch support in `android-boot` plugin. Switching back to 1 from 2: we have no permission to distribute the original bootloader so that won't be supported, similar to Quectel in ModemManager with the Pine64 community firmware.

Once U-Boot UEFI is installed, we have the option to install updates through UEFI Capsule Updates. fwupd has support for this, but I'm not sure what we exactly need to do to use it with U-Boot. U-Boot just needs to have the capsule on the EFI partition, reboot, and the U-Boot applies it. No separate EFI app needed. Any suggestions here?

**Comment by DylanVanAssche** [comment]
> >  UEFI U-Boot bootloader installed on device
>
> How do we get the branch name from the device?

I was thinking of detecting UEFI vs Android Bootloader. If Android Bootloader we report the default branch, if UEFI, we report community branch?

> It should just work if you're using Capsule-on-Disk -- e.g. see https://github.com/fwupd/fwupd/blob/main/plugins/uefi-capsule/README.md#capsule-update-on-disk

Hmmm high chances ;) @calebccff ^^^

**Comment by hughsie** [comment]
> If Android Bootloader we report the default branch, if UEFI, we report community branch?

Can we tell *which* community? Or is there only going to be one?

**Comment by DylanVanAssche** [comment]
> Can we tell which community? Or is there only going to be one?

We can maybe set the vendor of the U-Boot via DMI to something like 'postmarketOS' and use that as branch name?
(I thought that the branch name was always 'community', I wasn't aware that for community things you can have something else as well)

**Comment by hughsie** [comment]
> (I thought that the branch name was always 'community'

I think you're right!

	tmp = xb_node_query_text(component, "../custom/value[@key='LVFS::Distributor']", NULL);
	if (g_strcmp0(tmp, "community") == 0)
		fwupd_release_add_flag(FWUPD_RELEASE(self), FWUPD_RELEASE_FLAG_IS_COMMUNITY);

**Comment by DylanVanAssche** [comment]
Aha! If you want to say which community the code could be adjust to be matching with everything starting with `community-` or something, so you can have `community-postmarketOS`.

However, we all work together in Linux Mobile, so even Mobian and others will just use the same stuff if we publish it under `community-postmarketOS` so `community` should be fine as well.

**Comment by calebccff** [comment]
Alright, thanks a lot for the feedback! Yeah the main idea here is that we avoid having some distro-specific bootloader and rather do it in a fully agnostic way, so maybe naming it community-postmarketOS wouldn't be ideal?

Really happy to see that capsule-on-disk works well! I'll work with Dylan to figure out a workflow for generating .cab files and give it a go.

For the initial installation, I guess we would want to use Dylans AndroidBoot plugin to flash the boot partition directly, as we won't have EFI runtime initially. This would happen either during some guided distro installation or for users to migrate an existing installation to UEFI.

**Comment by axelkar** [comment]
This is unrelated but may I have a link to the U-Boot ports?

**Comment by ericcurtin** [comment]
I have a tangential interest in this from the Automotive perspective. It is a pity we can't teach XBL/ABL to do UEFI alternatively, because in Automotive, milliseconds matter in boot time and every new bootloader you chainload is more things to boot.

**Comment by hughsie** [comment]
I think https://github.com/fwupd/fwupd/pull/6514 solved this for the most part -- at least from a fwupd point of view.
