### ISSUE TITLE
Launch Configurable Keyboard firmware updates do not work on Windows 11

### ISSUE THREAD

**Issue by beautifulcoder** [fwupd/fwupd#6582]
**Describe the bug**
When I attempt to update the firmware in my keyboard from Windows 11 I get this error.

> Update metadata only supported on Linux

**Steps to Reproduce**
Simply install the latest version of fwupd on Windows 11, and attempt to update the firmware in a Launch Configurable Keyboard.

**Expected behavior**
The tool reports back with:

```shell
Devices with no available firmware updates:
 • Launch Configurable Keyboard (launch 1)
No updatable devices
```

I expect updates since my device is over a year old.

**fwupd version information**
Please provide the version of the daemon and client.

```shell
> fwupdmgr --version
runtime   org.freedesktop.fwupd         1.9.10
compile   com.hughsie.libxmlb           0.3.12
runtime   com.hughsie.libjcat           0.1.14
compile   org.freedesktop.gusb          0.4.5
compile   com.hughsie.libjcat           0.1.14
compile   org.freedesktop.fwupd         1.9.10
runtime   org.freedesktop.gusb          0.4.5
```

Please note how you installed it (`apt`, `dnf`, `pacman`, source, etc):

I used the provided MSI installer.

<summary>**fwupd device information**</summary>

Please provide the output of the fwupd devices recognized in your system.

```shell
> fwupdmgr get-devices --show-all-devices
Dell Inc. OptiPlex 7090
│
└─Launch Configurable Keyboard (launch 1):
      Device ID:          99912a218f606cedd7ce336eaf3f0a9379eda0b6
      Current version:    0.7.103-4026-g7fd2f5
      Vendor:             System76 (USB:0x3384)
      GUIDs:              b2cfb86e-dacd-5663-83e6-58059831ab6d
                          af6272df-30f2-5067-ae05-201e69cd08a5 ← USB\VID_3384&PID_0001
                          7549de75-189b-5fa6-911a-c9f5d127dc28 ← USB\VID_3384&PID_0001&REV_0001
      Device Flags:       • Updatable
                          • Unsigned Payload
      Device Requests:    • Image
```

**Additional questions**

- Operating system and version: Windows 11
- Have you tried rebooting? Yes
- Is this a regression? I don't know, I think there is no support for Windows 11, can you all confirm this?

**Comment by hughsie** [comment]
Are you using `fwupdtool.exe`?

**Comment by beautifulcoder** [comment]
Thank you, okay, I did the following.

```shell
>fwupdtool refresh
Downloading…             [*************************************  ]

>fwupdtool update
Loading…                 [************************************** ]
Devices with the latest available firmware version:
 • Launch Configurable Keyboard (launch 1)
```

I think it simply reports there are no updates available. Not really following what this means actually.

**Comment by hughsie** [comment]
It's saying that;s the newest firmware. Does "fwupdtool.exe get-devices" report something older than https://fwupd.org/lvfs/devices/com.system76.launch_1.firmware ?

**Comment by beautifulcoder** [comment]
Oh dip, I feel dumb. Yes, `0.7.103-4026-g7fd2f5` is the latest version of the firmware which is the one I reported in the bug report. Thanks for the help!
