### ISSUE TITLE
HP "USB-C Dock G5" prompts for reboot after update

### ISSUE THREAD

**Issue by superm1** [fwupd/fwupd#6656]
**Describe the bug**

After updating the dock I was prompted to reboot.  I couldn't really figure out why, I looked at the device and it doesn't have any flags saying it needs to reboot.  It seems like a client bug.

**Steps to Reproduce**
1. Update USB-C dock G5.

**Expected behavior**
No prompt to reboot

**fwupd version information**
hash d387b3ea9
```
$ fwupdmgr --version 
compile   com.hughsie.libxmlb           0.3.15
compile   org.freedesktop.Passim        0.1.4
compile   com.hughsie.libjcat           0.1.14
compile   org.freedesktop.fwupd         2.0.0
compile   org.freedesktop.gusb          0.4.8
runtime   com.hughsie.libjcat           0.1.14
runtime   org.freedesktop.gusb          0.4.8
runtime   org.freedesktop.fwupd         2.0.0
runtime   org.kernel                    6.6.9-200.fc39.x86_64
```

I had the daemon running in verbose when this happened so here is the interaction from it.  Also the client log, but this wasn't in verbose.
[daemon.log](https://github.com/fwupd/fwupd/files/13907325/daemon.log)
[client.log](https://github.com/fwupd/fwupd/files/13907326/client.log)

My guess here is that `fu_util_update_device_changed_cb()` was triggered on the DMC which might have had `FWUPD_DEVICE_FLAG_UNKNOWN` set instead of `FWUPD_DEVICE_FLAG_NONE`

**Comment by superm1** [comment]
If my guess is right; maybe a regression from fbcffc7ee478037115289bb9133f7c147d6d923e?

**Comment by superm1** [comment]
The device does allow reinstall, so here is reproduced with client in verbose.
[client_verbose.log](https://github.com/fwupd/fwupd/files/13907512/client_verbose.log)

**Comment by hughsie** [comment]
I'm very confused; I've just tried the same thing with a G5 dock here and don't see the spurious `device-changed` events at all. The events you're getting are from things like your NVMe drive and system firmware too -- which is very odd. Can you stick a g_warning() in `fu_engine_emit_device_changed()` and maybe get a backtrace when something like the NVMe drive device-id is asked to emit?

**Comment by superm1** [comment]
That PR doesn't help, but I think I found what's happening that's different for you and me by backtracing the engine.
I'm powering the system from the dock.  So when the dock power cycles I get a call to `fu_engine_context_power_changed_cb`  which leads to `fu_engine_ensure_device_power_inhibit` and to `fu_device_add_problem` and then `fu_device_inhibit_full` and then `fu_device_ensure_inhibits` which then removes the flag with `fwupd_device_remove_flag`.  This triggers the device changed for all these other devices.

**Comment by superm1** [comment]
Considering this finding I see a few ways to approach this issue.
1. Suppress the updates to power in `fu_engine_ensure_device_power_inhibit` while the engine is actively updating devices.  I tested this; here's how it looks: https://github.com/fwupd/fwupd/pull/6663
2. https://github.com/fwupd/fwupd/pull/6657  I think it's still correct because think about collateral damage of devices connected _to the dock_.

What do you think with this finding, any other ideas?

**Comment by hughsie** [comment]
@superm1 counter proposal in https://github.com/fwupd/fwupd/pull/6665 -- lightly tested -- and now I understand why you're getting spurious events and I'm not -- your dock was supplying power, and mine wasn't.
