### ISSUE TITLE
Stale update reporting metadata on UEFI XPS 9560 system firmware

### ISSUE THREAD

**Issue by Echelon9** [fwupd/fwupd#671]
Thanks for an awesome Linux firmware update tool and infrastructure @hughsie 

As I know how useful reporting can be, I wanted to note what appears to be `fwupdmgr` attempting to report stale update metrics back to LVFS.

After a recent, successful, UEFI firmware update `fwupdmgr` asked me to report the following:
```shell
Devices that have been updated successfully:

 • XPS 15 9560 System Firmware (0.1.9.4 → 0.1.10.1)
```
And the JSON metadata similarly reports stale data:
```shell
...
"VersionOld" : "0.1.9.4",
"VersionNew" : "0.1.10.1",
...
``` 

... however, this is stale data. This from version -> to version is actually the *prior* system firmware update, which was already reported back to LVFS. So `fwupdmgr` is missing that the most recent update was from `0.1.10.1` to `0.1.11.0`.

If I say yes to reporting this stale data, and then re-run `fwupdmgr`, it doesn't prompt to report the most recent update data either.
I recall seeing this occur on the prior successful update. Given it has happened again, I wanted to report it.

----
To help us pinpoint your issue, please insert the output of the
following commands when ran on the system with the issue:

```shell
$ fwupdmgr --version
client version:	1.0.6
daemon version:	1.0.6
compile-time dependency versions
	appstream-glib:	0.7.4
	gusb:	0.2.11
	fwupdate:	10
	efivar:	34
```

```shell
$ fwupdmgr get-devices
XPS 15 9560 TPM 2.0
  DeviceId:             cc2b222929056ab3e9a208df9f86b7d9a74ae514
  Guid:                 bc891321-25aa-54f6-86e7-633d065b8d5d
  Summary:              Platform TPM device
  Plugin:               dell
  Flags:                internal|updatable|require-ac|supported|registered|needs-reboot
  Vendor:               Dell Inc.
  Version:              1.3.2.8
  Icon:                 computer
  Created:              2018-08-19

XPS 15 9560 TPM 1.2
  DeviceId:             8e1ddd96334dca0c0f1059c12c3ff08b15d3766a
  Guid:                 c5e6d7ef-4270-54bf-af0f-8b8ef2a561e6
  Summary:              Alternate mode for platform TPM device
  Plugin:               dell
  Flags:                internal|require-ac|locked|registered
  Icon:                 computer
  Created:              2018-08-19

Intel AMT [unprovisioned]
  DeviceId:             088df415cdee883ec89563e41e6d495924250174
  Guid:                 2800f812-b7b4-2d4b-aca8-46e0ff65814c
  Summary:              Hardware and firmware technology for remote out-of-band management
  Plugin:               amt
  Flags:                internal|registered
  Vendor:               Intel Corporation
  Version:              11.8.55
  VersionBootloader:    11.8.55
  Icon:                 computer
  Created:              2018-08-19

XPS 15 9560 System Firmware
  DeviceId:             f49999b6e3af5b4bf8ad1f2ed2922b76df457271
  Guid:                 34578c72-11dc-4378-bc7f-b643866f598c
  Plugin:               uefi
  Flags:                internal|updatable|require-ac|supported|registered|needs-reboot
  Version:              0.1.11.0
  VersionLowest:        0.1.11.0
  Icon:                 computer
  Created:              2018-08-19

GP107M [GeForce GTX 1050 Mobile]
  DeviceId:             3f0f51a4f03bccdad9f8ae1334bad4584b5ba875
  Guid:                 37921484-dff0-57a0-b7dd-4cd6a82b54a1
  Plugin:               udev
  Flags:                internal|registered
  Vendor:               NVIDIA Corporation
  VendorId:             PCI:0x10DE
  Icon:                 audio-card
  Created:              2018-08-19

Unknown Device
  DeviceId:             8de6c7959053fd5798006dcc63590d33fa5e51cb
  Guid:                 3ab5fe9e-bef7-5421-920a-ef7301884933
  Plugin:               udev
  Flags:                internal|registered
  Vendor:               Intel Corporation
  VendorId:             PCI:0x8086
  Icon:                 audio-card
  Created:              2018-08-19

XPS 9560 Thunderbolt Controller
  DeviceId:             985cfe680e79bf12f356c4a539bd1f2e2086d1c1
  Guid:                 4d86f168-e1cc-5995-afd3-ae9df6a14f5e
  Guid:                 72533768-6a6c-5c06-994a-367374336810
  Summary:              Unmatched performance for high-speed I/O
  Plugin:               thunderbolt
  Flags:                internal|updatable|supported|registered
  Vendor:               Dell
  VendorId:             TBT:0x00D4
  Version:              00.00
  Icon:                 computer
  Created:              2018-08-19
```

```shell
$ efibootmgr -v
BootCurrent: 0002
Timeout: 0 seconds
BootOrder: 0002,0001
Boot0000* Windows Boot Manager	HD(1,GPT,6782ebfe-f436-4b1e-abec-409485a020e5,0x800,0xfa000)/File(\EFI\Microsoft\Boot\bootmgfw.efi)WINDOWS.........x...B.C.D.O.B.J.E.C.T.=.{.9.d.e.a.8.6.2.c.-.5.c.d.d.-.4.e.7.0.-.a.c.c.1.-.f.3.2.b.3.4.4.d.4.7.9.5.}...K................
Boot0001* UEFI: THNSN5512GPUK NVMe TOSHIBA 512GB, Partition 1	HD(1,GPT,6782ebfe-f436-4b1e-abec-409485a020e5,0x800,0x100000)/File(EFI\boot\bootx64.efi)..BO
Boot0002* ubuntu	HD(1,GPT,6782ebfe-f436-4b1e-abec-409485a020e5,0x800,0x100000)/File(\EFI\ubuntu\shimx64.efi)
```

```shell
$ efivar -l | grep fw
<nothing>
```

```shell
$ tree /boot
/boot
...
├── efi
│   └── EFI
│       ├── BOOT
│       │   ├── BOOTX64.EFI
│       │   └── fbx64.efi
│       ├── Dell
│       │   ├── Bios
│       │   │   └── Recovery
│       │   │       ├── BIOS_CUR.RCV
│       │   │       └── BIOS_PRE.rcv
│       │   └── logs
│       │       ├── diags_current.xml
│       │       └── diags_previous.xml
│       └── ubuntu
│           ├── BOOTX64.CSV
│           ├── fw
│           ├── fwupx64.efi
│           ├── grub.cfg
│           ├── grubx64.efi
│           ├── mmx64.efi
│           └── shimx64.efi
...
```

Please answer the following questions:

- Operating system and version: Ubuntu 18.04
- How did you install fwupd (ex: `from source`, `pacman`, `apt-get`, etc): apt-get
- Have you tried rebooting? Yes.
- Are you using an NVMe disk? Yes.
- Is secure boot enabled (only for the UEFI plugin)? No.

**Comment by superm1** [comment]
Well the way that a UEFI update works is that you need to reboot to install the update.  Only after the reboot can `fwupd` check to see if it was "successful".  At that point is when you need to prompt the user, but they might not be running `fwupdmgr` to check at that time.

So I suspect what's happening with you is you upgraded and then didn't touch `fwupdmgr` for a while, and then upgraded again a while later to notice this.  Can you confirm that matches your above description?

So unfortunately I think this is "by design" when it comes to `fwupdmr`.  Perhaps with `gnome-software` which will start up when logging in the reporting message can be a popup instead and more closely correlated with the installation of the firmware upgrade.

**Comment by Echelon9** [comment]
Hrmm, it's possible that was the order.
Fine if this is a known limitation of UEFI update methodology, and thus a limitation of the data reporting.

Just surprising that, if that was the case, the second update didn't overwrite the value "VersionNew" derives from and show `0.1.11.0`.

**Comment by superm1** [comment]
Well they are "separate" update transactions that could potentially fail.  So it makes sense that they "should" be treated separately to be tracked if one particular version upgrade is failing more commonly for example.

**Comment by Echelon9** [comment]
Sorry to revive this report, there's definitely something odd going on with the metadata reporting stale updates consistent with the original report.

Upon the most recent XPS 9560 system bios update (version `0.1.12.1`), I saw the following:
* (Before current update) ran `fwupdmgr get-updates`, reported up to LVFS the successful prior `0.1.10.1` -> `0.1.11.0` that occurred some months ago.
* Ran `fwupdmgr update` successfully (because `0.1.12.1` is now available).
* Restarted after the successful bios update.
* (After current update) ran `fwupdmgr get-updates`, **and I was asked to again to report "XPS 15 9560 System Firmware (0.1.10.1 → 0.1.11.0)". But this was reported already.**

The last message was: `Upload message: XXXXX899624 replaces old report`

I am so far unable, *after a successful restart*, to report to LVFS the update from `0.1.11.0` -> `0.1.12.1`.

**Comment by superm1** [comment]
Can you share your pending.db from `/var/lib/fwupd/`?

**Comment by Echelon9** [comment]
@superm1 I've sent my pending.db to you directly. Let me know how I can help debug this further.

**Comment by vpavic** [comment]
I've got the same thing occurring regularly on ThinkPad T480s:

```bash
$ fwupdmgr refresh && fwupdmgr get-updates 
Fetching metadata https://cdn.fwupd.org/downloads/firmware.xml.gz
Downloading…             [***************************************] Less than one minute remaining…
Fetching signature https://cdn.fwupd.org/downloads/firmware.xml.gz.asc

No upgrades for 20L7001LSC System Firmware, current is 0.1.33: 0.1.33=same, 0.1.31=older, 0.1.30=older, 0.1.29=older, 0.1.27=older
No upgrades for UEFI Device Firmware, current is 184.65.3590: 184.65.3590=same, 184.60.3561=older, 184.55.3510=older
No upgrades for UEFI Device Firmware, current is 0.1.16: 0.1.16=same, 0.1.13=older
Not compatible with bootloader version: failed predicate [BOT03.0[0-1]_* regex BOT03.02_B0009]
________________________________________________

Devices that have been updated successfully:

 • 20L7001LSC System Firmware (0.1.30 → 0.1.31)
 • UEFI Device Firmware (0.1.8 → 0.1.13)

Uploading firmware reports helps hardware vendors to quickly identify failing and successful updates on real devices.
Upload report now? (Requires internet connection) [Y|n]: 
```

The updates made were actually 0.1.31 → 0.1.33 and 0.1.13 → 0.1.16.

**Comment by vpavic** [comment]
Even more interesting situation today:

```bash
$ fwupdmgr refresh && fwupdmgr get-updates 
Fetching metadata https://cdn.fwupd.org/downloads/firmware.xml.gz
Downloading…             [***************************************]
Fetching signature https://cdn.fwupd.org/downloads/firmware.xml.gz.asc

No upgrades for 20L7001LSC System Firmware, current is 0.1.34: 0.1.34=same, 0.1.33=older, 0.1.31=older, 0.1.30=older, 0.1.29=older
No upgrades for UEFI Device Firmware, current is 184.65.3590: 184.65.3590=same, 184.60.3561=older, 184.55.3510=older
No upgrades for UEFI Device Firmware, current is 0.1.17: 0.1.17=same, 0.1.16=older, 0.1.13=older
Not compatible with bootloader version: failed predicate [BOT03.0[0-1]_* regex BOT03.02_B0009]
________________________________________________

Devices that were not updated correctly:

 • UEFI Device Firmware (0.1.8 → 0.1.13)

Devices that have been updated successfully:

 • 20L7001LSC System Firmware (0.1.31 → 0.1.33)
 • UEFI Device Firmware (0.1.13 → 0.1.16)

Uploading firmware reports helps hardware vendors to quickly identify failing and successful updates on real devices.
Upload report now? (Requires internet connection) [Y|n]: 
```

I've actually had _20L7001LSC System Firmware_ updated from `0.1.33` to `0.1.34`, and _UEFI Device Firmware_ updated from `0.1.16` to `0.1.17` with first update attempt failed due to no AC power. But the report shows `0.1.8 → 0.1.13` as failed and `0.1.13 → 0.1.16` as successful updates.
