### ISSUE TITLE
Lenovo T14s Gen 3 AMD won't wake up after suspend

### ISSUE THREAD

**Issue by HellmannK** [fwupd/fwupd#6747]
Hi,

I hope I'm doing right here, I'm not sure if this is a bug that it related to fwupd or not, but it is the only hint I found in my logs. For about a month or so (sorry I can't reproduce the exact time when it appeared the first time) my T14s Gen 3 AMD won't wake up after suspend in some cases. The display remains dark, power-button and fn-keys led's staying on. Switching tty does not work and "blindly" logging in as root and reboot does not work either. 
I'm on archlinux with everything up-to-date and running the latest linux kernel "Linux 6.7.2-arch1-1 x86_64" the issue appeared the first time about a month ago.

If I'm just on battery I can't reproduce the problem. It happens in about 50%. If I plug it in to mains it is kind of reproducible and happens in 90%.

The only hint I found in my logs was this after a unsuccessful resume ( that is the reason why I came here): 

```
Jan 30 13:05:01 mymachine fwupd[2860]: 12:05:01.100 FuPluginUpower       failed to query lid state
Jan 30 13:05:01 mymachine fwupd[2860]: 12:05:01.100 FuPluginUpower       failed to query lid state
```
Versions:

```shell
fwupdmgr --version
compile   com.hughsie.libxmlb           0.3.15
compile   org.freedesktop.Passim        0.1.5
compile   com.hughsie.libjcat           0.2.0
compile   org.freedesktop.fwupd         1.9.12
runtime   org.freedesktop.Passim        0.1.5
compile   org.freedesktop.gusb          0.4.8
runtime   com.hughsie.libjcat           0.2.1
runtime   org.freedesktop.gusb          0.4.8
runtime   org.kernel                    6.7.2-arch1-1
runtime   org.freedesktop.fwupd         1.9.12
```
fwupd is installed via pacman

<summary>**fwupd device information**</summary>

Please provide the output of the fwupd devices recognized in your system.

```shell
  fwupdmgr get-devices --show-all-devices
```
Should I provide this in my case?

I'm thankful for any hint :)

**Comment by hughsie** [comment]
I think it looks like a bug, but I'm afraid it's not *our* bug :) I think I'd advise posting on the Lenovo forum -- Mark is pretty good at answering there.
