### ISSUE TITLE
Bug: Fails to start in Noble Numbat

### ISSUE THREAD

**Issue by kroese** [fwupd/fwupd#6751]
I am running Ubuntu Server 24.04 development branch , and since recently (after updating the packages) I get this every hour:

```
systemd[1]: fwupd.service: Failed with result 'exit-code'.
systemd[1]: Failed to start fwupd.service - Firmware update daemon.
systemd[1]: fwupd-refresh.service: Failed with result 'exit-code'.
systemd[1]: Failed to start fwupd-refresh.service - Refresh fwupd metadata and update motd.
``` 

I have three machines on 24.04, and it only happens one 1 machine, so it must be some kind of conflict with another package on that machine.

**Comment by superm1** [comment]
Did your package upgrade or is it a fresh install?

Can you try removing /etc/fwupd/fwupd.conf?

**Comment by superm1** [comment]
Yeah this should be fixed by https://github.com/fwupd/fwupd/commit/3f33000706c3f25f99c23c0cc52a8037c74a7e8a

We haven't flushed out a 1.9.x release with it backported yet tho.

@hughsie how soon do you think we should?

**Comment by hughsie** [comment]
> @hughsie how soon do you think we should?

I've got a couple of other bugs on my plate that might affect 1.9.x -- then I think we should di one in a few days.

**Comment by hughsie** [comment]
Fixed in https://github.com/fwupd/fwupd/pull/6773
