### ISSUE TITLE
NO_CAST.INTEGER_OVERFLOW in plugins/bcm57xx/fu-bcm57xx-device.c

### ISSUE THREAD

**Issue by AlexRudyuk** [fwupd/fwupd#6761]
[plugins/bcm57xx/fu-bcm57xx-device.c](https://github.com/fwupd/fwupd/blob/339e3c841a6ba4f9ae74a6fdfbd9677fbd2d3d76/plugins/bcm57xx/fu-bcm57xx-device.c#L390C1-L394C1)

https://github.com/fwupd/fwupd/blob/339e3c841a6ba4f9ae74a6fdfbd9677fbd2d3d76/plugins/bcm57xx/fu-bcm57xx-device.c#L391

in line 391:
The `dict_cnt` variable has the `guint` type. When adding with the value 0x80, a situation may arise when the sum goes beyond the upper bound of guint, and only then there will be a type change to `guint64` in the `fu_firmware_set_idx()` function, which can lead to errors.

Found by Linux Verification Center ([portal.linuxtesting.ru](https://portal.linuxtesting.ru/)) with SVACE.
Author A. Slepykh ([a.slepykh@fobos-nt.ru](mailto:a.slepykh@fobos-nt.ru)).

**Comment by hughsie** [comment]
We call fu_firmware_add_image() exactly 3 times, and there's no way to add other images as the image is created at the top of the function. `0x80 + 3` is well within limits of UINT_MAX.
