### ISSUE TITLE
UNREACHABLE_CODE in /libfwupdplugin/fu-bios-settings.c

### ISSUE THREAD

**Issue by AlexRudyuk** [fwupd/fwupd#6762]
[/libfwupdplugin/fu-bios-settings.c](https://github.com/fwupd/fwupd/blob/339e3c841a6ba4f9ae74a6fdfbd9677fbd2d3d76/libfwupdplugin/fu-bios-settings.c#L344C1-L345C16)

https://github.com/fwupd/fwupd/blob/339e3c841a6ba4f9ae74a6fdfbd9677fbd2d3d76/libfwupdplugin/fu-bios-settings.c#L345

in line 345:
The `fu_bios_settings_run_folder_fixups` function returns only the TRUE value.

Found by Linux Verification Center ([portal.linuxtesting.ru](https://portal.linuxtesting.ru/)) with SVACE.
Author E. Bykhanova ([e.bykhanova@fobos-nt.ru](mailto:e.bykhanova@fobos-nt.ru)).

**Comment by hughsie** [comment]
It literally doesn't: https://github.com/fwupd/fwupd/blob/339e3c841a6ba4f9ae74a6fdfbd9677fbd2d3d76/libfwupdplugin/fu-bios-settings.c#L257

@AlexRudyuk this is your last chance. Please check all submissions before auto-filing issues of I'll be forced to ban your user account.
