### ISSUE TITLE
UNREACHABLE_CODE in libfwupdplugin/fu-io-channel.c

### ISSUE THREAD

**Issue by AlexRudyuk** [fwupd/fwupd#6765]
[libfwupdplugin/fu-io-channel.c](https://github.com/fwupd/fwupd/blob/339e3c841a6ba4f9ae74a6fdfbd9677fbd2d3d76/libfwupdplugin/fu-io-channel.c#L176C1-L179C3)

https://github.com/fwupd/fwupd/blob/339e3c841a6ba4f9ae74a6fdfbd9677fbd2d3d76/libfwupdplugin/fu-io-channel.c#L178

in line 178:
The `fu_io_channel_flush_input` function returns only `TRUE`, so line 178 will never be executed.

Found by Linux Verification Center ([portal.linuxtesting.ru](https://portal.linuxtesting.ru/)) with SVACE.
Author A. Burke ([aiburke@fobos-nt.ru](mailto:aiburke@fobos-nt.ru)).

**Comment by hughsie** [comment]
I've blocked you, this is just spam now.
