### ISSUE TITLE
UNREACHABLE_CODE in plugins/tpm/fu-tpm-plugin.c

### ISSUE THREAD

**Issue by AlexRudyuk** [fwupd/fwupd#6767]
[plugins/tpm/fu-tpm-plugin.c](https://github.com/fwupd/fwupd/blob/92b69e6a4c602e286225f9624a6ef90f9b42e3c3/plugins/tpm/fu-tpm-plugin.c#L93)

https://github.com/fwupd/fwupd/blob/92b69e6a4c602e286225f9624a6ef90f9b42e3c3/plugins/tpm/fu-tpm-plugin.c#L93

in line 93:
The csum_type variable has the GChecksumType type, which indicates that it is possible to contain the value `G_CHECKSUM_SHA384.` However, the `fwupd_checksum_guess_kind` function (line 84) never returns the value `G_CHECKSUM_SHA384,` which makes lines 94 and 95 unrealizable in this compilation.

Found by Linux Verification Center ([portal.linuxtesting.ru](https://portal.linuxtesting.ru/)) with SVACE.
Author E. Bykhanova ([e.bykhanova@fobos-nt.ru](mailto:e.bykhanova@fobos-nt.ru)).

**Comment by hughsie** [comment]
It's valid, but unfixable as G_CHECKSUM_SHA384 and G_CHECKSUM_SHA512 have the same hash length.
