### ISSUE TITLE
link to privacy policy is broken

### ISSUE THREAD

**Issue by fenio** [fwupd/fwupd#6791]
README.md points to https://fwupd.org/privacy for privacy policy but that site doesn't exist.

It should probably point to https://lvfs.readthedocs.io/en/latest/privacy.html

**Comment by hughsie** [comment]
Could you do a PR please? I'm away until Monday. Thanks!

**Comment by fenio** [comment]
Well I intentionally avoided creating PR for such a small fix as I thought it would be easier for your to modify it and submit yourself but I'll do that ;)
