### ISSUE TITLE
Dell WD19 upgrade issue

### ISSUE THREAD

**Issue by SinBirb** [fwupd/fwupd#6811]
**Describe the bug**

It seems like the update failed via gnome-software, but I'm actually not sure if it failed. It seemed like the issue in https://github.com/fwupd/fwupd/issues/5709, but not sure anymore.

I rebooted to see if it makes any differences, didn't seem like it. I attached two journalctl logs for that.

**Steps to Reproduce**

1. Click update in gnome-software UI, Updates tab
2. Get the message box "The update will continue when the device USB cable has been unplugged" with "Cancel" button and disabled "Install" button.
3. Unplug USB ports (mouse, keyboard) from the dock - nothing happens
4. Unplug Thunderbolt cable from my laptop (laptop has only one USB-C-/Thunderbolt combo port, no additional USB-C port)
5. Wait a few seconds
6. Plug in Thunderbolt port
7. Message box is still active, "Install" button still disabled
8. Press cancel

Snippet from `fwupdmgr get-history` appears to show that the update did not succeed:

```
└─WD19TB:
  │   Device ID:          570867f4ddda9915445da59bd85cd0e0e507270e
  │   Previous version:   01.01.00.01
  │   Update State:       Success
  │   Update Error:       Device has been removed, Pending activation
  │   Last modified:      2022-07-13 06:46
  │   GUID:               cd357cf1-40b2-5d87-b8df-bb2dd82774aa
  │   Device Flags:       • Supported on remote server
  │                       • Reported to remote server
  │                       • Device update needs activation
  │                       • Device stages updates
  │                       • Device can recover flash failures
  │                       • Device is usable for the duration of the update
  │
  └─WD19/WD22 EC Embedded Controller Update:
        New version:      01.01.00.03
        Remote ID:        lvfs
        Release ID:       13769
        Summary:          Firmware update for WD19/WD22 EC
        License:          Proprietary
        Size:             131,0 kB
        Created:          2022-06-08
        Urgency:          High
        Vendor:           Dell
        Duration:         1 minute
        Release Flags:    • Trusted metadata
                          • Is downgrade
        Description:
        -Improved the display compatibility between systems and monitors.
```

**Expected behavior**

The message should be more clear, e.g. tell me to unplug the Thunderbolt (not USB) cable plugged into the laptop. It just told me to unplug "the USB cable".

There should be any kind of success or failure message/notification, even if it's minutes later.

There to be no `Update Error` if the status is success.

**fwupd version information**
Please provide the version of the daemon and client.

```shell
❯ fwupdmgr --version

compile   com.hughsie.libxmlb           0.3.15
compile   org.freedesktop.Passim        0.1.5
compile   com.hughsie.libjcat           0.2.1
compile   org.freedesktop.fwupd         1.9.13
runtime   org.freedesktop.fwupd-efi     1.4
compile   org.freedesktop.gusb          0.4.8
runtime   org.freedesktop.Passim        0.1.5
runtime   org.freedesktop.gusb          0.4.8
runtime   com.hughsie.libjcat           0.2.1
runtime   org.kernel                    6.7.4-zen1-1-zen
runtime   org.freedesktop.fwupd         1.9.13
```

Please note how you installed it (`apt`, `dnf`, `pacman`, source, etc): **pacman**

<details>

<summary>**fwupd device information**</summary>

Please provide the output of the external fwupd devices recognized in your system.

```shell
❯ fwupdmgr get-devices --filter=~internal
Dell Inc. XPS 15 7590
│
├─WD19TB:
│ │   Device ID:          570867f4ddda9915445da59bd85cd0e0e507270e
│ │   Summary:            High performance dock
│ │   Current version:    01.01.00.07
│ │   Vendor:             Dell Inc. (USB:0x413C)
│ │   Install Duration:   1 minute
│ │   Serial Number:      C5RCGX2/3121917359564623
│ │   GUID:               cd357cf1-40b2-5d87-b8df-bb2dd82774aa ← USB\VID_413C&PID_B06E&hub&embedded
│ │   Device Flags:       • Updatable
│ │                       • Supported on remote server
│ │                       • Device stages updates
│ │                       • Device can recover flash failures
│ │                       • Device is usable for the duration of the update
│ │                       • Signed Payload
│ │
│ ├─Package level of Dell dock:
│ │     Device ID:        073624c16dd99abe01ba1da223a70321e4f29beb
│ │     Summary:          A representation of dock update status
│ │     Current version:  01.00.36.01
│ │     Vendor:           Dell Inc. (USB:0x413C)
│ │     Install Duration: 5 seconds
│ │     GUIDs:            d8927ff5-a5b2-5618-848b-8e8bfb75b66f
│ │                       8ceeeffd-51b6-580c-9b75-69143227aff8 ← USB\VID_413C&PID_B06E&hub&status
│ │     Device Flags:     • Updatable
│ │                       • Supported on remote server
│ │                       • Device can recover flash failures
│ │                       • Device is usable for the duration of the update
│ │                       • Unsigned Payload
│ │
│ ├─RTS5413 in Dell dock:
│ │     Device ID:        0acceea54e71c4d8002593822afe0f4705616613
│ │     Summary:          USB 3.1 Generation 1 Hub
│ │     Current version:  01.22
│ │     Vendor:           Dell Inc. (USB:0x413C)
│ │     Install Duration: 14 seconds
│ │     GUIDs:            b27d25f1-019d-5718-b41a-02ddaefe5577 ← USB\VID_413C&PID_B06F
│ │                       ac5b774c-b49d-566b-9255-85f0f7f8a4ed ← USB\VID_413C&PID_B06F&hub
│ │     Device Flags:     • Updatable
│ │                       • Supported on remote server
│ │                       • Device stages updates
│ │                       • Device is usable for the duration of the update
│ │                       • Signed Payload
│ │
│ ├─RTS5487 in Dell dock:
│ │     Device ID:        96969b82d977fdcbf607df084ef0dcf10119409b
│ │     Summary:          USB 3.1 Generation 2 Hub
│ │     Current version:  01.57
│ │     Vendor:           Dell Inc. (USB:0x413C)
│ │     Install Duration: 3 seconds
│ │     GUIDs:            acfcd89b-105d-55b9-b85b-08bf8508f38c ← USB\VID_413C&PID_B06E
│ │                       568ffa1e-a0db-5287-9ea3-872b60f7730b ← USB\VID_413C&PID_B06E&hub
│ │     Device Flags:     • Updatable
│ │                       • Supported on remote server
│ │                       • Device stages updates
│ │                       • Device is usable for the duration of the update
│ │                       • Signed Payload
│ │
│ ├─VMM5331 in Dell dock:
│ │     Device ID:        228ac6846b64d532dd1ea1b7e651e8f5f55fbc34
│ │     Summary:          Multi Stream Transport controller
│ │     Current version:  05.07.04
│ │     Vendor:           Dell Inc. (USB:0x413C)
│ │     Install Duration: 6 minutes
│ │     GUID:             89fec0b6-6b76-5008-b82c-5e5c6c164007 ← MST-panamera-vmm5331-259
│ │     Device Flags:     • Updatable
│ │                       • Supported on remote server
│ │                       • Device stages updates
│ │                       • Device is usable for the duration of the update
│ │                       • Unsigned Payload
│ │
│ └─Thunderbolt controller in Dell dock:
│       Device ID:        3bc47383c685ea0f4d3bff25dff17202a684d109
│       Summary:          Thunderbolt controller
│       Current version:  60.00
│       Vendor:           Dell Inc. (THUNDERBOLT:0x00D4, TBT:0x00D4)
│       Install Duration: 22 seconds
│       GUIDs:            08a8c886-2818-544c-b1a3-588eb07ae487 ← THUNDERBOLT\VEN_00D4&DEV_B070
│                         c94770ca-1773-592c-b20a-e87243bc7cd0 ← TBT-00d4b070
│                         017a6b19-1f84-5be6-89f5-14ebd10a52de ← TBT-00d4b070-controller0-1
│       Device Flags:     • Updatable
│                         • System requires external power source
│                         • Supported on remote server
│                         • Install to parent device first
│                         • Device stages updates
│                         • Device is usable for the duration of the update
│                         • Signed Payload
│
```

</details>

**Dock SKU**
Please mention which module is installed in your WD19.

- [ ] WD19 (Single-C)
- [x] WD19TB (Thunderbolt)
- [ ] WD19DC (Dual-C)

**Peripherals connected to the dock**

* USB-A mouse
* USB-A keyboard
* DisplayPort monitor
* USB-A cable, no client

**Verbose daemon logs**
First enable daemon verbose logs collection.

```shell
fwupdmgr modify-config "VerboseDomains" "*"
```

Then try to reproduce the issue.  Even if it doesn't reproduce, please attach the
daemon verbose logs collected from the system journal.

```shell
❯ journalctl -b -u fwupd.service
Feb 17 16:07:42 XPS-REDACTED systemd[1]: Starting Firmware update daemon...
Feb 17 16:07:44 XPS-REDACTED fwupd[2606]: 15:07:44.480 FuPluginIntelMe      failed to get public key using /fpf/OemCred: generic failure [0xb]
Feb 17 16:07:48 XPS-REDACTED fwupd[2606]: 15:07:48.166 FuMain               Daemon ready for requests (locale en_US.UTF-8)
Feb 17 16:07:48 XPS-REDACTED systemd[1]: Started Firmware update daemon.
Feb 17 16:38:29 XPS-REDACTED systemd[1]: fwupd.service: Deactivated successfully.
Feb 17 16:38:29 XPS-REDACTED systemd[1]: fwupd.service: Consumed 2.974s CPU time.
Feb 17 16:38:29 XPS-REDACTED systemd[1]: Starting Firmware update daemon...
Feb 17 16:38:30 XPS-REDACTED fwupd[6931]: 15:38:30.714 FuPluginIntelMe      failed to get public key using /fpf/OemCred: generic failure [0xb]
Feb 17 16:38:31 XPS-REDACTED fwupd[6931]: 15:38:31.643 FuMain               Daemon ready for requests (locale en_US.UTF-8)
Feb 17 16:38:31 XPS-REDACTED systemd[1]: Started Firmware update daemon.
```

```shell
❯ journalctl -b -1 -u fwupd.service
Feb 16 17:54:28 XPS-REDACTED systemd[1]: Starting Firmware update daemon...
Feb 16 17:54:30 XPS-REDACTED fwupd[2950]: 16:54:30.601 FuPluginIntelMe      failed to get public key using /fpf/OemCred: generic failure [0xb]
Feb 16 17:54:31 XPS-REDACTED fwupd[2950]: 16:54:31.680 FuMain               Daemon ready for requests (locale en_US.UTF-8)
Feb 16 17:54:31 XPS-REDACTED systemd[1]: Started Firmware update daemon.
Feb 17 15:49:22 XPS-REDACTED fwupd[2950]: 14:49:22.183 FuPluginIntelMe      failed to get public key using /fpf/OemCred: generic failure [0xb]
Feb 17 15:53:31 XPS-REDACTED fwupd[2950]: 14:53:31.961 FuPluginDellDock     [EC Bug] EC read invalid MST version 00000000
Feb 17 15:53:31 XPS-REDACTED fwupd[2950]: 14:53:31.961 FuPluginDellDock     [EC bug] EC read invalid Thunderbolt version 00000000
Feb 17 15:53:32 XPS-REDACTED fwupd[2950]: 14:53:32.979 FuEngine             failed to add device usb:01:00:05:05: failed to add device using on dell_dock: device recovery not possible: failed to>
Feb 17 15:53:33 XPS-REDACTED fwupd[2950]: 14:53:33.666 FuEngine             failed to probe device usb:01:00:05:03: failed to get interfaces: USB error on device 0bda:5413 : Entity not found [-5]
Feb 17 16:06:49 XPS-REDACTED fwupd[2950]: 15:06:49.173 FuPluginUpower       failed to query lid state
Feb 17 16:06:49 XPS-REDACTED fwupd[2950]: 15:06:49.173 FuPluginUpower       failed to query lid state
Feb 17 16:06:49 XPS-REDACTED fwupd[2950]: 15:06:49.468 FuMain               Received SIGTERM
Feb 17 16:06:49 XPS-REDACTED systemd[1]: Stopping Firmware update daemon...
Feb 17 16:06:49 XPS-REDACTED systemd[1]: fwupd.service: Deactivated successfully.
Feb 17 16:06:49 XPS-REDACTED systemd[1]: Stopped Firmware update daemon.
Feb 17 16:06:49 XPS-REDACTED systemd[1]: fwupd.service: Consumed 9.768s CPU time.
```

**Additional questions**

- Operating system and version: Arch Linux
- Have you tried unplugging the dock or any peripherals from your machine?
  - Yes, see repro steps.
- Have you tried to power cycle the dock from the AC adapter?
  - No, not today, wanted to make sure not to brick it.
- Is this a regression? ?

**Comment by teppot** [comment]
After failing many times before, this now worked for me with fwupd 1.9.14 on Fedora Silverblue 40.20240315.n.0.

**Comment by DonJaviJavi** [comment]
Just sharing my experience in case it helps anyone:

I recently bought a used WD19 Docking Station. Out of the box it worked flawlessly on my Samsung 940X5N laptop.
I use Fedora 39 with fwupd 1.9.15.
I noticed there were firmware updates on gnome software application.
I went ahead and tried to update and had the same problems as described in this issue. I was asked to unplug USB, but I didn't get any confirmation if the update was successful. It turns out that after updating the device no longer worked, the OS even got frozen trying to boot. 
I tried to switch to windows to downgrade, but the firmware utility from dell did not detect the device.
I wen back to linux, plugued the device after the OS booted and managed to downgrade using `fwupdmgr downgrade [DEVICE-ID]`.
Again I received the messages to unplug the USB cable and nothing happened.
Using `fwupdtool --get-history` I noticed some of the child devices on the WD19 had the message: `Update Error:       Pending activation`
I used `sudo fwupdtool activate` with each device id and got some of them activated (don't remember which ones).
After that I realized it had problems with the connected devices turning on and off.
I went back to windows and downloaded 3 different firmware updates available on Dell official support site:
https://www.dell.com/support/home/en-us/product-support/product/dell-wd19-130w-dock/drivers
01.00.36, 01.00.20 (04 Jan 2024)
01.00.32, 01.00.16 (25 may 2023)
01.00.25, 01.00.09 (04 jul 2022)
I manage to install these older versions in windows with `/f` parameter, but still none of the above resolved the issue, but I learned it was something related to the power management, the dock kept rebooting and the light on the connector flashing. I noticed it worked fine when I pluged the laptop wall charger (some progress at least).
Finally stumbled with this issue:
https://www.dell.com/community/en/conversations/latitude/dell-docking-wd19-connection-issue-after-update-to-the-latest-010024-a07-firmware-version/647f9c62f4ccf8a8de07e8f9
Somebody was kind enough to upload an even older firmware, I tried it and it finally resolved the issue.
https://drive.google.com/file/d/1o7eF6xfAa-UiYMJ2GB5a-PhYqFz2jJYz/view?usp=share_link


Sorry about my English.
Hope it helps anyone.

**Comment by lemmyg** [comment]
I have this issue with:
```
fwupdmgr --version
compile   com.hughsie.libxmlb           0.3.17
compile   com.hughsie.libjcat           0.2.0
compile   org.freedesktop.fwupd         1.9.16
runtime   org.freedesktop.fwupd-efi     1.4
compile   org.freedesktop.gusb          0.4.8
runtime   com.hughsie.libjcat           0.2.0
runtime   org.freedesktop.gusb          0.4.8
runtime   org.kernel                    6.9.3-t2-noble
runtime   org.freedesktop.fwupd         1.9.16
```

`fwupdmgr get-history 
WARNING: UEFI capsule updates not available or enabled in firmware setup
See https://github.com/fwupd/fwupd/wiki/PluginFlag:capsules-unsupported for more information.
Apple Inc. MacBookPro16,1
│
├─Package level of Dell dock:
│ │   Device ID:          a2607245c04ed6a1b6f17a3816ca41b329588675
│ │   Previous version:   01.00.36.01
│ │   Update State:       Success
│ │   Update Error:       Pending activation
│ │   Last modified:      2024-06-13 07:44
│ │   GUID:               d8927ff5-a5b2-5618-848b-8e8bfb75b66f
│ │   Device Flags:       • Supported on remote server
│ │                       • Device can recover flash failures
│ │                       • Device is usable for the duration of the update
│ │                       • Updatable
│ │                       • Unsigned Payload
│ │ 
│ └─WD19 Dock Update:
│       New version:      01.00.36.01
│       Remote ID:        lvfs
│       Release ID:       75526
│       Summary:          Firmware update for WD19
│       License:          Proprietary
│       Size:             24 bytes
│       Created:          2023-12-14
│       Urgency:          Critical
│       Tested by Allion:
│         Tested:         2024-03-29
│         Distribution:   chromeos 125
│         Old version:    01.01.00.05
│         Version[fwupd]: 1.9.13
│       Vendor:           Dell
│       Duration:         5 seconds
│       Release Flags:    • Trusted metadata
│       Description:      
│       -Update the firmware package version of WD19/WD22 Dell docking station's composite devices to 01.00.36
│       Checksum:         0572352b20a0b071331971f0698625afdd140596f2e38a24359aaf25c8ab4cf8
│     
├─RTS5413 in Dell dock:
│ │   Device ID:          f528949e906d08c2805a1291a26b756320bbc187
│ │   Previous version:   01.22
│ │   Install Duration:   13 seconds
│ │   Update State:       Success
│ │   Last modified:      2024-06-13 07:44
│ │   GUID:               b27d25f1-019d-5718-b41a-02ddaefe5577
│ │   Device Flags:       • Supported on remote server
│ │                       • Device stages updates
│ │                       • Device is usable for the duration of the update
│ │                       • Updatable
│ │                       • Signed Payload
│ │ 
│ └─WD19/WD22 USB 3.1 Generation 1 Controller Update:
│       New version:      01.22
│       Remote ID:        lvfs
│       Release ID:       75533
│       Summary:          Firmware update for WD19/WD22 USB 3.1 Generation 1
│       License:          Proprietary
│       Size:             65.5 kB
│       Created:          2023-12-14
│       Urgency:          High
│       Tested by Allion:
│         Tested:         2024-03-29
│         Distribution:   chromeos 125
│         Old version:    01.01.00.05
│         Version[fwupd]: 1.9.13
│       Vendor:           Dell
│       Duration:         14 seconds
│       Release Flags:    • Trusted metadata
│       Description:      
│       -Fixed the issue where there is no audio when you use a USB headset during conference calls.This issue occurs when the system is connected to the Dell Dock WD19 and WD22 series docks
│       Checksum:         0572352b20a0b071331971f0698625afdd140596f2e38a24359aaf25c8ab4cf8
│     
├─RTS5487 in Dell dock:
│ │   Device ID:          468bd0a927f56032ec562eb7a4402d59a9fc59d2
│ │   Previous version:   01.57
│ │   Install Duration:   2 seconds
│ │   Update State:       Success
│ │   Last modified:      2024-06-13 07:44
│ │   GUID:               acfcd89b-105d-55b9-b85b-08bf8508f38c
│ │   Device Flags:       • Supported on remote server
│ │                       • Device stages updates
│ │                       • Device is usable for the duration of the update
│ │                       • Updatable
│ │                       • Signed Payload
│ │ 
│ └─WD19/WD22 USB 3.1 Generation 2 Controller Update:
│       New version:      01.57
│       Remote ID:        lvfs
│       Release ID:       75534
│       Summary:          Firmware update for WD19/WD22 USB 3.1 Generation 2
│       License:          Proprietary
│       Size:             65.5 kB
│       Created:          2023-12-14
│       Urgency:          High
│       Tested by Allion:
│         Tested:         2024-03-29
│         Distribution:   chromeos 125
│         Old version:    01.01.00.05
│         Version[fwupd]: 1.9.13
│       Vendor:           Dell
│       Duration:         3 seconds
│       Release Flags:    • Trusted metadata
│       Description:      
│       -Fixed the issue where there is no audio when you use a USB headset during conference calls.This issue occurs when the system is connected to the Dell Dock WD19 and WD22 series docks.
│       Checksum:         0572352b20a0b071331971f0698625afdd140596f2e38a24359aaf25c8ab4cf8
│     
├─VMM5331 in Dell dock:
│ │   Device ID:          06ab2c1f2f9e96085360893ae8e8de9b5e6edd4b
│ │   Previous version:   05.07.04
│ │   Install Duration:   34 seconds
│ │   Update State:       Success
│ │   Update Error:       Pending activation
│ │   Last modified:      2024-06-13 07:44
│ │   GUID:               89fec0b6-6b76-5008-b82c-5e5c6c164007
│ │   Device Flags:       • Supported on remote server
│ │                       • Device stages updates
│ │                       • Device is usable for the duration of the update
│ │                       • Updatable
│ │                       • Unsigned Payload
│ │ 
│ └─WD19/WD22 VMM5331 MST Controller Update:
│       New version:      05.07.04
│       Remote ID:        lvfs
│       Release ID:       75531
│       Summary:          Firmware update for WD19/WD22 VMM5331 MST
│       License:          Proprietary
│       Size:             524.3 kB
│       Created:          2023-12-14
│       Urgency:          High
│       Tested by Allion:
│         Tested:         2024-03-29
│         Distribution:   chromeos 125
│         Old version:    01.01.00.05
│         Version[fwupd]: 1.9.13
│       Vendor:           Dell
│       Duration:         6 minutes
│       Release Flags:    • Trusted metadata
│       Description:      
│       -Fixed the issue where a black screen is displayed intermittently when the external monitor is connected to the Dell Dock WD19, WD19TB, and WD22TB4.- Improved the display compatibility of WD19, WD22, and HD22 series dock between systems and monitors.
│       Checksum:         0572352b20a0b071331971f0698625afdd140596f2e38a24359aaf25c8ab4cf8
│     
└─WD19:
  │   Device ID:          d2141f8b95426f7c80924585c9966e48dbe3324f
  │   Previous version:   01.01.00.07
  │   Install Duration:   2 seconds
  │   Update State:       Success
  │   Last modified:      2024-06-13 07:45
  │   GUID:               cd357cf1-40b2-5d87-b8df-bb2dd82774aa
  │   Device Flags:       • Supported on remote server
  │                       • Device update needs activation
  │                       • Device stages updates
  │                       • Device can recover flash failures
  │                       • Device is usable for the duration of the update
  │                       • Updatable
  │                       • Signed Payload
  │ 
  └─WD19/WD22 EC Embedded Controller Update:
        New version:      01.01.00.07
        Remote ID:        lvfs
        Release ID:       75529
        Summary:          Firmware update for WD19/WD22 EC
        License:          Proprietary
        Size:             131.0 kB
        Created:          2023-12-14
        Urgency:          High
        Tested by Allion:
          Tested:         2024-03-29
          Distribution:   chromeos 125
          Old version:    01.01.00.05
          Version[fwupd]: 1.9.13
        Vendor:           Dell
        Duration:         1 minute
        Release Flags:    • Trusted metadata
        Description:      
        -Added the Universal Power Button feature for the Dell Dock WD19.
        Checksum:         0572352`
