### ISSUE TITLE
Check Fails

### ISSUE THREAD

**Issue by tw0123456789101** [fwupd/fwupd#6815]
I'm having check fails

Device Security Report
======================

Report details
  Date generated:                                  2024-02-18 19:53:09
  fwupd version:                                   1.9.13

System details
  Hardware model:                                  ASUSTeK COMPUTER INC. VivoBook_ASUSLaptop X412DAP_F412DA
  Processor:                                       AMD Ryzen 3 3250U with Radeon Graphics
  OS:                                              Fedora Linux 39 (Workstation Edition)
  Security level:                                  HSI:0 (v1.9.13)

HSI-1 Tests
  UEFI Platform Key:                               Pass (Valid)
  UEFI Bootservice Variables:                      Pass (Locked)
  TPM v2.0:                                        Pass (Found)
  BIOS Firmware Updates:                           Pass (Enabled)
  UEFI Secure Boot:                                Pass (Enabled)
  Fused Platform:                                ! Fail 
  TPM Platform Configuration:                      Pass (Valid)

HSI-2 Tests
  AMD Firmware Write Protection:                 ! Fail 
  TPM Reconstruction:                              Pass (Valid)
  IOMMU Protection:                                Pass (Enabled)
  Platform Debugging:                            ! Fail 

HSI-3 Tests
  Suspend To RAM:                                ! Fail (Enabled)
  Pre-boot DMA Protection:                       ! Fail (Not Enabled)
  AMD Firmware Replay Protection:                ! Fail 
  Control-flow Enforcement Technology:           ! Fail (Not Supported)
  Suspend To Idle:                               ! Fail (Not Enabled)

HSI-4 Tests
  Encrypted RAM:                                 ! Fail 
  Supervisor Mode Access Prevention:               Pass (Enabled)
  AMD Secure Processor Rollback Protection:      ! Fail 

Runtime Tests
  Firmware Updater Verification:                   Pass (Not Tainted)
  Linux Swap:                                      Pass (Encrypted)
  Linux Kernel Verification:                       Pass (Not Tainted)
  Linux Kernel Lockdown:                           Pass (Enabled)

Host security events
  2024-02-09 22:09:14   Linux Kernel Lockdown        Pass (Not Enabled → Enabled)
  2024-02-09 22:09:14   UEFI Secure Boot             Pass (Not Enabled → Enabled)

ASUSTeK COMPUTER INC. VivoBook_ASUSLaptop X412DAP_F412DA
│
├─ELAN1301:00 04F3:30C6:
│     Device ID:          4187819f28d6b7c72aaec26529ca6a9c0390ebed
│     Summary:            Touchpad
│     Current version:    0x0003
│     Bootloader Version: 0x0000
│     Vendor:             ELAN Microelectronics (HIDRAW:0x04F3)
│     GUIDs:              7d752ae5-689d-56dc-9925-6dbb73717889 ← HIDRAW\VEN_04F3&DEV_30C6
│                         eb0a723c-d668-507a-a270-fdb717451cb3 ← HIDRAW\VEN_04F3&DEV_30C6&MOD_001E
│                         26c43c77-b0a1-544a-a714-195f02f5ac1a ← ELANTP\ICTYPE_0D&MOD_001E
│                         71c46d72-12a1-5e32-9755-73667859ffb8 ← ELANTP\ICTYPE_0D&MOD_001E&DRIVER_HID
│     Device Flags:       • Internal device
│                         • Updatable
│   
├─AMD Ryzen 3 3250U with Radeon Graphics:
│ │   Device ID:          4bde70ba4e39b28f9eab1628f9dd6e6244c03027
│ │   Current version:    0x08108109
│ │   Vendor:             Advanced Micro Devices, Inc.
│ │   GUIDs:              38cd08d3-c885-5730-bff8-fdf71774a4a2 ← CPUID\PRO_0&FAM_17&MOD_18
│ │                       cbe5ceff-2b79-5935-9e79-ad728587b62f ← CPUID\PRO_0&FAM_17&MOD_18&STP_1
│ │   Device Flags:       • Internal device
│ │ 
│ ├─Graphics Processing Unit (GPU):
│ │ │   Device ID:        3743975ad7f64f8d6575a9ae49fb3a8856fe186f
│ │ │   Summary:          Raven2 Generic VBIOS
│ │ │   Current version:  016.002.000.011.000000
│ │ │   Vendor:           Advanced Micro Devices, Inc. [AMD/ATI] (PCI:0x1002)
│ │ │   GUID:             52ace094-cd5f-5868-9115-d2516a39a599 ← AMD\113-RAVEN2-117
│ │ │   Device Flags:     • Internal device
│ │ │ 
│ │ └─NT140FHM-N44:
│ │       Device ID:      aec1a869eb0df71b7cea6b3ac71d39b830faf164
│ │       GUID:           6969d083-8a4f-5748-a45d-fc7f8e95e03b ← DRM\VEN_BOE&DEV_07F6
│ │       Device Flags:   • Internal device
│ │     
│ └─Secure Processor:
│       Device ID:        c54ab0237d7a8db8c717b68e0be78e4374a2a079
│       Vendor:           Advanced Micro Devices, Inc. (PCI:0x1022)
│       GUIDs:            0e8dc554-a0a2-51fb-b439-1eb72b14ec38 ← PCI\VEN_1022&DEV_15DF
│                         bd5a5081-60b8-57cb-91d6-78e850123204 ← PCI\VEN_1022&DEV_15DF&SUBSYS_102215DF
│       Device Flags:     • Internal device
│     
├─GPIO controller:
│     Device ID:          f685512aa07369c9e77742acef941d779d31e766
│     GUID:               37b440a9-2473-5087-a39b-db84f32a8ed8 ← GPIO\ID_AMDI0030:00
│   
├─MZVLQ256HAJD-00000:
│     Device ID:          03281da317dccd2b18de2bd1cc70a782df40ed7e
│     Summary:            NVM Express solid state drive
│     Current version:    FXV7000Q
│     Vendor:             Samsung (NVME:0x144D)
│     Serial Number:      S4Y6NF0MB41064
│     GUIDs:              8b86707a-1412-5389-8f66-725224d28879 ← NVME\VEN_144D&DEV_A809
│                         71c19ff0-0bc0-5c85-aa6f-ba47fcc33eee ← NVME\VEN_144D&DEV_A809&SUBSYS_144DA801
│                         5a26f86c-6203-515c-9b96-afc4c77218a4 ← SAMSUNG MZVLQ256HAJD-00000
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│                         • Signed Payload
│   
├─SD8SB8U1T00:
│     Device ID:          ff5bf9f6641211b248157b73007e1b638b3f0a05
│     Summary:            ATA drive
│     Current version:    X4140000
│     Vendor:             SanDisk (ATA:0x101C, ATA:0x15B7, OUI:001b44)
│     Serial Number:      164710801433
│     GUIDs:              e75d2044-7982-587f-8245-d5b3b346e159 ← IDE\SanDisk_SD8SB8U1T00_____________________X4140000
│                         71963742-a262-51a3-aaab-62974287aeb2 ← IDE\0SanDisk_SD8SB8U1T00_____________________
│                         894c624d-63c1-5ee8-a497-d433788b8ba9 ← SanDisk SD8SB8U1T00
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─System Firmware:
│ │   Device ID:          a45df35ac0e948ee180fe216a5f703f32dda163f
│ │   Summary:            UEFI ESRT device
│ │   Current version:    771
│ │   Minimum Version:    771
│ │   Vendor:             ASUSTeK COMPUTER INC. (DMI:American Megatrends Inc.)
│ │   Update State:       Success
│ │   GUID:               9392a009-3bb8-5f91-ae00-36b9c0e0a8b5
│ │   Device Flags:       • Internal device
│ │                       • Updatable
│ │                       • System requires external power source
│ │                       • Needs a reboot after installation
│ │                       • Cryptographic hash verification is available
│ │                       • Device is usable for the duration of the update
│ │   Device Requests:    • Message
│ │ 
│ └─UEFI dbx:
│       Device ID:        362301da643102b9f38477387e2193e57abaa590
│       Summary:          UEFI revocation database
│       Current version:  371
│       Minimum Version:  371
│       Vendor:           UEFI:Linux Foundation
│       Install Duration: 1 second
│       GUIDs:            c8749f7f-439b-5c3c-a2ea-3baacf663a5a ← UEFI\CRT_C3E5C7D58D7EE6C6844FEF2F6ECAA3F5F8B5BAFD800BC6F0275D140CB0688967&ARCH_X64
│                         f8ba2887-9411-5c36-9cee-88995bb39731 ← UEFI\CRT_A1117F516A32CEFCBA3F2D1ACE10A87972FD6BBE8FE0D0B996E09E65D802A503&ARCH_X64
│                         0c7691e1-b6f2-5d71-bc9c-aabee364c916 ← UEFI\CRT_ED1FE72CB9CA31C9AF5B757AFCD733323D675825032E6CED7FE1AE9EB767998C&ARCH_X64
│       Device Flags:     • Internal device
│                         • Updatable
│                         • Supported on remote server
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│                         • Only version upgrades are allowed
│                         • Signed Payload
│     
├─TPM:
│     Device ID:          c6a80ac3a22083423992a3cb15018989f37834d6
│     Summary:            TPM 2.0 Device
│     Current version:    3.34.0.4
│     Vendor:             Advanced Micro Devices, Inc. (TPM:AMD)
│     GUIDs:              9305de1c-1e12-5665-81c4-37f8e51219b8 ← TPM\VEN_AMD&DEV_0001
│                         78a291ae-b499-5b0f-8f1d-74e1fefd0b1c ← TPM\VEN_AMD&MOD_AMD
│                         65a3fced-b423-563f-8098-bf5c329fc063 ← TPM\VEN_AMD&DEV_0001&VER_2.0
│                         5e704f0d-83cb-5364-8384-f46d725a23b8 ← TPM\VEN_AMD&MOD_AMD&VER_2.0
│     Device Flags:       • Internal device
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device can recover flash failures
│                         • Full disk encryption secrets may be invalidated when updating
│                         • Signed Payload
│   
└─UEFI Platform Key:
      Device ID:          6924110cde4fa051bfdc600a60620dc7aa9d3c6a
      Summary:            ASUSTeK Notebook PK Certificate
      GUID:               2a08fc11-e178-5bb3-b937-175714a10166 ← UEFI\CRT_3C68BEE0F409F762115E39CDF72BC0C6DED8EA85

**Comment by superm1** [comment]
You need to contact your manufacturer. The platform doesn't report enough data to make a calculation.

There isn't a bug with fwupd.
