### ISSUE TITLE
Make test devices better

### ISSUE THREAD

**Issue by rishabh-chromium** [fwupd/fwupd#6836]
**Is your feature request related to a problem? Please describe.**
Currently there is 1 cab file on LVFS to test for install upgrades on the FakeWebcam device (test device) because of which there is no way to test different cases (wait time, requests etc).

**Describe the solution you'd like**
We can make the test plugin more dynamic that can take in arguments/flags to configure how it behaves.

**Describe alternatives you've considered**
Alternatively, we can upload multiple cab files that test different cases (time consuming and it is almost impossible to cover every single case)

**Additional context**
Spoke with Richard regarding this on GVC.

**Comment by rishabh-chromium** [comment]
Nope, we did our own tests to test for signed reports (if that's what you are asking for). Not sure what signed cabinet archives mean exactly

**Comment by hughsie** [comment]
@rishabh-chromium what about something like https://github.com/fwupd/fwupd/pull/6837 -- can you remember what values you wanted to change at runtime? I think this is going to work a lot better than a custom payload.

**Comment by rishabh-chromium** [comment]
This looks good to me. Is it also possible to fake fail the update with a particular error so we can test for errors mentioned in https://fwupd.github.io/libfwupd/error.Error.html

**Comment by hughsie** [comment]
> fake fail the update

What scenarios were you thinking of? It's probably something we should test in CI too...

**Comment by rishabh-chromium** [comment]
I think it will be valuable to test all error messages in general, but more importantly maybe test `AlreadyPending`, `IncorrectFile`, `ACPowerNotConnected` and other general error messages. I am currently trying to add test cases for these errors and I don't seem to find a way to mimic these errors without physically trying to create these errors

**Comment by rishabh-chromium** [comment]
We can probably add another parameter in the `fwupd.conf` file that is something like:
`FailWithError` and has one of the error codes or names: `FWUPD_ERROR_INTERNAL`  or something. 
If `FailWithError` parameter is found, instantly (or after mentioned delay?) fail with that error code.

**Comment by rishabh-chromium** [comment]
I see a `fwupd_error_from_string` function here: https://github.com/fwupd/fwupd/blob/main/libfwupd/fwupd-error.c#L78
Maybe we can add the string in the `conf` file instead of the code name to make it easier. However, these strings aren't really public, only the code names are. :((
This probably an implementation detail that I will leave up to you.

**Comment by superm1** [comment]
> We can probably add another parameter in the `fwupd.conf` file that is something like:
> `FailWithError` and has one of the error codes or names: `FWUPD_ERROR_INTERNAL`  or something. 
> If `FailWithError` parameter is found, instantly (or after mentioned delay?) fail with that error code.

I don't think it's a useful test to just immediately fail with an error code. It exercises no new parts of the daemon.

For AC vs DC emulation I feel that we are better off using umockdev to emulate a power supply and or battery.

For emulation of a bad payload, how about just pass a bad payload?

**Comment by rishabh-chromium** [comment]
> For emulation of a bad payload, how about just pass a bad payload?

I am not sure how I can emulate a `FWUPD_ERROR_INTERNAL` or few other error codes with a bad payload. Am I missing something here, perhaps I am not understand what a `bad payload` is exactly?

**Comment by superm1** [comment]
> > For emulation of a bad payload, how about just pass a bad payload?
> 
> I am not sure how I can emulate a `FWUPD_ERROR_INTERNAL` or few other error codes with a bad payload. Am I missing something here, perhaps I am not understand what a `bad payload` is exactly?
> 
> 

Yeah might not be able to do them all this way.

**Comment by hughsie** [comment]
Yes, I think we can return a lot of the errors just using the "wrong" or "older" payload; I think it's more important to provide the requests functionality from a UI testing point of view. I'm not super keen on the idea of a firmware update ever failing with an obscure error; that's why we have prepare and that kind of thing. Users aren't going to understand the error anyway.
