### ISSUE TITLE
Dell WD19 upgrade issue

### ISSUE THREAD

**Issue by Overcraft90** [fwupd/fwupd#6874]
**Describe the bug**
Every time I restart my workstation, I get prompted an error message concerning the `fwupd` service.

**Steps to Reproduce**
I'm using a Dell Precision 7750, anything that trigger a restart or even refreshing the page of the **Software app** causes this message to appear.

**Expected behavior**
As per before, from what I'm aware of, this should not be happening; however, I'm not sure to what is related to. It seems that launching the command `sudo service fwupd start` solves the issue.

**fwupd version information**
Please provide the version of the daemon and client.

```shell
runtime   org.freedesktop.fwupd         1.7.9
runtime   com.dell.libsmbios            2.4
compile   org.freedesktop.gusb          0.3.10
runtime   org.kernel                    6.5.0-21-generic
compile   com.hughsie.libjcat           0.1.9
compile   org.freedesktop.fwupd         1.7.9
runtime   org.freedesktop.gusb          0.3.10

```

Please note how you installed it (`apt`, `dnf`, `pacman`, source, etc): `Falthub`

<details>

<summary>**fwupd device information**</summary>

Please provide the output of the external fwupd devices recognized in your system.

```shell
Precision 7750
│
├─WD19DCS:
│ │   Device ID:          70baeee61c76c1ff376c0b74a696fc7c7213c734
│ │   Summary:            High performance dock
│ │   Current version:    01.01.00.07
│ │   Vendor:             Dell Inc. (USB:0x413C)
│ │   Install Duration:   1 minute
│ │   GUID:               cd357cf1-40b2-5d87-b8df-bb2dd82774aa
│ │   Device Flags:       • Updatable
│ │                       • Supported on remote server
│ │                       • Device stages updates
│ │                       • Device can recover flash failures
│ │                       • Device is usable for the duration of the update
│ │                       • Signed Payload
│ │ 
│ ├─Package level of Dell dock:
│ │     Device ID:        1ca18ce9f1c74d3f7b648aade28ce38ca077f373
│ │     Summary:          A representation of dock update status
│ │     Current version:  01.00.36.01
│ │     Vendor:           Dell Inc. (USB:0x413C)
│ │     Install Duration: 5 seconds
│ │     GUID:             8ceeeffd-51b6-580c-9b75-69143227aff8
│ │     Device Flags:     • Updatable
│ │                       • Supported on remote server
│ │                       • Device can recover flash failures
│ │                       • Device is usable for the duration of the update
│ │                       • Unsigned Payload
│ │   
│ ├─RTS5413 in Dell dock:
│ │     Device ID:        3b7d38c59fa333512ced0c08664219fa22c90b8d
│ │     Summary:          USB 3.1 Generation 1 Hub
│ │     Current version:  01.22
│ │     Vendor:           Dell Inc. (USB:0x413C)
│ │     Install Duration: 14 seconds
│ │     GUIDs:            86fb40c0-8bf5-5a8b-a4ad-3156cf6bfaf4
│ │                       b27d25f1-019d-5718-b41a-02ddaefe5577
│ │                       ac5b774c-b49d-566b-9255-85f0f7f8a4ed
│ │     Device Flags:     • Updatable
│ │                       • Supported on remote server
│ │                       • Device stages updates
│ │                       • Device is usable for the duration of the update
│ │                       • Signed Payload
│ │   
│ ├─RTS5487 in Dell dock:
│ │     Device ID:        c33d3b2a5870a4c5d95ee7c41784dec1f68078e8
│ │     Summary:          USB 3.1 Generation 2 Hub
│ │     Current version:  01.57
│ │     Vendor:           Dell Inc. (USB:0x413C)
│ │     Install Duration: 3 seconds
│ │     GUIDs:            707c63d2-e597-5c40-84db-9b1bb4c48d96
│ │                       acfcd89b-105d-55b9-b85b-08bf8508f38c
│ │                       568ffa1e-a0db-5287-9ea3-872b60f7730b
│ │     Device Flags:     • Updatable
│ │                       • Supported on remote server
│ │                       • Device stages updates
│ │                       • Device is usable for the duration of the update
│ │                       • Signed Payload
│ │   
│ └─VMM5331 in Dell dock:
│       Device ID:        c108504056150122cb663b10de22aa18147fa21e
│       Summary:          Multi Stream Transport controller
│       Current version:  05.07.04
│       Vendor:           Dell Inc. (USB:0x413C)
│       Install Duration: 6 minutes
│       GUID:             89fec0b6-6b76-5008-b82c-5e5c6c164007
│       Device Flags:     • Updatable
│                         • Supported on remote server
│                         • Device stages updates
│                         • Device is usable for the duration of the update
│                         • Unsigned Payload
│     
└─Unifying Receiver:
      Device ID:          82091cc2e67e8e248d8dad9ac847708118484457
      Summary:            Miniaturised USB wireless receiver
      Current version:    RQR24.11_B0036
      Bootloader Version: BOT03.02_B0009
      Vendor:             HIDRAW:0x046D|USB:0x046D
      Install Duration:   30 seconds
      GUIDs:              cc4cbfa9-bf9d-540b-b92b-172ce31013c1
                          fcf55bf5-767b-51ce-9c17-f6f538c4ee9f
                          279ed287-3607-549e-bacc-f873bb9838c4
      Device Flags:       • Updatable
                          • Signed Payload
```

</details>

**Dock SKU**
Please mention which module is installed in your WD19.

- [ ] WD19 (Single-C)
- [ ] WD19TB (Thunderbolt)
- [x] WD19DC (Dual-C)

I believe the above is the case, as I'm using a WD19DCS with two type-C/thunderbolt connectors.

**Peripherals connected to the dock**
N/A

**Verbose daemon logs**
First enable daemon verbose logs collection.

```shell
Restart the daemon to make the change effective? [Y|n]: Y
Successfully modified configuration value
```

Then try to reproduce the issue.  Even if it doesn't reproduce, please attach the
daemon verbose logs collected from the system journal.

```shell
Mar 05 11:11:16 NeoPC-mat systemd[1]: Starting Firmware update daemon...
Mar 05 11:11:17 NeoPC-mat fwupd[1112081]: 10:11:17:0033 FuEngine             failed to get releases for UEFI dbx: No releases found: Not compatible with org.freedesktop.fwupd version 1.7.9, requires >= 1.9.1
Mar 05 11:11:17 NeoPC-mat fwupd[1112081]: 10:11:17:0035 FuEngine             failed to get releases for UEFI dbx: No releases found: Not compatible with org.freedesktop.fwupd version 1.7.9, requires >= 1.9.1
Mar 05 11:11:19 NeoPC-mat fwupd[1112081]: 10:11:19:0188 FuEngine             failed to add device /sys/devices/pci0000:00/0000:00:1f.5/spi_master/spi0/spi0.0/mtd/mtd0ro: attribute size returned no data
Mar 05 11:11:20 NeoPC-mat systemd[1]: Started Firmware update daemon.
Mar 05 11:20:26 NeoPC-mat fwupd[1112081]: 10:20:26:0543 FuConfig             /etc/fwupd/daemon.conf.O36VJ2 changed, reloading all configs
Mar 05 11:20:26 NeoPC-mat fwupd[1112081]: 10:20:26:0543 FuConfig             trying to load config values from /etc/fwupd/daemon.conf
Mar 05 11:20:26 NeoPC-mat fwupd[1112081]: 10:20:26:0543 FuCommon             reading /etc/fwupd/daemon.conf with 1931 bytes
Mar 05 11:20:26 NeoPC-mat fwupd[1112081]: 10:20:26:0543 FuConfig             trying to load config values from /var/etc/fwupd/daemon.conf
Mar 05 11:20:26 NeoPC-mat fwupd[1112081]: 10:20:26:0543 FuConfig             using autodetected max archive size 18.4 EB
Mar 05 11:20:26 NeoPC-mat fwupd[1112081]: 10:20:26:0543 GLib                 setenv()/putenv() are not thread-safe and should not be used after threads are created
Mar 05 11:20:26 NeoPC-mat fwupd[1112081]: 10:20:26:0543 FuConfig             ::configuration changed
Mar 05 11:20:26 NeoPC-mat fwupd[1112081]: 10:20:26:0543 FuIdle               setting timeout to 7200s
Mar 05 11:20:26 NeoPC-mat fwupd[1112081]: 10:20:26:0543 FuConfig             /etc/fwupd/daemon.conf changed, reloading all configs
Mar 05 11:20:26 NeoPC-mat fwupd[1112081]: 10:20:26:0543 FuConfig             trying to load config values from /etc/fwupd/daemon.conf
Mar 05 11:20:26 NeoPC-mat fwupd[1112081]: 10:20:26:0543 FuCommon             reading /etc/fwupd/daemon.conf with 1931 bytes
Mar 05 11:20:26 NeoPC-mat fwupd[1112081]: 10:20:26:0543 FuConfig             trying to load config values from /var/etc/fwupd/daemon.conf
Mar 05 11:20:26 NeoPC-mat fwupd[1112081]: 10:20:26:0543 FuConfig             using autodetected max archive size 18.4 EB
Mar 05 11:20:26 NeoPC-mat fwupd[1112081]: 10:20:26:0543 GLib                 setenv()/putenv() are not thread-safe and should not be used after threads are created
Mar 05 11:20:26 NeoPC-mat fwupd[1112081]: 10:20:26:0543 FuConfig             ::configuration changed
Mar 05 11:20:26 NeoPC-mat fwupd[1112081]: 10:20:26:0543 FuIdle               setting timeout to 7200s
Mar 05 11:20:26 NeoPC-mat fwupd[1112081]: 10:20:26:0543 FuConfig             /etc/fwupd/daemon.conf changed, reloading all configs
Mar 05 11:20:26 NeoPC-mat fwupd[1112081]: 10:20:26:0543 FuConfig             trying to load config values from /etc/fwupd/daemon.conf
Mar 05 11:20:26 NeoPC-mat fwupd[1112081]: 10:20:26:0543 FuCommon             reading /etc/fwupd/daemon.conf with 1931 bytes
Mar 05 11:20:26 NeoPC-mat fwupd[1112081]: 10:20:26:0543 FuConfig             trying to load config values from /var/etc/fwupd/daemon.conf
Mar 05 11:20:26 NeoPC-mat fwupd[1112081]: 10:20:26:0543 FuConfig             using autodetected max archive size 18.4 EB
Mar 05 11:20:26 NeoPC-mat fwupd[1112081]: 10:20:26:0543 GLib                 setenv()/putenv() are not thread-safe and should not be used after threads are created
Mar 05 11:20:26 NeoPC-mat fwupd[1112081]: 10:20:26:0543 FuConfig             ::configuration changed
Mar 05 11:20:26 NeoPC-mat fwupd[1112081]: 10:20:26:0543 FuIdle               setting timeout to 7200s
Mar 05 11:20:40 NeoPC-mat systemd[1]: Stopping Firmware update daemon...
Mar 05 11:20:40 NeoPC-mat fwupd[1112081]: 10:20:40:0342 FuPlugin             destroy(synaptics_mst)
Mar 05 11:20:40 NeoPC-mat fwupd[1112081]: 10:20:40:0342 FuPlugin             destroy(logind)
Mar 05 11:20:40 NeoPC-mat fwupd[1112081]: 10:20:40:0342 FuPlugin             destroy(pci_mei)
Mar 05 11:20:40 NeoPC-mat fwupd[1112081]: 10:20:40:0342 FuPlugin             destroy(upower)
Mar 05 11:20:40 NeoPC-mat fwupd[1112081]: 10:20:40:0342 FuPlugin             destroy(modem_manager)
Mar 05 11:20:40 NeoPC-mat fwupd[1112081]: 10:20:40:0342 FuPlugin             destroy(linux_lockdown)
Mar 05 11:20:40 NeoPC-mat fwupd[1112081]: 10:20:40:0342 FuPlugin             destroy(linux_swap)
Mar 05 11:20:40 NeoPC-mat fwupd[1112081]: 10:20:40:0342 FuPlugin             destroy(dell)
Mar 05 11:20:40 NeoPC-mat fwupd[1112081]: 10:20:40:0342 FuPlugin             destroy(linux_tainted)
Mar 05 11:20:40 NeoPC-mat fwupd[1112081]: 10:20:40:0343 FuPlugin             destroy(tpm)
Mar 05 11:20:40 NeoPC-mat fwupd[1112081]: 10:20:40:0343 FuPlugin             destroy(redfish)
Mar 05 11:20:40 NeoPC-mat fwupd[1112081]: 10:20:40:0343 FuPlugin             destroy(uefi_capsule)
Mar 05 11:20:40 NeoPC-mat systemd[1]: fwupd.service: Deactivated successfully.
Mar 05 11:20:40 NeoPC-mat systemd[1]: Stopped Firmware update daemon.
Mar 05 11:20:40 NeoPC-mat systemd[1]: fwupd.service: Consumed 1.730s CPU time.
```

**Additional questions**

- Operating system and version: `Ubuntu 22.04.4`
- Have you tried unplugging the dock or any peripherals from your machine? No.
- Have you tried to power cycle the dock from the AC adapter? No.
- Is this a regression? No.

Not sure if this is a `bug` or a `Dell WD19 bug` loking up it seems to be related to the dock but I'm not sure. This is an image of the exact exact message; it appears the service fails to start upon restarting the machine.
![Screenshot from 2024-03-04 21-51-24](https://github.com/fwupd/fwupd/assets/98895614/5099d89f-dc3f-4043-bdf7-026e8a2ce503)

**Comment by CragW** [comment]
Are your referring to `$ snap-store` for the software application?  Have you refreshed all your snaps to the latest?

**Comment by Overcraft90** [comment]
It's not actually the `$ snap-store` app shipped with Ubuntu, it is the one downloaded to manage `Faltpack` applications. That said, I run the following:
```
snap refresh --time

last: today at 16:07 CET
next: today at 22:20 CET
```
then
```
snap refresh --list
Name     Version    Rev   Size   Publisher  Notes
firefox  123.0.1-1  3941  280MB  mozilla✓   -
```

and installed Firefox with the following
```
sudo snap refresh
```
The problem still persist, as I think Firefox is not directly involved in the `fwupd` startup. Let me know, thanks!

**Comment by superm1** [comment]
The issue with the snap store you're seeing is tracked here: https://forum.snapcraft.io/t/confined-fwupd-snap-and-snap-store/38510.  You can see that workaround until they've come up with an architectural solution.

**Comment by superm1** [comment]
Also you shouldn't have both DPKG and SNAP versions installed at same time,
You should remove one of them.

**Comment by superm1** [comment]
* fwupd 1.7.9 is in Ubuntu 22.04 "natively" as a dpkg package.
* fwupd 1.9.14 is available in the snap store.

You can use either; but don't have both installed.  If you choose the snap version then you need to do the manual connection step.

**Comment by Overcraft90** [comment]
For clarity, I do have only one app the one installed with Flatpack from the following address: [Flathub](https://flathub.org/apps/org.gnome.Firmware)

**Comment by Overcraft90** [comment]
Ah I see, I think I got it! So, simply do the connection step will fix this and the issue should not reappear again, right?

**Comment by superm1** [comment]
It _should_ help your issue.

**Comment by Overcraft90** [comment]
Just to make sure, is this normal? I'm getting the following

> error: snap "fwupd" is not installed

after running: `snap connect snap-store:fwupd fwupd:fwupd`. However, as stated above I have a Flatpack version of the firmware app. 

So, I followed up and removed the version I was running installed from the link above (supposedly the `1.7.9` although from my understanding Flatpack should have more up-to-date version of several packages) and installed the `snap store` one.
Then, I run `snap connect snap-store:fwupd fwupd:fwupd` and this time everything seemed to be fine; however, now I'm getting this... any idea?
![Screenshot from 2024-03-05 20-20-18](https://github.com/fwupd/fwupd/assets/98895614/83246f4e-7b37-41cd-9d98-642b4bdaeb87)

**Comment by Overcraft90** [comment]
@superm1 also, the handy GUI interface to see all peripherals connected has disappeared from my apps...

**Comment by superm1** [comment]
It seems to me that you must have had a snap at some point and mixed things up. I suggest using just one package type.

**Comment by Overcraft90** [comment]
I see, that's possible. This will imply, however, to do a fresh new install and somehow purge all possible configuration of `fwupd`. How can I do so? The simple remove/uninstall won't do it...

Also, hopefully there is a safe way to do it; I'd rather avoid a system crash for this.

**Comment by superm1** [comment]
It's possible you can do apt purge fwupd and then apt install fwupd and it will overwrite anything from the previously classic snap.

**Comment by Overcraft90** [comment]
@superm1 Great! That was the problem, now it appears everything is back to normal. I'm running the built in version `1.7.9` but I guess that is not that big of a deal. I think we can close fr now, thanks again!

**Comment by Overcraft90** [comment]
@superm1 Re-opening as I need some clarifications.

The problem with the `1.7.9` version appeared to be fixed be after a restart today it showed up again. So, I though maybe this older shipped version is not the appropriate one for more up-to-date kernels/versions of Ubuntu. Hence, I `apt purge fwupd` then installed the Software version `1.9.14`.

At this point the message disappeared, the nice GUI icon is there, but t the same
![Screenshot from 2024-03-05 20-20-18](https://github.com/fwupd/fwupd/assets/98895614/b0af143e-c29d-4b1f-8839-2be6a69de46b)
appears again...

After a bit of research, I came across several posts talking about `Discover` a package for Ubuntu that should help with apps management I suppose? In this package there is the option in the Settings to _disable vendo-directory_ under Firmware Updates.

This seems to definitively solve the problem. But, for one what is this doing and secondly is it safe to leave as it is now? Please any insight would be great. let me know. Thanks in advance!

**Comment by superm1** [comment]
Let's discuss it in a new issue I just opened instead of this WD19 one.
