### ISSUE TITLE
1.9.15: meson fails because messy dependencies checks

### ISSUE THREAD

**Issue by kloczek** [fwupd/fwupd#6913]
**Describe the bug**
Looks like instead checking dependencies on meson layer new po/test-deps script has been introduced.
😞 
**Steps to Reproduce**
Just run meson without installed gobject-introspection.

**Expected behavior**
All  dependency checks shuld be done by meson.

**fwupd version information**
1.9.15

**Additional questions**
- Operating system and version: Linux x86/64
- Have you tried rebooting? N/A
- Is this a regression? N/A

Without installed gobject-introspection meson fails with enigmatic
```console
Configuring simple_client.py using configuration
Configuring fwupd.spec.in using configuration
Configuring 35_fwupd using configuration
Run-time dependency fwupd-efi found: YES 1.4

plugins/uefi-capsule/meson.build:123:2: ERROR: Command `/usr/bin/python3 /home/tkloczko/rpmbuild/BUILD/fwupd-1.9.15/po/test-deps /home/tkloczko/rpmbuild/BUILD/fwupd-1.9.15/po/LINGUAS` failed with status 1.

A full log can be found at /home/tkloczko/rpmbuild/BUILD/fwupd-1.9.15/x86_64-redhat-linux-gnu/meson-logs/meson-log.txt
```

**Comment by kloczek** [comment]
Just checked po/test-deps
```python
try:
    import gi
except ImportError:
    print("Error: missing dependency python gobject introspection (python3-gi)")
    err = 1
try:
    gi.require_version("Pango", "1.0")
    from gi.repository import Pango
except ValueError:
    print("Error: missing pango gobject introspection library")
    err = 1
try:
    gi.require_version("PangoCairo", "1.0")
    from gi.repository import PangoCairo
except ValueError:
    print("Error: missing pangocairo gobject introspection library")
    err = 1

try:
    gi.require_version("cairo", "1.0")
    from gi.repository import cairo
except ValueError:
    print("Error: missing cairo gobject introspection library")
    err = 1

try:
    import cairo
except ImportError:
    print("Error: missing dependency python cairo (python3-cairo)")
    err = 1
```
All above build requirements have proper pkgconfig interface so looks like that script can be removed and replaced by few `dependency ()` calls in main meson.build.

**Comment by hughsie** [comment]
>  Looks like instead checking dependencies on meson layer new po/test-deps script has been introduced.

Yup, in 2017...

> so looks like that script can be removed and replaced by few dependency () calls in main meson.build

Patches certainly welcome.
