### ISSUE TITLE
About unique computer GUID restriction

### ISSUE THREAD

**Issue by vincent-tang1** [fwupd/fwupd#6937]
**Is your feature request related to a problem? Please describe.**
Considering a scenario, in server product development stage or after MP, we might provide a testing firmware to customer by uploading to LVFS testing remote such that customer can easily install it. However, we do not want to let other people to be also able to install this testing firmware. So, adding a unquie computer GUID limitation might be a choose to achieve it.  

**Describe the solution you'd like**
Not sure it is appropriate that we can limit a unquie computer GUID to access. (allow OR operation)

Thanks

**Comment by hughsie** [comment]
I don't think this is something we want to support; having that component in the metadata downloaded over a million times per day for a single machine seems a huge amount of overhead and waste. The testing firmware can be uploaded into the private remote and then you can give the customer the URL to the cab file to be installed manually.

**Comment by vincent-tang1** [comment]
Got it, aggree your consideration and many thinks for your suggestion.
