### ISSUE TITLE
Failed to download due to server limit

### ISSUE THREAD

**Issue by Schlentzen** [fwupd/fwupd#6994]
**Describe the question**
I am trying to update a pool of Devices but every time i get the Error:
Failed to download due to server limit

**fwupd version information**
```
fwupdmgr --version
compile   com.hughsie.libxmlb           0.3.15
compile   org.freedesktop.Passim        0.1.5
compile   com.hughsie.libjcat           0.2.1
compile   org.freedesktop.fwupd         1.9.15
runtime   org.freedesktop.fwupd-efi     1.5
compile   org.freedesktop.gusb          0.4.8
runtime   org.freedesktop.Passim        0.1.5
runtime   org.freedesktop.gusb          0.4.8
runtime   com.hughsie.libjcat           0.2.1
runtime   org.kernel                    6.8.1-arch1-1
runtime   org.freedesktop.fwupd         1.9.15
```

The Problem stays the same no matter what device i use

**Comment by hughsie** [comment]
What's the public IP you're using to download please?

**Comment by Schlentzen** [comment]
> What's the public IP you're using to download please?

193.175.84.201

**Comment by hughsie** [comment]
Th tl;dr: is:

![Screenshot 2024-03-27 at 13-40-30 LVFS Client ACLs](https://github.com/fwupd/fwupd/assets/151380/75347726-674f-4dc8-866c-204570f2e1a7)

![Screenshot 2024-03-27 at 13-41-27 LVFS Update Client ACL Details](https://github.com/fwupd/fwupd/assets/151380/85f0b1dd-cc4d-4e14-bb92-2f7cd5c6f428)

I've deleted the ACL that blocked updates -- but please also be careful of the 250/day limit for the same firmware file.

**Comment by proximous** [comment]
I believe I'm having the same issue. 71.127.49.162. If you can provide any info that would help me identify the errant device causing the problem please let me know.

**Comment by hughsie** [comment]
> 71.127.49.162

Blocked 20411 times, last seen 12 hours ago. It's downloading the same Dell Precision 7X30 firmware over and over again.

<img width="1329" height="1112" alt="Image" src="https://github.com/user-attachments/assets/faeac23f-f69d-4f10-b423-b90755a784fb" />

**Comment by proximous** [comment]
My apologies and thanks. I believe I have corrected the problem. Can I respectfully request to be unblocked?

**Comment by hughsie** [comment]
> I believe I have corrected the problem

Out of morbid curiosity, what was the problem please?

**Comment by proximous** [comment]
:) I created a firewall rule to block all traffic to fwupd.org and log the IP address. Unfortunately we have around 10 identical systems needing the update, so I'm not yet sure who is the offender, but at least we will stop spamming the site, and the logs should point me to the offender.

**Comment by hughsie** [comment]
Okay, ACL deleted -- please try again gently.
