### ISSUE TITLE
Send mail on available update

### ISSUE THREAD

**Issue by JNKL** [fwupd/fwupd#7002]
I think the feature that fwupd daemon sends a (local) mail when a new firmware is available is missing.

It could be implemented as unattended-upgrades and smartmontools do.

Thanks for your work!

**Comment by hughsie** [comment]
I don't think many people have the local smtp service set up these days unfortunately. I think a better solution is to use something like Red Hat Insights and get a per-site report of this kind of thing. There's also a message in the MOTD too about pending updates -- if you have that configured.
