### ISSUE TITLE
Switching between firmware variants, "No supported devices found", no way to override

### ISSUE THREAD

**Issue by intelfx** [fwupd/fwupd#7240]
**Describe the question**

The Lenovo X1 Carbon 6th (2018) laptop has two different firmware variants available on LVFS:

- the default one with Computrace module built-in: https://fwupd.org/lvfs/devices/com.lenovo.ThinkPadN23ETXXW.firmware
- the alternative one without Computrace: https://fwupd.org/lvfs/devices/com.lenovo.ThinkPadN23ETXXP.firmware

The LVFS files for these firmware variants declare different GUIDs visible in firmware.metainfo.xml:

- N23ET88W declares `<firmware type="flashed">a4b51dca-8f97-4310-8821-3330f83c9135</firmware>`
- N23ET88P declares `<firmware type="flashed">99d47dfe-68fc-4a6f-b541-32e003c886fb</firmware>`

However, I do not see a supported procedure to switch to the other variant.

Attempting to `fwupdmgr install <file> <device ID>` or `fwupdmgr install <file> <guid>` against the "other" variant yields a "No supported devices found" message. Any combination of `--force`, `--no-safety-check` or `--allow-branch-switch` flags does not seem to affect the behavior.

What is the correct procedure (if any) to switch between the firmware variants?

<details>
<summary>fwupdmgr get-devices (current firmware is non-Computrace)</summary>

```
LENOVO 20KH006MRT
│
├─Core™ i7-8550U CPU @ 1.80GHz:
│     Device ID:          4bde70ba4e39b28f9eab1628f9dd6e6244c03027
│     Current version:    0x000000f4
│     Vendor:             Intel
│     GUIDs:              561403e8-143a-5071-ab09-bf5e4c146983 ← CPUID\PRO_0&FAM_06&MOD_8E
│                         54bdc429-0179-5019-9cb6-8a343324c97c ← CPUID\PRO_0&FAM_06&MOD_8E&STP_A
│     Device Flags:       • Internal device
│
├─MZVLB1T0HALR-000L7:
│     Device ID:          04e17fcf7d3de91da49a163ffe4907855c3648be
│     Summary:            NVM Express solid state drive
│     Current version:    5L2QEXA7
│     Vendor:             Samsung (NVME:0x144D)
│     Serial Number:      S3TPNX0K703194
│     GUIDs:              47335265-a509-51f7-841e-1c94911af66b ← NVME\VEN_144D&DEV_A808
│                         c9d531ea-ee7d-5562-8def-c64d0d144813 ← NVME\VEN_144D&DEV_A808&SUBSYS_144DA801
│                         08575ca8-c22c-540a-8ac9-e784c04f6e5a ← SAMSUNG MZVLB1T0HALR-000L7
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│                         • Signed Payload
│
├─System Firmware:
│     Device ID:          ea3642aa8bfdbf7ebe22b36cb51c7da16bc5c6df
│     Summary:            UEFI System Resource Table device (updated via NVRAM)
│     Current version:    0.1.62
│     Minimum Version:    0.0.1
│     Vendor:             Lenovo Ltd. (DMI:LENOVO)
│     Update State:       Needs reboot
│     Last modified:      2024-05-10 22:12
│     GUID:               99d47dfe-68fc-4a6f-b541-32e003c886fb
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Cryptographic hash verification is available
│                         • Device is usable for the duration of the update
│     Device Requests:    • Message
│                         • Message (custom)
│
├─TPM:
│     Device ID:          c6a80ac3a22083423992a3cb15018989f37834d6
│     Current version:    7.63.13.6400
│     Vendor:             Infineon (TPM:IFX)
│     GUIDs:              5eebb112-75ad-5536-b173-a11eb3399402 ← TPM\VEN_IFX&DEV_0000
│                         ddf995da-1b32-5a8a-bc1b-8d5af4b38b51 ← TPM\VEN_IFX&MOD_SLB9670
│                         6d81ab63-db2e-50ac-934f-6be9accf5e02 ← TPM\VEN_IFX&DEV_0000&VER_2.0
│                         301555de-680d-5ddc-b995-7553fc9138f1 ← TPM\VEN_IFX&MOD_SLB9670&VER_2.0
│     Device Flags:       • Internal device
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device can recover flash failures
│                         • Full disk encryption secrets may be invalidated when updating
│                         • Signed Payload
│
├─UEFI Device Firmware:
│     Device ID:          274bedb630d0fd782c31d84e0ec0be27d42a9e14
│     Summary:            UEFI System Resource Table device (updated via NVRAM)
│     Current version:    184.94.4494
│     Minimum Version:    0.0.1
│     Vendor:             Lenovo Ltd. (DMI:LENOVO)
│     Update State:       Success
│     GUID:               9c9d9769-32fa-4841-b550-ea998e754e99
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│     Device Requests:    • Message
│
├─UEFI Device Firmware:
│     Device ID:          a54e6e63dc271f06218a877e5bf661c28ae95c64
│     Summary:            UEFI System Resource Table device (updated via NVRAM)
│     Current version:    0.1.22
│     Minimum Version:    0.1.22
│     Vendor:             Lenovo Ltd. (DMI:LENOVO)
│     Update State:       Success
│     GUID:               3babca5f-b2bf-4f4b-a72e-2bdc84eb4019
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│     Device Requests:    • Message
│
├─UEFI Device Firmware:
│     Device ID:          f462afd2d2f26b490c804fc6fe1ce5d7dda9c9aa
│     Summary:            UEFI System Resource Table device (updated via NVRAM)
│     Current version:    7.63.3353
│     Minimum Version:    7.63.3353
│     Vendor:             Lenovo Ltd. (DMI:LENOVO)
│     Update State:       Success
│     GUID:               d5aedfd0-ada1-ea61-fffa-f5d5d6472fdb
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│     Device Requests:    • Message
│
└─UHD Graphics 620:
      Device ID:          5792b48846ce271fab11c4a545f7a3df0d36e00a
      Current version:    07
      Vendor:             Intel Corporation (PCI:0x8086)
      GUIDs:              8b72a10c-1279-5f8e-a28a-34fb11a58240 ← PCI\VEN_8086&DEV_5917
                          0284ca6a-a235-5433-b190-1de21c753494 ← PCI\VEN_8086&DEV_5917&SUBSYS_17AA225C
      Device Flags:       • Internal device
                          • Cryptographic hash verification is available
```
</details>

**fwupd version information**
Please provide the version of the daemon and client if applicable to your current installation of `fwupd`.

```shell
# fwupdmgr --version
compile   com.hughsie.libxmlb           0.3.19
compile   org.freedesktop.Passim        0.1.8
compile   com.hughsie.libjcat           0.2.1
compile   org.freedesktop.fwupd         1.9.19
runtime   org.freedesktop.fwupd-efi     1.6
compile   org.freedesktop.gusb          0.4.8
runtime   com.hughsie.libxmlb           0.3.19
runtime   org.freedesktop.Passim        0.1.8
runtime   org.freedesktop.gusb          0.4.8
runtime   com.hughsie.libjcat           0.2.1
runtime   org.kernel                    6.8.9-arch1pf7-2
runtime   org.freedesktop.fwupd         1.9.19
```

**Comment by hughsie** [comment]
@mrhpearson is this supported by Lenovo? If not, might it work anyway or is it always going to fail? Thanks.

**Comment by mrhpearson** [comment]
I knew I'd looked at this a long time ago....but couldn't remember the details. Fortunately the internet is great and I found my original reply! 
https://forums.lenovo.com/t5/Other-Linux-Discussions/Replacing-W-BIOS-with-P-BIOS-Non-Absolute-Persistence-Module-version/m-p/4611154?page=1#4620577
Summary:

> W-BIOS to P-BIOS is acceptable by following way. But once P-BIOS is installed, user can never return to W-BIOS. Please advise this important restriction to customer.
> 
> 1. Open BIOS Setup.
> 2. Move to Security -> Absolute Persistence® Module.
> 3. Select Permanently Disabled. Then, press F10 to Save and Exit.
> 4. Install P-BIOS. Then, BIOS is automatically moved from W-BIOS to P-BIOS.
> 

The tricky bit is step 4 and in the thread above someone hacks the metadata to do the update. If you go this route and it doesn't work, let me know and I'll go and hunt on the FW server for the UEFI files and you can do it from there.
Given how old the X1C6 is I don't know that I personally would risk messing with it at this point - it will be tough getting support if it goes horribly wrong.

**Comment by hughsie** [comment]
Thanks @mrhpearson  -- that's a great write-up. Given this is a one-way branch switch, I don't think it makes sense to officially support in fwupd. @intelfx I hope that helps!

**Comment by mrhpearson** [comment]
Are you sure? P-BIOS to W-BIOS should not be possible. Can you confirm you're running the W BIOS from the BIOS setup screen (F1 during early boot). 
If you're just updating P-BIOS - that's a normal update, nothing special. Both updated W and P BIOS's are on the server. I don't understand why you are wanting to switch between versions. 
What am I missing?

**Comment by mrhpearson** [comment]
Hmm - I'm not on the VPN right now, so ping me on Monday and I'll get a ticket open.

Why on earth would you want a P-BIOS older than 1.43? That's 4 years old
The latest version (1.63) is there. Why not just update to that? What are you trying to achieve with this thread?

**Comment by mrhpearson** [comment]
oh...ok...interesting.
I strongly don't recommend and hope you don't brick the system in the process. Keep in mind that ME firmware usually can't be downgraded, which won't you need to do as well? There are often steps between BIOS and EC FW that have to be done in sync too.... Good luck!
