### ISSUE TITLE
  Package fwupd is not configured yet

### ISSUE THREAD

**Issue by estatistics** [fwupd/fwupd#7260]
`Summary:
  Upgrading: 0, Installing: 0, Removing: 0, Not Upgrading: 195
  3 not fully installed or removed.
  Download size: 0 B / 330 kB
  Space needed: 0 B / 1830 GB available

Continue? [Y/n] y
Setting up fwupd (1.9.19-1) ...
+ [ configure = configure ]
+ systemd-sysusers fwupd.conf
Creating group 'fwupd-refresh' with GID 994.
Creating user 'fwupd-refresh' (Firmware update daemon) with UID 994 and GID 994.
dpkg: error processing package fwupd (--configure):
 installed fwupd package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of fwupd-tests:
 fwupd-tests depends on fwupd; however:
  Package fwupd is not configured yet.

dpkg: error processing package fwupd-tests (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 fwupd
 fwupd-tests
Error: Sub-process /usr/bin/dpkg returned an error code (1)
eros@eros:/mnt/Projects/home/eros/Downloads/_linux/vokoscreenNG/src$ sudo apt upgrade

 sudo apt install fwupd
fwupd is already the newest version (1.9.19-1).
Summary:
  Upgrading: 0, Installing: 0, Removing: 0, Not Upgrading: 195
  3 not fully installed or removed.
  Download size: 0 B / 330 kB
  Space needed: 0 B / 1830 GB available

Continue? [Y/n] y
Setting up fwupd (1.9.19-1) ...
+ [ configure = configure ]
+ systemd-sysusers fwupd.conf
Creating group 'fwupd-refresh' with GID 994.
Creating user 'fwupd-refresh' (Firmware update daemon) with UID 994 and GID 994.
dpkg: error processing package fwupd (--configure):
 installed fwupd package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of fwupd-tests:
 fwupd-tests depends on fwupd; however:
  Package fwupd is not configured yet.

dpkg: error processing package fwupd-tests (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 fwupd
 fwupd-tests
Error: Sub-process /usr/bin/dpkg returned an error code (1)

sudo dpkg --configure -a
Setting up fwupd (1.9.19-1) ...
+ [ configure = configure ]
+ systemd-sysusers fwupd.conf
Creating group 'fwupd-refresh' with GID 994.
Creating user 'fwupd-refresh' (Firmware update daemon) with UID 994 and GID 994.
dpkg: error processing package fwupd (--configure):
 installed fwupd package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of fwupd-tests:
 fwupd-tests depends on fwupd; however:
  Package fwupd is not configured yet.

dpkg: error processing package fwupd-tests (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 fwupd
 fwupd-tests

sudo fwupdmgr get-devices --show-all-devices
Gigabyte Technology Co., Ltd. B550M AORUS ELITE
?
??Unknown Device:
?     Device ID:          a29de8124928f7dc31db026069ac1d601a56056f
?     GUID:               2d9ac22e-0ffe-5691-9e21-f9fecce8761c ? GPIO\ID_AMDIF030:00
?   
??500 Series Chipset SATA Controller (ASM1062 Serial ATA Controller):
?     Device ID:          7d29f2075dcafb4488b40c73f199cf46bb76bddb
?     Vendor:             Advanced Micro Devices, Inc. [AMD] (PCI:0x1022)
?     GUIDs:              1ac50181-6bbf-5e5e-967f-8fcb5bd5494a ? PCI\VEN_1022&DEV_43EB
?                         fe2f43c0-0657-572f-9496-f9fc686fffc6 ? PCI\VEN_1022&DEV_43EB&SUBSYS_1B211062
?                         2d530482-50db-5cbc-97f7-6ae02507276d ? PCI\VEN_1022&DEV_1483
?                         0b05f0c1-7f0b-59e0-adb4-0e58b9b6e7e3 ? PCI\VEN_1022&DEV_1483&SUBSYS_10221453
?     Device Flags:       ? Internal device
?                         ? Cryptographic hash verification is available
?   
??AMD Ryzen 9 5900X 12-Core Processor:
? ?   Device ID:          4bde70ba4e39b28f9eab1628f9dd6e6244c03027
? ?   Current version:    0x0a20120a
? ?   Vendor:             Advanced Micro Devices, Inc.
? ?   GUIDs:              af6af62f-513f-5d1b-8c80-23c44eafbe19 ? CPUID\PRO_0&FAM_19&MOD_21
? ?                       066e2405-0349-51a6-be7f-923dbd4e9873 ? CPUID\PRO_0&FAM_19&MOD_21&STP_2
? ?   Device Flags:       ? Internal device
? ? 
? ??Secure Processor:
?       Device ID:        c54ab0237d7a8db8c717b68e0be78e4374a2a079
?       Vendor:           Advanced Micro Devices, Inc. (PCI:0x1022)
?       GUIDs:            bb3bed27-5f4a-554a-87c4-b52ba58e58eb ? PCI\VEN_1022&DEV_1486
?                         1501f064-a7ff-5fae-9c4b-c79bb1a276fc ? PCI\VEN_1022&DEV_1486&SUBSYS_10221486
?       Device Flags:     ? Internal device
?     
??GPIO controller:
?     Device ID:          f685512aa07369c9e77742acef941d779d31e766
?     GUID:               37b440a9-2473-5087-a39b-db84f32a8ed8 ? GPIO\ID_AMDI0030:00
?   
??HDWD110:
?     Device ID:          d1002e65580df1e43a91623c1bb9d65f1e57bed1
?     Summary:            ATA drive
?     Current version:    MS2OA9A0
?     Vendor:             Toshiba (ATA:0x1179, OUI:000039)
?     Serial Number:      Y2EBP5LNS
?     GUIDs:              d46de2eb-23dd-5f33-8e17-f3a97b284e66 ? IDE\TOSHIBA_HDWD110_________________________MS2OA9A0
?                         6badafc3-4f1b-52c0-957c-6c53f7a323db ? IDE\0TOSHIBA_HDWD110_________________________
?                         e9bb055c-1ce2-58bb-8403-fbab14cd8981 ? TOSHIBA HDWD110
?     Device Flags:       ? Internal device
?                         ? Updatable
?                         ? System requires external power source
?                         ? Needs a reboot after installation
?                         ? Device is usable for the duration of the update
?   
??Integrated Webcam?:
?     Device ID:          08d460be0f1f9f128413f816022a6439e0078018
?     Summary:            Fake webcam
?     Current version:    1.2.4
?     Minimum Version:    1.2.0
?     Bootloader Version: 0.1.2
?     Vendor:             ACME Corp. (USB:0x046D)
?     Update State:       Success
?     Last modified:      2024-05-14 17:53
?     GUID:               b585990a-003e-5270-89d5-3705a17f9a43
?     Device Flags:       ? Updatable
?                         ? System requires external power source
?                         ? Supported on remote server
?                         ? Cryptographic hash verification is available
?                         ? Unsigned Payload
?     Device Requests:    ? Message
?   
??Intenso SSD SATAIII:
?     Device ID:          4869f6ccf087a28c26998f57bcfa7bea8dfa5056
?     Summary:            ATA drive
?     Current version:    W0825A0
?     Serial Number:      AAAA0000000000001931
?     Update Error:       No vendor ID set
?     GUIDs:              7ffa2ae3-55f6-5f71-a1dd-7b4fc5377cc8 ? IDE\Intenso_SSD_SATAIII_____________________W0825A0
?                         4bb13c0b-6382-5de9-85b3-1e0633183406 ? IDE\0Intenso_SSD_SATAIII_____________________
?                         c8adbb78-25c1-52d1-bf2b-b1f9c5ef8f89 ? Intenso SSD SATAIII
?     Device Flags:       ? Internal device
?                         ? System requires external power source
?                         ? Needs a reboot after installation
?                         ? Device is usable for the duration of the update
?                         ? Updatable
?   
??Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] (Sapphire NITRO+ RX 5700 XT):
? ?   Device ID:          0ec05f487924f76b6f4eee3433bdee489638de9d
? ?   Summary:            NAVI10 A1/A2 D19901 XT 8GB 300e/875m
? ?   Current version:    017.001.000.049.000000
? ?   Vendor:             Advanced Micro Devices, Inc. [AMD/ATI] (PCI:0x1002)
? ?   GUID:               21ab3209-6c69-5fcb-a817-3d1adba085b2 ? AMD\113-410XT-US4
? ?   Device Flags:       ? Cryptographic hash verification is available
? ? 
? ??Unknown Device:
?       Device ID:        a6c89aee142798063900a459b2f564f72137305e
?       Serial Number:    H7BR201202
?       GUID:             32d2a785-5d3e-57f7-8760-e3ad65456a06 ? DRM\VEN_SAM&DEV_71A8
?     
??TPM:
?     Device ID:          c6a80ac3a22083423992a3cb15018989f37834d6
?     Summary:            TPM 2.0 Device
?     Current version:    3.84.0.5
?     Vendor:             Advanced Micro Devices, Inc. (TPM:AMD)
?     GUIDs:              9305de1c-1e12-5665-81c4-37f8e51219b8 ? TPM\VEN_AMD&DEV_0001
?                         78a291ae-b499-5b0f-8f1d-74e1fefd0b1c ? TPM\VEN_AMD&MOD_AMD
?                         65a3fced-b423-563f-8098-bf5c329fc063 ? TPM\VEN_AMD&DEV_0001&VER_2.0
?                         5e704f0d-83cb-5364-8384-f46d725a23b8 ? TPM\VEN_AMD&MOD_AMD&VER_2.0
?     Device Flags:       ? Internal device
?                         ? System requires external power source
?                         ? Needs a reboot after installation
?                         ? Device can recover flash failures
?                         ? Full disk encryption secrets may be invalidated when updating
?                         ? Signed Payload
?   
??WDC WD50NDZW-11BCSS0:
      Device ID:          d05265ff31433b8099efe5515ddfa5e26639faf9
      Summary:            ATA drive
      Current version:    01.01A01
      Vendor:             Western Digital (ATA:0x101C, OUI:0014ee)
      Serial Number:      WD-WX82D32P5J98
      GUIDs:              eac7baa8-8da8-56b1-a7d9-851cd6d99263 ? IDE\WDC_WD50NDZW-11BCSS0____________________01.01A01
                          512196cc-e302-5b07-8726-334d91ad4326 ? IDE\0WDC_WD50NDZW-11BCSS0____________________
                          11fbdbcb-5a74-5b7c-924d-8a2c2f2a9140 ? WDC WD50NDZW-11BCSS0
      Device Flags:       ? Updatable
                          ? System requires external power source
                          ? Needs a reboot after installation
    
`

**Comment by estatistics** [comment]
sudo fwupdmgr update 
Devices with no available firmware updates: 
 ? Intenso SSD SATAIII
 ? HDWD110
 ? WDC WD50NDZW-11BCSS0
Devices with the latest available firmware version:
 ? Integrated Webcam?

**Comment by hughsie** [comment]
I think you need to file an issue with Ubuntu or Debian -- this is for upstream issues I'm afraid.

**Comment by estatistics** [comment]
i removed completely the package and upgrade completed. thanks
