### ISSUE TITLE
Regression: wacom_usb touch module

### ISSUE THREAD

**Issue by jigpu** [fwupd/fwupd#7267]
**Describe the bug**
Commit 62f6f19d269212871493ba8343bf0d53204c7fb7 seems to have introduced a regression in `plugins/wacom-usb/fu-wac-module-touch.c`. Starting with this commit, the plugin tries to write the raw / unparsed IHEX file to the device rather than the parsed bytes. Attempting to flash firmware in the current state causes the flash to fail with the touch becoming non-functional until a proper blob is re-written.

For example, the first data packet sent when flashing a particular firmware file is the following:

~~~
21:08:37.908 FuHidDevice          HID::SetReport [wValue=0x03e4, wIndex=0]:
       | 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f 10 11 12 13 14 15 16 17 18 19 1a 1b 1c 1d 1e 1f 
-------+------------------------------------------------------------------------------------------------
0x0000 | e4 00 02 01 01 00 80 00 00 10 3b 20 47 31 31 54 20 66 69 72 6d 77 61 72 65 20 66 69 6c 65 20 66 
0x0020 | 6f 72 20 4c 43 38 38 2b 41 52 4d 0d 0a 3b 0d 0a 3b 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 
0x0040 | 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 
0x0060 | 0d 0a 3b 2a 20 4d 61 69 6e 20 46 57 20 66 6f 72 20 4c 43 38 38 20 63 6f 72 65 0d 0a 3b 2a 2a 2a 
0x0080 | 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x00a0 | ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x00c0 | ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x00e0 | ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0100 | ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0120 | ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0140 | ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0160 | ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0180 | ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x01a0 | ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x01c0 | ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x01e0 | ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
~~~

The actual data is the 128 bytes starting at 0x0A, which turns out to just be the first 128 bytes of the IHEX file itself:

~~~
; G11T firmware file for LC88+ARM
;
;***********************************************
;* Main FW for LC88 core
;*************
~~~

Reverting the commit's change to this module seems to fix the issue.

Other plugins may have also regressed but I have no way of testing. The other Wacom module appear to be fine -- they're either writing data that doesn't need parsing (bluetooth-id6, bluetooth-id9) or just using `fu_firmware_get_stream` to read data that is then parsed before use (fu-wac-firmware.c).

**Steps to Reproduce**
1. Attach a Wacom device which has a "touch" module
2. Attempt to flash the touch firmware, with verbose output
3. Observe that the flash fails
4. Observe that the data flashed to the device is just the raw IHEX file, not the parsed bytes (see example above)

**Expected behavior**
* Flash should not fail
* Data flashed to the device should be blob parsed from the IHEX file

**fwupd version information**
Working from the `main` development branch at e684466d81a5f8f97b737bac78fcec91cd383a9f inside the venv

**Additional questions**

- Operating system and version: Arch Linux
- Have you tried rebooting? No
- Is this a regression? Yes

**Comment by hughsie** [comment]
Good catch! PR incoming.

**Comment by jigpu** [comment]
Gimme a few minutes and I'll get my system and hardware out for testing and get back to you :)
