### ISSUE TITLE
fu-self-test seems flaky after 1.9.16

### ISSUE THREAD

**Issue by rishabh-chromium** [fwupd/fwupd#7525]
**Describe the bug**
Some of our boards are failing `fu-self-test` with a timeout. This is the last log line, it is trying to generate a private key.
```
fwupd-1.9.16-r6: # Jcat-DEBUG: generating a 3072 bit RSA private key...
fwupd-1.9.16-r6:  [1;36mstderr: [0m
fwupd-1.9.16-r6: platform2_test.py: Signaled to shutdown: caught 15 signal.
fwupd-1.9.16-r6: 
fwupd-1.9.16-r6: 
fwupd-1.9.16-r6: 
fwupd-1.9.16-r6: Summary of Failures:
fwupd-1.9.16-r6: 
fwupd-1.9.16-r6: 19/19 fu-self-test                    [1;31mTIMEOUT        [0m 180.54s   killed by signal 9 SIGKILL
fwupd-1.9.16-r6: 
```
The boards it is failing on are low spec boards with low RAM and CPU but never failed any tests before 1.9.16
Any ideas what this might be?

**Comment by hughsie** [comment]
>  Any ideas what this might be?

Every release we seem to add more tests -- although 180s is a pretty long duration for that! On my system it's ~3.3s.

Still, on my system `generating a 3072 bit RSA private key...` takes a measurable blip of time, so lets dig into that a bit. Running `valgrind --tool=callgrind ./src/fu-self-test` I see:

![Screenshot from 2024-07-25 08-49-19](https://github.com/user-attachments/assets/98e86776-f6f1-44db-af62-a9b94cdb509e)

So 95% of the time is spent in `gnutls_x509_privkey_generate2` -- and we seem to be doing it at 7 times! We don't actually need the client cert in those tests, so I think we can just turn that off in the disposable engine tests.

Doing that takes my runtime from 3.3s to 1.0s, with a new callgrind of:

![Screenshot from 2024-07-25 09-01-13](https://github.com/user-attachments/assets/cce8035b-c877-466f-9cc4-5e79de04806f)

..which looks much more normal. We do spend 11% of the time just dlload-ing plugins, and we can probably turn that off too.
