### ISSUE TITLE
`fwupdmgr security` support for Qubes OS

### ISSUE THREAD

**Issue by duck09** [fwupd/fwupd#7534]
**Is your feature request related to a problem? Please describe.**
`fwupdmgr security` is not supported on Qubes OS and fails with the message `HSI unavailable for hypervisor`

**Describe the solution you'd like**
For `fwupdmgr security` to be supported on Qubes OS as `fwupdmgr` is already supported with the command `qubes-fwupdmgr`

**Describe alternatives you've considered**
Booting into a live Linux OS and using `fwupdmgr security` to check the firmware protections of the device.

**Additional context**

**Comment by superm1** [comment]
Shouldn't this bug be filed against Qubes?

**Comment by hughsie** [comment]
**Can** fwupd security work on a hypervisor? Isn't it all going to be fake data? It'd need to be tunnelled into the actual bare metal, and it's not really "here's a file descriptor" but actual low level hardware access.

**Comment by marmarek** [comment]
> **Can** fwupd security work on a hypervisor? Isn't it all going to be fake data? It'd need to be tunnelled into the actual bare metal, and it's not really "here's a file descriptor" but actual low level hardware access.

What specifically does it need? Dom0 has access to most of the hardware, so it should be possible.

**Comment by superm1** [comment]
There is an expectation the daemon and plugins loaded from it can access all hardware directly. Is that true in Qubes?

**Comment by marmarek** [comment]
With very few exceptions (like reconfiguring devices used by Xen itself - interrupt controllers, IOMMU etc), yes. The important distinction is that Xen dom0 (the privileged VM) can do all that stuff, domU (unprivileged VM) cannot. This can be distinguished by looking at `/sys/hypervisor/start_flags/privileged`.
