### ISSUE TITLE
[redfish plugin] potential issue that be unable to exit 'fwupd' install excution

### ISSUE THREAD

**Issue by vincent-tang1** [fwupd/fwupd#7593]
**Describe the bug**
Sometimes, after fwupd finished firmware writing via redfish protocol, then entered 'wait' status, but for very long time, it still be unable to exit this excution. 

**Steps to Reproduce**
1. Upgrade BMC firmware via redfish protocol, then can see that it was being written
```
(fwupd) root@vincent:/home/vincent/fwupd# fwupdmgr reinstall
WARNING: This package has not been validated, it may not work properly.
Selected device: FWA6172 Platform Management
╔══════════════════════════════════════════════════════════════════════════════╗
║ Reinstall FWA6172 Platform Management to 1.07.0000?                          ║
╠══════════════════════════════════════════════════════════════════════════════╣
║ This unstable release fixes the following issues:                            ║
║                                                                              ║
║ • Fix bug for test 1                                                         ║
║ • Improve performance for test 1                                             ║
║                                                                              ║
║ Some new functionality has also been added:                                  ║
║                                                                              ║
║ • Add support for test 1                                                     ║
║                                                                              ║
║ FWA6172 Platform Management and all connected devices may not be usable      ║
║ while updating.                                                              ║
╚══════════════════════════════════════════════════════════════════════════════╝
Perform operation? [Y|n]: Y
Writing…                 [********************************       ] Less than one minute remaining…
```
2. After finished writing firmware, then entered to 'Restarting device' status and then to 'Waiting' finnally, but for very long time, it still be unable to exit this excution. 
```
Restarting device…       [***************************************] Less than one minute remaining…
Waiting…                 [***************************************] Less than one minute remaining…
```

**Expected behavior**
fwupd install excution can close normally with reasonalbe time

**Root cause analysis**
After finished the firmware writing, then BMC will reboot. During BMC boot, 'fwupd' will try connect BMC and wait BMC come back. When BMC finished booting, becacuse 'fwupd' got some problem to lead to unable correctly connect into BMC. As result 'fwup' keep retying same callback function such that can not exit the excuation. For more detail reason, please see below:

1. In x86 host, can see the network interface 'usb4bmc' which is used to communicate to BMC Redfish service (eno1 & eno2 for out of band usage, usb4bmc for in-band usage)
```
(fwupd) root@vincent:/home/vincent/fwupd# ifconfig
eno1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.10.74  netmask 255.255.254.0  broadcast 172.17.11.255
        inet6 fe80::c600:adff:feb8:be36  prefixlen 64  scopeid 0x20<link>
        ether c4:00:ad:b8:be:36  txqueuelen 1000  (Ethernet)
        RX packets 327267  bytes 39696766 (39.6 MB)
        RX errors 0  dropped 145391  overruns 0  frame 0
        TX packets 14806  bytes 3141812 (3.1 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device memory 0x96100000-9617ffff

eno2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.10.73  netmask 255.255.254.0  broadcast 172.17.11.255
        inet6 fe80::c600:adff:feb8:be37  prefixlen 64  scopeid 0x20<link>
        ether c4:00:ad:b8:be:37  txqueuelen 1000  (Ethernet)
        RX packets 14055  bytes 1110803 (1.1 MB)
        RX errors 0  dropped 3830  overruns 0  frame 0
        TX packets 73  bytes 6520 (6.5 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device memory 0x96200000-9627ffff

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 241  bytes 21713 (21.7 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 241  bytes 21713 (21.7 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

usb4bmc: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.234.147.130  netmask 255.255.255.0  broadcast 10.234.147.255
        inet6 fe80::d940:1ffe:d854:ce61  prefixlen 64  scopeid 0x20<link>
        ether b2:72:6c:41:61:14  txqueuelen 1000  (Ethernet)
        RX packets 58  bytes 13754 (13.7 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 43  bytes 4209 (4.2 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

2. When BMC reboot, can see the  'usb4bmc' interface will disappear
```
(fwupd) root@vincent:/home/vincent/fwupd# ifconfig
eno1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.10.74  netmask 255.255.254.0  broadcast 172.17.11.255
        inet6 fe80::c600:adff:feb8:be36  prefixlen 64  scopeid 0x20<link>
        ether c4:00:ad:b8:be:36  txqueuelen 1000  (Ethernet)
        RX packets 323089  bytes 39379337 (39.3 MB)
        RX errors 0  dropped 143902  overruns 0  frame 0
        TX packets 14478  bytes 3018728 (3.0 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device memory 0x96100000-9617ffff

eno2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.10.73  netmask 255.255.254.0  broadcast 172.17.11.255
        inet6 fe80::c600:adff:feb8:be37  prefixlen 64  scopeid 0x20<link>
        ether c4:00:ad:b8:be:37  txqueuelen 1000  (Ethernet)
        RX packets 9612  bytes 757817 (757.8 KB)
        RX errors 0  dropped 2341  overruns 0  frame 0
        TX packets 47  bytes 4808 (4.8 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device memory 0x96200000-9627ffff

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 228  bytes 20433 (20.4 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 228  bytes 20433 (20.4 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

3. During BMC reboot, fwupd will first call the callback function 'fu_redfish_plugin_cleanup_setup_cb()' to wait BMC come back. (this callback function is with retry mechanism)
```
static gboolean
fu_redfish_plugin_cleanup(FuPlugin *plugin,
              FuDevice *device,
              FuProgress *progress,
              FwupdInstallFlags flags,
              GError **error)
{
...
    /* wait for the BMC to come back */
    if (!fu_device_retry_full(device,
                  fu_redfish_plugin_cleanup_setup_cb,
                  reset_timeout / FU_REDFISH_PLUGIN_CLEANUP_RETRIES_DELAY,
                  FU_REDFISH_PLUGIN_CLEANUP_RETRIES_DELAY * 1000,
                  self,
                  error)) {
        g_prefix_error(error, "manager failed to come back from setup: ");
        return FALSE;
    }
...
}
```
4. when BMC finished the booting (x86 host can see 'usb4bmc' network interface come back), the response for querying URI '/redfish/v1' will feedback into 'fu_redfish_plugin_cleanup_setup_cb()'. As result, the response has error http status code from BMC redfish service because BMC redfish service detected into different network domain between target IP '10.234.147.1' and source IP '172.17.10.74' . In fact, the 'source IP'  should also be in-band address, not out of band address.

5. following 4-th point, after that, 'fu_redfish_plugin_cleanup_setup_cb()'' retried again and again because BMC still detected into incorrect source IP '172.17.10.74' coming

**Furthermore root cause analysis:** 
From above 5-th point, this is because curl share object for 'connect' data is used as below (set in init call), so previous incorrect 'connect' data will be propagated. (For testing, after removing this curl share setting, the error will be no longer propagation and this issue is gone)
```
static void
fu_redfish_backend_init(FuRedfishBackend *self)
{
    ...
    ...
    curl_share_setopt(self->curlsh, CURLSHOPT_SHARE, CURL_LOCK_DATA_CONNECT);
}

```

**Potential solution:**
We knew it would be more efficient to use curl share object for connect data 'CURL_LOCK_DATA_CONNECT' as official site description:
https://curl.se/libcurl/c/CURLSHOPT_SHARE.html#CURL_LOCK_DATA_CONNECT

but in order to aviod the error propagation in connect info, not sure if we can : 
1. remove this share setting "curl_share_setopt(self->curlsh, CURLSHOPT_SHARE, CURL_LOCK_DATA_CONNECT);"
2. or, other better method you think 

**fwupd version information**

```shell
root@vincent:/home/vincent# fwupdmgr --version
compile   org.freedesktop.fwupd         1.9.16
compile   com.hughsie.libxmlb           0.3.17
compile   com.hughsie.libjcat           0.2.0
runtime   org.freedesktop.fwupd-efi     1.4
compile   org.freedesktop.gusb          0.4.8
runtime   com.hughsie.libjcat           0.2.0
runtime   org.freedesktop.gusb          0.4.8
runtime   org.kernel                    6.8.0-31-generic
runtime   org.freedesktop.fwupd         1.9.16
```
**fwupd device information**
```shell
root@vincent:/home/vincent# fwupdmgr get-devices
Advantech FWA-6172
│
├─BIOS:
│     Device ID:          562313e34c756a05a2e878861377765582bbf971
│     Summary:            Redfish host bus adapter
│     Current version:    1.00.0000
│     Vendor:             Advantech (REDFISH:ADVANTECH)
│     GUIDs:              467a7e47-2db8-5400-9fd1-8915df8e01d4 ← REDFISH\VENDOR_Advantech&SOFTWAREID_894feb65-2ca8-4378-a5d3-41c78ff5b59f-BIOS
│                         84591cf7-9cee-5641-99d5-11af7ab46ecd ← REDFISH\VENDOR_Advantech&ID_BIOS
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│
├─BL:
│     Device ID:          92b9cdf108e011d817c6a97824eab088f9dd1194
│     Summary:            Redfish host bus adapter
│     Current version:    0.30.0000
│     Vendor:             Advantech (REDFISH:ADVANTECH)
│     GUIDs:              208e148d-02da-52df-8458-857871ff624e ← REDFISH\VENDOR_Advantech&SOFTWAREID_894feb65-2ca8-4378-a5d3-41c78ff5b59f-BL
│                         ac7965d0-0781-5aa1-951d-4a263bb7a68b ← REDFISH\VENDOR_Advantech&ID_BL
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│
├─BMCONF:
│     Device ID:          234a9bdfc3540c1797d9693fe5389f3486b5942c
│     Summary:            Redfish host bus adapter
│     Current version:    1.06.0000
│     Vendor:             Advantech (REDFISH:ADVANTECH)
│     GUIDs:              2326661c-41db-5760-9443-5b6dec414802 ← REDFISH\VENDOR_Advantech&SOFTWAREID_894feb65-2ca8-4378-a5d3-41c78ff5b59f-BMCONF
│                         a92c90ab-448f-53e9-b0dc-ff6741f13b0a ← REDFISH\VENDOR_Advantech&ID_BMCONF
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│
├─FPGA:
│     Device ID:          c15823b7bd2b3abb8ec782bb77c941359a49fd1f
│     Summary:            Redfish host bus adapter
│     Current version:    0.12.0000
│     Vendor:             Advantech (REDFISH:ADVANTECH)
│     GUIDs:              70b760f5-078b-5281-84d5-a6b7531a4965 ← REDFISH\VENDOR_Advantech&SOFTWAREID_894feb65-2ca8-4378-a5d3-41c78ff5b59f-FPGA
│                         d53fb01b-be1c-572e-8e88-1711a52083b1 ← REDFISH\VENDOR_Advantech&ID_FPGA
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│
├─FWA6172 Platform Management:
│     Device ID:          62c1cd95692c5225826cf8568a460427ea3b1827
│     Summary:            Redfish host bus adapter
│     Current version:    1.07.0000
│     Vendor:             Advantech (REDFISH:ADVANTECH)
│     GUIDs:              10598c6b-6f24-518d-9065-bb948baa4907 ← REDFISH\VENDOR_Advantech&SOFTWAREID_894feb65-2ca8-4378-a5d3-41c78ff5b59f-BMC
│                         69ec5e09-0466-5679-83f5-0dc75e3ff4d5 ← REDFISH\VENDOR_Advantech&ID_BMC
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Supported on remote server
│
├─NVRAM:
│     Device ID:          e62d2a3a9c875839f7b57843190f695bca7f222f
│     Summary:            Redfish host bus adapter
│     Current version:    3.00.0000
│     Vendor:             Advantech (REDFISH:ADVANTECH)
│     GUIDs:              30a77683-3cfe-5fe8-b2ed-b89f0ba2a16d ← REDFISH\VENDOR_Advantech&SOFTWAREID_894feb65-2ca8-4378-a5d3-41c78ff5b59f-NVRAM
│                         afe3785d-abe4-546c-8889-1d3fbe16e6c1 ← REDFISH\VENDOR_Advantech&ID_NVRAM
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
...
```
**Additional questions**
- Operating system and version: ubuntu 24.04 LTS

**Comment by vincent-tang1** [comment]
I think it should be common issue.
not sure if above information is enough, or do you want to know more other furthermore information? thanks a lot ^^

**Comment by superm1** [comment]
> I think it should be common issue.
> not sure if above information is enough, or do you want to know more other furthermore information? thanks a lot ^^

Can you please upgrade to current tip and see if it still reproduces? Richard had some clean ups the last week or so that I think it's worth double checking.

**Comment by vincent-tang1** [comment]
> > I think it should be common issue.
> > not sure if above information is enough, or do you want to know more other furthermore information? thanks a lot ^^
> 
> Can you please upgrade to current tip and see if it still reproduces? Richard had some clean ups the last week or so that I think it's worth double checking.

Yes, and after applied Hughsie patch, this issue already solved

**Comment by vincent-tang1** [comment]
thanks for the commit!
And not sure if there is a opportunity that this solution can also can merged into Ubuntu 24.04 LTS distrubution ?

**Comment by hughsie** [comment]
> this solution can also can merged into Ubuntu 24.04 LTS distrubution

No idea about when Ubuntu would rebase, but I've backported it into 1_9_X for the next release.

**Comment by vincent-tang1** [comment]
not sure if my understanding is correct.

1. So next release fwupd v1.9.24 will included this solution, right ?
2. If Ubuntu 24.04 can rebase in the future, it can change into new fwupd version 1.9.16-2 from current 1.9.16-1 and include the solution, correct ?

Many thanks

**Comment by hughsie** [comment]
> So next release fwupd v1.9.24 will included this solution, right

Right.

> If Ubuntu 24.04 can rebase in the future, it can change into new fwupd version

Ubuntu would need to rebase to v1.9.24 -- or backport the patch that fixes the issue. Either way you should file a bug report with them in launchpad.

**Comment by vincent-tang1** [comment]
Got thanks! From below [table](https://wiki.ubuntu.com/Releases),
1. Not sure if new Ubuntu 24.10 version will use fwupd v1.9.24 or above version ?
2. Will Ubuntu 24.04.1 LTS version rebase in 8/29/2024 ?

![image](https://github.com/user-attachments/assets/7c1cee6c-b7f8-4536-adc8-6f0ba3495c46)

**Comment by hughsie** [comment]
No idea! I work for Red Hat not Canonical :)

**Comment by vincent-tang1** [comment]
> Ubuntu would need to rebase to v1.9.24 -- or backport the patch that fixes the issue. Either way you should file a bug report with them in launchpad.

Created the request into launchpad
https://bugs.launchpad.net/ubuntu/+source/fwupd/+bug/2077411

**Comment by vincent-tang1** [comment]
>Created the request into launchpad
https://bugs.launchpad.net/ubuntu/+source/fwupd/+bug/2077411

@superm1 thanks your update in the Launchpad ticket
Seems like ubuntu 24.10 (Oracular) already rebased into fwupd v1.9.24, right ? 
However, ubuntu 24.04 (Noble) have not rebased into the v1.9.24 yet because official site still be reviewing it, correct ? thanks

![image](https://github.com/user-attachments/assets/f141c77e-3caf-49f0-a495-cded09a49454)

**Comment by superm1** [comment]
Canonical sru team will decide whether to accept 1.9.24. I can't force them.

**Comment by vincent-tang1** [comment]
got it, many thanks :)

**Comment by superm1** [comment]
@vincent-tang1 they accepted it, but it needs to be validated.  Can you please test it and then leave the comment on the bug if it works?

**Comment by vincent-tang1** [comment]
@superm1 thanks for the reminder
Following their test proposed package, verified result as work  and left the comment on the bug
