### ISSUE TITLE
update firmware fail (FuStructCfuPayload requested 0x5 and got 0x3)

### ISSUE THREAD

**Issue by MichaelCheng04** [fwupd/fwupd#7679]
**Describe the bug**
    We encountered the fail when update the firmware. The log shows "failed to write-firmware: FuStructCfuPayload requested 0x5 and got 0x3"

**Steps to Reproduce**
1. download main branch.
2. build source code.
3. execute fwupd -vv to record log.
4. execute fwupdmgr install /home/xxx.cab to update firmware.
5. the result shows "failed to write-firmware: FuStructCfuPayload requested 0x5 and got 0x3"

**Expected behavior**
1. update success.
2. Could update firmware success on branch v1.9.24

**fwupd version information**
compile   info.libusb                   1.0.25
compile   com.hughsie.libxmlb           0.3.18
compile   com.hughsie.libjcat           0.2.1
compile   org.freedesktop.fwupd         2.0.0
runtime   org.freedesktop.fwupd-efi     1.0
runtime   com.hughsie.libjcat           0.2.1
runtime   com.hughsie.libxmlb           0.3.x
runtime   org.kernel                    5.15.0-25-generic
runtime   org.freedesktop.fwupd         2.0.0

```shell
fwupdmgr --version
```

Please note how you installed it (`apt`, `dnf`, `pacman`, source, etc):
source
<details>

<summary>**fwupd device information**</summary>

Please provide the output of the fwupd devices recognized in your system.
├─Fingerprint Sensor:
│     Device ID:          46d8fca8af11228d2f0fb62b13611af6c39e1deb
│     Summary:            Match-On-Chip Fingerprint Sensor
│     Current version:    0413
│     Vendor:             Elan Microelectronics Corp. (USB:0x04F3)
│     Install Duration:   10 seconds
│     GUID:               d769cc37-760c-57f2-aa1f-433e72ad281f ← USB\VID_04F3&PID_0C7E
│     Device Flags:       • Updatable
│                         • Device can recover flash failures
│                         • Signed Payload

```shell
fwupdmgr get-devices --show-all-devices
```

</details>

**Additional questions**

- Operating system and version:
- Have you tried rebooting?
- Is this a regression?

**Comment by hughsie** [comment]
@MichaelCheng04 good catch! Can you try https://github.com/fwupd/fwupd/pull/7682 please, and let me know if that fixes the problem either way. Thanks!
