### ISSUE TITLE
Unmatched policykit message for "emulation data collection"

### ISSUE THREAD

**Issue by rffontenelle** [fwupd/fwupd#7908]
**Describe the bug**
In the following code below, the PolicyKit message is not matching with its description:

https://github.com/fwupd/fwupd/blob/54b01d3af464b1ffd956cc6a6b72d5d10e91cc7e/policy/org.freedesktop.fwupd.policy.in#L278-L281

Should the message be "Authentication is required to emulation data collection" ?

These were introduced in https://github.com/fwupd/fwupd/pull/7847

**Steps to Reproduce**
N/A

**Expected behavior**
Message match description, as in the other messages from same file.

**fwupd version information**
post-2.0.1, post commit 5467e8eb8

**Additional questions**

- Operating system and version:
- Have you tried rebooting?
- Is this a regression?

**Comment by hughsie** [comment]
@superm1 which sounds less weird?

**Comment by rffontenelle** [comment]
> How about 
> 
> > Authentication is required to enable emulation data collection

That was my intention, but forgot the "enable".

**Comment by superm1** [comment]
Mind opening a PR?
