### ISSUE TITLE
Unexpected "Me FW Downgrade - Request MeSpiLock Failed"

### ISSUE THREAD

**Issue by Lj907** [fwupd/fwupd#7935]
**Describe the question**
I've had an odd issue, twice, with a 3rd-gen Lenovo Thinkpad X1 Carbon unning UEFI BIOS version N14ET25W (1.03) from 2014-12-01 and ME Firmware Version 10.0.29.1000.  OS is Ubuntu 22.04.

On two separate dates, a few months apart, I've had errors on boot: "Me FW Downgrade - Request MeSpiLock Failed" - much like the error described here: https://github.com/fwupd/firmware-lenovo/issues/199 

The first day it happened, it occurred a few times in a row - I had to power off/on the laptop a few times before it would boot normally.

I understand this error is normally associated with a failed UEFI/firmware update - but *I've never made any attempt to update my firmware on any occasion.*

When I run this command, it shows no attempts to update my firmware by fwupd:

```
$ fwupdmgr get-history
WARNING: UEFI capsule updates not available or enabled in firmware setup
See https://github.com/fwupd/fwupd/wiki/PluginFlag:capsules-unsupported for more information.
No history
```

Running fwupdmgr get-devices just shows my SSD.

Could fwupd be responsible for this boot error by attempting to automatically upgrade my firmware?  If so, is there some way I can confirm this from syslog or some other log?

If not fwupd, is there any other service in Ubuntu that might be responsible?  (Should I be concerned about malware?)

Any input from the learned people here would be appreciated.

**fwupd version information**
```
$ wupdmgr --version
runtime   org. freedesktop. fwupd      1.7.9
runtime   com. dell. libsmbios         2.4
compile   org. freedesktop.gusb        0.3.10
compile   com. hughsie. libjcat        0.1.9
runtime   org. kernel                  6.8.0-47-generic
compile   org. freedesktop. fwupd      1.7.9
runtime   org. freedesktop.gusb        0.3.10
```

**Comment by hughsie** [comment]
I think this is *a* bug, but I don't think it's our bug unfortunately. I would suggest contacting Lenovo support.

**Comment by hu606** [comment]
Is there some output/string in syslog (or some other log) that could be searched for to see if fwupd did indeed attempt a bios/uefi firmware update that corresponds with these incidents?

**Comment by hughsie** [comment]
> fwupd did indeed attempt a bios/uefi firmware update

fwupd doesn't do anything automatically; the daemon doesn't even have network access. If you asked it to do an upgrade it would be in the history database.

> WARNING: UEFI capsule updates not available or enabled in firmware setup

This tells me that fwupd wouldn't be able to update the firmware even if you wanted to. It's literally incapable of updating firmware on your system in it's current BIOS configuration.

**Comment by hu606** [comment]
Would fwupd not be able to update my firmware because it is too old?  (I do see in syslog from FuPluginPciMei that "ME family not supported for 0:10.0.29.1000").

Any wild guesses as to what might cause the "Request MeSpiLock Failed" in this case?  I've had this laptop many years and never seen this before this year.

**Comment by hu606** [comment]
Thanks - really appreciate your responses!
