### ISSUE TITLE
Error in the firmwarepackager.py README.md

### ISSUE THREAD

**Issue by dbharbin** [fwupd/fwupd#7955]
**Describe the bug**
README says --exe is REQUIRED, code doesn't, and the script works without the field

**Comment by hughsie** [comment]
Thanks for the report! Would you be able to do us a pull request with that small change please?

**Comment by dbharbin** [comment]
Done. https://github.com/fwupd/fwupd/pull/7957

**Comment by JohnAZoidberg** [comment]
The PR has been merged.
