### ISSUE TITLE
dell-k2: Structurally dead code

### ISSUE THREAD

**Issue by hughsie** [fwupd/fwupd#8017]
Coverity shows this, and I'm not sure what the right fix is:

	309static FuDevice *
	310fu_dell_k2_plugin_get_ec_from_devices(GPtrArray *devices)
	311{
	CID 1601435: (#1 of 1): Structurally dead code (UNREACHABLE)
	unreachable: Since the loop increment i++; is unreachable, the loop body will never execute more than once.
	312        for (guint i = 0; i <= devices->len; i++) {
	313                FuDevice *dev = g_ptr_array_index(devices, i);
	314                FuDevice *parent = fu_device_get_parent(dev);
	315
	316                if (parent == NULL)
	317                        parent = dev;
	318
	319                if (FU_IS_DELL_K2_EC(parent))
	320                        return parent;
	321
	322                break;
	323        }
	324        return NULL;
	325}

I'm *guessing* the `break` needs to be removed.

**Comment by superm1** [comment]
To me looking at that code I think the `break` has to go too.
