### ISSUE TITLE
Host Security ID (HSI) is not supported, No detected devices and PCR7 binding issues

### ISSUE THREAD

**Issue by User486375** [fwupd/fwupd#8055]
**Describe the bug**
I receive the error "Host Security ID (HSI) is not supported" when I run most commands.  Even the get-devices command below does not work. 

The reason I am even trying to check HSI is because I am running into BitLocker PCR7 binding issues, where it only binds with CSM enabled in my motherboards bios. This is despite my partition being GPT, secure boot enabled and all recent hardware, as well as the latest drivers/chipset/bios/firmware versions, and getting no other PCR7 errors while CSM is off other than a general "PCR7 binding not possible". Having it bound or not, however, does not change this error. The reason I want to avoid running CSM mode is because it seems worse for overall security, Resizable BAR is incompatible with it and I want BitLocker to fully utilize the TPM. This PCR7 issue itself seems extremely rare when researching it, that or no one cares about it. In the same way that, searching this repositories issues for the HSI error comes up with no results, neither did google besides source code for this project.

**Steps to Reproduce**
Run the following commands
```powershell
PS C:\Program Files (x86)\fwupd\bin> .\fwupdtool.exe security
Host Security ID (HSI) is not supported
PS C:\Program Files (x86)\fwupd\bin> .\fwupdtool.exe security --force --show-all
Host Security ID (HSI) is not supported
PS C:\Program Files (x86)\fwupd\bin> .\fwupdmgr.exe security
Host Security ID (HSI) is not supported
PS C:\Program Files (x86)\fwupd\bin> .\fwupdmgr.exe security --force --show-all
Host Security ID (HSI) is not supported
PS C:\Program Files (x86)\fwupd\bin> .\fwupdmgr get-devices --show-all-devices
No detected devices
```

**Expected behavior**
An output such as https://github.com/fwupd/fwupd/issues/7157 or https://github.com/fwupd/fwupd/issues/7547

**fwupd version information**
Please provide the version of the daemon and client.

```shell
runtime   org.freedesktop.fwupd         2.0.0
runtime   com.hughsie.libxmlb           0.3.19
compile   com.hughsie.libxmlb           0.3.19
runtime   com.hughsie.libjcat           0.2.1
compile   com.hughsie.libjcat           0.2.1
compile   info.libusb                   1.0.24
compile   org.freedesktop.fwupd         2.0.0
```

Please note how you installed it (`apt`, `dnf`, `pacman`, source, etc): The executable from GitHub.

<details>

<summary>**fwupd device information**</summary>

Please provide the output of the fwupd devices recognized in your system.

```shell
PS C:\Program Files (x86)\fwupd\bin> .\fwupdmgr get-devices --show-all-devices
No detected devices
```

Considering that does not work, I'll just list some information from msinfo.
OS Name	Microsoft Windows 11 Enterprise
Version	10.0.22631 Build 22631
System Type	x64-based PC
Processor	AMD Ryzen 9 7950X3D 16-Core Processor, 4201 Mhz, 16 Core(s), 32 Logical Processor(s)
BIOS Version/Date	American Megatrends Inc. 2506, 28/10/2024
SMBIOS Version	3.6
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	ASUSTeK COMPUTER INC.
BaseBoard Product	ROG CROSSHAIR X670E HERO
BaseBoard Version	Rev 1.xx
Secure Boot State	On
PCR7 Configuration	Binding Not Possible
Device Encryption Support	Reasons for failed automatic device encryption: PCR7 binding is not supported

</details>

**Additional questions**

- Operating system and version: Windows 11 Enterprise 23H2
- Have you tried rebooting? Yes
- Is this a regression? No

**Comment by hughsie** [comment]
We can't do any of the HSI tests on Windows I'm afraid. It's going to partially work on MacOS, and fully work on Linux, including ChromeOS.
