### ISSUE TITLE
 fwupd[34417]: Failed to load daemon: syscall filtering is configured but not working

### ISSUE THREAD

**Issue by ambasta** [fwupd/fwupd#8078]
**Describe the bug**

fwupd.service fails to start with
```
fwupd[34417]: Failed to load daemon: syscall filtering is configured but not working
```

**Steps to Reproduce**
```
emerge fwupd
systemctl daemon-reload
systemctl start fwupd
```

**Expected behavior**
`fwupd.service` should start successfully

**fwupd version information**
```
sys-apps/fwupd-2.0.1::gentoo  USE="amdgpu archive bash-completion bluetooth fastboot flashrom gnutls lzma nvme policykit spi sqlite systemd tpm uefi -amt -cbor (-elogind) -gtk-doc -introspection -logitech -minimal -modemmanager -synaptics -test" PYTHON_SINGLE_TARGET="python3_13 -python3_10 -python3_11 -python3_12" 
```

```shell
fwupdmgr --version
compile   info.libusb                   1.0.27
compile   com.hughsie.libxmlb           0.3.19
compile   com.hughsie.libjcat           0.2.2
compile   org.freedesktop.fwupd         2.0.1
runtime   org.freedesktop.fwupd-efi     1.7
runtime   com.hughsie.libxmlb           0.3.19
runtime   com.hughsie.libjcat           0.2.2
runtime   org.kernel                    6.11.3-gentoo
runtime   org.freedesktop.fwupd         2.0.1
```

Please note how you installed it (`apt`, `dnf`, `pacman`, source, etc):
```emerge -1v fwupd```

<details>

<summary>**fwupd device information**</summary>

Please provide the output of the fwupd devices recognized in your system.

```shell
fwupdmgr get-devices --show-all-devices
Framework Laptop 13 (AMD Ryzen 7040Series)
│
├─AMD Ryzen 7 7840U w/ Radeon 780M Graphics:
│ │   Device ID:          4bde70ba4e39b28f9eab1628f9dd6e6244c03027
│ │   Current version:    0x0a704104
│ │   Vendor:             Advanced Micro Devices, Inc.
│ │   GUIDs:              2a1df9de-fe02-59c8-8af1-32c8bb011f94 ← CPUID\PRO_0&FAM_19&MOD_74
│ │                       5a4bca32-6547-584f-bb36-920d9adede25 ← CPUID\PRO_0&FAM_19&MOD_74&STP_1
│ │   Device Flags:       • Internal device
│ │ 
│ ├─AMD Radeon 780M:
│ │ │   Device ID:        83eba1fa14bdefee1f6b4bcf06069b298e1c338f
│ │ │   Summary:          AMD AMD_PHOENIX_GENERIC
│ │ │   Current version:  022.012.000.027.000001
│ │ │   Vendor:           Advanced Micro Devices, Inc. [AMD/ATI] (PCI:0x1002)
│ │ │   GUID:             4a1501b7-b500-5255-9d9c-41d652a4d5bc ← AMD\113-PHXGEN
│ │ │   Device Flags:     • Internal device
│ │ │                     • Can tag for emulation
│ │ │ 
│ │ └─NE135FBM-N41:
│ │       Device ID:      10feb8f8641be9b4f44d52078baa6338209a53ef
│ │       Vendor:         PNP:BOE
│ │       GUID:           ace3bb34-1bbb-5a5f-9694-73c4cede9692 ← DRM\VEN_BOE&DEV_0BCA
│ │       Device Flags:   • Internal device
│ │                       • Can tag for emulation
│ │     
│ ├─Secure Processor:
│ │     Device ID:        c54ab0237d7a8db8c717b68e0be78e4374a2a079
│ │     Current version:  00.2d.00.7a
│ │     Bootloader Version: 00.2d.00.7a
│ │     Vendor:           Advanced Micro Devices, Inc. [AMD] (PCI:0x1022)
│ │     GUID:             9eb6a793-7f97-5fb5-b49c-139d2ce3ee46 ← PCI\VEN_1022&DEV_15C7
│ │     Device Flags:     • Internal device
│ │                       • Can tag for emulation
│ │   
│ ├─System Management Unit (SMU):
│ │     Device ID:        db0330716216c629bb2c07256e5d018f499eb6ce
│ │     Summary:          Microcontroller used within CPU/APU program 0
│ │     Current version:  76.82.0
│ │     Vendor:           Advanced Micro Devices, Inc.
│ │     GUID:             3ac3159e-6eef-5f6b-bc8d-67686b238747 ← /sys/devices/platform/AMDI0009:00
│ │     Device Flags:     • Internal device
│ │                       • Can tag for emulation
│ │   
│ └─TPM:
│       Device ID:        1d8d50a4dbc65618f5c399c2ae827b632b3ccc11
│       Current version:  6.3.1.615
│       Vendor:           Microsoft (TPM:MSFT)
│       GUIDs:            2a65d4b6-60a0-5e8c-acfa-d86cc3cbe4c3 ← TPM\VEN_MSFT&DEV_0001
│                         31a7bb1b-f5e1-53ff-b0e5-8692a21caed6 ← TPM\VEN_MSFT&MOD_Pluton.TPM.A
│                         5bea8d58-c840-513e-a5ad-0184cbaa9821 ← TPM\VEN_MSFT&DEV_0001&VER_2.0
│                         e02519c6-9139-5de8-89d4-9dca2f5c3b66 ← TPM\VEN_MSFT&MOD_Pluton.TPM.A&VER_2.0
│       Device Flags:     • Internal device
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device can recover flash failures
│                         • Full disk encryption secrets may be invalidated when updating
│                         • Signed Payload
│                         • Can tag for emulation
│     
├─Fingerprint Sensor:
│     Device ID:          813b4757e78d708603a80ead0a2b6ef1364b7790
│     Summary:            Match-On-Chip fingerprint sensor
│     Current version:    01000334
│     Vendor:             Shenzhen Goodix Technology Co.,Ltd. (USB:0x27C6)
│     Install Duration:   10 seconds
│     Serial Number:      UID9AE2000E_XXXX_MOC_B0
│     GUID:               1e8c8470-a49c-571a-82fd-19c9fa32b8c3 ← USB\VID_27C6&PID_609C
│     Device Flags:       • Updatable
│                         • Supported on remote server
│                         • Device stages updates
│                         • Device can recover flash failures
│                         • Signed Payload
│                         • Can tag for emulation
│   
├─HDMI Expansion Card:
│     Device ID:          b8a2645298053fb62ea03e27feea6c483d3fd27e
│     Current version:    3.0.16.106
│     Bootloader Version: 3.0.2.900
│     Vendor:             Framework (USB:0x32AC)
│     Serial Number:      11AD1D00A49C401233210B00
│     GUIDs:              ff59aed5-f8a7-5742-901a-1876d48ea0b5 ← USB\VID_32AC&PID_0002
│                         7cffc965-2ead-5c70-bd62-ce81a42d37fc ← USB\VID_32AC&PID_0002&MODE_FW2
│     Device Flags:       • Updatable
│                         • Device stages updates
│                         • Unsigned Payload
│                         • Can tag for emulation
│   
├─Predator SSD GM7000 2TB:
│     Device ID:          03281da317dccd2b18de2bd1cc70a782df40ed7e
│     Summary:            NVM Express solid state drive
│     Current version:    3.A.J.CR
│     Vendor:             INNOGRIT Corporation (PCI:0x1DBE)
│     Serial Number:      PSBG53490901195
│     GUIDs:              5703c6ec-f40b-57c4-90ad-e19ab9d16a80 ← NVME\VEN_1DBE&DEV_5236
│                         558ccb37-e1dc-5b72-9466-f8a03650d35e ← NVME\VEN_1DBE&DEV_5236&SUBSYS_1DBE5236
│                         2e8c81ba-a0c1-5f32-af20-3565d3245e3c ← Predator SSD GM7000 2TB
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│                         • Can tag for emulation
│   
├─System Firmware:
│ │   Device ID:          1e4fa9cea0b89e613370cf9657ffa0b6d3f37fec
│ │   Summary:            UEFI System Resource Table device (Updated via capsule-on-disk)
│ │   Current version:    0.0.3.5
│ │   Minimum Version:    0.0.0.1
│ │   Vendor:             Framework (DMI:INSYDE Corp.)
│ │   Update State:       Success
│ │   GUID:               b5f7dcc1-568c-50f8-a4dd-e39d1f93fda1
│ │   Device Flags:       • Internal device
│ │                       • Updatable
│ │                       • System requires external power source
│ │                       • Supported on remote server
│ │                       • Needs a reboot after installation
│ │                       • Cryptographic hash verification is available
│ │                       • Device is usable for the duration of the update
│ │   Device Requests:    • Message
│ │ 
│ └─UEFI dbx:
│       Device ID:        362301da643102b9f38477387e2193e57abaa590
│       Summary:          UEFI revocation database
│       Current version:  421
│       Minimum Version:  421
│       Vendor:           UEFI:Linux Foundation
│       Install Duration: 1 second
│       GUIDs:            f8ba2887-9411-5c36-9cee-88995bb39731 ← UEFI\CRT_A1117F516A32CEFCBA3F2D1ACE10A87972FD6BBE8FE0D0B996E09E65D802A503&ARCH_X64
│                         115f7cac-f705-5d34-9a47-37177c3e8514 ← UEFI\CRT_B38FAD316F525F27B27A21B486456C3E4279748BF16893827BF16FE659C0F75E&ARCH_X64
│       Device Flags:     • Internal device
│                         • Updatable
│                         • Supported on remote server
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│                         • Only version upgrades are allowed
│                         • Signed Payload
│     
└─UEFI Platform Key:
      Device ID:          6924110cde4fa051bfdc600a60620dc7aa9d3c6a
      Summary:            frame.work-LaptopAMDPK
      GUID:               c701846d-5461-5c19-a7ae-2d89b2f44c14 ← UEFI\CRT_D610D8205624E644D9435383826B2DBF7298859C
```

</details>

**Additional questions**

- Operating system and version: Gentoo
- Have you tried rebooting? No
- Is this a regression? I think so

**Comment by hughsie** [comment]
Hi @ambasta. This is Gentoo, so there's a lot that could be wrong; there might be a missing kernel option, systemd compile option, or something lower level like glibc or libseccomp. I'm afraid we have no experience with Gentoo, and I think it might be best for you to debug this on a Gentoo-specific forum. Sorry that's not more helpful.

**Comment by computerix** [comment]
Same problem here, also Gentoo.

It is a regression, and it must be a change in fwupd, because downgrading to fwupd-1.9.24 helps:
fwupd-1.9.24 works fine on exactly the same system.

See https://bugs.gentoo.org/943319

**Comment by computerix** [comment]
Could it be that these two versions use or check different syscalls?
Is it possible to find out why the check failed and for which syscall?

As I said: I can switch forth and back between 1.9.24 and 2.0.1 on the same system, 
and the old version works, the new version does not.

**Comment by superm1** [comment]
So in 1.9.x we did revert 0d10078268adb29c5256514a62af5d7111faf2e2 (with 6e1d5109a83aafd207fc681e075f81a892f76234)

So yes; we do have a pretty big difference in how the systemd unit is built between the two.

**Comment by superm1** [comment]
The check that we do in 2.0.x is for the `mlock` system call.  It's not clear to me if this is a problem being first reported in Gentoo (with newer systemd etc) or if it's a unique problem to Gentoo.  I would _expect_ some reports like this from Arch as well.

**Comment by superm1** [comment]
@hughsie before you do the 2.0.2 release this week ,can you explicitly double check this in Rawhide?  That could help us make sure it's not a tip of tree type of problem.

**Comment by hughsie** [comment]
It seems to work fine in Fedora 41, I'll try rawhide later -- I'm guessing this has to be a physical machine... It smells specific to Gentoo for some reason.

**Comment by joakim-tjernlund** [comment]
RH still have some caps actions in its .spec(post install) even though caps were moved to Makefile.am
Maybe a mismatch between Makefile.am and .spec?

**Comment by computerix** [comment]
Problem analyzed and solved: More or less gentoo specific.
Gentoo allows to compile systemd with or without syscall filtering,
but configures fwupd with syscall filtering even if systemd does not have it.

More in https://bugs.gentoo.org/943319 .

**Comment by hughsie** [comment]
> Gentoo allows to compile systemd with or without syscall filtering,
> More or less gentoo specific

I'd say very much Gentoo specific personally; the reason we don't officially support Gentoo is that it allows the end user to have a completely unique system with all kinds of contradictory options that are impossible to debug and support. I've personally spent over an hour on trying to reproduce this bug and it's also delayed the 2.0.2 release.

**Comment by computerix** [comment]
Well, syscall filtering is a configurable option of systemd's meson configuration.
So everyone is free to set or reset it, not just gentoo.
You should not take features for granted which are not granted, 
at least not without testing for them during your build configuration.
I think "syscall filtering off" is not that unusual e.g. for small or embedded systems,
and gentoo supports such systems.

The problem is not that there are millions of options to configure a gentoo system.
Gentoo is quite sophisticated in getting such dependencies right if the ebuild scripts are written correctly.
Unfortunately, the owner of the fwupd ebuild script was not aware of the dependency on systemd's syscall filtering,
but it is a one line change to fix that.

The problem is that there are millions of combinations of systemd options,
and your meson.build script always assumes that systemd is built with syscall filtering,
without actually testing if systemd was built with syscall filtering,
and without providing a configurable meson option 
to give the user the option to build fwupd with syscall filtering completely disabled 
(at least that's what the meson.build looks to me at the first glance).

**Comment by computerix** [comment]
Not really as far as meson is concerned.
After all, I'm an advanced user, not a (gentoo) developer.
And I'm not into meson at all.

In general, I think the command "systemd-analyze syscall-filter" outputs "Not compiled with syscall filters, sorry." when systemd was compiled without syscall filtering and exits with exit code 1.

For gentoo, it would be easier, because gentoo ebuild's have configurations flags (USE flags).
For each package, they store the USE flags actually used when building the package 
in the installed packages metadata.
Other ebuild's can specify required USE flags for the packages they depend on,
and the build system detects any inconsistencies.
