### ISSUE TITLE
CI didn't publish docs and windows binaries on release

### ISSUE THREAD

**Issue by superm1** [fwupd/fwupd#8150]
I noticed that CI failed for both actions in the publish job because the artifacts couldn't be found.

https://github.com/fwupd/fwupd/actions/runs/12007039916

I thought at first it might be a dependency order problem but it appears that even retried job they fail.

**Comment by superm1** [comment]
I wonder if it's because those jobs are called "on tag" rather than on pushes so they're missing artifacts from a regular push?

**Comment by CragW** [comment]
The new implemented plugin is missing in the docs, supposedly it should be published along with 2.0.2.
https://fwupd.github.io/libfwupdplugin/?q=kestrel

**Comment by superm1** [comment]
The job didn't find the artifact. So NO docs are updated.

**Comment by hughsie** [comment]
@superm1 I'm so out of my depth on CI stuff. Anything I can do to debug more?

**Comment by superm1** [comment]
I am suspecting that "on tag" artifacts can only be used in "on tag" jobs. If that's right, we might have to trigger all the jobs as on tag. I'll push something later when I get a chance.
