### ISSUE TITLE
fu_dell_kestrel_ec_get_package_version() uses GUINT32_FROM_BE

### ISSUE THREAD

**Issue by hughsie** [fwupd/fwupd#8168]
The GUINT32_FROM_BE function shouldn't be needed as `FuStructDellKestrelDockData.dock_firmware_pkg_ver` is defined as little endian. I'm a bit confused what it's doing. :)

**Comment by CragW** [comment]
We should change `dock_firmware_pkg_ver` from `u32le` to `u32be` then we can remove `GUINT32_FROM_BE` away, thanks for the catch.
