### ISSUE TITLE
Updating Quectel EM120 fails with  failed to open /dev/wwan0qcdm0

### ISSUE THREAD

**Issue by neilzone** [fwupd/fwupd#8223]
**Describe the bug**
I am trying to upgrade EM120R GL from EM120RGLAPR02A07M4G_10.010.10.010 to EM120RGLAPR02A07M4G_20.020.20.020.

The process ends early with:

```
Restarting device…       [                                       ]
failed to write-firmware: failed after 30 retries: failed to open /dev/wwan0qcdm0: Operation not permitted
```

Running `fwupdmgr get-devices --show-all-devices` after the failed update, I get:

```
EM120R GL:
│     Device ID:          bba54f76de66958e5d70964b6ddd2d1e6c7dae9e
│     Summary:            Quectel EM120 firehose prog file
│     Current version:    EM120RGLAPR02A07M4G_10.010.10.010
│     Vendor:             quectel (PCI:0x1EAC)
│     Update State:       Failed
│     Update Error:       Device has been removed
```

**Steps to Reproduce**

Run `fwupdmgr update`
Confirm upgrade of EM120R GL from EM120RGLAPR02A07M4G_10.010.10.010 to EM120RGLAPR02A07M4G_20.020.20.020
After download and writing, it fails with the error message above.

**Expected behavior**
Firmware to be updated

**fwupd version information**

Debian testing, `fwupdmgr` was installed by default.
```
compile   info.libusb                   1.0.27
compile   org.freedesktop.fwupd         2.0.3
compile   com.hughsie.libxmlb           0.3.21
compile   com.hughsie.libjcat           0.2.0
runtime   org.freedesktop.fwupd-efi     1.7
runtime   com.hughsie.libjcat           0.2.0
runtime   com.hughsie.libxmlb           0.3.21
runtime   org.kernel                    6.11.10-amd64
runtime   org.freedesktop.fwupd         2.0.3
```

Please note how you installed it (`apt`, `dnf`, `pacman`, source, etc):

<details>

<summary>**fwupd device information**</summary>

There are lots of devices.

The relevant device is:

```
├─EM120R GL:
│     Device ID:          bba54f76de66958e5d70964b6ddd2d1e6c7dae9e
│     Summary:            Quectel EM120 firehose prog file
│     Current version:    EM120RGLAPR02A07M4G_10.010.10.010
│     Vendor:             quectel (PCI:0x1EAC)
│     GUIDs:              5033ad90-c250-5a13-b5ff-b34bb5262773 ← PCI\VID_1EAC&PID_1001&REV_0000&CARRIER_ROW_COMMERCIAL&NAME_EM120RG
│                         53f8dd6d-c5ee-5a79-9da1-f98d39e28699 ← PCI\VID_1EAC&PID_1001&REV_0000&CARRIER_ROW_COMMERCIAL
│                         4294f9ad-e7b2-53fb-bd16-be64092ebb1d ← PCI\VID_1EAC&PID_1001&REV_0000
│                         3b2b9e7f-2620-546f-becb-727b6e4b662f ← PCI\VID_1EAC&PID_1001
│     Device Flags:       • Updatable
│                         • System requires external power source
│                         • Supported on remote server
│                         • Unsigned Payload

```

</details>

**Additional questions**

- Operating system and version:

Debian testing, 6.11.10-amd64

- Have you tried rebooting?

Yes

- Is this a regression?

Unknown.

**Comment by neilzone** [comment]
Unhelpfully, I have solved my problem, without really being clear about the underlying issue.

I booted the machine in question with Debian 12 (stable), from a USB stick, and run `fwupdmgr update`. That completed the firmware update on this device successfully, first time.

I do not know why it failed using Debian testing, but it is fixed for me, so I'm leaving the note in case it helps anyone else.

**Comment by pzauner** [comment]
Have a similar issue on Fedora 43.
It starts updating but then fails to reattach. Need to restart the device completely so that it comes back up again. Will try out updating with a live distro and if that won't help maybe even using windows.. 

```bash
✘ user@t14  ~  sudo -v && fwupdmgr refresh --force && fwupdmgr update -y
Wird aktualisiert lvfs
Herunterladen …          [***************************************]
Neue Metadaten erfolgreich heruntergeladen:
 • 22 Geräte sind aktualisierbar
 • 8 Geräte werden in den aktivierten Gegenstellen unterstützt (eine Aktualisierung wurde veröffentlicht)
Gerät wird neu gestartet …[                                       ]Weniger als eine Minute verbleiben…
failed to detach: failed to wait for detach replug: device 5d6d0cbb367670e90e2542a8d780e37498616cf4 did not come back
 ✘ user@t14  ~ 
```
