### ISSUE TITLE
Provide hashes of firmware update

### ISSUE THREAD

**Issue by TobiPeterG** [fwupd/fwupd#8255]
**Is your feature request related to a problem? Please describe.**
On openSUSE Tumbleweed and Aeon Desktop, it's possible to encrypt the root drive and bind it to the TPM. On Aeon, it is bound by default to PCR 0 as well.
This, however, breaks with every firmware update of the platform, as the new hash is unknown before installation.

**Describe the solution you'd like**
It would be great if fwupd provided the hashes beforehand (is this even possible?), so we could enroll them and have a seamless update process that doesn't break the TPM unlocking.

**Describe alternatives you've considered**
Is there currently a way to measure the firmware after download and before the next reboot?

**Additional context**

**Comment by superm1** [comment]
Duplicate of #6318
