### ISSUE TITLE
Specified Firmware version is older than installed

### ISSUE THREAD

**Issue by arpit1585** [fwupd/fwupd#835]
I am working on generating .cab file and I am having issues getting fwupdmgr to update the firmware due to firmware version comparison. 
It complains with error "Specified firmware is older than installed '0.0.47 < 47RA906H", FW on device is 47RA906H, and the specified/new FW is "47RA906J"
It seems fwupdmgr converts specified firmware from "47RA906J" to 0.0.47 and tries to compare it with FW on device 47RA906H, and hence it fails.

Strange that it converted only specified FW and not the FW version on device.
I also tried to specify custom tag, and make it plain, but still same error.
here is the snippet of it
     `<custom>
        <id compare="ge" version="47RA906J">org.freedesktop.fwupd</id>
         <value key="LVFS::VersionFormat">plain</value>
     </custom>`

**Error:-** 
Decompressing…         [***************************************]
Specified firmware is older than installed '0.0.47 < 47RA906H'

**Comment by hughsie** [comment]
Two problems I believe:

* fwupd too old to recognize 'plain` metadata
* needs a device quirk like https://github.com/hughsie/fwupd/blob/master/plugins/uefi/uefi.quirk

I've sent you an email with a ton more detail. I'm happy to add the quirks upstream if you can give me a list of GUIDs.

**Comment by jparr721** [comment]
I am having the same error as him actually on my Lenovo Thinkpad carbon X1 gen 6. Do you have any plans to add quirks for that model?

**Comment by hughsie** [comment]
@jparr721 that's a different issue, I don't think it's anything to do with this bug.

**Comment by hughsie** [comment]
@jparr721 you've not actually provided any information about the problem you're seeing. Can you open a new issue please.
